import {hasAction,canActOn} from '../../access-policy';
import {route,readBody,HttpError,all,first,stmt,batch,uid,now,str,idOf,num,date,oneOf,parseJson,auditStatement} from '../../server/core';
import {canSeeWork,loadWork,type WorkRow} from '../../server/work';
import * as st from '../../server/strategy';
import type {Member} from '../../server/policy';

// Goals-to-execution API: the strategy hierarchy (Work records), rollups with method and sources, key-result
// data sources and progress updates, check-ins (including cited AI drafts), review packs, portfolio views,
// capacity and private planning scenarios.
const planner=(u:Member)=>u.role==='admin'||hasAction(u,'strategy','plan');
export const GET=route(async(req,u)=>{
 if(!hasAction(u,'strategy'))throw new HttpError(403,'Strategy is not available to you.');
 const q=new URL(req.url).searchParams;const view=q.get('view')||'tree';
 if(view==='tree'){
  const rows=(await all<WorkRow>(`SELECT * FROM work_records WHERE tenant_id=? AND deleted_at IS NULL AND kind IN (${st.STRATEGY_KINDS.map(()=>'?').join(',')}) ORDER BY created_at`,u.tenantId,...st.STRATEGY_KINDS)).filter(r=>canSeeWork(u,r)&&(!q.get('period')||parseJson<{periodId?:string}>(r.data_json,{}).periodId===q.get('period')||!['objective','key_result'].includes(r.kind)));
  const {canSeeProject}=await import('../../server/collab');const projIds=[...new Set(rows.flatMap(r=>parseJson<{projects?:string[]}>(r.data_json,{}).projects||[]))];
  const projects=projIds.length?(await all<import('../../server/collab').ProjectRow&{code:string,name:string,progress:number,health:string,stage:string,target_date:string|null}>(`SELECT * FROM projects WHERE tenant_id=? AND id IN (${projIds.map(()=>'?').join(',')})`,u.tenantId,...projIds)).filter(p=>canSeeProject(u,p)):[];
  const milestones=projects.length?await all<{id:string,title:string,status:string,due_date:string|null,project_id:string}>(`SELECT id,title,status,due_date,project_id FROM tasks WHERE tenant_id=? AND deleted_at IS NULL AND milestone=1 AND project_id IN (${projects.map(()=>'?').join(',')}) ORDER BY due_date`,u.tenantId,...projects.map(p=>p.id)):[];
  const taskCounts=projects.length?await all<{project_id:string,n:number,done:number}>(`SELECT project_id,count(*) AS n,sum(status='Done') AS done FROM tasks WHERE tenant_id=? AND deleted_at IS NULL AND milestone=0 AND project_id IN (${projects.map(()=>'?').join(',')}) GROUP BY project_id`,u.tenantId,...projects.map(p=>p.id)):[];
  return {items:rows.map(r=>({id:r.id,kind:r.kind,number:r.number,title:r.title,status:r.status,parentId:r.parent_id,ownerId:r.owner_id,department:r.department,progress:r.progress,start:r.start_date,end:r.end_date,amount:r.amount,visibility:r.visibility,data:parseJson(r.data_json,{})})),projects:projects.map(p=>({id:p.id,code:p.code,name:p.name,progress:p.progress,health:p.health,stage:p.stage,targetDate:p.target_date,milestones:milestones.filter(m=>m.project_id===p.id),tasks:taskCounts.find(t=>t.project_id===p.id)||{n:0,done:0}})),periods:await all('SELECT id,name,kind,start_date AS startDate,end_date AS endDate,status FROM planning_periods WHERE tenant_id=? ORDER BY start_date DESC',u.tenantId),canPlan:planner(u),canCreate:hasAction(u,'strategy','create')&&hasAction(u,'business','create')};
 }
 if(view==='item'){const r=await loadWork(u,idOf(q.get('id'),'Record'));if(!st.STRATEGY_KINDS.includes(r.kind))throw new HttpError(404,'Record not found.');
  const [ro,children,checkIns,updates,versions,acks]=await Promise.all([st.rollup(u,r),all<WorkRow>('SELECT * FROM work_records WHERE tenant_id=? AND parent_id=? AND deleted_at IS NULL ORDER BY created_at',u.tenantId,r.id),all('SELECT * FROM strategy_check_ins WHERE tenant_id=? AND target_id=? ORDER BY created_at DESC LIMIT 50',u.tenantId,r.id),all('SELECT id,value,previous_value AS previousValue,progress,source_kind AS source,source_ref AS ref,lineage_json AS lineage,note,status,actor,created_at AS createdAt FROM progress_updates WHERE tenant_id=? AND target_id=? ORDER BY created_at DESC LIMIT 100',u.tenantId,r.id),all('SELECT version,published,edited_by AS editedBy,created_at AS createdAt FROM work_record_versions WHERE tenant_id=? AND record_id=? ORDER BY version DESC LIMIT 50',u.tenantId,r.id),r.kind==='strategy'?all<{member_id:string,version:number}>('SELECT member_id,version FROM strategy_acks WHERE tenant_id=? AND record_id=?',u.tenantId,r.id):Promise.resolve([])]);
  const d=parseJson<Record<string,unknown>>(r.data_json,{});
  // Children show their live rollup (not the stored column, which the sweep refreshes periodically).
  const kids=children.filter(c=>canSeeWork(u,c)).slice(0,60);const live=new Map<string,number|null>();for(const c of kids)if(st.STRATEGY_KINDS.includes(c.kind))live.set(c.id,(await st.rollup(u,c,3)).progress);
  return {record:{id:r.id,kind:r.kind,number:r.number,title:r.title,description:r.description,status:r.status,parentId:r.parent_id,ownerId:r.owner_id,department:r.department,start:r.start_date,end:r.end_date,amount:r.amount,currency:r.currency,visibility:r.visibility,version:r.version,data:d},rollup:ro,children:kids.map(c=>({id:c.id,kind:c.kind,number:c.number,title:c.title,status:c.status,progress:live.has(c.id)?live.get(c.id)??null:c.progress,ownerId:c.owner_id})),hiddenChildren:children.filter(c=>!canSeeWork(u,c)).length,
   checkIns:(checkIns as {citations_json:string,evidence_json:string}[]).map(c=>({...c,citations:parseJson(c.citations_json,[]),evidence:parseJson(c.evidence_json,[])})),updates:(updates as {lineage:string}[]).map(x=>({...x,lineage:parseJson(x.lineage,{})})),versions,acknowledged:(acks as {member_id:string}[]).some(a=>a.member_id===u.id),ackCount:acks.length,
   canUpdate:r.owner_id===u.id||u.role==='admin'||canActOn(u,'strategy','update',r.department,r.owner_id||''),canPlan:planner(u)};
 }
 if(view==='portfolio')return st.portfolio(u,{filter:q.get('filter')||'all',department:q.get('department')||'',theme:q.get('theme')||''});
 if(view==='capacity')return st.capacity(u,{from:q.get('from')||undefined,to:q.get('to')||undefined,department:q.get('department')||undefined});
 if(view==='check-ins'){const rows=(await all<WorkRow>("SELECT * FROM work_records WHERE tenant_id=? AND deleted_at IS NULL AND kind IN ('objective','key_result','initiative','programme')",u.tenantId)).filter(r=>canSeeWork(u,r)&&(q.get('all')==='1'?true:r.owner_id===u.id));
  const today=now().slice(0,10);const drafts=await all<{id:string,target_id:string,ai_drafted:number,created_at:string}>("SELECT id,target_id,ai_drafted,created_at FROM strategy_check_ins WHERE tenant_id=? AND status='draft'",u.tenantId);
  return {due:rows.map(r=>{const d=parseJson<Record<string,unknown>>(r.data_json,{});return {id:r.id,kind:r.kind,title:r.title,ownerId:r.owner_id,nextCheckIn:d.nextCheckIn||null,overdue:typeof d.nextCheckIn==='string'&&d.nextCheckIn<today,cadence:d.checkInCadence||d.frequency||'',drafts:drafts.filter(x=>x.target_id===r.id).length}}).sort((a,b)=>String(a.nextCheckIn||'9999').localeCompare(String(b.nextCheckIn||'9999'))),recent:await all("SELECT c.id,c.target_id AS targetId,w.title,c.progress,c.confidence,c.health,c.status,c.ai_drafted AS aiDrafted,c.submitted_at AS submittedAt,c.created_at AS createdAt FROM strategy_check_ins c JOIN work_records w ON w.id=c.target_id AND w.tenant_id=c.tenant_id WHERE c.tenant_id=? ORDER BY c.created_at DESC LIMIT 60",u.tenantId).then(rs=>(rs as {targetId:string}[]).filter(x=>rows.some(r=>r.id===x.targetId)||q.get('all')==='1'))}}
 if(view==='reviews'){const rows=await all<{id:string,kind:string,title:string,department:string,status:string,created_by:string,created_at:string}>('SELECT id,kind,title,department,status,created_by,created_at FROM strategy_reviews WHERE tenant_id=? ORDER BY created_at DESC LIMIT 100',u.tenantId);return {reviews:rows.filter(r=>r.created_by===u.id||planner(u))}}
 if(view==='review'){const r=await first<{id:string,kind:string,title:string,department:string,content_json:string,status:string,created_by:string,created_at:string}>('SELECT * FROM strategy_reviews WHERE id=? AND tenant_id=?',idOf(q.get('id'),'Review'),u.tenantId);if(!r||(r.created_by!==u.id&&!planner(u)))throw new HttpError(404,'Review not found.');
  // Packs are re-filtered for the reader: items they cannot see are removed.
  const c=parseJson<{items?:{id:string}[],atRisk?:{id:string}[]}>(r.content_json,{});const ids=[...new Set([...(c.items||[]),...(c.atRisk||[])].map(i=>i.id))];const {visibleWork}=await import('../../server/work');const vis=await visibleWork(u,ids);
  return {review:{...r,content:{...c,items:(c.items||[]).filter(i=>vis.has(i.id)),atRisk:(c.atRisk||[]).filter(i=>vis.has(i.id))}}}}
 if(view==='scenarios'){const rows=await all<{id:string,name:string,owner_id:string,status:string,updated_at:string}>('SELECT id,name,owner_id,status,updated_at FROM planning_scenarios WHERE tenant_id=? AND status<>? ORDER BY updated_at DESC',u.tenantId,'deleted');return {scenarios:rows.filter(s=>s.owner_id===u.id||((u.role==='admin'||hasAction(u,'strategy','approve'))&&s.status!=='draft')),canPlan:planner(u)}}
 if(view==='scenario'){const s=await st.loadScenario(u,idOf(q.get('id'),'Scenario'));return {scenario:{...s,result:parseJson(s.result_json,{})},changes:(await all<{params_json:string}>('SELECT * FROM scenario_changes WHERE tenant_id=? AND scenario_id=? ORDER BY created_at',u.tenantId,s.id)).map(c=>({...c,params:parseJson(c.params_json,{})})),changeTypes:st.CHANGE_TYPES,canApprove:(u.role==='admin'||hasAction(u,'strategy','approve'))&&s.owner_id!==u.id,isOwner:s.owner_id===u.id}}
 if(view==='periods')return {periods:await all('SELECT id,name,kind,start_date AS startDate,end_date AS endDate,status FROM planning_periods WHERE tenant_id=? ORDER BY start_date DESC',u.tenantId)};
 if(view==='report'){const rows=(await all<WorkRow>("SELECT * FROM work_records WHERE tenant_id=? AND deleted_at IS NULL AND kind IN ('objective','key_result','initiative','programme')",u.tenantId)).filter(r=>canSeeWork(u,r));const out=[];for(const r of rows.slice(0,300)){const ro=await st.rollup(u,r);out.push({id:r.id,kind:r.kind,number:r.number,title:r.title,department:r.department,status:r.status,progress:ro.progress,health:ro.health,method:ro.method,missing:ro.missing.length,confidence:ro.confidence,lastUpdated:ro.lastUpdated})}return {rows:out}}
 throw new HttpError(400,'Unknown view.');
},{module:'strategy'});

export const POST=route(async(req,u)=>{
 if(!hasAction(u,'strategy'))throw new HttpError(403,'Strategy is not available to you.');
 const b=await readBody(req,200000);const action=str(b.action,'Action',40);
 switch(action){
  case 'period-save':{if(!planner(u))throw new HttpError(403,'Only planners manage planning periods.');const s=date(b.startDate,'Start',true)!,e=date(b.endDate,'End',true)!;if(e<s)throw new HttpError(400,'The end must be after the start.');const id=b.id?idOf(b.id,'Period'):uid();
   await batch([b.id?stmt('UPDATE planning_periods SET name=?,kind=?,start_date=?,end_date=?,status=? WHERE id=? AND tenant_id=?',str(b.name,'Name',80),oneOf(b.kind||'quarter',['annual','quarter','month','custom'] as const,'period type'),s,e,oneOf(b.status||'active',['planned','active','closed'] as const,'status'),id,u.tenantId):stmt('INSERT INTO planning_periods(id,tenant_id,name,kind,start_date,end_date,status,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)',id,u.tenantId,str(b.name,'Name',80),oneOf(b.kind||'quarter',['annual','quarter','month','custom'] as const,'period type'),s,e,oneOf(b.status||'active',['planned','active','closed'] as const,'status'),u.id,now()),auditStatement(u,'Planning period saved',id,'Strategy',null,{name:b.name})]);return {id}}
  case 'check-in':{const r=await loadWork(u,idOf(b.id,'Record'));return st.saveCheckIn(u,r,{...b,id:b.checkInId})}
  case 'draft-check-in':{const r=await loadWork(u,idOf(b.id,'Record'));if(r.owner_id!==u.id&&u.role!=='admin'&&!canActOn(u,'strategy','update',r.department,r.owner_id||''))throw new HttpError(403,'Only the owner drafts check-ins.');return st.draftCheckIn(u,r)}
  case 'override':case 'clear-override':{const r=await loadWork(u,idOf(b.id,'Record'));if(r.owner_id!==u.id&&u.role!=='admin'&&!canActOn(u,'strategy','update',r.department,r.owner_id||''))throw new HttpError(403,'Only the owner overrides progress.');const d=parseJson<Record<string,unknown>>(r.data_json,{});
   const next=action==='override'?{...d,override:{value:Math.round(num(b.value,'Progress',0,100)),reason:str(b.reason,'Reason for the override',300),by:u.id,at:now()}}:(({override,...rest})=>{void override;return rest})(d);
   await batch([stmt('UPDATE work_records SET data_json=?,progress=CASE WHEN ? IS NULL THEN progress ELSE ? END,version=version+1,updated_at=? WHERE id=? AND tenant_id=?',JSON.stringify(next),action==='override'?Number(b.value):null,action==='override'?Math.round(Number(b.value)):null,now(),r.id,u.tenantId),auditStatement(u,action==='override'?'Progress overridden manually':'Progress override removed',r.id,r.department,{override:d.override||null},{override:action==='override'?(next as {override:unknown}).override:null})]);return {ok:true}}
  case 'set-source':{const r=await loadWork(u,idOf(b.id,'Key result'));if(r.kind!=='key_result')throw new HttpError(400,'Only key results have data sources.');if(r.owner_id!==u.id&&u.role!=='admin')throw new HttpError(403,'Only the owner sets the data source.');
   const kind=oneOf(b.kind,['manual','project','purchasing','asset','report','studio','connector'] as const,'data source');const s0=(b.source&&typeof b.source==='object'?b.source:{}) as Record<string,unknown>;
   const src:Record<string,unknown>={kind};for(const k of ['projectId','budgetId','measure','app','report','category','status','connectorId','resource','query'])if(s0[k]!==undefined&&s0[k]!=='')src[k]=str(s0[k],k,120);
   // The source must be readable by the owner now (it is read with the owner's permissions on every sync).
   if(kind==='project'){const {loadProject}=await import('../../server/collab');await loadProject(u,String(src.projectId||''))}
   if(kind==='connector'){const {loadConnector}=await import('../../server/connectors');const {mayUse}=await import('../../server/fabric');const c=await loadConnector(u.tenantId,idOf(src.connectorId,'Connector'));if(!mayUse(u,c))throw new HttpError(403,'You cannot use this connector.')}
   if(kind==='purchasing'&&!['actual','committed','ordered','received','budget','remaining','forecast','requested','invoiced','paid'].includes(String(src.measure||'actual')))throw new HttpError(400,'Choose a financial measure.');
   const d=parseJson<Record<string,unknown>>(r.data_json,{});await batch([stmt('UPDATE work_records SET data_json=?,updated_at=? WHERE id=? AND tenant_id=?',JSON.stringify({...d,dataSource:src}),now(),r.id,u.tenantId),auditStatement(u,'Key result data source set',r.id,r.department,{source:d.dataSource||null},{source:src})]);
   const changed=await st.syncKeyResults(u.tenantId);return {ok:true,synced:changed}}
  case 'ai-recommend':{
   // AI-recommended key-result values stay drafts; the owner accepts or rejects them (lineage kept).
   const r=await loadWork(u,idOf(b.id,'Key result'));if(r.kind!=='key_result')throw new HttpError(400,'Only key results.');const value=num(b.value,'Recommended value',-1e13,1e13);const id=uid();
   await batch([stmt("INSERT INTO progress_updates(id,tenant_id,target_id,value,source_kind,source_ref,lineage_json,note,status,actor,created_at) VALUES(?,?,?,?,'ai_recommendation',?,?,?,'draft',?,?)",id,u.tenantId,r.id,value,str(b.ref||'',"Reference",120,false),JSON.stringify({citations:Array.isArray(b.citations)?b.citations.slice(0,10):[]}),str(b.note,'Reason',500),u.id,now()),auditStatement(u,'AI value recommendation recorded (draft)',r.id,r.department,null,{value})]);return {id}}
  case 'update-decide':{const x=await first<{id:string,target_id:string,value:number,status:string,source_kind:string,lineage_json:string}>('SELECT * FROM progress_updates WHERE id=? AND tenant_id=?',idOf(b.updateId,'Update'),u.tenantId);if(!x||x.status!=='draft')throw new HttpError(404,'Draft update not found.');const r=await loadWork(u,x.target_id);if(r.owner_id!==u.id&&u.role!=='admin')throw new HttpError(403,'Only the owner accepts value updates.');
   if(b.approve===true){await st.applyKrValue(u.tenantId,r.id,x.value,u.id,{kind:`${x.source_kind} (accepted)`,ref:x.id,lineage:parseJson(x.lineage_json,{})});await stmt("UPDATE progress_updates SET status='accepted' WHERE id=?",x.id).run()}else await stmt("UPDATE progress_updates SET status='rejected' WHERE id=?",x.id).run();return {ok:true}}
  case 'publish':case 'acknowledge':{const r=await loadWork(u,idOf(b.id,'Strategy'));if(r.kind!=='strategy')throw new HttpError(400,'Only strategies are published.');
   if(action==='publish'){if(!planner(u)&&r.owner_id!==u.id)throw new HttpError(403,'Only planners publish the strategy.');const v=Number(r.version||1);await batch([stmt("UPDATE work_records SET status='Published',updated_at=? WHERE id=? AND tenant_id=?",now(),r.id,u.tenantId),stmt('INSERT INTO work_record_versions(id,tenant_id,record_id,version,snapshot_json,published,edited_by,created_at) VALUES(?,?,?,?,?,1,?,?) ON CONFLICT(tenant_id,record_id,version) DO UPDATE SET published=1',uid(),u.tenantId,r.id,v,JSON.stringify({title:r.title,description:r.description,data:parseJson(r.data_json,{})}),u.id,now()),auditStatement(u,`Strategy published (version ${v})`,r.id,r.department,{status:r.status},{status:'Published',version:v})]);return {version:v}}
   await stmt('INSERT INTO strategy_acks(id,tenant_id,record_id,version,member_id,created_at) VALUES(?,?,?,?,?,?) ON CONFLICT(tenant_id,record_id,version,member_id) DO NOTHING',uid(),u.tenantId,r.id,Number(r.version||1),u.id,now()).run();return {ok:true}}
  case 'review-generate':{if(!planner(u)&&u.role!=='manager')throw new HttpError(403,'Review packs are for planners and managers.');const kind=oneOf(b.kind||'monthly',['weekly','monthly','qbr','executive','department'] as const,'review type');const dept=kind==='department'?str(b.department||u.department,'Department',160):str(b.department,'Department',160,false);
   const content=await st.reviewPack(u,kind,{department:dept||undefined,periodId:b.periodId?idOf(b.periodId,'Period'):undefined});const id=uid();const labels:Record<string,string>={weekly:'Weekly check-in review',monthly:'Monthly review',qbr:'Quarterly business review',executive:'Executive review pack',department:`Department review pack · ${dept}`};
   await batch([stmt("INSERT INTO strategy_reviews(id,tenant_id,kind,title,period_id,department,content_json,status,created_by,created_at) VALUES(?,?,?,?,?,?,?,'final',?,?)",id,u.tenantId,kind,`${labels[kind]} · ${now().slice(0,10)}`,b.periodId||null,dept,JSON.stringify(content),u.id,now()),auditStatement(u,`Review pack generated (${kind})`,id,'Strategy',null,{items:content.items.length})]);return {id}}
  case 'capacity-save':{const m=idOf(b.memberId,'Person');if(m!==u.id&&u.role!=='admin'&&!(u.role==='manager'))throw new HttpError(403,'Only managers set capacity for others.');await batch([stmt('INSERT INTO capacity_profiles(id,tenant_id,member_id,hours_per_week,skills_json,updated_by,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(tenant_id,member_id) DO UPDATE SET hours_per_week=excluded.hours_per_week,skills_json=excluded.skills_json,updated_by=excluded.updated_by,updated_at=excluded.updated_at',uid(),u.tenantId,m,num(b.hoursPerWeek,'Hours per week',0,80),JSON.stringify((Array.isArray(b.skills)?b.skills:[]).map(x=>str(x,'Skill',60)).slice(0,30)),u.id,now()),auditStatement(u,'Capacity profile updated',m,'Strategy',null,{hours:b.hoursPerWeek})]);return {ok:true}}
  case 'time-off':{const m=b.memberId?idOf(b.memberId,'Person'):u.id;if(m!==u.id&&u.role!=='admin'&&u.role!=='manager')throw new HttpError(403,'Only managers record time off for others.');const s=date(b.startDate,'Start',true)!,e=date(b.endDate,'End',true)!;if(e<s)throw new HttpError(400,'The end must be after the start.');const id=uid();await batch([stmt("INSERT INTO time_off(id,tenant_id,member_id,start_date,end_date,kind,status,created_by,created_at) VALUES(?,?,?,?,?,?,'Approved',?,?)",id,u.tenantId,m,s,e,str(b.kind||'Leave','Type',40),u.id,now()),auditStatement(u,'Time off recorded',m,'Strategy',null,{from:s,to:e})]);return {id}}
  case 'scenario-create':{if(!planner(u))throw new HttpError(403,'Only planners create scenarios.');const id=uid();await batch([stmt("INSERT INTO planning_scenarios(id,tenant_id,name,description,owner_id,status,created_at,updated_at) VALUES(?,?,?,?,?,'draft',?,?)",id,u.tenantId,str(b.name,'Name',120),str(b.description,'Description',2000,false),u.id,now(),now()),auditStatement(u,'Planning scenario created (private)',id,'Strategy',null,{name:b.name})]);return {id}}
 }
 // Scenario actions
 const s=await st.loadScenario(u,idOf(b.id,'Scenario'));
 const own=s.owner_id===u.id;const approver=(u.role==='admin'||hasAction(u,'strategy','approve'))&&!own;
 switch(action){
  case 'scenario-change':{if(!own||s.status!=='draft')throw new HttpError(409,'Only the owner edits a draft scenario.');const type=oneOf(b.changeType,st.CHANGE_TYPES,'change');const target=str(b.targetType,'Target type',30);const tid=idOf(b.targetId,'Target');
   const params=(b.params&&typeof b.params==='object'?b.params:{}) as Record<string,unknown>;if(JSON.stringify(params).length>2000)throw new HttpError(400,'The change is too large.');const id=uid();await stmt('INSERT INTO scenario_changes(id,tenant_id,scenario_id,change_type,target_type,target_id,params_json,created_at) VALUES(?,?,?,?,?,?,?,?)',id,u.tenantId,s.id,type,target,tid,JSON.stringify(params),now()).run();return {id}}
  case 'scenario-change-remove':{if(!own||s.status!=='draft')throw new HttpError(409,'Only the owner edits a draft scenario.');await stmt('DELETE FROM scenario_changes WHERE id=? AND tenant_id=? AND scenario_id=?',idOf(b.changeId,'Change'),u.tenantId,s.id).run();return {ok:true}}
  case 'scenario-evaluate':return {effects:await st.evaluateScenario(u,s.id)};
  case 'scenario-submit':{if(!own||s.status!=='draft')throw new HttpError(409,'Only the owner submits a draft.');await st.evaluateScenario(u,s.id);await batch([stmt("UPDATE planning_scenarios SET status='submitted',submitted_at=?,updated_at=? WHERE id=?",now(),now(),s.id),auditStatement(u,'Planning scenario submitted for approval',s.id,'Strategy',null,null)]);const admins=(await all<{id:string}>("SELECT id FROM members WHERE tenant_id=? AND active=1 AND role='admin' AND id<>?",u.tenantId,u.id)).map(r=>r.id);const {notify}=await import('../../server/notify');await notify(u,admins,{kind:'approval',title:`Scenario to approve: ${s.name}`,link:`#/strategy/scenarios/${s.id}`});return {ok:true}}
  case 'scenario-approve':case 'scenario-reject':{if(!approver)throw new HttpError(403,'Another planner or an administrator approves scenarios.');if(s.status!=='submitted')throw new HttpError(409,'Only submitted scenarios can be decided.');const to=action==='scenario-approve'?'approved':'rejected';await batch([stmt('UPDATE planning_scenarios SET status=?,decided_by=?,decided_at=?,updated_at=? WHERE id=?',to,u.id,now(),now(),s.id),auditStatement(u,`Planning scenario ${to}`,s.id,'Strategy',null,{note:str(b.note,'Note',500,false)})]);return {status:to}}
  case 'scenario-apply':{if(!approver&&u.role!=='admin')throw new HttpError(403,'Applying a scenario needs an approver.');return st.applyScenario(req,u,s.id)}
  case 'scenario-delete':{if(!own||!['draft','rejected'].includes(s.status))throw new HttpError(409,'Only draft or rejected scenarios can be deleted.');await batch([stmt('DELETE FROM scenario_changes WHERE tenant_id=? AND scenario_id=?',u.tenantId,s.id),stmt("UPDATE planning_scenarios SET status='deleted',updated_at=? WHERE id=?",now(),s.id)]);return {ok:true}}
 }
 throw new HttpError(400,'Unknown action.');
},{module:'strategy'});
