import {hasAction,canActOn} from '../access-policy';
import {all,first,stmt,batch,run,uid,now,HttpError} from './core';
import {canSeeTicket,canSeeAsset,canSeeDoc,canSeeFile,canSeePage,type TicketRow,type AssetRow,type PurchaseRow,type FileRow,type PageRow} from './entities';
import {canSeeProject,canSeeTask,taskContext,canSeeSpace,canAccessChannel,TASK_SELECT,type ProjectRow,type TaskRow,type SpaceRow,type ChannelRow} from './collab';
import type {Member} from './policy';

// ── One Work Graph ───────────────────────────────────────────────────────────
// A relationship layer over every module. Nodes and edges live in D1 (graph_nodes / graph_edges) behind this
// module's functions only, so a dedicated graph store could replace the tables without touching callers.
// Nodes are projections of source records and are rebuilt from them (idempotent); edges derived from source
// records carry origin 'event' and are replaced on each projection, while 'user', 'ai' and 'connector' edges
// are kept. Reads never trust the graph for access: every returned node is re-checked against the module's
// own visibility rule for the viewer, and edges are only returned between two visible nodes.

export const RELATIONSHIPS:Record<string,{label:string,inverse:string}>={
 belongs_to:{label:'belongs to',inverse:'contains'},member_of:{label:'is a member of',inverse:'has member'},manages:{label:'manages',inverse:'is managed by'},
 reports_to:{label:'reports to',inverse:'has report'},assigned_to:{label:'is assigned to',inverse:'is responsible for'},owns:{label:'owns',inverse:'is owned by'},
 created_by:{label:'was created by',inverse:'created'},requested_by:{label:'was requested by',inverse:'requested'},approved_by:{label:'was approved by',inverse:'approved'},
 funded_by:{label:'is funded by',inverse:'funds'},purchased_through:{label:'was purchased through',inverse:'purchased'},supplied_by:{label:'is supplied by',inverse:'supplies'},
 received_through:{label:'was received through',inverse:'received'},created_asset:{label:'created asset',inverse:'was created from'},depends_on:{label:'depends on',inverse:'is needed by'},
 blocks:{label:'blocks',inverse:'is blocked by'},related_to:{label:'is related to',inverse:'is related to'},attached_to:{label:'is attached to',inverse:'has attachment'},
 mentioned_in:{label:'is mentioned in',inverse:'mentions'},decided_in:{label:'was decided in',inverse:'decided'},resulted_in:{label:'resulted in',inverse:'resulted from'},
 maintained_by:{label:'is maintained by',inverse:'maintains'},connected_through:{label:'is connected through',inverse:'connects'},generated_by_agent:{label:'was generated by agent',inverse:'generated'},
 located_at:{label:'is located at',inverse:'hosts'},has_role:{label:'has role',inverse:'is held by'},sponsors:{label:'sponsors',inverse:'is sponsored by'},
 part_of:{label:'is part of',inverse:'includes'},contributes_to:{label:'contributes to',inverse:'is delivered by'},attended:{label:'attended',inverse:'was attended by'},decided_by:{label:'was decided by',inverse:'decided'},triggered_by:{label:'was triggered by',inverse:'triggered'},
};
export const NODE_LABELS:Record<string,string>={goal:'Goal',objective:'Objective',initiative:'Initiative',customer:'Customer',contract:'Contract',service:'Service',person:'Person',department:'Department',location:'Location',role:'Role',group:'Group',project:'Project',task:'Task',milestone:'Milestone',decision:'Decision',risk:'Risk',issue:'Issue',meeting:'Meeting',project_record:'Plan item',PR:'Purchase requisition',PO:'Purchase order',receipt:'Goods receipt',vendor:'Vendor',budget:'Budget',asset:'Asset',ticket:'Ticket',work_order:'Work order',maintenance_plan:'Maintenance plan',inventory_item:'Inventory item',file:'File',page:'Page',space:'Space',message:'Message',approval:'Approval',studio_record:'App record',connector:'Connector',external:'External record',agent:'AI agent',agent_run:'Agent run',automation_run:'Automation run'};
export type NodeSpec={type:string,sourceId:string,title:string,summary?:string,status?:string,ownerId?:string|null,department?:string,location?:string,module:string,url:string,classification?:string,search?:string,provider?:string|null,externalId?:string|null,syncMode?:string|null,lastVerifiedAt?:string|null,meta?:Record<string,unknown>};
type Ref={type:string,sourceId:string};
export type EdgeSpec={type:string,to:Ref,reverse?:boolean,meta?:Record<string,unknown>};
export type GraphNode={id:string,type:string,source_id:string,title:string,summary:string,status:string,owner_id:string|null,department:string,location:string,module:string,url:string,classification:string,provider:string|null,external_id:string|null,sync_mode:string|null,last_verified_at:string|null,meta_json:string,created_at:string,updated_at:string,deleted_at:string|null};
export type GraphEdge={id:string,src_id:string,dst_id:string,type:string,origin:string,created_by:string,confidence:number|null,effective_at:string|null,expires_at:string|null,meta_json:string,created_at:string};

const clip=(s:unknown,n=400)=>String(s??'').replace(/\s+/g,' ').trim().slice(0,n);
const recordKinds:Record<string,string>={milestone:'milestone',decision:'decision',risk:'risk',issue:'issue',meeting:'meeting'};

// ── Projection: source record → node + derived relationships ────────────────
export async function projectRecord(tenantId:string,type:string,id:string):Promise<{node:NodeSpec,edges:EdgeSpec[]}|null>{
 const e:EdgeSpec[]=[];const add=(t:string,to:Ref|null|undefined|false,reverse=false,meta?:Record<string,unknown>)=>{if(to&&to.sourceId)e.push({type:t,to,reverse,meta})};
 const P=(i:string|null|undefined)=>i?{type:'person',sourceId:i}:null;
 // Goals, objectives, initiatives, customers, contracts, services and stand-alone meetings/decisions.
 if(type==='work_record'||['goal','objective','initiative','customer','contract','service'].includes(type)){const {projectWork}=await import('./work');return projectWork(tenantId,id)}
 const deptRef=async(name:string|null|undefined)=>{if(!name)return null;const d=await first<{id:string}>('SELECT id FROM departments WHERE tenant_id=? AND lower(name)=lower(?)',tenantId,name);return d?{type:'department',sourceId:d.id}:null};
 const locRef=async(name:string|null|undefined)=>{if(!name)return null;const l=await first<{id:string}>('SELECT id FROM locations WHERE tenant_id=? AND (lower(path)=lower(?) OR lower(name)=lower(?)) ORDER BY length(path) DESC LIMIT 1',tenantId,name,name);return l?{type:'location',sourceId:l.id}:null};
 switch(type){
  case 'person':{const m=await first<{id:string,name:string,title:string,department:string,location:string,manager_id:string|null,role_id:string|null,active:number}>('SELECT id,name,title,department,location,manager_id,role_id,active FROM members WHERE id=? AND tenant_id=?',id,tenantId);if(!m)return null;
   add('member_of',await deptRef(m.department));add('located_at',await locRef(m.location));add('reports_to',P(m.manager_id));if(m.role_id)add('has_role',{type:'role',sourceId:m.role_id});
   for(const g of await all<{group_id:string}>('SELECT group_id FROM group_members WHERE tenant_id=? AND member_id=?',tenantId,id))add('member_of',{type:'group',sourceId:g.group_id});
   return {node:{type,sourceId:id,title:m.name,summary:m.title,status:m.active?'Active':'Inactive',department:m.department,location:m.location,module:'people',url:`#/people/directory/${id}`},edges:e}}
  case 'department':{const d=await first<{id:string,name:string,description:string,head_id:string|null,parent_id:string|null,status:string}>('SELECT id,name,description,head_id,parent_id,status FROM departments WHERE id=? AND tenant_id=?',id,tenantId);if(!d)return null;
   if(d.head_id)add('manages',P(d.head_id),true);if(d.parent_id)add('part_of',{type:'department',sourceId:d.parent_id});
   return {node:{type,sourceId:id,title:d.name,summary:d.description,status:d.status||'active',department:d.name,module:'people',url:'#/people/departments'},edges:e}}
  case 'location':{const l=await first<{id:string,name:string,path:string,parent_id:string|null,kind:string}>('SELECT id,name,path,parent_id,kind FROM locations WHERE id=? AND tenant_id=?',id,tenantId);if(!l)return null;
   if(l.parent_id)add('part_of',{type:'location',sourceId:l.parent_id});return {node:{type,sourceId:id,title:l.path||l.name,summary:l.kind,location:l.path,module:'locations',url:'#/people/locations'},edges:e}}
  case 'role':{const r=await first<{id:string,name:string,description:string}>('SELECT id,name,description FROM roles WHERE id=? AND tenant_id=?',id,tenantId);if(!r)return null;return {node:{type,sourceId:id,title:r.name,summary:r.description,module:'settings',url:`#/admin/roles/${id}`},edges:e}}
  case 'group':{const g=await first<{id:string,name:string,description:string,status:string}>('SELECT id,name,description,status FROM groups WHERE id=? AND tenant_id=?',id,tenantId);if(!g)return null;return {node:{type,sourceId:id,title:g.name,summary:g.description,status:g.status,module:'settings',url:`#/admin/groups/${id}`},edges:e}}
  case 'project':{const p=await first<ProjectRow>('SELECT * FROM projects WHERE id=? AND tenant_id=?',id,tenantId);if(!p)return null;
   add('belongs_to',await deptRef(p.department));add('owns',P(p.owner_id),true);add('manages',P(p.manager_id),true);add('sponsors',P(p.sponsor_id),true);add('located_at',await locRef(p.location));
   for(const m of await all<{member_id:string,role:string}>('SELECT member_id,role FROM project_members WHERE tenant_id=? AND project_id=?',tenantId,id))add('member_of',P(m.member_id),true,{role:m.role});
   for(const b of await all<{id:string}>('SELECT id FROM budgets WHERE tenant_id=? AND project_id=?',tenantId,id))add('funded_by',{type:'budget',sourceId:b.id});
   // Materialize the project's direct context from authoritative links, even when the child nodes have
   // never been browsed/indexed. Child projections use the same orientation, so these upserts are idempotent.
   for(const t of await all<{id:string,milestone:number}>('SELECT id,milestone FROM tasks WHERE tenant_id=? AND project_id=? AND deleted_at IS NULL',tenantId,id))add('belongs_to',{type:t.milestone?'milestone':'task',sourceId:t.id},true);
   for(const r of await all<{id:string,kind:string}>('SELECT id,kind FROM project_records WHERE tenant_id=? AND project_id=? AND deleted_at IS NULL',tenantId,id)){const child=recordKinds[r.kind]||'project_record';add(child==='decision'?'decided_in':'belongs_to',{type:child,sourceId:r.id},true)}
   for(const d of await all<{id:string,kind:string}>('SELECT id,kind FROM purchase_docs WHERE tenant_id=? AND project_id=?',tenantId,id))add('belongs_to',{type:d.kind,sourceId:d.id},true);
   for(const a of await all<{id:string}>('SELECT id FROM assets WHERE tenant_id=? AND project_id=?',tenantId,id))add('belongs_to',{type:'asset',sourceId:a.id},true);
   for(const f of await all<{file_id:string}>('SELECT file_id FROM file_links WHERE tenant_id=? AND entity_type=\'project\' AND entity_id=?',tenantId,id))add('attached_to',{type:'file',sourceId:f.file_id},true);
   return {node:{type,sourceId:id,title:`${p.code} · ${p.name}`,summary:clip(p.description),status:p.stage,ownerId:p.manager_id||p.owner_id,department:p.department,location:p.location,module:'projects',url:`#/projects/${id}`,meta:{health:p.health,progress:p.progress,budget:p.approved_budget,currency:p.currency}},edges:e}}
  case 'project_record':case 'milestone':case 'decision':case 'risk':case 'issue':case 'meeting':{const r=await first<{id:string,project_id:string,kind:string,title:string,body:string,status:string,owner_id:string|null,due_date:string|null,deleted_at:string|null}>('SELECT id,project_id,kind,title,body,status,owner_id,due_date,deleted_at FROM project_records WHERE id=? AND tenant_id=?',id,tenantId);if(!r&&(type==='meeting'||type==='decision')){const {projectWork}=await import('./work');return projectWork(tenantId,id)}if(!r||r.deleted_at)return null;
   const t=recordKinds[r.kind]||'project_record';add(t==='decision'?'decided_in':'belongs_to',{type:'project',sourceId:r.project_id});add('owns',P(r.owner_id),true);
   return {node:{type:t,sourceId:id,title:r.title,summary:clip(r.body),status:r.status,ownerId:r.owner_id,module:'projects',url:`#/projects/${r.project_id}/${['risk','issue','decision','meeting'].includes(r.kind)?'risks':'plan'}`,meta:{kind:r.kind,due:r.due_date,projectId:r.project_id}},edges:e}}
  case 'task':{const t=await first<TaskRow>(`SELECT ${TASK_SELECT} FROM tasks t WHERE t.id=? AND t.tenant_id=?`,id,tenantId);if(!t||t.deleted_at)return null;
   if(t.project_id)add('belongs_to',{type:'project',sourceId:t.project_id});if(t.space_id)add('belongs_to',{type:'space',sourceId:t.space_id});if(t.parent_id)add('part_of',{type:'task',sourceId:t.parent_id});
   for(const a of (t.assignees||'').split(',').filter(Boolean))add('assigned_to',P(a));add('created_by',P(t.created_by));
   for(const d of await all<{depends_on:string}>('SELECT depends_on FROM task_deps WHERE tenant_id=? AND task_id=?',tenantId,id))add('depends_on',{type:'task',sourceId:d.depends_on});
   if(t.source_type&&t.source_id&&['ticket','PR','PO','asset'].includes(t.source_type))add('resulted_in',{type:t.source_type,sourceId:t.source_id},true);
   return {node:{type:t.milestone?'milestone':'task',sourceId:id,title:t.title,summary:clip(t.description),status:t.status,ownerId:t.owner_id,department:t.department,module:'tasks',url:`#/tasks/all/${id}`,meta:{due:t.due_date,priority:t.priority}},edges:e}}
  case 'PR':case 'PO':{const d=await first<PurchaseRow&{pr_id:string|null,project_id:string|null}>('SELECT * FROM purchase_docs WHERE id=? AND tenant_id=?',id,tenantId);if(!d)return null;
   add('requested_by',P(d.requester_id));add('belongs_to',await deptRef(d.department));if(d.project_id)add('belongs_to',{type:'project',sourceId:d.project_id});if(d.vendor_id)add('supplied_by',{type:'vendor',sourceId:d.vendor_id});
   if(d.pr_id)add('purchased_through',{type:'PR',sourceId:d.pr_id},true);if(d.budget_id)add('funded_by',{type:'budget',sourceId:d.budget_id});
   for(const a of await all<{decided_by:string|null,status:string,step_name:string}>("SELECT decided_by,status,step_name FROM approvals WHERE tenant_id=? AND doc_id=? AND status='Approved'",tenantId,id))add('approved_by',P(a.decided_by),false,{step:a.step_name});
   for(const g of await all<{id:string}>('SELECT id FROM goods_receipts WHERE tenant_id=? AND po_id=?',tenantId,id))add('received_through',{type:'receipt',sourceId:g.id});
   for(const a of await all<{id:string}>('SELECT id FROM assets WHERE tenant_id=? AND purchase_doc_id=?',tenantId,id))add('created_asset',{type:'asset',sourceId:a.id});
   return {node:{type:d.kind,sourceId:id,title:`${d.number} · ${d.title}`,summary:clip(d.justification),status:d.status,ownerId:d.requester_id,department:d.department,location:d.location,module:d.kind==='PO'?'procurement':'requests',url:`#/purchasing/${d.kind.toLowerCase()}/${id}`,meta:{total:d.total,currency:d.currency}},edges:e}}
  case 'receipt':{const g=await first<{id:string,po_id:string,number:string,received_by:string,created_at:string,lines_json:string}>('SELECT * FROM goods_receipts WHERE id=? AND tenant_id=?',id,tenantId);if(!g)return null;
   add('created_by',P(g.received_by));return {node:{type,sourceId:id,title:g.number,summary:`Goods receipt for purchase order`,status:'Received',module:'receipts',url:`#/purchasing/po/${g.po_id}`,meta:{poId:g.po_id}},edges:e}}
  case 'vendor':{const v=await first<{id:string,name:string,category:string,status:string}>('SELECT id,name,category,status FROM vendors WHERE id=? AND tenant_id=?',id,tenantId);if(!v)return null;return {node:{type,sourceId:id,title:v.name,summary:v.category,status:v.status,module:'suppliers',url:'#/purchasing/vendors'},edges:e}}
  case 'budget':{const b=await first<{id:string,name:string,department:string,project_id:string|null,amount:number,currency:string,status:string}>('SELECT id,name,department,project_id,amount,currency,status FROM budgets WHERE id=? AND tenant_id=?',id,tenantId);if(!b)return null;
   add('belongs_to',await deptRef(b.department));return {node:{type,sourceId:id,title:b.name,status:b.status,department:b.department,module:'budgets',url:'#/purchasing/budgets',meta:{amount:b.amount,currency:b.currency}},edges:e}}
  case 'asset':{const a=await first<AssetRow&{purchase_doc_id:string|null,project_id:string|null,vendor:string}>('SELECT * FROM assets WHERE id=? AND tenant_id=?',id,tenantId);if(!a)return null;
   add('assigned_to',P(a.assigned_to));add('belongs_to',await deptRef(a.department));add('located_at',await locRef(a.location));if(a.project_id)add('belongs_to',{type:'project',sourceId:a.project_id});
   if(a.purchase_doc_id){const d=await first<{kind:string}>('SELECT kind FROM purchase_docs WHERE id=? AND tenant_id=?',a.purchase_doc_id,tenantId);if(d)add('created_asset',{type:d.kind,sourceId:a.purchase_doc_id},true)}
   if(a.vendor){const v=await first<{id:string}>('SELECT id FROM vendors WHERE tenant_id=? AND lower(name)=lower(?)',tenantId,a.vendor);if(v)add('supplied_by',{type:'vendor',sourceId:v.id})}
   for(const w of await all<{id:string}>('SELECT id FROM work_orders WHERE tenant_id=? AND asset_id=?',tenantId,id))add('maintained_by',{type:'work_order',sourceId:w.id});
   for(const m of await all<{id:string}>('SELECT id FROM maintenance_plans WHERE tenant_id=? AND asset_id=?',tenantId,id))add('maintained_by',{type:'maintenance_plan',sourceId:m.id});
   for(const t of await all<{id:string}>('SELECT id FROM tickets WHERE tenant_id=? AND asset_id=?',tenantId,id))add('related_to',{type:'ticket',sourceId:t.id},true);
   for(const f of await all<{file_id:string}>('SELECT file_id FROM file_links WHERE tenant_id=? AND entity_type=\'asset\' AND entity_id=?',tenantId,id))add('attached_to',{type:'file',sourceId:f.file_id},true);
   return {node:{type,sourceId:id,title:`${a.code} · ${a.name}`,summary:[a.category,a.brand,a.model].filter(Boolean).join(' · '),status:a.status,ownerId:a.assigned_to,department:a.department,location:a.location,module:'assets',url:`#/assets/${id}`,meta:{cost:(a as unknown as {purchase_cost:number}).purchase_cost,warranty:(a as unknown as {warranty_until:string|null}).warranty_until}},edges:e}}
  case 'ticket':{const t=await first<TicketRow>('SELECT * FROM tickets WHERE id=? AND tenant_id=?',id,tenantId);if(!t)return null;
   add('requested_by',P(t.requester_id));add('assigned_to',P(t.assignee_id));add('belongs_to',await deptRef(t.department));if(t.asset_id)add('related_to',{type:'asset',sourceId:t.asset_id});
   return {node:{type,sourceId:id,title:`${t.number} · ${t.title}`,summary:clip(t.description),status:t.status,ownerId:t.assignee_id,department:t.department,location:t.location,module:'maintenance',url:`#/tickets/${id}`,meta:{priority:t.priority}},edges:e}}
  case 'work_order':{const w=await first<{id:string,number:string,title:string,status:string,assignee_id:string|null,department:string,asset_id:string|null,ticket_id:string|null,plan_id:string|null,labor_cost:number,parts_cost:number}>('SELECT id,number,title,status,assignee_id,department,asset_id,ticket_id,plan_id,labor_cost,parts_cost FROM work_orders WHERE id=? AND tenant_id=?',id,tenantId);if(!w)return null;
   add('assigned_to',P(w.assignee_id));if(w.asset_id)add('maintained_by',{type:'asset',sourceId:w.asset_id},true);if(w.ticket_id)add('resulted_in',{type:'ticket',sourceId:w.ticket_id},true);if(w.plan_id)add('part_of',{type:'maintenance_plan',sourceId:w.plan_id});
   return {node:{type,sourceId:id,title:`${w.number} · ${w.title}`,status:w.status,ownerId:w.assignee_id,department:w.department,module:'schedules',url:`#/maintenance/orders/${id}`,meta:{cost:(w.labor_cost||0)+(w.parts_cost||0)}},edges:e}}
  case 'maintenance_plan':{const m=await first<{id:string,title:string,next_due:string|null,active:number,department:string,assignee_id:string|null}>('SELECT id,title,next_due,active,department,assignee_id FROM maintenance_plans WHERE id=? AND tenant_id=?',id,tenantId);if(!m)return null;
   add('assigned_to',P(m.assignee_id));return {node:{type,sourceId:id,title:m.title,status:m.active?'Active':'Paused',department:m.department,module:'schedules',url:'#/maintenance/plans',meta:{nextDue:m.next_due}},edges:e}}
  case 'inventory_item':{const i=await first<{id:string,sku:string,name:string,category:string,status:string}>('SELECT id,sku,name,category,status FROM inventory_items WHERE id=? AND tenant_id=?',id,tenantId);if(!i)return null;
   return {node:{type,sourceId:id,title:`${i.sku} · ${i.name}`,summary:i.category,status:i.status,module:'inventory',url:`#/inventory/items/${id}`},edges:e}}
  case 'file':{const f=await first<FileRow&{owner_id:string|null,space_id:string|null,deleted_at:string|null,processing_status:string}>('SELECT * FROM files WHERE id=? AND tenant_id=?',id,tenantId);if(!f||f.deleted_at)return null;
   add('created_by',P(f.owner_id||f.uploaded_by));if(f.space_id)add('belongs_to',{type:'space',sourceId:f.space_id});
   const typeOf:Record<string,string>={project:'project',task:'task',ticket:'ticket',asset:'asset',PR:'PR',PO:'PO',vendor:'vendor',person:'person',message:'message',page:'page',work_order:'work_order',space:'space',department:'department'};
   for(const l of await all<{entity_type:string,entity_id:string}>('SELECT entity_type,entity_id FROM file_links WHERE tenant_id=? AND file_id=?',tenantId,id))if(typeOf[l.entity_type])add('attached_to',{type:typeOf[l.entity_type],sourceId:l.entity_id});
   return {node:{type,sourceId:id,title:f.name,summary:f.description,status:f.processing_status,ownerId:f.owner_id||f.uploaded_by,department:f.department,module:'documents',url:`#/files/${f.folder_id||'root'}/${id}`,meta:{mime:f.mime}},edges:e}}
  case 'page':{const p=await first<PageRow&{space_id:string|null,author_id:string}>('SELECT * FROM pages WHERE id=? AND tenant_id=?',id,tenantId);if(!p||p.deleted_at)return null;
   add('created_by',P(p.author_id));if(p.space_id)add('belongs_to',{type:'space',sourceId:p.space_id});
   return {node:{type,sourceId:id,title:p.title,summary:clip(p.body,300),status:p.status,ownerId:p.author_id,department:p.department,module:'knowledge',url:`#/spaces/page/${id}`,meta:{kind:p.kind}},edges:e}}
  case 'space':{const s=await first<SpaceRow>('SELECT * FROM spaces WHERE id=? AND tenant_id=?',id,tenantId);if(!s)return null;if(s.project_id)add('belongs_to',{type:'project',sourceId:s.project_id});
   return {node:{type,sourceId:id,title:s.name,summary:s.description,status:s.status,department:s.department,module:'knowledge',url:`#/spaces/${id}`},edges:e}}
  case 'message':{const m=await first<{id:string,channel_id:string,author_id:string,body:string,deleted_at:string|null,hidden:number,created_at:string}>('SELECT id,channel_id,author_id,body,deleted_at,hidden,created_at FROM messages WHERE id=? AND tenant_id=?',id,tenantId);if(!m||m.deleted_at||m.hidden)return null;
   add('created_by',P(m.author_id));
   // Records referenced by link in the message ("mentioned in").
   for(const x of m.body.matchAll(/#\/(projects|tasks\/[a-z-]+|tickets|assets|purchasing\/(?:pr|po)|files\/[\w-]+|spaces\/page)\/([0-9a-f-]{36})/gi)){const kind=x[1].split('/')[0];const t=kind==='projects'?'project':kind==='tasks'?'task':kind==='tickets'?'ticket':kind==='assets'?'asset':kind==='files'?'file':kind==='spaces'?'page':x[1].toLowerCase().endsWith('pr')?'PR':'PO';add('mentioned_in',{type:t,sourceId:x[2]},true)}
   return {node:{type,sourceId:id,title:clip(m.body,120)||'Message',module:'messages',url:`#/messages/${m.channel_id}`,meta:{channelId:m.channel_id}},edges:e}}
  case 'connector':{const c=await first<{id:string,name:string,provider:string,status:string,scope:string,owner_member_id:string|null}>('SELECT id,name,provider,status,scope,owner_member_id FROM connectors WHERE id=? AND tenant_id=?',id,tenantId);if(!c)return null;
   if(c.owner_member_id)add('owns',P(c.owner_member_id),true);return {node:{type,sourceId:id,title:c.name,summary:c.provider,status:c.status,module:'connectors',url:`#/admin/connectors/${id}`,provider:c.provider},edges:e}}
  case 'external':{const r=await first<{id:string,connector_id:string,source_id:string,kind:string,title:string,body:string,url:string,deleted_at:string|null,last_verified_at:string|null,synced_at:string}>('SELECT * FROM connector_records WHERE id=? AND tenant_id=?',id,tenantId);if(!r||r.deleted_at)return null;
   const c=await first<{provider:string,name:string}>('SELECT provider,name FROM connectors WHERE id=? AND tenant_id=?',r.connector_id,tenantId);add('connected_through',{type:'connector',sourceId:r.connector_id});
   for(const l of await all<{entity_type:string,entity_id:string}>('SELECT entity_type,entity_id FROM connector_links WHERE tenant_id=? AND connector_id=? AND external_id=?',tenantId,r.connector_id,r.source_id))add('related_to',{type:l.entity_type,sourceId:l.entity_id});
   return {node:{type,sourceId:id,title:r.title||r.source_id,summary:clip(r.body,300),status:r.kind,module:'connectors',url:r.url||`#/admin/connectors/${r.connector_id}`,provider:c?.provider||null,externalId:r.source_id,syncMode:'synced',lastVerifiedAt:r.last_verified_at||r.synced_at,classification:'external',meta:{connector:c?.name||'',kind:r.kind}},edges:e}}
  case 'studio_record':{const {projectStudioRecord}=await import('./studio');return projectStudioRecord(tenantId,id)}
  case 'agent':{const a=await first<{id:string,name:string,description:string,status:string,owner_id:string}>('SELECT id,name,description,status,owner_id FROM ai_agents WHERE id=? AND tenant_id=?',id,tenantId);if(!a)return null;add('owns',P(a.owner_id),true);
   return {node:{type,sourceId:id,title:a.name,summary:a.description,status:a.status,module:'agents',url:`#/admin/ai/agents/${id}`},edges:e}}
  case 'agent_run':{const r=await first<{id:string,agent_id:string,requested_by:string,status:string,trigger:string,started_at:string}>('SELECT id,agent_id,requested_by,status,trigger,started_at FROM ai_agent_runs WHERE id=? AND tenant_id=?',id,tenantId);if(!r)return null;
   add('generated_by_agent',{type:'agent',sourceId:r.agent_id});add('requested_by',P(r.requested_by));
   return {node:{type,sourceId:id,title:`Agent run ${r.started_at.slice(0,16).replace('T',' ')}`,status:r.status,module:'agents',url:`#/admin/ai/runs/${id}`,meta:{trigger:r.trigger}},edges:e}}
  case 'automation_run':{const r=await first<{id:string,app_id:string,automation_id:string,status:string,trigger:string,started_at:string}>('SELECT id,app_id,automation_id,status,trigger,started_at FROM studio_automation_runs WHERE id=? AND tenant_id=?',id,tenantId);if(!r)return null;
   return {node:{type,sourceId:id,title:`Automation ${r.automation_id} · ${r.trigger}`,status:r.status,module:'studio',url:`#/studio/apps/${r.app_id}/automations`},edges:e}}
 }
 return null;
}

// Which table an audited record id belongs to (ids are UUIDs, unique across tables).
export async function resolveType(tenantId:string,id:string):Promise<string|null>{
 if(!/^[0-9a-f-]{8,40}$/i.test(id))return null;
 // Use CASE/EXISTS rather than a large UNION ALL: D1/SQLite limits compound SELECT terms,
 // and a source-type lookup must continue working as the graph adds more module types.
 const r=await first<{t:string|null}>(`SELECT CASE
  WHEN EXISTS(SELECT 1 FROM tickets WHERE id=?1 AND tenant_id=?2) THEN 'ticket'
  WHEN EXISTS(SELECT 1 FROM assets WHERE id=?1 AND tenant_id=?2) THEN 'asset'
  WHEN EXISTS(SELECT 1 FROM purchase_docs WHERE id=?1 AND tenant_id=?2) THEN (SELECT kind FROM purchase_docs WHERE id=?1 AND tenant_id=?2 LIMIT 1)
  WHEN EXISTS(SELECT 1 FROM projects WHERE id=?1 AND tenant_id=?2) THEN 'project'
  WHEN EXISTS(SELECT 1 FROM tasks WHERE id=?1 AND tenant_id=?2) THEN 'task'
  WHEN EXISTS(SELECT 1 FROM project_records WHERE id=?1 AND tenant_id=?2) THEN 'project_record'
  WHEN EXISTS(SELECT 1 FROM files WHERE id=?1 AND tenant_id=?2) THEN 'file'
  WHEN EXISTS(SELECT 1 FROM pages WHERE id=?1 AND tenant_id=?2) THEN 'page'
  WHEN EXISTS(SELECT 1 FROM members WHERE id=?1 AND tenant_id=?2) THEN 'person'
  WHEN EXISTS(SELECT 1 FROM departments WHERE id=?1 AND tenant_id=?2) THEN 'department'
  WHEN EXISTS(SELECT 1 FROM locations WHERE id=?1 AND tenant_id=?2) THEN 'location'
  WHEN EXISTS(SELECT 1 FROM vendors WHERE id=?1 AND tenant_id=?2) THEN 'vendor'
  WHEN EXISTS(SELECT 1 FROM budgets WHERE id=?1 AND tenant_id=?2) THEN 'budget'
  WHEN EXISTS(SELECT 1 FROM work_orders WHERE id=?1 AND tenant_id=?2) THEN 'work_order'
  WHEN EXISTS(SELECT 1 FROM maintenance_plans WHERE id=?1 AND tenant_id=?2) THEN 'maintenance_plan'
  WHEN EXISTS(SELECT 1 FROM inventory_items WHERE id=?1 AND tenant_id=?2) THEN 'inventory_item'
  WHEN EXISTS(SELECT 1 FROM groups WHERE id=?1 AND tenant_id=?2) THEN 'group'
  WHEN EXISTS(SELECT 1 FROM roles WHERE id=?1 AND tenant_id=?2) THEN 'role'
  WHEN EXISTS(SELECT 1 FROM spaces WHERE id=?1 AND tenant_id=?2) THEN 'space'
  WHEN EXISTS(SELECT 1 FROM studio_records WHERE id=?1 AND tenant_id=?2) THEN 'studio_record'
  WHEN EXISTS(SELECT 1 FROM connectors WHERE id=?1 AND tenant_id=?2) THEN 'connector'
  WHEN EXISTS(SELECT 1 FROM ai_agents WHERE id=?1 AND tenant_id=?2) THEN 'agent'
  WHEN EXISTS(SELECT 1 FROM work_records WHERE id=?1 AND tenant_id=?2) THEN 'work_record'
  ELSE NULL END AS t`,id,tenantId);
 return r?.t||null;
}

async function nodeId(tenantId:string,ref:Ref){return (await first<{id:string}>('SELECT id FROM graph_nodes WHERE tenant_id=? AND type=? AND source_id=?',tenantId,ref.type,ref.sourceId))?.id||null}
function upsertStatement(tenantId:string,id:string,n:NodeSpec){
 const ts=now();const search=[n.title,n.summary,n.status,n.department,n.location,n.search].filter(Boolean).join(' ').toLowerCase().slice(0,2000);
 return stmt(`INSERT INTO graph_nodes(id,tenant_id,type,source_id,title,summary,status,owner_id,department,location,module,url,classification,search_text,provider,external_id,sync_mode,last_verified_at,meta_json,created_at,updated_at,deleted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NULL)
  ON CONFLICT(tenant_id,type,source_id) DO UPDATE SET title=excluded.title,summary=excluded.summary,status=excluded.status,owner_id=excluded.owner_id,department=excluded.department,location=excluded.location,module=excluded.module,url=excluded.url,classification=excluded.classification,search_text=excluded.search_text,provider=excluded.provider,external_id=excluded.external_id,sync_mode=excluded.sync_mode,last_verified_at=excluded.last_verified_at,meta_json=excluded.meta_json,updated_at=excluded.updated_at,deleted_at=NULL`,
  id,tenantId,n.type,n.sourceId,clip(n.title,300),clip(n.summary,600),clip(n.status,60),n.ownerId||null,n.department||'',n.location||'',n.module,n.url,n.classification||'internal',search,n.provider||null,n.externalId||null,n.syncMode||null,n.lastVerifiedAt||null,JSON.stringify(n.meta||{}),ts,ts);
}
// A node for a referenced record (title only) so edges always have both ends; its own edges follow via an event.
async function ensureNode(tenantId:string,ref:Ref):Promise<string|null>{
 const have=await nodeId(tenantId,ref);if(have)return have;
 const p=await projectRecord(tenantId,ref.type,ref.sourceId).catch(()=>null);if(!p)return null;
 const id=uid();await batch([upsertStatement(tenantId,id,p.node),stmt("INSERT INTO domain_events(id,tenant_id,type,entity_id,action,actor,payload_json,status,attempts,error,created_at) VALUES(?,?,'project',?,?,'system',?,'pending',0,'',?)",uid(),tenantId,ref.sourceId,ref.type,JSON.stringify({type:p.node.type}),now())]);
 return (await nodeId(tenantId,{type:p.node.type,sourceId:ref.sourceId}))||id;
}
// Rebuilds one record's node and derived relationships. Safe to repeat (idempotent) and to run concurrently.
export async function syncNode(tenantId:string,type:string,sourceId:string){
 const p=await projectRecord(tenantId,type,sourceId);
 if(!p){await run('UPDATE graph_nodes SET deleted_at=coalesce(deleted_at,?) WHERE tenant_id=? AND source_id=? AND type IN (?,?,?,?,?,?)',now(),tenantId,sourceId,type,'task','milestone','project_record','decision','risk');return null}
 // A record can change node type (task ↔ milestone, plan item kinds): retire the other projection.
 await run('UPDATE graph_nodes SET deleted_at=? WHERE tenant_id=? AND source_id=? AND type<>? AND deleted_at IS NULL',now(),tenantId,sourceId,p.node.type);
 await upsertStatement(tenantId,uid(),p.node).run();
 const me=(await nodeId(tenantId,{type:p.node.type,sourceId}))!;
 const s:D1PreparedStatement[]=[stmt("UPDATE graph_edges SET removed_at=? WHERE tenant_id=? AND (src_id=? OR dst_id=?) AND origin='event' AND removed_at IS NULL AND json_extract(meta_json,'$.from')=?",now(),tenantId,me,me,me)];
 for(const e of p.edges){const other=await ensureNode(tenantId,e.to);if(!other||other===me)continue;const [src,dst]=e.reverse?[other,me]:[me,other];
  s.push(stmt("INSERT INTO graph_edges(id,tenant_id,src_id,dst_id,type,origin,created_by,confidence,effective_at,expires_at,meta_json,created_at,removed_at) VALUES(?,?,?,?,?,'event','system',NULL,?,NULL,?,?,NULL) ON CONFLICT(tenant_id,src_id,dst_id,type) DO UPDATE SET removed_at=NULL,meta_json=excluded.meta_json",uid(),tenantId,src,dst,e.type,now(),JSON.stringify({...(e.meta||{}),from:me}),now()))}
 for(let i=0;i<s.length;i+=90)await batch(s.slice(i,i+90));
 return me;
}

// ── Visibility: every node is re-checked against its module's own rule ──────
type Row=Record<string,unknown>;
export async function visibleNodes(u:Member,nodes:GraphNode[]):Promise<Set<string>>{
 const ok=new Set<string>();if(!nodes.length)return ok;
 const byType=new Map<string,GraphNode[]>();for(const n of nodes){if(n.deleted_at)continue;byType.set(n.type,[...(byType.get(n.type)||[]),n])}
 const ids=(l:GraphNode[])=>l.map(n=>n.source_id);const IN=(l:unknown[])=>l.map(()=>'?').join(',');
 const pass=(l:GraphNode[],f:(n:GraphNode)=>boolean)=>{for(const n of l)if(f(n))ok.add(n.id)};
 const rows=async<T>(sql:string,l:GraphNode[])=>{const out=new Map<string,T>();const list=ids(l);for(let i=0;i<list.length;i+=90){const part=list.slice(i,i+90);for(const r of await all<T&{id:string}>(sql.replace('%IN%',IN(part)),u.tenantId,...part))out.set(r.id,r)}return out};
 for(const [type,grouped] of byType){
  let l=grouped;
  switch(type){
   case 'person':pass(l,n=>hasAction(u,'people')||n.source_id===u.id);break;
   case 'department':case 'location':pass(l,()=>hasAction(u,'people')||hasAction(u,'locations')||u.role==='admin');break;
   case 'role':pass(l,()=>u.role==='admin'||hasAction(u,'settings','configure'));break;
   case 'group':{const m=await rows<{id:string,visibility:string,status:string}>('SELECT id,visibility,status FROM groups WHERE tenant_id=? AND id IN (%IN%)',l);pass(l,n=>{const g=m.get(n.source_id);return !!g&&(u.role==='admin'||u.groupIds?.includes(g.id)||(g.visibility==='company'&&g.status==='active'))});break}
   case 'project':{const m=await rows<ProjectRow>('SELECT * FROM projects WHERE tenant_id=? AND id IN (%IN%)',l);pass(l,n=>{const p=m.get(n.source_id);return !!p&&canSeeProject(u,p)});break}
   case 'goal':case 'objective':case 'initiative':case 'customer':case 'contract':case 'service':{const {visibleWork}=await import('./work');const vis=await visibleWork(u,ids(l));pass(l,n=>vis.has(n.source_id));break}
   case 'project_record':case 'milestone':case 'decision':case 'risk':case 'issue':case 'meeting':case 'task':{
    const biz=l.filter(n=>n.module==='business');if(biz.length){const {visibleWork}=await import('./work');const vis=await visibleWork(u,ids(biz));pass(biz,n=>vis.has(n.source_id))}l=l.filter(n=>n.module!=='business');
    const recs=l.filter(n=>n.module==='projects'&&type!=='task'&&!(type==='milestone'&&n.url.startsWith('#/tasks')));const tasks=l.filter(n=>!recs.includes(n));
    if(recs.length){const pr=await rows<{id:string,project_id:string}>('SELECT id,project_id FROM project_records WHERE tenant_id=? AND deleted_at IS NULL AND id IN (%IN%)',recs);const projects=new Map((await all<ProjectRow>(`SELECT * FROM projects WHERE tenant_id=? AND id IN (${IN([...new Set([...pr.values()].map(r=>r.project_id))])||"''"})`,u.tenantId,...new Set([...pr.values()].map(r=>r.project_id)))).map(p=>[p.id,p]));pass(recs,n=>{const r=pr.get(n.source_id);const p=r&&projects.get(r.project_id);return !!p&&canSeeProject(u,p)})}
    if(tasks.length){const tr=[...(await rows<TaskRow>(`SELECT ${TASK_SELECT} FROM tasks t WHERE t.tenant_id=? AND t.deleted_at IS NULL AND t.id IN (%IN%)`,tasks)).values()];const ctx=await taskContext(u,tr);const vis=new Set(tr.filter(t=>canSeeTask(u,t,ctx.projects,ctx.spaces)).map(t=>t.id));pass(tasks,n=>vis.has(n.source_id))}
    break}
   case 'PR':case 'PO':{const m=await rows<PurchaseRow>("SELECT d.*,(SELECT group_concat(j.value) FROM approvals a, json_each(a.approver_ids) j WHERE a.doc_id=d.id AND a.tenant_id=d.tenant_id) AS approver_ids FROM purchase_docs d WHERE d.tenant_id=? AND d.id IN (%IN%)",l);pass(l,n=>{const d=m.get(n.source_id);return !!d&&canSeeDoc(u,d)});break}
   case 'receipt':{const g=await rows<{id:string,po_id:string}>('SELECT id,po_id FROM goods_receipts WHERE tenant_id=? AND id IN (%IN%)',l);const poIds=[...new Set([...g.values()].map(x=>x.po_id))];const pos=new Map((poIds.length?await all<PurchaseRow>(`SELECT d.*,(SELECT group_concat(j.value) FROM approvals a, json_each(a.approver_ids) j WHERE a.doc_id=d.id AND a.tenant_id=d.tenant_id) AS approver_ids FROM purchase_docs d WHERE d.tenant_id=? AND d.id IN (${IN(poIds)})`,u.tenantId,...poIds):[]).map(d=>[d.id,d]));pass(l,n=>{const r=g.get(n.source_id);const d=r&&pos.get(r.po_id);return !!d&&canSeeDoc(u,d)&&(hasAction(u,'receipts')||hasAction(u,'procurement')||d.requester_id===u.id)});break}
   case 'vendor':pass(l,()=>hasAction(u,'suppliers')||hasAction(u,'procurement')||hasAction(u,'requests'));break;
   case 'budget':{const m=await rows<{id:string,department:string,created_by:string}>('SELECT id,department,created_by FROM budgets WHERE tenant_id=? AND id IN (%IN%)',l);pass(l,n=>{const b=m.get(n.source_id);return !!b&&canActOn(u,'budgets','view',b.department,b.created_by)});break}
   case 'asset':{const m=await rows<AssetRow>('SELECT * FROM assets WHERE tenant_id=? AND id IN (%IN%)',l);pass(l,n=>{const a=m.get(n.source_id);return !!a&&canSeeAsset(u,a)});break}
   case 'ticket':{const m=await rows<TicketRow>('SELECT * FROM tickets WHERE tenant_id=? AND id IN (%IN%)',l);pass(l,n=>{const t=m.get(n.source_id);return !!t&&canSeeTicket(u,t)});break}
   case 'work_order':{const m=await rows<{id:string,department:string,assignee_id:string|null,created_by:string}>('SELECT id,department,assignee_id,created_by FROM work_orders WHERE tenant_id=? AND id IN (%IN%)',l);pass(l,n=>{const w=m.get(n.source_id);return !!w&&(w.assignee_id===u.id||canActOn(u,'schedules','view',w.department||u.department,w.created_by))});break}
   case 'maintenance_plan':{const m=await rows<{id:string,department:string,created_by:string}>('SELECT id,department,created_by FROM maintenance_plans WHERE tenant_id=? AND id IN (%IN%)',l);pass(l,n=>{const p=m.get(n.source_id);return !!p&&canActOn(u,'schedules','view',p.department||u.department,p.created_by)});break}
   case 'inventory_item':pass(l,()=>hasAction(u,'inventory'));break;
   case 'file':{const m=await rows<FileRow>('SELECT * FROM files WHERE tenant_id=? AND id IN (%IN%)',l);pass(l,n=>{const f=m.get(n.source_id);return !!f&&canSeeFile(u,f)});break}
   case 'page':{const m=await rows<PageRow>('SELECT * FROM pages WHERE tenant_id=? AND id IN (%IN%)',l);pass(l,n=>{const p=m.get(n.source_id);return !!p&&canSeePage(u,p)});break}
   case 'space':{const m=await rows<SpaceRow>('SELECT * FROM spaces WHERE tenant_id=? AND id IN (%IN%)',l);pass(l,n=>{const s=m.get(n.source_id);return !!s&&canSeeSpace(u,s)});break}
   case 'message':{const m=await rows<{id:string,channel_id:string}>('SELECT id,channel_id FROM messages WHERE tenant_id=? AND deleted_at IS NULL AND hidden=0 AND id IN (%IN%)',l);const chans=[...new Set([...m.values()].map(x=>x.channel_id))];const allowed=new Set<string>();
    for(const c of chans.length?await all<ChannelRow>(`SELECT * FROM channels WHERE tenant_id=? AND id IN (${IN(chans)})`,u.tenantId,...chans):[])if(await canAccessChannel(u,c))allowed.add(c.id);pass(l,n=>{const x=m.get(n.source_id);return !!x&&allowed.has(x.channel_id)});break}
   case 'connector':case 'external':{const {canUseConnector}=await import('./connectors');
    const recs=type==='external'?await rows<{id:string,connector_id:string,permissions_json:string}>('SELECT id,connector_id,permissions_json FROM connector_records WHERE tenant_id=? AND deleted_at IS NULL AND id IN (%IN%)',l):new Map<string,{id:string,connector_id:string,permissions_json:string}>();
    const cids=[...new Set(type==='external'?[...recs.values()].map(r=>r.connector_id):ids(l))];
    const cons=new Map((cids.length?await all<Row&{id:string}>(`SELECT * FROM connectors WHERE tenant_id=? AND id IN (${IN(cids)})`,u.tenantId,...cids):[]).map(c=>[c.id,c]));
    const may=(cid:string)=>{const c=cons.get(cid);if(!c)return false;if(c.scope==='user')return c.owner_member_id===u.id;return u.role==='admin'||hasAction(u,'connectors','configure')||canUseConnector(u,c as never,'app-pages')||canUseConnector(u,c as never,'assistant')};
    pass(l,n=>{if(type==='connector')return may(n.source_id);const r=recs.get(n.source_id);if(!r||!may(r.connector_id))return false;const p=JSON.parse(r.permissions_json||'{}') as {people?:string[],departments?:string[]};if(p.people?.length&&!p.people.includes(u.id)&&u.role!=='admin')return false;if(p.departments?.length&&!p.departments.some(d=>d.toLowerCase()===u.department.toLowerCase())&&u.role!=='admin')return false;return true});break}
   case 'studio_record':{const {visibleStudioRecords}=await import('./studio');const vis=await visibleStudioRecords(u,ids(l));pass(l,n=>vis.has(n.source_id));break}
   case 'agent':pass(l,()=>hasAction(u,'agents'));break;
   case 'agent_run':{const m=await rows<{id:string,requested_by:string}>('SELECT id,requested_by FROM ai_agent_runs WHERE tenant_id=? AND id IN (%IN%)',l);pass(l,n=>{const r=m.get(n.source_id);return !!r&&(r.requested_by===u.id||u.role==='admin'||hasAction(u,'agents','configure'))});break}
   case 'automation_run':pass(l,()=>u.role==='admin'||hasAction(u,'studio','configure'));break;
  }
 }
 return ok;
}

// ── Reading the graph ───────────────────────────────────────────────────────
const live="removed_at IS NULL AND (expires_at IS NULL OR expires_at>?)";
export async function findNode(u:Member,type:string,sourceId:string){
 let n=await first<GraphNode>('SELECT * FROM graph_nodes WHERE tenant_id=? AND source_id=? AND (type=? OR ?) AND deleted_at IS NULL ORDER BY type=? DESC LIMIT 1',u.tenantId,sourceId,type,type==='any'?1:0,type);
 // Refresh the selected root from its authoritative source on open. Events provide background freshness;
 // this bounded read-through also repairs a missed/delayed child event without requiring an admin rebuild.
 if(n){if(!(await visibleNodes(u,[n])).has(n.id))throw new HttpError(404,'Record not found.');await syncNode(u.tenantId,n.type,sourceId).catch(()=>null);n=await first<GraphNode>('SELECT * FROM graph_nodes WHERE tenant_id=? AND source_id=? AND (type=? OR ?) AND deleted_at IS NULL ORDER BY type=? DESC LIMIT 1',u.tenantId,sourceId,type,type==='any'?1:0,type)}
 // Records created before the graph existed are projected on first use.
 else if(type!=='any'){await syncNode(u.tenantId,type,sourceId).catch(()=>null);n=await first<GraphNode>('SELECT * FROM graph_nodes WHERE tenant_id=? AND source_id=? AND deleted_at IS NULL LIMIT 1',u.tenantId,sourceId)}
 if(!n||!(await visibleNodes(u,[n])).has(n.id))throw new HttpError(404,'Record not found.');
 return n;
}
export type GraphOpts={depth?:number,types?:string[],relationships?:string[],from?:string,to?:string,department?:string,location?:string,limit?:number};
// Breadth-first context around a node. Hidden nodes are skipped (and never used as stepping stones); only a
// count of restricted neighbours is returned, never their type or title.
export async function context(u:Member,root:GraphNode,o:GraphOpts={}){
 const depth=Math.min(3,Math.max(1,o.depth||1));const limit=Math.min(400,o.limit||200);const ts=now();
 const nodes=new Map<string,GraphNode>([[root.id,root]]);const edges=new Map<string,GraphEdge>();let restricted=0;let frontier=[root.id];
 for(let d=0;d<depth&&frontier.length&&nodes.size<limit;d++){
  const next:string[]=[];
  for(let i=0;i<frontier.length;i+=45){const part=frontier.slice(i,i+45);const q=part.map(()=>'?').join(',');
   const es=await all<GraphEdge>(`SELECT * FROM graph_edges WHERE tenant_id=? AND ${live} AND (src_id IN (${q}) OR dst_id IN (${q}))${o.relationships?.length?` AND type IN (${o.relationships.map(()=>'?').join(',')})`:''} LIMIT 600`,u.tenantId,ts,...part,...part,...(o.relationships||[]));
   const otherIds=[...new Set(es.flatMap(e=>[e.src_id,e.dst_id]).filter(x=>!nodes.has(x)))];
   const others=otherIds.length?await all<GraphNode>(`SELECT * FROM graph_nodes WHERE tenant_id=? AND deleted_at IS NULL AND id IN (${otherIds.map(()=>'?').join(',')})`,u.tenantId,...otherIds):[];
   const vis=await visibleNodes(u,others);
   for(const n of others){if(!vis.has(n.id)){restricted++;continue}if(o.types?.length&&!o.types.includes(n.type))continue;if(o.department&&n.department.toLowerCase()!==o.department.toLowerCase())continue;if(o.location&&!n.location.toLowerCase().startsWith(o.location.toLowerCase()))continue;if(o.from&&n.updated_at<o.from)continue;if(o.to&&n.created_at>o.to)continue;if(nodes.size>=limit)break;nodes.set(n.id,n);next.push(n.id)}
   for(const e of es)if(nodes.has(e.src_id)&&nodes.has(e.dst_id))edges.set(e.id,e);
  }
  frontier=next;
 }
 return {root:shape(root),nodes:[...nodes.values()].map(shape),edges:[...edges.values()].map(shapeEdge),restricted};
}
export const shape=(n:GraphNode)=>({id:n.id,type:n.type,label:NODE_LABELS[n.type]||n.type,sourceId:n.source_id,title:n.title,summary:n.summary,status:n.status,department:n.department,location:n.location,module:n.module,url:n.url,classification:n.classification,provider:n.provider,externalId:n.external_id,syncMode:n.sync_mode,lastVerifiedAt:n.last_verified_at,meta:JSON.parse(n.meta_json||'{}'),createdAt:n.created_at,updatedAt:n.updated_at});
const shapeEdge=(e:GraphEdge)=>({id:e.id,src:e.src_id,dst:e.dst_id,type:e.type,label:RELATIONSHIPS[e.type]?.label||e.type.replace(/_/g,' '),inverseLabel:RELATIONSHIPS[e.type]?.inverse||e.type.replace(/_/g,' '),origin:e.origin,confidence:e.confidence,createdAt:e.created_at,meta:(()=>{const m=JSON.parse(e.meta_json||'{}');delete m.from;return m})()});

// Shortest path between two visible nodes, explained in words. Hidden nodes are never traversed.
export async function explainPath(u:Member,a:GraphNode,b:GraphNode,maxDepth=5){
 const ts=now();const prev=new Map<string,{from:string,edge:GraphEdge}>();const seen=new Set([a.id]);let frontier=[a.id];const cache=new Map<string,GraphNode>([[a.id,a],[b.id,b]]);
 for(let d=0;d<maxDepth&&frontier.length&&!seen.has(b.id);d++){
  const q=frontier.map(()=>'?').join(',');const es=await all<GraphEdge>(`SELECT * FROM graph_edges WHERE tenant_id=? AND ${live} AND (src_id IN (${q}) OR dst_id IN (${q})) LIMIT 2000`,u.tenantId,ts,...frontier,...frontier);
  const cand=[...new Set(es.flatMap(e=>[e.src_id,e.dst_id]).filter(x=>!seen.has(x)))].slice(0,500);
  const ns=cand.length?await all<GraphNode>(`SELECT * FROM graph_nodes WHERE tenant_id=? AND deleted_at IS NULL AND id IN (${cand.map(()=>'?').join(',')})`,u.tenantId,...cand):[];
  const vis=await visibleNodes(u,ns);for(const n of ns)cache.set(n.id,n);
  const next:string[]=[];
  for(const e of es){for(const [from,to] of [[e.src_id,e.dst_id],[e.dst_id,e.src_id]]){if(frontier.includes(from)&&!seen.has(to)&&vis.has(to)){seen.add(to);prev.set(to,{from,edge:e});next.push(to)}}}
  frontier=next;
 }
 if(!seen.has(b.id))return {found:false,steps:[],sentence:'No connection was found among the records you can see.'};
 const steps:{from:ReturnType<typeof shape>,to:ReturnType<typeof shape>,relationship:string,label:string}[]=[];
 for(let c=b.id;c!==a.id;){const p=prev.get(c)!;const e=p.edge;const forward=e.src_id===p.from;const rel=RELATIONSHIPS[e.type];steps.unshift({from:shape(cache.get(p.from)!),to:shape(cache.get(c)!),relationship:e.type,label:forward?rel?.label||e.type:rel?.inverse||e.type});c=p.from}
 return {found:true,steps,sentence:steps.map(s=>`${s.from.title} ${s.label} ${s.to.title}`).join('; ')+'.'};
}
export async function searchNodes(u:Member,q:string,types:string[]=[],limit=30){
 const terms=q.toLowerCase().split(/\s+/).filter(t=>t.length>1).slice(0,5);if(!terms.length)return [];
 const rows=await all<GraphNode>(`SELECT * FROM graph_nodes WHERE tenant_id=? AND deleted_at IS NULL ${terms.map(()=>'AND instr(search_text,?)>0').join(' ')}${types.length?` AND type IN (${types.map(()=>'?').join(',')})`:''} ORDER BY updated_at DESC LIMIT 300`,u.tenantId,...terms,...types);
 const vis=await visibleNodes(u,rows);return rows.filter(r=>vis.has(r.id)).slice(0,limit).map(shape);
}
// Permission-aware index view used by the Explorer before a search is entered.
export async function browseNodes(u:Member,types:string[]=[],limit=60){
 const rows=await all<GraphNode>(`SELECT * FROM graph_nodes WHERE tenant_id=? AND deleted_at IS NULL${types.length?` AND type IN (${types.map(()=>'?').join(',')})`:''} ORDER BY updated_at DESC LIMIT 500`,u.tenantId,...types);
 // Existing workspaces predate the graph projection. Start a durable, idempotent backfill on first
 // browse rather than silently presenting an empty graph. Each job handles one bounded table chunk.
 if(!rows.length){
  const active=await first<{id:string}>("SELECT id FROM jobs WHERE tenant_id=? AND kind='graph.rebuild' AND status IN ('queued','retrying','running') LIMIT 1",u.tenantId);
  const done=await first<{id:string}>("SELECT id FROM jobs WHERE tenant_id=? AND kind='graph.rebuild' AND status='done' ORDER BY updated_at DESC LIMIT 1",u.tenantId);
  if(!active&&!done){
   const {enqueueStatement}=await import('./jobs');
   await enqueueStatement(u.tenantId,'graph.rebuild','0:0',{table:0,offset:0},{key:'graph-rebuild:0:0',maxAttempts:5}).run();
  }
 }
 const vis=await visibleNodes(u,rows);return rows.filter(r=>vis.has(r.id)).slice(0,Math.min(100,Math.max(1,limit))).map(shape);
}
export async function graphIndexing(tenantId:string){
 const job=await first<{status:string,stage:string}>("SELECT status,stage FROM jobs WHERE tenant_id=? AND kind='graph.rebuild' AND status IN ('queued','retrying','running') ORDER BY created_at LIMIT 1",tenantId);
 if(job&&job.status!=='running')(await import('./jobs')).kick(1);
 return job?{active:true,stage:job.stage}: {active:false,stage:''};
}
// Relationships added by people, AI suggestions (with confidence) and connectors. Both ends must be visible.
export async function addRelationship(u:Member,src:GraphNode,dst:GraphNode,type:string,origin:'user'|'ai'|'connector',o:{confidence?:number,expiresAt?:string|null,effectiveAt?:string|null,meta?:Record<string,unknown>}={}){
 if(!RELATIONSHIPS[type])throw new HttpError(400,'Choose a known relationship type.');if(src.id===dst.id)throw new HttpError(400,'A record cannot be related to itself.');
 const id=uid();await batch([stmt('INSERT INTO graph_edges(id,tenant_id,src_id,dst_id,type,origin,created_by,confidence,effective_at,expires_at,meta_json,created_at,removed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,NULL) ON CONFLICT(tenant_id,src_id,dst_id,type) DO UPDATE SET removed_at=NULL,origin=excluded.origin,created_by=excluded.created_by,confidence=excluded.confidence,expires_at=excluded.expires_at',id,u.tenantId,src.id,dst.id,type,origin,u.id,o.confidence??null,o.effectiveAt||now(),o.expiresAt||null,JSON.stringify(o.meta||{}),now()),
  stmt('INSERT INTO audit(id,action,actor,record_id,department,before_json,after_json,created_at,tenant_id,support_session_id) VALUES(?,?,?,?,?,NULL,?,?,?,?)',uid(),`Relationship added (${origin})`,u.id,src.source_id,src.department||'',JSON.stringify({type,to:dst.source_id,confidence:o.confidence??null}),now(),u.tenantId,u.supportSessionId||null)]);
 return id;
}
export async function removeRelationship(u:Member,edgeId:string){
 const e=await first<GraphEdge>('SELECT * FROM graph_edges WHERE id=? AND tenant_id=? AND removed_at IS NULL',edgeId,u.tenantId);if(!e)throw new HttpError(404,'Relationship not found.');
 if(e.origin==='event')throw new HttpError(409,'This relationship comes from the records themselves; change the record instead.');
 const ns=await all<GraphNode>('SELECT * FROM graph_nodes WHERE tenant_id=? AND id IN (?,?)',u.tenantId,e.src_id,e.dst_id);const vis=await visibleNodes(u,ns);if(ns.length<2||ns.some(n=>!vis.has(n.id)))throw new HttpError(404,'Relationship not found.');
 if(e.created_by!==u.id&&u.role!=='admin')throw new HttpError(403,'Only the person who added it or an administrator can remove it.');
 await batch([stmt('UPDATE graph_edges SET removed_at=? WHERE id=? AND tenant_id=?',now(),e.id,u.tenantId),stmt('INSERT INTO audit(id,action,actor,record_id,department,before_json,after_json,created_at,tenant_id,support_session_id) VALUES(?,?,?,?,?,?,NULL,?,?,?)',uid(),'Relationship removed',u.id,ns[0].source_id,'',JSON.stringify({type:e.type}),now(),u.tenantId,u.supportSessionId||null)]);
}
// Integrity: edges pointing at retired nodes, and nodes whose source record no longer exists.
export async function brokenRelationships(u:Member){
 const edges=await all<{id:string,type:string,src:string,dst:string}>("SELECT e.id,e.type,s.title AS src,d.title AS dst FROM graph_edges e JOIN graph_nodes s ON s.id=e.src_id JOIN graph_nodes d ON d.id=e.dst_id WHERE e.tenant_id=? AND e.removed_at IS NULL AND (s.deleted_at IS NOT NULL OR d.deleted_at IS NOT NULL) LIMIT 200",u.tenantId);
 const expired=await first<{n:number}>('SELECT count(*) AS n FROM graph_edges WHERE tenant_id=? AND removed_at IS NULL AND expires_at IS NOT NULL AND expires_at<=?',u.tenantId,now());
 const dangling=await first<{n:number}>('SELECT count(*) AS n FROM graph_edges e WHERE e.tenant_id=? AND e.removed_at IS NULL AND (NOT EXISTS(SELECT 1 FROM graph_nodes n WHERE n.id=e.src_id) OR NOT EXISTS(SELECT 1 FROM graph_nodes n WHERE n.id=e.dst_id))',u.tenantId);
 return {toRetiredNodes:edges,expired:expired?.n||0,dangling:dangling?.n||0};
}
export async function pruneBroken(u:Member){return run('UPDATE graph_edges SET removed_at=? WHERE tenant_id=? AND removed_at IS NULL AND (src_id IN (SELECT id FROM graph_nodes WHERE tenant_id=? AND deleted_at IS NOT NULL) OR dst_id IN (SELECT id FROM graph_nodes WHERE tenant_id=? AND deleted_at IS NOT NULL) OR NOT EXISTS(SELECT 1 FROM graph_nodes n WHERE n.id=src_id) OR NOT EXISTS(SELECT 1 FROM graph_nodes n WHERE n.id=dst_id))',now(),u.tenantId,u.tenantId,u.tenantId)}
export async function graphStats(tenantId:string){
 const [nodes,edges,pending,failed,deferred]=await Promise.all([all<{type:string,n:number}>('SELECT type,count(*) AS n FROM graph_nodes WHERE tenant_id=? AND deleted_at IS NULL GROUP BY type ORDER BY n DESC',tenantId),first<{n:number}>('SELECT count(*) AS n FROM graph_edges WHERE tenant_id=? AND removed_at IS NULL',tenantId),first<{n:number}>("SELECT count(*) AS n FROM domain_events WHERE tenant_id=? AND status IN ('pending','processing','retrying')",tenantId),first<{n:number}>("SELECT count(*) AS n FROM domain_events WHERE tenant_id=? AND status='failed'",tenantId),first<{n:number}>("SELECT count(*) AS n FROM domain_events WHERE tenant_id=? AND status='deferred'",tenantId)]);
 return {nodes,edges:edges?.n||0,pendingEvents:pending?.n||0,failedEvents:failed?.n||0,deferredEvents:deferred?.n||0};
}
// Full, resumable rebuild: one job per table chunk re-projects every record (safe to run repeatedly).
export const REBUILD_TABLES:[string,string,string][]=[['work_records','work_record','AND deleted_at IS NULL'],['members','person',''],['departments','department',''],['locations','location',''],['groups','group',''],['vendors','vendor',''],['budgets','budget',''],['projects','project',''],['project_records','project_record','AND deleted_at IS NULL'],['tasks','task','AND deleted_at IS NULL'],['purchase_docs','doc',''],['goods_receipts','receipt',''],['assets','asset',''],['tickets','ticket',''],['work_orders','work_order',''],['maintenance_plans','maintenance_plan',''],['inventory_items','inventory_item',''],['files','file','AND deleted_at IS NULL'],['pages','page','AND deleted_at IS NULL'],['spaces','space',''],['connectors','connector',''],['connector_records','external','AND deleted_at IS NULL'],['studio_records','studio_record','AND deleted_at IS NULL'],['ai_agents','agent','']];
export async function rebuildChunk(tenantId:string,tableIndex:number,offset:number){
 const t=REBUILD_TABLES[tableIndex];if(!t)return null;const [table,type,where]=t;
 const rows=await all<{id:string,kind?:string}>(`SELECT id${table==='purchase_docs'?',kind':''} FROM ${table} WHERE tenant_id=? ${where} ORDER BY id LIMIT 60 OFFSET ?`,tenantId,offset);
 for(const r of rows)await syncNode(tenantId,type==='doc'?r.kind!:type,r.id).catch(e=>console.error('graph rebuild',table,(e as Error).message));
 return rows.length<60?{table:tableIndex+1,offset:0}:{table:tableIndex,offset:offset+60};
}
