import {hasAction} from '../../access-policy';
import {requireUser,sameOrigin,readBody,HttpError,db,json,failure,auditStatement} from '../../server/core';
import {hasITAccess} from '../../server/it-policy';
async function user(req:Request){const u=await requireUser(req);if(!hasITAccess(u))throw new HttpError(403,'This page is restricted to IT employees, IT managers and administrators.');return u}
export async function GET(req:Request){try{const u=await user(req);const url=new URL(req.url),date=url.searchParams.get('date')||new Date().toISOString().slice(0,10),device=url.searchParams.get('device')||'',offset=Math.max(0,Math.min(100000,Math.floor(Number(url.searchParams.get('offset'))||0)));if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new HttpError(400,'Choose a date.');const devices=(await db().prepare('SELECT id,name,address,location FROM it_nvrs WHERE tenant_id=? ORDER BY name').bind(u.tenantId).all()).results;const rows=await db().prepare('SELECT r.*,n.name AS nvr_name,n.address,n.location,m.name AS recorded_by_name FROM it_nvr_readings r JOIN it_nvrs n ON n.id=r.nvr_id JOIN members m ON m.id=r.recorded_by WHERE n.tenant_id=? AND r.reading_date=? AND (?=\'\' OR r.nvr_id=?) ORDER BY n.name,r.disk_no LIMIT 101 OFFSET ?').bind(u.tenantId,date,device,device,offset).all();const checked=(await db().prepare('SELECT DISTINCT r.nvr_id FROM it_nvr_readings r JOIN it_nvrs n ON n.id=r.nvr_id WHERE n.tenant_id=? AND r.reading_date=?').bind(u.tenantId,date).all<{nvr_id:string}>()).results.map(r=>r.nvr_id);return json({devices,readings:rows.results.slice(0,100),hasMore:rows.results.length>100,checked,date})}catch(e){return failure(e)}}
export async function POST(req:Request){try{const u=await user(req);sameOrigin(req);const b=await readBody(req);if(!hasAction(u,'it',b.action==='device'?'manage_devices':'create'))throw new HttpError(403,'This action is not assigned to your account.');if(b.action==='device'){if(typeof b.name!=='string'||!b.name.trim()||b.name.length>120||typeof b.address!=='string'||b.address.length>250||typeof b.location!=='string'||b.location.length>120)throw new HttpError(400,'Enter an NVR name, web address and location.');let url:URL;try{url=new URL(b.address)}catch{throw new HttpError(400,'Enter a valid http or https NVR address.')}if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw new HttpError(400,'Use an http or https address without credentials.');const address=url.origin;if(await db().prepare('SELECT id FROM it_nvrs WHERE address=? AND tenant_id=?').bind(address,u.tenantId).first())throw new HttpError(409,'This NVR is already registered.');const id=crypto.randomUUID();await db().batch([db().prepare('INSERT INTO it_nvrs(id,name,address,location,created_by,created_at,tenant_id) VALUES(?,?,?,?,?,?,?)').bind(id,b.name.trim(),address,b.location.trim(),u.id,new Date().toISOString(),u.tenantId),auditStatement(u,'NVR registered',id,'IT',null,{name:b.name,address})]);return json({id},201)}
 if(b.action!=='reading'||typeof b.nvrId!=='string'||typeof b.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(b.date)||!Number.isFinite(Date.parse(b.date))||new Date(b.date).toISOString().slice(0,10)!==b.date||b.date>new Date().toISOString().slice(0,10)||!Array.isArray(b.disks)||b.disks.length<1||b.disks.length>64||typeof b.notes!=='string'||b.notes.length>2000)throw new HttpError(400,'Select an NVR, a valid date and at least one disk reading.');
 if(!await db().prepare('SELECT id FROM it_nvrs WHERE id=? AND tenant_id=?').bind(b.nvrId,u.tenantId).first())throw new HttpError(404,'NVR not found.');const numbers=new Set<number>();const disks=b.disks as Record<string,unknown>[];for(const d of disks){if(!Number.isInteger(d.disk)||Number(d.disk)<1||Number(d.disk)>256||numbers.has(Number(d.disk))||typeof d.capacity!=='number'||!Number.isFinite(d.capacity)||d.capacity<0||d.capacity>100000000||typeof d.remaining!=='number'||!Number.isFinite(d.remaining)||d.remaining<0||d.remaining>d.capacity||!['Normal','Warning','Error','Not Exist','Uninitialized','Unknown'].includes(String(d.status))||!['R/W','Read-only','Unknown'].includes(String(d.attribute))||!['Local','NAS','SAN','Unknown'].includes(String(d.type)))throw new HttpError(400,'Check disk numbers, capacities and status. Remaining capacity cannot exceed total capacity.');numbers.add(Number(d.disk))}
 const existing=await db().prepare('SELECT disk_no FROM it_nvr_readings WHERE nvr_id=? AND reading_date=?').bind(b.nvrId,b.date).all<{disk_no:number}>();if(existing.results.some(r=>numbers.has(r.disk_no)))throw new HttpError(409,'A reading already exists for this NVR, disk and date. Choose another date or disk.');const now=new Date().toISOString();await db().batch([...disks.map(d=>db().prepare('INSERT INTO it_nvr_readings(id,nvr_id,reading_date,disk_no,capacity_gb,remaining_gb,status,attribute,storage_type,notes,recorded_by,recorded_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),b.nvrId,b.date,d.disk,d.capacity,d.remaining,d.status,d.attribute,d.type,b.notes,u.id,now)),auditStatement(u,'Daily NVR storage recorded',b.nvrId,'IT',null,{date:b.date,disks:disks.length})]);return json({ok:true},201)
 }catch(e){return failure(e)}}
