'use client';
import {useEffect,useState} from 'react';
type Batch={id:string,dataset:string,source:string,filename:string,row_count:number,imported_at:string,headers_json:string};
type Row={id:string,source_key:string,row_number:number,payload_json:string};
export default function CompanyData({role}:{role?:string}){
 const [batches,setBatches]=useState<Batch[]>([]),[batch,setBatch]=useState(''),[rows,setRows]=useState<Row[]>([]),[q,setQ]=useState(''),[page,setPage]=useState(0),[total,setTotal]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(false),[selected,setSelected]=useState<Row|null>(null);
 useEffect(()=>{if(role!=='admin')return;const c=new AbortController();fetch('/api/company-data',{signal:c.signal}).then(async r=>{const d=await r.json() as {batches:Batch[],error?:string};if(!r.ok)throw Error(d.error);setBatches(d.batches);if(d.batches.length)setBatch(d.batches[0].id)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[role]);
 useEffect(()=>{if(!batch)return;const c=new AbortController();setLoading(true);setSelected(null);const t=setTimeout(()=>fetch(`/api/company-data?batch=${encodeURIComponent(batch)}&q=${encodeURIComponent(q)}&page=${page}`,{signal:c.signal}).then(async r=>{const d=await r.json() as {rows:Row[],total:number,error?:string};if(!r.ok)throw Error(d.error);setRows(d.rows);setTotal(d.total);setError('')}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)}),250);return()=>{clearTimeout(t);c.abort()}},[batch,q,page]);
 if(role!=='admin')return <section className="panel"><div className="empty"><h2>Your company data, connected</h2><p>Staff, locations, assets, procurement, inventory and tickets are imported into a protected source archive.</p><p>Sign in as an authorised administrator to search the imported records. Each export retains its original fields and import date.</p><p>Use your staff account to sign in from Access & connections.</p></div></section>;
 const current=batches.find(b=>b.id===batch);const columns=current?(JSON.parse(current.headers_json) as string[]).filter(c=>!c.startsWith('Unnamed')).slice(0,6):[];
 return <section className="panel records-panel"><div className="panel-title"><h2>Company source archive</h2><span className="badge active">Administrator access</span></div><div className="filters"><select aria-label="Choose dataset" value={batch} onChange={e=>{setBatch(e.target.value);setPage(0);setQ('')}}>{batches.map(b=><option key={b.id} value={b.id}>{b.dataset} · {b.row_count.toLocaleString()} rows · {b.source}</option>)}</select><div className="search"><input aria-label="Search source data" placeholder="Search all fields in this dataset…" value={q} onChange={e=>{setQ(e.target.value);setPage(0)}}/></div></div>{current&&<div className="table-footer">{current.filename}<span>Imported {new Date(current.imported_at).toLocaleString()} · Read-only snapshot</span></div>}{error&&<p role="alert" className="error">{error}</p>}{loading?<div className="empty">Loading records…</div>:<div className="table-scroll"><table><thead><tr><th>Source row</th>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map(r=>{const p=JSON.parse(r.payload_json);return <tr key={r.id}><td><button className="record-title" onClick={()=>setSelected(r)}>View row {r.row_number}</button></td>{columns.map(c=><td key={c}>{String(p[c]??'—').slice(0,120)}</td>)}</tr>})}</tbody></table>{!rows.length&&<div className="empty">No source records found.</div>}</div>}<div className="table-footer"><span>{total.toLocaleString()} matching rows · Page {page+1} of {Math.max(1,Math.ceil(total/50))}</span><div><button disabled={page===0||loading} onClick={()=>setPage(page-1)}>Previous</button> <button disabled={(page+1)*50>=total||loading} onClick={()=>setPage(page+1)}>Next</button></div></div>{selected&&<div className="source-detail"><div className="panel-title"><h2>Source row {selected.row_number}</h2><button onClick={()=>setSelected(null)}>Close details</button></div><dl className="record-details">{Object.entries(JSON.parse(selected.payload_json)).filter(([k])=>!k.startsWith('Unnamed')).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v??'Not provided')}</dd></div>)}</dl></div>}</section>
}

