// Connector types offered in the Connector Center (platform and company level).
// config = non-secret settings stored as JSON; secrets = fields sealed with AES-GCM and never returned.
export type ConnectorAuth='oauth2'|'api_key'|'bearer'|'basic'|'none'|'webhook'|'mcp';
export type ConnectorField={key:string,label:string,hint?:string,required?:boolean,options?:string[],placeholder?:string};
export type ConnectorType={id:string,name:string,category:string,description:string,auth:ConnectorAuth,icon:string,family?:'microsoft'|'google',oauth?:{authorize:string,token:string,scopes:string[],test:string,base:string},config:ConnectorField[],secrets:ConnectorField[],readable:boolean};
const ms=(id:string,name:string,description:string,scopes:string[],test='https://graph.microsoft.com/v1.0/me'):ConnectorType=>({id,name,category:'Microsoft',description,auth:'oauth2',icon:'Building2',family:'microsoft',oauth:{authorize:'https://login.microsoftonline.com/{directory}/oauth2/v2.0/authorize',token:'https://login.microsoftonline.com/{directory}/oauth2/v2.0/token',scopes:['offline_access',...scopes],test,base:'https://graph.microsoft.com/v1.0'},config:[{key:'directory',label:'Directory (tenant) ID',hint:'Your Entra tenant ID, or "organizations".',placeholder:'organizations'},{key:'clientId',label:'Application (client) ID',hint:'Leave empty to use the platform’s Microsoft app registration.'}],secrets:[{key:'clientSecret',label:'Client secret',hint:'Only needed with your own app registration.'}],readable:true});
const gg=(id:string,name:string,description:string,scopes:string[],test='https://www.googleapis.com/oauth2/v3/userinfo'):ConnectorType=>({id,name,category:'Google',description,auth:'oauth2',icon:'Globe',family:'google',oauth:{authorize:'https://accounts.google.com/o/oauth2/v2/auth',token:'https://oauth2.googleapis.com/token',scopes:['openid','email',...scopes],test,base:'https://www.googleapis.com'},config:[{key:'clientId',label:'OAuth client ID',hint:'Leave empty to use the platform’s Google app.'}],secrets:[{key:'clientSecret',label:'Client secret',hint:'Only needed with your own OAuth client.'}],readable:true});
const rest=(id:string,name:string,category:string,description:string,icon:string):ConnectorType=>({id,name,category,description,auth:'api_key',icon,config:[{key:'baseUrl',label:'Base URL',required:true,placeholder:'https://api.example.com/v1'},{key:'authType',label:'Authentication',options:['api_key','bearer','basic','none']},{key:'header',label:'API key header',placeholder:'X-API-Key'},{key:'username',label:'Username (basic auth)'},{key:'testPath',label:'Test path',placeholder:'/health'}],secrets:[{key:'secret',label:'API key, token or password'}],readable:true});
export const connectorTypes:ConnectorType[]=[
 ms('microsoft365','Microsoft 365','Sign in with Microsoft and read profile data.',['User.Read']),
 ms('entra','Microsoft Entra ID','Directory users and groups.',['User.Read.All','Group.Read.All'],'https://graph.microsoft.com/v1.0/organization'),
 ms('outlook','Outlook','Mail and calendar (read).',['Mail.Read','Calendars.Read'],'https://graph.microsoft.com/v1.0/me/mailFolders/inbox'),
 ms('teams','Microsoft Teams','Teams and channels (read).',['Team.ReadBasic.All','Channel.ReadBasic.All'],'https://graph.microsoft.com/v1.0/me/joinedTeams'),
 ms('sharepoint','SharePoint','Sites and document libraries (read).',['Sites.Read.All'],'https://graph.microsoft.com/v1.0/sites/root'),
 ms('onedrive','OneDrive','Files in OneDrive (read).',['Files.Read'],'https://graph.microsoft.com/v1.0/me/drive'),
 ms('excel','Excel','Workbooks in OneDrive/SharePoint.',['Files.Read'],'https://graph.microsoft.com/v1.0/me/drive'),
 gg('google-workspace','Google Workspace','Sign in with Google and read profile data.',['profile']),
 gg('gmail','Gmail','Mail (read).',['https://www.googleapis.com/auth/gmail.readonly'],'https://gmail.googleapis.com/gmail/v1/users/me/profile'),
 gg('google-calendar','Google Calendar','Calendars and events (read).',['https://www.googleapis.com/auth/calendar.readonly'],'https://www.googleapis.com/calendar/v3/users/me/calendarList'),
 gg('google-drive','Google Drive','Files in Drive (read).',['https://www.googleapis.com/auth/drive.readonly'],'https://www.googleapis.com/drive/v3/about?fields=user'),
 rest('rest','Generic REST API','APIs','Any HTTPS JSON API with an API key, bearer token or basic auth.','Code'),
 {id:'oauth2','name':'OAuth 2.0 service',category:'APIs',description:'Any service that uses the OAuth 2.0 authorization-code flow.',auth:'oauth2',icon:'KeyRound',config:[{key:'authorizeUrl',label:'Authorization URL',required:true},{key:'tokenUrl',label:'Token URL',required:true},{key:'scopes',label:'Scopes',hint:'Space separated'},{key:'clientId',label:'Client ID',required:true},{key:'baseUrl',label:'API base URL',required:true},{key:'testPath',label:'Test path',placeholder:'/me'}],secrets:[{key:'clientSecret',label:'Client secret',required:true}],readable:true},
 {id:'webhook',name:'Incoming webhook',category:'APIs',description:'Receive signed events from another system.',auth:'webhook',icon:'Send',config:[{key:'events',label:'Expected events',hint:'Optional, comma separated'}],secrets:[],readable:false},
 {id:'mcp',name:'MCP server',category:'AI & MCP',description:'A Model Context Protocol server (streamable HTTP): discover tools and resources, allow them per role.',auth:'mcp',icon:'Cpu',config:[{key:'endpoint',label:'Server URL',required:true,placeholder:'https://mcp.example.com/mcp'},{key:'authType',label:'Authentication',options:['bearer','api_key','none']},{key:'header',label:'API key header',placeholder:'X-API-Key'},{key:'timeoutSeconds',label:'Timeout (seconds)',placeholder:'20'}],secrets:[{key:'secret',label:'Token or API key'}],readable:true},
 rest('database','Database (HTTP API)','Data','A database reachable over an HTTPS API (for example a REST or SQL-over-HTTP endpoint).','Database'),
 rest('file-storage','File storage (HTTP API)','Data','An HTTPS file or object storage API.','HardDrive'),
 rest('custom','Custom internal service','APIs','An internal HTTPS service your company runs.','Workflow'),
];
export const connectorTypeById=new Map(connectorTypes.map(c=>[c.id,c]));
