'use client';
import {useState,useEffect,useCallback} from 'react';
import {HardDrive,ShieldCheck,Plus} from 'lucide-react';
type Device={id:string,name:string,address:string,location:string};
type Disk={disk:number,capacity:string,remaining:string,status:string,attribute:string,type:string};
type Reading={id:string,nvr_name:string,address:string,location:string,disk_no:number,capacity_gb:number,remaining_gb:number,status:string,attribute:string,storage_type:string,notes:string,recorded_by_name:string,recorded_at:string,reading_date:string};
const blank=(disk:number):Disk=>({disk,capacity:'',remaining:'',status:'Normal',attribute:'R/W',type:'Local'});
const today=()=>new Date().toISOString().slice(0,10);
async function api(url:string,body?:unknown){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const d=await r.json() as any;if(!r.ok)throw Error(d.error||'Request failed.');return d}
export default function IT({permissions}:{permissions?:Record<string,string>}){const allow=(a:string)=>!!permissions?.[a]&&permissions[a]!=='none';const [date,setDate]=useState(today),[device,setDevice]=useState(''),[devices,setDevices]=useState<Device[]>([]),[rows,setRows]=useState<Reading[]>([]),[checked,setChecked]=useState<string[]>([]),[page,setPage]=useState(0),[more,setMore]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[allowed,setAllowed]=useState(false),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[addDevice,setAddDevice]=useState(false),[entry,setEntry]=useState(false),[entryNvr,setEntryNvr]=useState(''),[entryDate,setEntryDate]=useState(today),[notes,setNotes]=useState(''),[disks,setDisks]=useState<Disk[]>([blank(1)]);
 const load=useCallback(async()=>{try{const d=await api(`/api/it?date=${date}&device=${encodeURIComponent(device)}&offset=${page*100}`);setDevices(d.devices);setRows(d.readings);setChecked(d.checked);setMore(d.hasMore);setAllowed(true)}catch(e){setError((e as Error).message);setAllowed(false)}finally{setLoaded(true)}},[date,device,page]);useEffect(()=>{load()},[load]);
 async function saveDevice(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);setBusy(true);setError('');try{const d=await api('/api/it',{action:'device',name:fd.get('name'),address:fd.get('address'),location:fd.get('location')});await load();setEntryNvr(d.id);setAddDevice(false);setMessage('NVR registered. Add its daily disk readings.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function saveReading(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/api/it',{action:'reading',nvrId:entryNvr,date:entryDate,notes,disks:disks.map(d=>({...d,capacity:Number(d.capacity),remaining:Number(d.remaining)}))});setDate(entryDate);setEntry(false);setDisks([blank(1)]);setNotes('');setMessage('Daily storage readings saved.');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function exportCsv(){const esc=(x:unknown)=>'"'+String(x??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const csv=[['Date','NVR','Address','Location','Disk','Total GB','Remaining GB','Used GB','Free %','Status','Attribute','Type','Notes','Recorded by','Recorded at'],...rows.map(r=>[r.reading_date,r.nvr_name,r.address,r.location,r.disk_no,r.capacity_gb,r.remaining_gb,r.capacity_gb-r.remaining_gb,r.capacity_gb?(100*r.remaining_gb/r.capacity_gb).toFixed(1):'',r.status,r.attribute,r.storage_type,r.notes,r.recorded_by_name,r.recorded_at])].map(r=>r.map(esc).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`nvr-storage-${date}-page-${page+1}.csv`;a.click();URL.revokeObjectURL(url)}
 if(!loaded)return <section className="panel research-loading">Loading IT workspace…</section>;if(!allowed)return <section className="panel research-loading"><ShieldCheck/><h2>IT access required</h2><p>{error}</p></section>;
 return <div className="it-workspace"><div className="research-toolbar"><span><ShieldCheck size={18}/> IT employees, IT managers & administrators</span><div><button hidden={!allow('manage_devices')} onClick={()=>setAddDevice(!addDevice)}><Plus size={16}/>Register NVR</button> <button className="primary" disabled={!devices.length||!allow('create')} onClick={()=>{setEntry(!entry);setEntryNvr(device||devices[0]?.id||'');setEntryDate(date)}}>Record daily storage</button></div></div>{error&&<p role="alert" className="research-error">{error}</p>}{message&&<p role="status">{message}</p>}
 <div className="it-summary"><article><HardDrive/><strong>{devices.length}</strong><span>Registered NVRs</span></article><article><strong>{checked.length}</strong><span>With readings on {date}</span></article><article><strong>{devices.length-checked.length}</strong><span>Awaiting a daily reading</span></article></div>
 {addDevice&&<section className="panel it-form"><h2>Register an NVR</h2><form onSubmit={saveDevice}><label>NVR name<input name="name" required maxLength={120}/></label><label>Web address<input name="address" type="url" required placeholder="https://192.168.3.50"/></label><label>Location<input name="location" maxLength={120} placeholder="Building or CCTV area"/></label><button className="primary" disabled={busy}>Save NVR</button></form></section>}
 {entry&&<section className="panel it-form"><h2>Daily disk readings</h2><form onSubmit={saveReading}><div className="filters"><label>NVR<select value={entryNvr} onChange={e=>setEntryNvr(e.target.value)}>{devices.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label>Reading date<input type="date" required max={today()} value={entryDate} onChange={e=>setEntryDate(e.target.value)}/></label></div><div className="table-scroll"><table><thead><tr><th>Disk</th><th>Total (GB)</th><th>Remaining (GB)</th><th>Status</th><th>Attribute</th><th>Type</th><th/></tr></thead><tbody>{disks.map((d,i)=><tr key={i}>{(['disk','capacity','remaining'] as const).map(k=><td key={k}><input aria-label={`${k} disk ${i+1}`} type="number" required min={k==='disk'?1:0} max={k==='disk'?256:100000000} step={k==='disk'?1:0.01} value={d[k]} onChange={e=>setDisks(ds=>ds.map((x,j)=>j===i?{...x,[k]:k==='disk'?Number(e.target.value):e.target.value}:x))}/></td>)}{(['status','attribute','type'] as const).map(k=><td key={k}><select aria-label={`${k} disk ${i+1}`} value={d[k]} onChange={e=>setDisks(ds=>ds.map((x,j)=>j===i?{...x,[k]:e.target.value}:x))}>{(k==='status'?['Normal','Warning','Error','Not Exist','Uninitialized','Unknown']:k==='attribute'?['R/W','Read-only','Unknown']:['Local','NAS','SAN','Unknown']).map(s=><option key={s}>{s}</option>)}</select></td>)}<td><button type="button" disabled={disks.length===1} onClick={()=>setDisks(ds=>ds.filter((_,j)=>i!==j))}>Remove</button></td></tr>)}</tbody></table></div><button type="button" disabled={disks.length>=64} onClick={()=>setDisks(ds=>[...ds,blank(Math.max(...ds.map(d=>d.disk))+1)])}>Add disk</button><label>Observation notes<textarea value={notes} maxLength={2000} onChange={e=>setNotes(e.target.value)} placeholder="Source, unusual status or checks performed"/></label><button className="primary" disabled={busy}>Save daily readings</button></form></section>}
 <details className="panel it-form"><summary>Registered NVRs</summary><div className="table-scroll"><table><thead><tr><th>Name</th><th>Address</th><th>Location</th></tr></thead><tbody>{devices.map(n=><tr key={n.id}><td>{n.name}</td><td><a href={n.address} target="_blank" rel="noreferrer">{n.address}</a></td><td>{n.location||'Not set'}</td></tr>)}</tbody></table></div></details><section className="panel"><div className="panel-title"><h2>CCTV NVR storage register</h2><button disabled={!rows.length||!allow('export')} onClick={exportCsv}>Export displayed rows</button></div><div className="filters"><label>Reading date<input aria-label="Filter reading date" type="date" value={date} onChange={e=>{if(e.target.value){setDate(e.target.value);setPage(0)}}}/></label><select aria-label="Filter NVR" value={device} onChange={e=>{setDevice(e.target.value);setPage(0)}}><option value="">All NVRs</option>{devices.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select><button onClick={()=>load()}>Refresh</button></div><div className="table-scroll"><table><thead><tr><th>NVR / location</th><th>Disk</th><th>Total GB</th><th>Remaining GB</th><th>Used GB</th><th>Free %</th><th>Status</th><th>Attribute / type</th><th>Observation</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.nvr_name}<small>{r.address} · {r.location||'Location not set'}</small></td><td>{r.disk_no}</td><td>{r.capacity_gb.toLocaleString()}</td><td>{r.remaining_gb.toLocaleString()}</td><td>{(r.capacity_gb-r.remaining_gb).toLocaleString()}</td><td>{r.capacity_gb?(100*r.remaining_gb/r.capacity_gb).toFixed(1)+'%':'N/A'}</td><td><span className={`badge ${r.status==='Normal'?'active':'pending'}`}>{r.status}</span></td><td>{r.attribute} / {r.storage_type}</td><td>{r.notes}<small>{r.recorded_by_name} · {new Date(r.recorded_at).toLocaleString()}</small></td></tr>)}</tbody></table>{!rows.length&&<div className="empty"><h3>No readings for this date</h3><p>Register an NVR, then record each disk’s reported storage values.</p></div>}</div><div className="table-footer"><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1}</span><button disabled={!more} onClick={()=>setPage(page+1)}>Next</button></div></section><p className="setup-note">Values are daily observations, not live telemetry. “Not Exist” means the NVR reports no disk in that slot. Free space alone does not show recording retention when overwrite is enabled. Private-network NVRs are not polled directly by this hosted page.</p></div>
}
