'use client';
import {useState,useEffect,useCallback} from 'react';
import {Upload,FlaskConical,ShieldCheck,FileAudio,RefreshCw,X} from 'lucide-react';
import {numberedTranscript} from './research-format';
type Recording={id:string,title:string,context:string,filename:string,mime:string,bytes:number,status:string,error:string|null,created_at:string,updated_at:string,lease_until:number,attempts:number,transcript?:string,summary?:string,transcription_model?:string,summary_model?:string};
type AccessMember={id:string,name:string,email:string,role:string,active:number,assigned:number};
async function request(url:string,init?:RequestInit){const r=await fetch(url,{cache:'no-store',...init});const d=await r.json() as any;if(!r.ok)throw Error(d.error||'The request could not be completed.');return d}
export default function Research({admin,onAccessChanged,permissions}:{admin:boolean,onAccessChanged:()=>Promise<void>,permissions?:Record<string,string>}){
 const [rows,setRows]=useState<Recording[]>([]),[selected,setSelected]=useState<Recording|null>(null),[query,setQuery]=useState(''),[page,setPage]=useState(0),[more,setMore]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[allowed,setAllowed]=useState(false),[busy,setBusy]=useState(''),[uploading,setUploading]=useState(false),[members,setMembers]=useState<AccessMember[]|null>(null),[accessBusy,setAccessBusy]=useState(''),[aiReady,setAiReady]=useState(false),[secondaryReady,setSecondaryReady]=useState(false);
 const load=useCallback(async()=>{try{const d=await request(`/api/research?q=${encodeURIComponent(query)}&offset=${page*30}`);setRows(d.records);setMore(d.hasMore);setAllowed(true);setAiReady(d.aiReady);setSecondaryReady(d.secondaryReady);setLoaded(true)}catch(e){setError((e as Error).message);setAllowed(false);setLoaded(true)}},[query,page]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{const active=rows.filter(r=>['Submitting','Queued','Transcribing','Summarizing','Awaiting confirmation'].includes(r.status));if(!active.length)return;let running=false;const timer=setInterval(async()=>{if(running)return;running=true;try{for(const r of active.slice(0,3))await request('/api/research/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:r.id})});await load();if(selected&&active.some(r=>r.id===selected.id))setSelected((await request('/api/research?id='+selected.id)).record)}catch(e){setError((e as Error).message)}finally{running=false}},15000);return()=>clearInterval(timer)},[rows,load,selected?.id]);
 async function process(id:string,provider?:string){setBusy(id);setError('');try{const d=await request('/api/research/process',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,provider})});if(d.error)setError(d.error);const detail=await request('/api/research?id='+id);setSelected(detail.record)}catch(e){setError((e as Error).message)}finally{setBusy('');await load()}}
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,fd=new FormData(form);const file=fd.get('file') as File;if(file.size>20000000){setError('Choose a recording of 20 MB or smaller.');return}setUploading(true);setError('');try{const d=await request('/api/research',{method:'POST',body:fd});form.reset();await load();if(d.processingError)setError(d.processingError);await process(d.id)}catch(e){setError((e as Error).message)}finally{setUploading(false)}}
 async function access(){try{const d=await request('/api/research/access');setMembers(d.members)}catch(e){setError((e as Error).message)}}
 async function assign(m:AccessMember){setAccessBusy(m.id);try{await request('/api/research/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:m.id,assigned:!m.assigned})});await access();await onAccessChanged()}catch(e){setError((e as Error).message)}finally{setAccessBusy('')}}
 function download(r:Recording){const text=`${r.title}\n${r.context}\n\nAI RESEARCH SUMMARY — review before use\n${r.summary||'Not available'}\n\nTRANSCRIPT\n${r.transcript?numberedTranscript(r.transcript):'Not available'}`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`research-${r.id}.txt`;a.click();URL.revokeObjectURL(url)}
 if(!loaded)return <section className="panel research-loading">Loading research library…</section>;
 if(!allowed)return <section className="panel research-loading"><ShieldCheck/><h2>Research access required</h2><p>{error}</p></section>;
 return <div className="research-workspace">
 <div className="research-toolbar"><span><ShieldCheck size={18}/> Private research team</span>{admin&&<a className="button" href="#/admin/overrides">Manage page permissions</a>}</div>
 {error&&<p className="research-error" role="alert">{error}</p>}
 <div className="research-layout"><section className="panel research-upload"><span className="metric-icon green"><Upload size={24}/></span><h2>Upload a recording</h2><p>Turn interviews and market visits into evidence your team can use.</p><form onSubmit={upload}><label>Research title<input name="title" required maxLength={160} placeholder="e.g. Tema retail interviews — September"/></label><label>Research question or context<textarea name="context" maxLength={3000} rows={3} placeholder="Product, location, study objective…"/></label><label className="research-file">Audio or video<input name="file" type="file" required accept=".mp3,.mp4,.m4a,.wav,.webm,.mpeg,.mpga"/></label><p className="setup-note">Up to 20 MB per recording. MP3, MP4, M4A, WAV, WEBM, MPEG or MPGA. Split or compress larger recordings. Video analysis uses the spoken audio only.</p><p className="setup-note">AssemblyAI is the primary service for transcription and timestamped AI summaries. Groq / Whisper is the secondary service. Recordings and transcripts are sent to these providers for processing. Upload only research you are authorised to process.</p><button className="primary" disabled={uploading||!!busy||!aiReady||permissions?.upload==='none'||permissions?.process==='none'}><Upload size={17}/>{uploading?(busy?'Transcribing & analysing…':'Uploading…'):'Upload & analyse'}</button>{!aiReady&&<p role="status">Add ASSEMBLYAI_API_KEY or GROQ_API_KEY to the site secrets and publish the configuration to enable processing.</p>}{(uploading||busy)&&<p role="status">Keep this page open until the upload is queued. AssemblyAI continues in the background after you close the page. Groq retries require this page to remain open until they finish.</p>}</form></section>
 <section className="panel research-library"><div className="panel-title"><h2>Research library</h2><button aria-label="Refresh research library" onClick={()=>load()}><RefreshCw size={16}/></button></div><div className="filters"><input aria-label="Search research" placeholder="Search title or research context" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></div>{!rows.length?<div className="empty"><FlaskConical size={32}/><h3>{query?'No matching recordings':'Your research starts here'}</h3><p>{query?'Try another search.':'Upload your first interview or market visit. Its transcript and AI brief will appear here.'}</p></div>:<div className="research-cards">{rows.map(r=><article key={r.id}><FileAudio size={22}/><div><button className="record-title" onClick={async()=>{try{setSelected((await request('/api/research?id='+r.id)).record)}catch(e){setError((e as Error).message)}}}>{r.title}</button><p>{r.context||r.filename}</p><small>{new Date(r.created_at).toLocaleDateString()} · {(r.bytes/1000000).toFixed(1)} MB</small></div><span className={`badge ${r.status==='Ready'?'active':r.status==='Failed'?'rejected':'pending'}`}>{r.status}</span></article>)}</div>}<div className="table-footer"><button disabled={page===0} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1}</span><button disabled={!more} onClick={()=>setPage(page+1)}>Next</button></div></section></div>
 {members&&<section className="panel research-access"><div className="panel-title"><h2>Research team access</h2><button onClick={()=>setMembers(null)} aria-label="Close access panel"><X size={18}/></button></div><p>Admins always have access. Assigned staff can upload and read all recordings, transcripts and summaries in this library. Other staff and managers cannot access it.</p><div className="table-scroll"><table><thead><tr><th>Staff member</th><th>Research access</th><th/></tr></thead><tbody>{members.filter(m=>m.active).map(m=><tr key={m.id}><td>{m.name}<small>{m.email}</small></td><td>{m.role==='admin'?'Administrator':m.assigned?'Assigned':'Not assigned'}</td><td>{m.role!=='admin'&&<button disabled={accessBusy===m.id} onClick={()=>assign(m)}>{m.assigned?'Remove access':'Grant access'}</button>}</td></tr>)}</tbody></table></div></section>}
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="drawer research-detail" role="dialog" aria-modal="true" aria-label="Research recording" onClick={e=>e.stopPropagation()}><button className="close icon-button" onClick={()=>setSelected(null)} aria-label="Close recording"><X/></button><p className="eyebrow">CONSUMER EVIDENCE</p><h2>{selected.title}</h2><p>{selected.context}</p><span className="badge">{selected.status}</span>{selected.mime.startsWith('video/')?<video key={selected.id} controls preload="metadata" src={'/api/research/media?id='+selected.id}/>:<audio key={selected.id} controls preload="metadata" src={'/api/research/media?id='+selected.id}/>}<p className="setup-note">{selected.filename} · Uploaded {new Date(selected.created_at).toLocaleString()}</p>{selected.error&&<p role="alert" className="research-error">{selected.error}</p>}{permissions?.process!=='none'&&selected.status!=='Ready'&&<button disabled={!!busy||selected.lease_until>Date.now()} onClick={()=>process(selected.id)}> {busy?'Processing…':'Process / refresh recording'}</button>}{secondaryReady&&permissions?.process!=='none'&&['Failed','Transcript ready','Uploaded'].includes(selected.status)&&<button disabled={!!busy||selected.lease_until>Date.now()} onClick={()=>process(selected.id,'groq')}>Retry with Groq / Whisper</button>}<p className="setup-note">{selected.transcription_model&&`Transcription: ${selected.transcription_model}. `}{selected.summary_model&&`Summary: ${selected.summary_model}.`}</p><h3>AI research summary</h3><p className="setup-note">AI-generated findings require review. AssemblyAI summaries reference recording timestamps. Groq research briefs reference transcript lines [L1]. Review findings against the original recording.</p><div className="research-prose">{selected.summary||'The summary will appear here after processing.'}</div><details open={!!selected.transcript}><summary>Full transcript</summary><pre className="research-transcript">{selected.transcript?numberedTranscript(selected.transcript):'Transcription has not finished.'}</pre></details>{permissions?.download!=='none'&&selected.transcript&&<button onClick={()=>download(selected)}>Download transcript & brief</button>}</section></div>}
 </div>
}
