// First-class connected entities that complete the One Work Graph: strategy (goals → objectives →
// initiatives, with projects contributing), commercial (customers → contracts → services) and governance
// (meetings → decisions). Each kind declares its fields; the server validates data against these
// definitions and every save becomes a Work Graph node with typed relationships.
export type WorkFieldType='text'|'textarea'|'number'|'currency'|'date'|'datetime'|'person'|'people'|'select'|'email'|'url'|'refs';
export type WorkField={key:string,label:string,type:WorkFieldType,options?:string[],refType?:string,help?:string,relationship?:string,reverse?:boolean};
export type WorkKind={id:string,label:string,plural:string,icon:string,group:'Strategy'|'Customers'|'Governance',statuses:string[],parent?:{kind:string,label:string,relationship:string},fields:WorkField[],numberPrefix:string,hasAmount?:string,hasDates?:[string,string]};
const refs=(key:string,label:string,refType:string,relationship:string,help?:string,reverse=false):WorkField=>({key,label,type:'refs',refType,relationship,help,reverse});
export const workKinds:WorkKind[]=[
 {id:'goal',label:'Goal',plural:'Goals',icon:'Target',group:'Strategy',statuses:['Draft','Active','At risk','Achieved','Missed','Cancelled'],numberPrefix:'GOAL',hasDates:['Start','Target date'],fields:[{key:'period',label:'Period',type:'text',help:'e.g. FY2027 or H1 2027'},{key:'metric',label:'Measure of success',type:'textarea'}]},
 {id:'objective',label:'Objective',plural:'Objectives',icon:'Crosshair',group:'Strategy',statuses:['Draft','On track','At risk','Off track','Achieved','Cancelled'],numberPrefix:'OBJ',parent:{kind:'goal',label:'Goal',relationship:'part_of'},hasDates:['Start','Due'],fields:[{key:'keyResults',label:'Key results',type:'textarea',help:'One per line'}]},
 {id:'initiative',label:'Initiative',plural:'Initiatives',icon:'Rocket',group:'Strategy',statuses:['Proposed','Approved','In progress','Completed','Cancelled'],numberPrefix:'INI',parent:{kind:'objective',label:'Objective',relationship:'part_of'},hasAmount:'Budget',hasDates:['Start','End'],fields:[refs('projects','Contributing projects','project','contributes_to','Projects that deliver this initiative.',true)]},
 {id:'customer',label:'Customer',plural:'Customers',icon:'Building2',group:'Customers',statuses:['Prospect','Active','On hold','Former'],numberPrefix:'CUS',fields:[{key:'industry',label:'Industry',type:'text'},{key:'contactName',label:'Main contact',type:'text'},{key:'email',label:'Contact email',type:'email'},{key:'phone',label:'Phone',type:'text'},{key:'website',label:'Website',type:'url'},refs('projects','Projects for this customer','project','related_to')]},
 {id:'contract',label:'Contract',plural:'Contracts',icon:'FileSignature',group:'Customers',statuses:['Draft','Negotiation','Active','Expiring','Expired','Terminated'],numberPrefix:'CON',parent:{kind:'customer',label:'Customer',relationship:'belongs_to'},hasAmount:'Contract value',hasDates:['Start','End'],fields:[{key:'renewalDate',label:'Renewal notice date',type:'date'},{key:'terms',label:'Key terms',type:'textarea'},refs('vendors','Vendors / subcontractors','vendor','supplied_by'),refs('files','Signed documents','file','attached_to',undefined,true),refs('projects','Delivery projects','project','related_to')]},
 {id:'service',label:'Service',plural:'Services',icon:'Handshake',group:'Customers',statuses:['Planned','Active','Suspended','Ended'],numberPrefix:'SRV',parent:{kind:'contract',label:'Contract',relationship:'part_of'},hasAmount:'Monthly value',hasDates:['Start','End'],fields:[{key:'serviceLevel',label:'Service level',type:'textarea',help:'Response and resolution commitments'},{key:'frequency',label:'Frequency',type:'select',options:['One-off','Weekly','Monthly','Quarterly','Annual','On demand']},refs('assets','Assets covered','asset','related_to')]},
 {id:'meeting',label:'Meeting',plural:'Meetings',icon:'CalendarClock',group:'Governance',statuses:['Scheduled','Held','Cancelled'],numberPrefix:'MTG',hasDates:['Date','Ends'],fields:[{key:'attendees',label:'Attendees',type:'people'},{key:'agenda',label:'Agenda',type:'textarea'},{key:'minutes',label:'Minutes / notes',type:'textarea'},refs('projects','Projects discussed','project','related_to'),refs('customers','Customers discussed','customer','related_to'),refs('files','Recordings and documents','file','attached_to',undefined,true)]},
 {id:'decision',label:'Decision',plural:'Decisions',icon:'Gavel',group:'Governance',statuses:['Proposed','Decided','Reversed','Superseded'],numberPrefix:'DEC',parent:{kind:'meeting',label:'Decided in meeting',relationship:'decided_in'},hasDates:['Decision date','Review date'],fields:[{key:'rationale',label:'Rationale',type:'textarea'},{key:'decidedBy',label:'Decided by',type:'person'},refs('affects','Affected projects','project','related_to'),refs('tasks','Resulting tasks','task','resulted_in')]},
];
export const workKindById=new Map(workKinds.map(k=>[k.id,k]));
export const WORK_KINDS=workKinds.map(k=>k.id);
