// First-class connected entities that complete the One Work Graph: strategy (goals → objectives →
// initiatives, with projects contributing), commercial (customers → contracts → services) and governance
// (meetings → decisions). Each kind declares its fields; the server validates data against these
// definitions and every save becomes a Work Graph node with typed relationships.
export type WorkFieldType='text'|'textarea'|'number'|'currency'|'date'|'datetime'|'person'|'people'|'select'|'email'|'url'|'refs';
export type WorkField={key:string,label:string,type:WorkFieldType,options?:string[],refType?:string,help?:string,relationship?:string,reverse?:boolean};
export type WorkKind={id:string,label:string,plural:string,icon:string,group:'Strategy'|'Customers'|'Governance',statuses:string[],parent?:{kind:string,label:string,relationship:string},parents?:{kind:string,relationship:string}[],fields:WorkField[],numberPrefix:string,hasAmount?:string,hasDates?:[string,string]};
const refs=(key:string,label:string,refType:string,relationship:string,help?:string,reverse=false):WorkField=>({key,label,type:'refs',refType,relationship,help,reverse});
export const workKinds:WorkKind[]=[
 {id:'strategy',label:'Company strategy',plural:'Strategies',icon:'Compass',group:'Strategy',statuses:['Draft','Published','Archived'],numberPrefix:'STR',hasDates:['Start','End'],fields:[{key:'mission',label:'Mission',type:'textarea'},{key:'vision',label:'Vision',type:'textarea'},{key:'priorities',label:'Priorities',type:'textarea',help:'One per line'},{key:'periodId',label:'Planning period',type:'text'},{key:'scope',label:'Scope',type:'select',options:['Company','Department']},{key:'requiresAck',label:'Staff must acknowledge',type:'select',options:['No','Yes']}]},
 {id:'theme',label:'Strategic theme',plural:'Themes',icon:'Layers',group:'Strategy',statuses:['Active','Retired'],numberPrefix:'THM',parent:{kind:'strategy',label:'Strategy',relationship:'part_of'},fields:[]},
 {id:'goal',label:'Goal',plural:'Goals',icon:'Target',group:'Strategy',statuses:['Draft','Active','At risk','Achieved','Missed','Cancelled'],numberPrefix:'GOAL',parent:{kind:'strategy',label:'Strategy',relationship:'part_of'},parents:[{kind:'strategy',relationship:'part_of'},{kind:'theme',relationship:'part_of'}],hasDates:['Start','Target date'],fields:[{key:'period',label:'Period',type:'text',help:'e.g. FY2027 or H1 2027'},{key:'metric',label:'Measure of success',type:'textarea'}]},
 {id:'objective',label:'Objective',plural:'Objectives',icon:'Crosshair',group:'Strategy',statuses:['Draft','On track','At risk','Off track','Achieved','Cancelled'],numberPrefix:'OBJ',parent:{kind:'goal',label:'Goal, theme, strategy or parent objective',relationship:'part_of'},parents:[{kind:'goal',relationship:'part_of'},{kind:'strategy',relationship:'part_of'},{kind:'theme',relationship:'part_of'},{kind:'objective',relationship:'part_of'}],hasDates:['Start','Due'],fields:[{key:'keyResults',label:'Key results (notes)',type:'textarea',help:'Structured key results are separate records'},{key:'periodId',label:'Planning period',type:'text'},{key:'priority',label:'Priority',type:'select',options:['Low','Medium','High','Critical']},{key:'confidence',label:'Confidence (%)',type:'number'},{key:'health',label:'Health',type:'select',options:['On track','At risk','Off track']},{key:'checkInCadence',label:'Check-in schedule',type:'select',options:['Weekly','Fortnightly','Monthly','Quarterly']},{key:'nextCheckIn',label:'Next check-in',type:'date'}]},
 {id:'key_result',label:'Key result',plural:'Key results',icon:'Gauge',group:'Strategy',statuses:['Not started','On track','At risk','Off track','Achieved','Missed'],numberPrefix:'KR',parent:{kind:'objective',label:'Objective',relationship:'part_of'},hasDates:['Start','Due'],fields:[{key:'metricType',label:'Measure',type:'select',options:['Number','Percentage','Currency','Yes/No','Milestones','Custom']},{key:'start',label:'Starting value',type:'number'},{key:'current',label:'Current value',type:'number'},{key:'target',label:'Target value',type:'number'},{key:'unit',label:'Unit',type:'text'},{key:'weight',label:'Weight',type:'number'},{key:'confidence',label:'Confidence (%)',type:'number'},{key:'frequency',label:'Update frequency',type:'select',options:['Weekly','Fortnightly','Monthly','Quarterly']},{key:'nextCheckIn',label:'Next check-in',type:'date'},refs('milestones','Milestones measured','task','contributes_to','For milestone key results: the milestone tasks.',true),refs('evidence','Evidence','file','attached_to',undefined,true)]},
 {id:'initiative',label:'Initiative',plural:'Initiatives',icon:'Rocket',group:'Strategy',statuses:['Proposed','Approved','In progress','On hold','Completed','Cancelled'],numberPrefix:'INI',parent:{kind:'objective',label:'Objective, key result or parent initiative',relationship:'part_of'},parents:[{kind:'objective',relationship:'contributes_to'},{kind:'key_result',relationship:'contributes_to'},{kind:'initiative',relationship:'part_of'}],hasAmount:'Funding',hasDates:['Start','End'],fields:[refs('projects','Contributing projects','project','contributes_to','Projects that deliver this initiative.',true),{key:'sponsor',label:'Sponsor',type:'person'},{key:'contributingDepartments',label:'Contributing departments',type:'text'},{key:'priority',label:'Priority',type:'select',options:['Low','Medium','High','Critical']},{key:'health',label:'Health',type:'select',options:['On track','At risk','Off track']},{key:'fundingSource',label:'Funding source',type:'text'},{key:'benefits',label:'Expected benefits',type:'textarea'},{key:'risks',label:'Risks',type:'textarea'},refs('dependsOn','Depends on','initiative','depends_on'),{key:'skillsRequired',label:'Skills required',type:'text'},{key:'rollupMethod',label:'Progress calculation',type:'select',options:['Projects','Milestones','Tasks','Key results','Manual']},{key:'checkInCadence',label:'Check-in schedule',type:'select',options:['Weekly','Fortnightly','Monthly','Quarterly']},{key:'nextCheckIn',label:'Next check-in',type:'date'}]},
 {id:'programme',label:'Programme',plural:'Programmes',icon:'FolderTree',group:'Strategy',statuses:['Proposed','Approved','In progress','On hold','Completed','Cancelled'],numberPrefix:'PGM',parent:{kind:'initiative',label:'Initiative',relationship:'part_of'},hasAmount:'Funding',hasDates:['Start','End'],fields:[refs('projects','Projects in this programme','project','part_of','',true),{key:'sponsor',label:'Sponsor',type:'person'},{key:'priority',label:'Priority',type:'select',options:['Low','Medium','High','Critical']},{key:'health',label:'Health',type:'select',options:['On track','At risk','Off track']},{key:'benefits',label:'Expected benefits',type:'textarea'},{key:'risks',label:'Risks',type:'textarea'},refs('dependsOn','Depends on','programme','depends_on'),{key:'rollupMethod',label:'Progress calculation',type:'select',options:['Projects','Milestones','Tasks','Manual']}]},
 {id:'customer',label:'Customer',plural:'Customers',icon:'Building2',group:'Customers',statuses:['Prospect','Active','On hold','Former'],numberPrefix:'CUS',fields:[{key:'industry',label:'Industry',type:'text'},{key:'contactName',label:'Main contact',type:'text'},{key:'email',label:'Contact email',type:'email'},{key:'phone',label:'Phone',type:'text'},{key:'website',label:'Website',type:'url'},refs('projects','Projects for this customer','project','related_to')]},
 {id:'contract',label:'Contract',plural:'Contracts',icon:'FileSignature',group:'Customers',statuses:['Draft','Negotiation','Active','Expiring','Expired','Terminated'],numberPrefix:'CON',parent:{kind:'customer',label:'Customer',relationship:'belongs_to'},hasAmount:'Contract value',hasDates:['Start','End'],fields:[{key:'renewalDate',label:'Renewal notice date',type:'date'},{key:'terms',label:'Key terms',type:'textarea'},refs('vendors','Vendors / subcontractors','vendor','supplied_by'),refs('files','Signed documents','file','attached_to',undefined,true),refs('projects','Delivery projects','project','related_to')]},
 {id:'service',label:'Service',plural:'Services',icon:'Handshake',group:'Customers',statuses:['Planned','Active','Suspended','Ended'],numberPrefix:'SRV',parent:{kind:'contract',label:'Contract',relationship:'part_of'},hasAmount:'Monthly value',hasDates:['Start','End'],fields:[{key:'serviceLevel',label:'Service level',type:'textarea',help:'Response and resolution commitments'},{key:'frequency',label:'Frequency',type:'select',options:['One-off','Weekly','Monthly','Quarterly','Annual','On demand']},refs('assets','Assets covered','asset','related_to')]},
 {id:'meeting',label:'Meeting',plural:'Meetings',icon:'CalendarClock',group:'Governance',statuses:['Scheduled','Held','Cancelled'],numberPrefix:'MTG',hasDates:['Date','Ends'],fields:[{key:'attendees',label:'Attendees',type:'people'},{key:'agenda',label:'Agenda',type:'textarea'},{key:'minutes',label:'Minutes / notes',type:'textarea'},refs('projects','Projects discussed','project','related_to'),refs('customers','Customers discussed','customer','related_to'),refs('files','Recordings and documents','file','attached_to',undefined,true)]},
 {id:'decision',label:'Decision',plural:'Decisions',icon:'Gavel',group:'Governance',statuses:['Proposed','Under review','Approved','Rejected','Implemented','Superseded','Expired'],numberPrefix:'DEC',parent:{kind:'meeting',label:'Decided in meeting',relationship:'decided_in'},hasDates:['Decision date','Review or expiry date'],fields:[{key:'decision',label:'Decision',type:'textarea'},{key:'rationale',label:'Rationale',type:'textarea'},{key:'alternatives',label:'Alternatives considered',type:'textarea'},{key:'decidedBy',label:'Decision maker',type:'person'},{key:'participants',label:'Participants',type:'people'},{key:'effectiveDate',label:'Effective date',type:'date'},{key:'impactedDepartments',label:'Impacted departments',type:'text'},{key:'risks',label:'Risks',type:'textarea'},refs('affects','Affected projects','project','related_to'),refs('goals','Related goals and objectives','objective','related_to'),refs('budgets','Related budgets','budget','related_to'),refs('evidence','Supporting evidence','file','attached_to',undefined,true),refs('tasks','Resulting tasks','task','resulted_in'),refs('supersededBy','Superseded by','decision','superseded_by')]},
];
export const workKindById=new Map(workKinds.map(k=>[k.id,k]));
export const WORK_KINDS=workKinds.map(k=>k.id);
