import {hasAction} from '../../access-policy';
import {route,readBody,HttpError,all,first,stmt,batch,uid,now,str,idOf,oneOf,parseJson,auditStatement} from '../../server/core';
import {search,autocomplete,loadKnowledge,visibleSources,registerSource,answerWithAi,freshnessSweep,ensureSweeps,STATES} from '../../server/knowledge-intel';
import {decideDecision,decisionDossier,reviewSuggestion,completeReview,ask,postAnswer,questionAction,questionDetail} from '../../server/knowledge-api';
import {canSeeWork,type WorkRow} from '../../server/work';
import {enqueueStatement,kick} from '../../server/jobs';
import type {Member} from '../../server/policy';

// Company Knowledge Intelligence API: search, knowledge items, pipeline operations, Decision Register,
// meetings, taxonomy, freshness reviews, questions and answers, and AI suggestions awaiting review.
const admin=(u:Member)=>u.role==='admin';
const TAXONOMY_KINDS=['topic','category','tag','term','acronym','process','record_type','sensitivity','retention_class','synonym'] as const;
export const GET=route(async(req,u)=>{
 const q=new URL(req.url).searchParams;const view=q.get('view')||'search';
 await ensureSweeps(u.tenantId).catch(()=>{});
 if(view==='search')return search(u,{q:q.get('q')||'',type:q.get('type')||'',kind:q.get('kind')||'',department:q.get('department')||'',projectId:q.get('project')||'',classification:q.get('classification')||'',owner:q.get('owner')||'',person:q.get('person')||'',from:q.get('from')||'',to:q.get('to')||'',fileType:q.get('fileType')||'',topic:q.get('topic')||'',page:Number(q.get('page'))||1,size:Number(q.get('size'))||20,semantic:q.get('semantic')!=='0'});
 if(view==='autocomplete')return {suggestions:await autocomplete(u,q.get('q')||'')};
 if(view==='searches')return {recent:await all("SELECT id,query,filters_json AS filters,created_at AS createdAt FROM knowledge_searches WHERE tenant_id=? AND member_id=? AND saved=0 ORDER BY created_at DESC LIMIT 15",u.tenantId,u.id),saved:await all("SELECT id,name,query,filters_json AS filters FROM knowledge_searches WHERE tenant_id=? AND member_id=? AND saved=1 ORDER BY name",u.tenantId,u.id)};
 if(view==='item'){const k=await loadKnowledge(u,idOf(q.get('id'),'Item'));const jobs=await all('SELECT stage,status,detail,cost_micros AS cost,attempt,created_at AS createdAt FROM knowledge_jobs WHERE tenant_id=? AND knowledge_id=? ORDER BY created_at DESC LIMIT 50',u.tenantId,k.id);const sugg=await all("SELECT id,kind,payload_json AS payload,citations_json AS citations,confidence,status FROM knowledge_suggestions WHERE tenant_id=? AND knowledge_id=? ORDER BY created_at DESC LIMIT 50",u.tenantId,k.id);
  return {item:{...k,search_text:undefined,detail:parseJson(k.detail_json,{}),topics:parseJson(k.topics_json,[]),tags:parseJson(k.tags_json,[]),entities:parseJson(k.entities_json,{}),lineage:parseJson(k.lineage_json,{})},jobs,suggestions:sugg.map(s=>({...(s as object),payload:parseJson(String((s as {payload:string}).payload),{}),citations:parseJson(String((s as {citations:string}).citations),[])})),canManage:admin(u)||k.owner_id===u.id}}
 if(view==='decisions'){const rows=(await all<WorkRow>("SELECT * FROM work_records WHERE tenant_id=? AND kind='decision' AND deleted_at IS NULL ORDER BY coalesce(start_date,created_at) DESC LIMIT 1000",u.tenantId)).filter(r=>canSeeWork(u,r)&&(!q.get('status')||r.status===q.get('status')));const text=(q.get('q')||'').toLowerCase();
  return {decisions:rows.filter(r=>!text||`${r.number} ${r.title} ${r.data_json}`.toLowerCase().includes(text)).map(r=>{const d=parseJson<Record<string,unknown>>(r.data_json,{});return {id:r.id,number:r.number,title:r.title,status:r.status,date:r.start_date,reviewDate:r.end_date,decisionMaker:d.decidedBy||r.owner_id,meetingId:r.parent_id,department:r.department,affects:Array.isArray(d.affects)?d.affects.length:0,evidence:Array.isArray(d.evidence)?d.evidence.length:0,superseded:Array.isArray(d.supersededBy)&&d.supersededBy.length>0}})}}
 if(view==='decision')return decisionDossier(u,idOf(q.get('id'),'Decision'));
 if(view==='meetings'){const rows=(await all<WorkRow>("SELECT * FROM work_records WHERE tenant_id=? AND kind='meeting' AND deleted_at IS NULL ORDER BY coalesce(start_date,created_at) DESC LIMIT 500",u.tenantId)).filter(r=>canSeeWork(u,r));
  const out=[];for(const m of rows){const files=await all<{id:string,name:string,mime:string,processing_status:string}>("SELECT f.id,f.name,f.mime,f.processing_status FROM file_links l JOIN files f ON f.id=l.file_id AND f.tenant_id=l.tenant_id WHERE l.tenant_id=? AND l.entity_type IN ('meeting','work_record') AND l.entity_id=? AND f.deleted_at IS NULL",u.tenantId,m.id).catch(()=>[]);out.push({id:m.id,number:m.number,title:m.title,status:m.status,date:m.start_date,recordings:files.filter(f=>/^(audio|video)\//.test(f.mime)).length,documents:files.length,decisions:(await first<{n:number}>("SELECT count(*) AS n FROM work_records WHERE tenant_id=? AND kind='decision' AND parent_id=? AND deleted_at IS NULL",u.tenantId,m.id))?.n||0})}return {meetings:out}}
 if(view==='policies'){const r=await search(u,{q:q.get('q')||'',kind:'policy',size:50});return r}
 if(view==='topics'){const tax=await all<{id:string,kind:string,name:string,definition:string,parent_id:string|null,synonyms_json:string,status:string}>("SELECT * FROM knowledge_taxonomy WHERE tenant_id=? AND status='active' AND kind IN ('topic','category','process') ORDER BY name",u.tenantId);const rows=await visibleSources(u,await all("SELECT * FROM knowledge_sources WHERE tenant_id=? AND removed_at IS NULL AND status IN ('ready','partial') AND topics_json<>'[]' LIMIT 3000",u.tenantId));
  return {topics:tax.map(t=>({id:t.id,kind:t.kind,name:t.name,definition:t.definition,parentId:t.parent_id,synonyms:parseJson(t.synonyms_json,[]),count:rows.filter(r=>r.topics_json.includes(`"id":"${t.id}"`)).length}))}}
 if(view==='taxonomy'){return {items:(await all<{id:string,kind:string,name:string,definition:string,parent_id:string|null,synonyms_json:string,retention_days:number|null,status:string,origin:string,proposed_by:string,approved_by:string|null,updated_at:string}>('SELECT * FROM knowledge_taxonomy WHERE tenant_id=? ORDER BY kind,name',u.tenantId)).map(t=>({id:t.id,kind:t.kind,name:t.name,definition:t.definition,parentId:t.parent_id,synonyms:parseJson(t.synonyms_json,[]),retentionDays:t.retention_days,status:t.status,origin:t.origin,approvedBy:t.approved_by,updatedAt:t.updated_at})),kinds:TAXONOMY_KINDS,canManage:admin(u),suggestions:admin(u)?await all("SELECT id,payload_json AS payload,created_at AS createdAt FROM knowledge_suggestions WHERE tenant_id=? AND kind='tag' AND status='pending' ORDER BY created_at DESC LIMIT 50",u.tenantId):[]}}
 if(view==='reviews'){const rows=await all<{id:string,knowledge_id:string,reason:string,detail:string,assignee_id:string|null,status:string,due_at:string|null,outcome:string,created_at:string}>(`SELECT * FROM knowledge_reviews WHERE tenant_id=? AND ${q.get('all')==='1'&&admin(u)?'1=1':'assignee_id=?'} ORDER BY status='open' DESC,created_at DESC LIMIT 300`,u.tenantId,...(q.get('all')==='1'&&admin(u)?[]:[u.id]));const ks=await all<{id:string,title:string,url:string,kind:string}>(`SELECT id,title,url,kind FROM knowledge_sources WHERE tenant_id=? AND id IN (${rows.map(()=>'?').join(',')||"''"})`,u.tenantId,...rows.map(r=>r.knowledge_id));
  return {reviews:rows.map(r=>({...r,item:ks.find(k=>k.id===r.knowledge_id)||null}))}}
 if(view==='questions'){const rows=await all<{id:string,title:string,status:string,department:string,visibility:string,asker_id:string,escalated_to:string,created_at:string}>('SELECT id,title,status,department,visibility,asker_id,escalated_to,created_at FROM knowledge_questions WHERE tenant_id=? ORDER BY created_at DESC LIMIT 500',u.tenantId);
  const vis=rows.filter(r=>u.role==='admin'||r.asker_id===u.id||r.visibility==='company'||r.department.toLowerCase()===u.department.toLowerCase()||r.escalated_to.toLowerCase()===u.department.toLowerCase());
  const ans=vis.length?await all<{question_id:string,kind:string,citations_json:string}>(`SELECT question_id,kind,citations_json FROM knowledge_answers WHERE tenant_id=? AND question_id IN (${vis.map(()=>'?').join(',')})`,u.tenantId,...vis.map(r=>r.id)):[];const {questionState}=await import('../../server/knowledge-api');
  return {questions:vis.filter(r=>!q.get('status')||r.status===q.get('status')).map(r=>({...r,state:questionState(r.status,r.escalated_to,ans.filter(a=>a.question_id===r.id).map(a=>({kind:a.kind,cited:a.citations_json!=='[]'})))}))}}
 if(view==='question')return questionDetail(u,idOf(q.get('id'),'Question'));
 if(view==='suggestions'){const rows=await all<{id:string,knowledge_id:string|null,kind:string,payload_json:string,citations_json:string,confidence:number|null,status:string,created_at:string}>("SELECT * FROM knowledge_suggestions WHERE tenant_id=? AND status='pending' AND kind IN ('decision','action_item','relationship') ORDER BY created_at DESC LIMIT 300",u.tenantId);
  const ks=await visibleSources(u,await all(`SELECT * FROM knowledge_sources WHERE tenant_id=? AND id IN (${rows.map(()=>'?').join(',')||"''"})`,u.tenantId,...rows.map(r=>r.knowledge_id)));const ok=new Map(ks.map(k=>[k.id,k]));
  return {suggestions:rows.filter(r=>r.knowledge_id&&ok.has(r.knowledge_id)).filter(r=>{const p=parseJson<{reviewerId?:string}>(r.payload_json,{});return admin(u)||!p.reviewerId||p.reviewerId===u.id||hasAction(u,'knowledge','update')}).map(r=>({id:r.id,kind:r.kind,payload:parseJson(r.payload_json,{}),citations:parseJson(r.citations_json,[]),confidence:r.confidence,source:{id:r.knowledge_id,title:ok.get(r.knowledge_id!)?.title,url:ok.get(r.knowledge_id!)?.url},createdAt:r.created_at}))}}
 if(view==='sources'){if(!admin(u))throw new HttpError(403,'Only administrators manage knowledge sources.');
  return {byStatus:await all('SELECT status,count(*) AS n FROM knowledge_sources WHERE tenant_id=? GROUP BY status',u.tenantId),byType:await all('SELECT source_type AS type,count(*) AS n,sum(cost_micros) AS cost FROM knowledge_sources WHERE tenant_id=? GROUP BY source_type',u.tenantId),recent:await all("SELECT id,title,source_type AS type,status,stage,last_error AS error,attempts,cost_micros AS cost,processed_at AS processedAt,updated_at AS updatedAt FROM knowledge_sources WHERE tenant_id=? ORDER BY updated_at DESC LIMIT 200",u.tenantId),failed:await all("SELECT id,title,source_type AS type,status,last_error AS error,attempts,updated_at AS updatedAt FROM knowledge_sources WHERE tenant_id=? AND status IN ('failed','retrying','unsupported','partial') ORDER BY updated_at DESC LIMIT 200",u.tenantId),states:STATES,jobs:await all("SELECT kind,status,count(*) AS n FROM jobs WHERE tenant_id=? AND kind LIKE 'knowledge.%' GROUP BY kind,status",u.tenantId)}}
 if(view==='retention'){if(!admin(u))throw new HttpError(403,'Only administrators manage retention.');return {classes:await all("SELECT id,name,definition,retention_days AS retentionDays,status FROM knowledge_taxonomy WHERE tenant_id=? AND kind='retention_class' ORDER BY name",u.tenantId),expired:await all("SELECT id,title,retention_class AS retentionClass,expires_at AS expiresAt FROM knowledge_sources WHERE tenant_id=? AND status='expired' ORDER BY expires_at DESC LIMIT 100",u.tenantId),removed:await all("SELECT id,title,source_type AS type,removed_at AS removedAt FROM knowledge_sources WHERE tenant_id=? AND removed_at IS NOT NULL ORDER BY removed_at DESC LIMIT 100",u.tenantId)}}
 if(view==='summary-versions'){const fid=idOf(q.get('fileId'),'File');const {canSeeFile}=await import('../../server/entities');const f=await first<Parameters<typeof canSeeFile>[1]>('SELECT * FROM files WHERE id=? AND tenant_id=?',fid,u.tenantId);if(!f||!canSeeFile(u,f))throw new HttpError(404,'File not found.');
  const machine=await first<{content:string,created_at:string}>("SELECT content,created_at FROM file_artifacts WHERE tenant_id=? AND file_id=? AND kind='summary' ORDER BY created_at DESC LIMIT 1",u.tenantId,fid);return {machine:machine?{content:parseJson(machine.content,{}),at:machine.created_at}:null,human:(await all<{content:string,edited_by:string,created_at:string,note:string}>("SELECT content,edited_by,created_at,note FROM artifact_versions WHERE tenant_id=? AND file_id=? AND kind='summary' ORDER BY created_at DESC LIMIT 20",u.tenantId,fid)).map(v=>({content:parseJson(v.content,{}),editedBy:v.edited_by,at:v.created_at,note:v.note}))}}
 throw new HttpError(400,'Unknown view.');
});
export const POST=route(async(req,u)=>{
 const b=await readBody(req,200000);const action=str(b.action,'Action',40);
 switch(action){
  case 'save-search':{const id=uid();await stmt('INSERT INTO knowledge_searches(id,tenant_id,member_id,query,filters_json,saved,name,created_at) VALUES(?,?,?,?,?,1,?,?)',id,u.tenantId,u.id,str(b.q,'Search',200,false),JSON.stringify(b.filters||{}).slice(0,2000),str(b.name,'Name',60),now()).run();return {id}}
  case 'delete-search':{await stmt('DELETE FROM knowledge_searches WHERE id=? AND tenant_id=? AND member_id=?',idOf(b.id,'Search'),u.tenantId,u.id).run();return {ok:true}}
  case 'reprocess':{const k=await loadKnowledge(u,idOf(b.id,'Item'));if(!admin(u)&&k.owner_id!==u.id)throw new HttpError(403,'Only the owner or an administrator reprocesses knowledge.');const typ=k.source_type==='work_record'?(await first<{kind:string}>('SELECT kind FROM work_records WHERE id=?',k.source_id))?.kind||'work_record':k.source_type;await registerSource(u.tenantId,typ,k.source_id,true);await auditStatement(u,'Knowledge reprocessing requested',k.source_id,k.department,null,null).run();return {queued:true}}
  case 'rebuild':{if(!admin(u))throw new HttpError(403,'Only administrators rebuild the knowledge index.');await enqueueStatement(u.tenantId,'knowledge.rebuild',u.tenantId,{},{key:`knowledge-rebuild:${now().slice(0,16)}`}).run();kick(2);return {queued:true}}
  case 'freshness':{if(!admin(u))throw new HttpError(403,'Only administrators run the freshness check.');return {created:await freshnessSweep(u.tenantId)}}
  case 'taxonomy-save':{
   const kind=oneOf(b.kind,TAXONOMY_KINDS,'taxonomy type');const name=str(b.name,'Name',120);const id=b.id?idOf(b.id,'Entry'):uid();
   // Staff (and AI) may propose; governed changes become active only when an administrator approves them.
   const status=admin(u)?'active':'proposed';const syn=JSON.stringify((Array.isArray(b.synonyms)?b.synonyms:[]).map(x=>str(x,'Synonym',80)).slice(0,30));
   const days=b.retentionDays===undefined||b.retentionDays===''||b.retentionDays===null?null:Math.round(Number(b.retentionDays));if(days!==null&&(!Number.isFinite(days)||days<1||days>36500))throw new HttpError(400,'Retention must be between 1 and 36,500 days.');
   if(b.id){if(!admin(u))throw new HttpError(403,'Only administrators change the taxonomy.');await batch([stmt('UPDATE knowledge_taxonomy SET name=?,definition=?,parent_id=?,synonyms_json=?,retention_days=?,updated_at=? WHERE id=? AND tenant_id=?',name,str(b.definition,'Definition',2000,false),b.parentId?idOf(b.parentId,'Parent'):null,syn,days,now(),id,u.tenantId),auditStatement(u,`Taxonomy ${kind} updated`,id,'Knowledge',null,{name})]);return {id}}
   if(await first('SELECT id FROM knowledge_taxonomy WHERE tenant_id=? AND kind=? AND lower(name)=lower(?)',u.tenantId,kind,name))throw new HttpError(409,'That entry already exists.');
   await batch([stmt('INSERT INTO knowledge_taxonomy(id,tenant_id,kind,name,definition,parent_id,synonyms_json,retention_days,status,origin,proposed_by,approved_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',id,u.tenantId,kind,name,str(b.definition,'Definition',2000,false),b.parentId?idOf(b.parentId,'Parent'):null,syn,days,status,'human',u.id,status==='active'?u.id:null,now(),now()),auditStatement(u,`Taxonomy ${kind} ${status==='active'?'added':'proposed'}`,id,'Knowledge',null,{name})]);return {id,status};
  }
  case 'taxonomy-approve':case 'taxonomy-retire':{if(!admin(u))throw new HttpError(403,'Only administrators govern the taxonomy.');const id=idOf(b.id,'Entry');await batch([stmt(`UPDATE knowledge_taxonomy SET status=?,approved_by=CASE WHEN ?='active' THEN ? ELSE approved_by END,updated_at=? WHERE id=? AND tenant_id=?`,action==='taxonomy-approve'?'active':'retired',action==='taxonomy-approve'?'active':'retired',u.id,now(),id,u.tenantId),auditStatement(u,`Taxonomy entry ${action==='taxonomy-approve'?'approved':'retired'}`,id,'Knowledge',null,null)]);return {ok:true}}
  case 'suggestion-accept':case 'suggestion-reject':return reviewSuggestion(req,u,idOf(b.id,'Suggestion'),action==='suggestion-accept',(b.edits&&typeof b.edits==='object'?b.edits:{}) as Record<string,unknown>);
  case 'review-complete':return completeReview(u,idOf(b.id,'Review'),{outcome:String(b.outcome||'still_accurate'),notes:str(b.notes,'Notes',1000,false),supersededBy:b.supersededBy?String(b.supersededBy):undefined,nextReviewDays:b.nextReviewDays?Number(b.nextReviewDays):undefined});
  case 'set-review':{const k=await loadKnowledge(u,idOf(b.id,'Item'));if(!admin(u)&&k.owner_id!==u.id)throw new HttpError(403,'Only the owner sets review dates.');await batch([stmt('UPDATE knowledge_sources SET next_review_at=?,expires_at=?,owner_id=coalesce(?,owner_id),updated_at=? WHERE id=?',b.nextReviewAt?new Date(String(b.nextReviewAt)).toISOString():k.next_review_at,b.expiresAt?new Date(String(b.expiresAt)).toISOString():k.expires_at,b.ownerId?idOf(b.ownerId,'Owner'):null,now(),k.id),auditStatement(u,'Knowledge review schedule changed',k.source_id,k.department,{next:k.next_review_at,expires:k.expires_at},{next:b.nextReviewAt,expires:b.expiresAt})]);return {ok:true}}
  case 'decide-decision':return decideDecision(u,idOf(b.id,'Decision'),b.approve===true,str(b.comment,'Comment',1000,false));
  case 'decision-status':{const {loadWork}=await import('../../server/work');const r=await loadWork(u,idOf(b.id,'Decision'));if(r.kind!=='decision')throw new HttpError(400,'Not a decision.');const to=oneOf(b.status,['Under review','Implemented','Superseded','Expired'] as const,'status');const {dispatch}=await import('../../server/dispatch');const d=parseJson<Record<string,unknown>>(r.data_json,{});
   if(to==='Superseded'&&!b.supersededBy)throw new HttpError(400,'Choose the decision that replaces it.');const data=to==='Superseded'?{...d,supersededBy:[idOf(b.supersededBy,'Decision')]}:d;await dispatch(req,'business',{action:'save',id:r.id,status:to,data});return {ok:true}}
  case 'ask':return ask(u,b);
  case 'answer':return postAnswer(u,idOf(b.id,'Question'),str(b.body,'Answer',8000),'expert');
  case 'ai-answer':return answerWithAi(u,idOf(b.id,'Question'));
  case 'question':return questionAction(req,u,idOf(b.id,'Question'),str(b.op,'Operation',20),b);
  case 'summary-edit':{
   // Human corrections of decisions, action items and summaries; the machine version is kept.
   const fid=idOf(b.fileId,'File');const {canSeeFile,canEditFile}=await import('../../server/entities');const f=await first<Parameters<typeof canSeeFile>[1]&{department:string}>('SELECT * FROM files WHERE id=? AND tenant_id=?',fid,u.tenantId);if(!f||!canSeeFile(u,f))throw new HttpError(404,'File not found.');if(!canEditFile(u,f))throw new HttpError(403,'You cannot correct this file’s knowledge.');
   const c=(b.content&&typeof b.content==='object'?b.content:{}) as Record<string,unknown>;const clean={short:str(c.short,'Summary',2000,false),detailed:str(c.detailed,'Detailed notes',20000,false),decisions:(Array.isArray(c.decisions)?c.decisions:[]).map(x=>str(x,'Decision',500)).slice(0,50),actionItems:(Array.isArray(c.actionItems)?c.actionItems:[]).slice(0,50).map((x:unknown)=>{const a=(x||{}) as Record<string,unknown>;return {text:str(a.text,'Action',500),owner:str(a.owner,'Owner',120,false),due:str(a.due,'Due',40,false)}})};
   await batch([stmt("INSERT INTO artifact_versions(id,tenant_id,file_id,kind,origin,content,note,edited_by,created_at) VALUES(?,?,?,'summary','human',?,?,?,?)",uid(),u.tenantId,fid,JSON.stringify(clean),str(b.note,'Note',300,false),u.id,now()),auditStatement(u,'Knowledge corrected (decisions, actions or summary)',fid,f.department,null,{decisions:clean.decisions.length,actions:clean.actionItems.length})]);
   await registerSource(u.tenantId,'file',fid,true);return {ok:true};
  }
  case 'retention-save':{if(!admin(u))throw new HttpError(403,'Only administrators manage retention.');const id=b.id?idOf(b.id,'Class'):uid();const days=Math.round(Number(b.retentionDays));if(!(days>=1&&days<=36500))throw new HttpError(400,'Retention must be between 1 and 36,500 days.');
   await batch([b.id?stmt('UPDATE knowledge_taxonomy SET name=?,definition=?,retention_days=?,updated_at=? WHERE id=? AND tenant_id=?',str(b.name,'Name',80),str(b.definition,'Definition',500,false),days,now(),id,u.tenantId):stmt("INSERT INTO knowledge_taxonomy(id,tenant_id,kind,name,definition,retention_days,status,origin,proposed_by,approved_by,created_at,updated_at) VALUES(?,?,'retention_class',?,?,?,'active','human',?,?,?,?)",id,u.tenantId,str(b.name,'Name',80),str(b.definition,'Definition',500,false),days,u.id,u.id,now(),now()),auditStatement(u,'Retention class saved',id,'Knowledge',null,{days})]);return {id}}
 }
 throw new HttpError(400,'Unknown action.');
});
