'use client';
import {useCallback,useEffect,useState,type ReactNode} from 'react';
import {api,useApi,useRoute,go,ago,cx,dateTime} from './lib';
import {useApp,Btn,Chip,Header,Field,ErrorNote,Skeleton,Empty,Icon,Note,Tabs,Modal,Card,Markdown,TagPicker} from './kit';

// The AI workforce. Agents live where the work is: each agent is assigned to pages and appears there (the
// agent dock and record "Ask an agent" buttons). The AI Control Tower is the governance console: agents,
// runs, approvals, providers, tools, knowledge, evaluations, usage and policies.
type AgentSum={id:string,name:string,description:string,template:string,ownerId:string,status:string,killed:boolean,publishedVersion:number|null,draftVersion:number,updatedAt:string,pages:string[],runAs?:string,tools:string[],purpose?:string};
type Def={purpose:string,instructions:string,pages:string[],recordScope:'own'|'department'|'all',serviceDepartment?:string,runAs:'requester'|'service',tools:string[],connectors:string[],knowledge:{search:boolean,graph:boolean,files:boolean,connectors:boolean},model?:string,temperature:number,maxSteps:number,tokenBudget:number,costBudgetMicros:number,schedule:'none'|'daily'|'weekly',scheduledPrompt?:string,triggers:{module?:string,action?:string,prompt:string}[],extraApprovals:string[],retentionDays:number,roles:string[]};
type Tool={id:string,label:string,description:string,kind:'read'|'mutation',risk:string,confirm:boolean,page:string,action:string,perRun:number,audit:string};
type Approval={id:string,runId:string,agentId:string,agent:string,tool:string,toolLabel:string,target:string,input:Record<string,unknown>,effect:string,evidence:{title:string,link:string}[],risk:string,requestedBy:string,createdAt:string};
type RunResult={runId:string,status:string,output:string,error:string,citations:{title:string,link:string}[],version:number,steps:number,approvals:{id:string,tool:string,target:string,effect:string,risk:string,status:string}[]};
const statusTone=(s:string)=>s==='active'||s==='succeeded'?'green':s==='failed'||s==='killed'||s==='disabled'?'red':s==='paused'||s==='waiting_approval'?'amber':'gray';
// Maps an app route to the permission page an agent is assigned to.
const PAGE_OF:Record<string,string>={home:'overview',tickets:'maintenance',assets:'assets',inventory:'inventory',maintenance:'schedules',people:'people',projects:'projects',tasks:'tasks',messages:'messages',spaces:'knowledge',files:'documents',reports:'reports',business:'business',pages:'app-pages',graph:'graph',studio:'studio',apps:'studio'};
export function pageOfRoute(app:string,parts:string[]){if(app==='purchasing')return parts[0]==='po'?'procurement':'requests';return PAGE_OF[app]||app}

// ── Run an agent (dock, widgets, AI workforce page) ──
export function AgentRun({agent,page,record,initial,onClose}:{agent:{id:string,name:string,purpose?:string},page?:string,record?:{type:string,id:string,title?:string}|null,initial?:string,onClose?:()=>void}){
 const {toast}=useApp();const [input,setInput]=useState(initial||'');const [busy,setBusy]=useState(false);const [res,setRes]=useState<RunResult|null>(null);const [decided,setDecided]=useState<Record<string,string>>({});
 const run=async()=>{setBusy(true);setRes(null);try{setRes(await api<RunResult>('/api/agents',{action:'run',id:agent.id,input,page,record:record?{type:record.type,id:record.id}:undefined}))}catch(e){toast((e as Error).message,'error')}finally{setBusy(false)}};
 const decide=async(id:string,approve:boolean)=>{try{await api('/api/agents',{action:approve?'approve':'reject',approvalId:id});setDecided(d=>({...d,[id]:approve?'approved':'rejected'}));toast(approve?'Done — the action ran with your permissions':'Rejected');window.dispatchEvent(new Event('ows:graph-changed'))}catch(e){toast((e as Error).message,'error')}};
 return <div className="agent-run">
  {record&&<div className="agent-ctx"><Icon name="Crosshair" size={13}/>About: <b>{record.title||record.type}</b> <small className="muted">({record.type})</small></div>}
  <form onSubmit={e=>{e.preventDefault();if(input.trim())run()}}><textarea rows={3} value={input} onChange={e=>setInput(e.target.value)} placeholder={agent.purpose||`Ask ${agent.name}…`} aria-label="Request"/><div className="row-gap"><Btn type="submit" variant="primary" icon="Send" busy={busy} disabled={!input.trim()}>Run</Btn>{onClose&&<Btn variant="ghost" onClick={onClose}>Close</Btn>}<small className="muted">Uses only what you can open. Changes need your approval.</small></div></form>
  {busy&&<Skeleton rows={3}/>}
  {res&&<div className="agent-out">
   <div className="row-gap"><Chip tone={statusTone(res.status)}>{res.status.replace('_',' ')}</Chip><small className="muted">v{res.version} · {res.steps} steps</small></div>
   {res.error&&<Note tone="warn">{res.error}</Note>}
   {res.output&&<Markdown text={res.output}/>}
   {res.citations.length>0&&<div className="cites"><small className="muted">Sources:</small>{res.citations.map((c,i)=><a key={i} className="chip chip-gray" href={c.link}>{c.title}</a>)}</div>}
   {res.approvals.length>0&&<div className="agent-approvals"><b>Proposed actions</b>{res.approvals.map(a=><div key={a.id} className="agent-approval"><div><Chip tone={a.risk==='high'?'red':a.risk==='medium'?'amber':'gray'}>{a.risk} risk</Chip> <b>{a.tool.replace(/_/g,' ')}</b><p className="small">{a.effect}</p></div>{decided[a.id]||a.status!=='pending'?<Chip tone={(decided[a.id]||a.status)==='approved'?'green':'gray'}>{decided[a.id]||a.status}</Chip>:<div className="row-gap"><Btn size="sm" variant="primary" icon="Check" onClick={()=>decide(a.id,true)}>Approve</Btn><Btn size="sm" icon="X" onClick={()=>decide(a.id,false)}>Reject</Btn></div>}</div>)}</div>}
  </div>}
 </div>;
}

// Floating dock: the agents assigned to the current page, with the open record as context.
export function AgentDock(){
 const {can}=useApp();const route=useRoute();const page=pageOfRoute(route.app,route.parts);
 const [open,setOpen]=useState(false);const [record,setRecord]=useState<{type:string,id:string,title?:string}|null>(null);const [sel,setSel]=useState<string>('');
 const enabled=can('agents');
 const {data,reload}=useApi<{agents:AgentSum[],killSwitch:boolean}>(enabled?`/api/agents?page=${encodeURIComponent(page)}`:null);
 useEffect(()=>{setRecord(null)},[route.app,route.parts.join('/')]);
 useEffect(()=>{const f=(e:Event)=>{const d=(e as CustomEvent).detail||{};setRecord(d.recordId?{type:d.recordType,id:d.recordId,title:d.title}:null);setOpen(true);reload()};window.addEventListener('ows:agent',f);return()=>window.removeEventListener('ows:agent',f)},[reload]);
 const agents=data?.agents||[];const agent=agents.find(a=>a.id===sel)||agents[0];
 if(!enabled||(!agents.length&&!open))return null;
 return <>{!open&&<button className="agent-fab" onClick={()=>setOpen(true)} title="Agents for this page"><Icon name="Bot" size={18}/><span>{agents.length} agent{agents.length===1?'':'s'}</span></button>}
  {open&&<aside className="agent-dock" aria-label="Agents for this page">
   <div className="agent-dock-head"><Icon name="Bot" size={17}/><b>Agents</b><small className="muted">on this page</small><span className="spacer"/><Btn size="sm" variant="ghost" icon="X" title="Close" onClick={()=>setOpen(false)}/></div>
   {data?.killSwitch?<Note tone="warn">AI is switched off for this company by an administrator.</Note>:!agents.length?<Empty icon="Bot" title="No agents for this page">An administrator can assign agents to this page in the AI Control Tower.</Empty>:<>
    {agents.length>1&&<select aria-label="Agent" value={agent?.id} onChange={e=>setSel(e.target.value)}>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>}
    {agent&&<><p className="muted small">{agent.purpose||agent.description}</p><AgentRun key={`${agent.id}:${record?.id||''}`} agent={agent} page={page} record={record}/></>}</>}
  </aside>}</>;
}

// ── AI workforce (for everyone): agents you can use, your runs and approvals ──
export default function Agents({parts=[]}:{parts?:string[]}){
 const {s}=useApp();const {data,error,reload}=useApi<{agents:AgentSum[],canManage:boolean,killSwitch:boolean}>('/api/agents');
 const [tab,setTab]=useState(parts[0]||'agents');const [open,setOpen]=useState<AgentSum|null>(null);
 return <div className="page"><Header icon="Bot" tone="violet" title="AI workforce" subtitle={`Agents working for ${s.tenant.name}. They also appear on the pages they are assigned to.`} actions={data?.canManage&&<Btn icon="RadioTower" onClick={()=>go('admin/ai')}>AI Control Tower</Btn>}/>
  <ErrorNote error={error} onRetry={reload}/>{data?.killSwitch&&<Note tone="warn">The company-wide AI kill switch is on.</Note>}
  <Tabs value={tab} onChange={setTab} items={[{id:'agents',label:'Agents'},{id:'runs',label:'My runs'},{id:'approvals',label:'Approvals'}]}/>
  {tab==='agents'&&(!data?<Skeleton/>:!data.agents.length?<Empty icon="Bot" title="No agents available to you"/>:<div className="module-grid">{data.agents.filter(a=>a.publishedVersion).map(a=><button key={a.id} className="module-card" onClick={()=>setOpen(a)}><Icon name="Bot" size={20}/><div><b>{a.name} <Chip tone={statusTone(a.killed?'killed':a.status)}>{a.killed?'stopped':a.status}</Chip></b><small>{a.description}</small><small className="muted">Works on: {a.pages.join(', ')||'any page'}</small></div></button>)}</div>)}
  {tab==='runs'&&<Runs mine/>}
  {tab==='approvals'&&<ApprovalQueue/>}
  {open&&<Modal open wide onClose={()=>setOpen(null)} title={open.name} subtitle={open.description}><AgentRun agent={open}/></Modal>}
 </div>;
}

// ── AI Control Tower (administrators) ──
const TOWER_TABS=[{id:'overview',label:'Overview'},{id:'agents',label:'Agents'},{id:'runs',label:'Runs'},{id:'approvals',label:'Approvals'},{id:'providers',label:'Providers'},{id:'tools',label:'Tools'},{id:'knowledge',label:'Knowledge'},{id:'evaluations',label:'Evaluations'},{id:'usage',label:'Usage'},{id:'policies',label:'Policies'}];
type Tower={agents:{status:string,killed:number,n:number}[],runsByStatus:{status:string,n:number}[],totals:{runs:number,tokens:number,cost:number,avg_ms:number,successRate:number|null,failureRate:number|null},tools:{tool:string,status:string,n:number}[],violations:{detail:string,runId:string,createdAt:string}[],evals:{agentId:string,version:number,passed:number,criticalFailed:number,createdAt:string,name:string}[],usage:{provider:string,model:string,requests:number,tokens:number,failures:number}[],provider:{name:string,model:string,source:string,lastSuccess:string|null,lastFailure:string|null,company:boolean,platformDefault:boolean}|null,killSwitch:boolean,prices:Record<string,{prompt:number,completion:number}>,pending:number};
export function ControlTower({parts=[],providers}:{parts?:string[],providers?:ReactNode}){
 const tab=parts[0]||'overview';
 const tower=useApi<Tower>('/api/agents?view=tower');
 return <div className="page"><Header icon="RadioTower" tone="violet" title="AI Control Tower" subtitle="Govern every agent: who it acts for, what it may touch, what it did, what it cost, and how to stop it."/>
  <ErrorNote error={tower.error} onRetry={tower.reload}/>
  <nav className="app-nav">{TOWER_TABS.map(t=><a key={t.id} href={`#/admin/ai/${t.id}`} className={cx('app-nav-link',tab===t.id&&'on')}>{t.label}{t.id==='approvals'&&tower.data?.pending?<b className="count">{tower.data.pending}</b>:null}</a>)}</nav>
  {tab==='overview'&&(tower.data?<Overview t={tower.data} reload={tower.reload}/>:<Skeleton/>)}
  {tab==='agents'&&(parts[1]?<AgentEditor id={parts[1]}/>:<AgentList/>)}
  {tab==='runs'&&(parts[1]?<RunDetail id={parts[1]}/>:<Runs/>)}
  {tab==='approvals'&&<ApprovalQueue/>}
  {tab==='providers'&&<>{tower.data&&<ProviderHealth t={tower.data} reload={tower.reload}/>}{providers}</>}
  {tab==='tools'&&<ToolsTab t={tower.data}/>}
  {tab==='knowledge'&&<Knowledge/>}
  {tab==='evaluations'&&<Evaluations t={tower.data}/>}
  {tab==='usage'&&(tower.data?<UsageTab t={tower.data}/>:<Skeleton/>)}
  {tab==='policies'&&(tower.data?<Policies t={tower.data} reload={tower.reload}/>:<Skeleton/>)}
 </div>;
}
function Stat({label,value,tone}:{label:string,value:ReactNode,tone?:string}){return <div className={cx('ctx-fact',tone&&`tone-${tone}`)}><small>{label}</small><b>{value}</b></div>}
function Overview({t,reload}:{t:Tower,reload:()=>void}){
 const count=(f:(x:Tower['agents'][number])=>boolean)=>t.agents.filter(f).reduce((n,x)=>n+x.n,0);
 return <>{t.killSwitch&&<Note tone="warn">The company-wide AI kill switch is ON. No agent can run.</Note>}
  <div className="ctx-facts"><Stat label="Active agents" value={count(a=>a.status==='active'&&!a.killed)}/><Stat label="Stopped / disabled" value={count(a=>!!a.killed||a.status==='disabled')} tone={count(a=>!!a.killed)?'red':undefined}/><Stat label="Runs (30 days)" value={t.totals.runs}/><Stat label="Success rate" value={t.totals.successRate==null?'—':`${t.totals.successRate}%`}/><Stat label="Failure rate" value={t.totals.failureRate==null?'—':`${t.totals.failureRate}%`} tone={(t.totals.failureRate||0)>20?'red':undefined}/><Stat label="Tokens" value={t.totals.tokens.toLocaleString()}/><Stat label="Cost" value={t.totals.cost?`$${(t.totals.cost/1e6).toFixed(2)}`:'—'}/><Stat label="Avg duration" value={`${(t.totals.avg_ms/1000).toFixed(1)} s`}/><Stat label="Waiting approval" value={t.pending} tone={t.pending?'amber':undefined}/><Stat label="Policy violations blocked" value={t.violations.length} tone={t.violations.length?'red':undefined}/></div>
  <Card title="Runs by status">{t.runsByStatus.length?<div className="lb-bars">{t.runsByStatus.map(s=><div key={s.status} className="lb-bar"><span>{s.status}</span><i style={{width:`${Math.max(4,s.n/Math.max(...t.runsByStatus.map(x=>x.n))*100)}%`}}/><b>{s.n}</b></div>)}</div>:<p className="muted small">No runs yet.</p>}</Card>
  <Card title="Recent policy violations">{t.violations.length?<ul className="mini-list">{t.violations.map((v,i)=><li key={i} className="mini-row"><a href={`#/admin/ai/runs/${v.runId}`}>{ago(v.createdAt)}</a><span className="small">{v.detail}</span></li>)}</ul>:<p className="muted small">None.</p>}</Card>
  <Btn size="sm" variant="ghost" icon="RefreshCw" onClick={reload}>Refresh</Btn></>;
}
function AgentList(){
 const {toast}=useApp();const {data,error,reload}=useApi<{agents:AgentSum[]}>('/api/agents');const tpl=useApi<{templates:{id:string,name:string,description:string,def:Partial<Def>}[]}>('/api/agents?view=templates');const [creating,setCreating]=useState(false);
 const create=async(template?:string,name?:string)=>{try{const r=await api<{id:string}>('/api/agents',{action:'create',template,name});go(`admin/ai/agents/${r.id}`)}catch(e){toast((e as Error).message,'error')}};
 return <>{<ErrorNote error={error} onRetry={reload}/>}<div className="row-gap"><Btn variant="primary" icon="Plus" onClick={()=>setCreating(true)}>New agent</Btn></div>
  {!data?<Skeleton/>:!data.agents.length?<Empty icon="Bot" title="No agents yet">Start from a template: executive briefing, procurement, project, IT support, asset, maintenance, HR, knowledge, finance, compliance or integration.</Empty>:
  <div className="lb-table"><table className="plain"><thead><tr><th>Agent</th><th>Status</th><th>Runs as</th><th>Pages</th><th>Tools</th><th>Version</th><th>Updated</th></tr></thead><tbody>{data.agents.map(a=><tr key={a.id}><td><a href={`#/admin/ai/agents/${a.id}`}><b>{a.name}</b></a><br/><small className="muted">{a.description}</small></td><td><Chip tone={statusTone(a.killed?'killed':a.status)}>{a.killed?'kill switch on':a.status}</Chip></td><td>{a.runAs==='service'?'Service identity':'Requester'}</td><td>{a.pages.join(', ')||'Any'}</td><td>{a.tools.length}</td><td>{a.publishedVersion?`v${a.publishedVersion}`:'draft'}</td><td className="muted">{ago(a.updatedAt)}</td></tr>)}</tbody></table></div>}
  {creating&&<Modal open wide onClose={()=>setCreating(false)} title="New agent" subtitle="Templates set purpose, pages, tools and instructions. You can change everything before publishing."><div className="module-grid">{(tpl.data?.templates||[]).map(t=><button key={t.id} className="module-card" onClick={()=>create(t.id)}><Icon name="Bot" size={18}/><div><b>{t.name}</b><small>{t.description}</small><small className="muted">{(t.def.tools||[]).length} tools · {(t.def.pages||[]).join(', ')}</small></div></button>)}<button className="module-card" onClick={()=>create(undefined,'Custom agent')}><Icon name="Plus" size={18}/><div><b>Blank agent</b><small>Read-only tools only, until you add more.</small></div></button></div></Modal>}</>;
}
function AgentEditor({id}:{id:string}){
 const {s,toast,ask}=useApp();
 const {data,error,reload}=useApi<{agent:AgentSum,definition:Def,published:Def|null,versions:{version:number,evalStatus:string,createdAt:string}[],evals:{id:string,version:number,results:{id:string,name:string,critical:boolean,status:string,detail:string}[],passed:number,criticalFailed:number,createdAt:string}[]}>(`/api/agents?id=${id}`);
 const tools=useApi<{tools:Tool[]}>('/api/agents?view=tools');const cons=useApi<{connectors:{id:string,name:string}[]}>('/api/connectors');const pages=useApi<{pages:string[]}>('/api/connectors');
 const [d,setD]=useState<Def|null>(null);const [meta,setMeta]=useState({name:'',description:''});const [busy,setBusy]=useState('');const [tab,setTab]=useState('setup');
 useEffect(()=>{if(data){setD(data.definition);setMeta({name:data.agent.name,description:data.agent.description})}},[data]);
 const call=useCallback(async(action:string,extra:Record<string,unknown>={},msg?:string)=>{setBusy(action);try{const r=await api<Record<string,unknown>>('/api/agents',{action,id,...extra});if(msg)toast(msg);reload();return r}catch(e){const m=(e as Error).message;try{const j=JSON.parse(m) as {message:string};toast(j.message,'error')}catch{toast(m,'error')}return null}finally{setBusy('')}},[id,reload,toast]);
 if(error)return <ErrorNote error={error} onRetry={reload}/>;if(!data||!d)return <Skeleton rows={8}/>;
 const a=data.agent;const set=(p:Partial<Def>)=>setD({...d,...p});
 const allPages=[...new Set([...(pages.data?.pages||[]),...d.pages])];
 return <div>
  <div className="record-head"><div><h2>{a.name}</h2><div className="row-gap"><Chip tone={statusTone(a.killed?'killed':a.status)}>{a.killed?'kill switch on':a.status}</Chip><small className="muted">{a.publishedVersion?`live v${a.publishedVersion}`:'not published'} · draft {a.draftVersion}</small></div></div>
   <div className="row-gap"><Btn icon="Save" busy={busy==='save'} onClick={()=>call('save',{definition:d,...meta},'Draft saved')}>Save draft</Btn><Btn icon="FlaskConical" busy={busy==='evaluate'} onClick={()=>call('evaluate',{},'Evaluation finished')}>Evaluate</Btn><Btn variant="primary" icon="Rocket" busy={busy==='publish'} onClick={async()=>{await call('save',{definition:d,...meta});await call('publish',{},'Published — critical evaluations passed')}}>Publish</Btn>
    {a.killed||a.status!=='active'?<Btn icon="Play" onClick={()=>call('resume',{},'Resumed')}>Resume</Btn>:<><Btn icon="Pause" onClick={()=>call('pause',{},'Paused')}>Pause</Btn><Btn icon="OctagonX" onClick={async()=>{if(await ask({title:`Stop ${a.name} now?`,body:'Running work is cancelled and the agent cannot run until resumed.',confirm:'Stop agent',danger:true})!==false)call('kill',{},'Stopped')}}>Kill switch</Btn></>}</div></div>
  <Tabs value={tab} onChange={setTab} items={[{id:'setup',label:'Setup'},{id:'access',label:'Access & tools'},{id:'triggers',label:'Triggers'},{id:'limits',label:'Limits'},{id:'test',label:'Test'},{id:'evals',label:'Evaluations',count:data.evals.length},{id:'versions',label:'Versions',count:data.versions.length},{id:'runs',label:'Runs'}]}/>
  {tab==='setup'&&<div className="form-grid"><Field label="Name"><input value={meta.name} onChange={e=>setMeta({...meta,name:e.target.value})}/></Field><Field label="Description"><input value={meta.description} onChange={e=>setMeta({...meta,description:e.target.value})}/></Field>
   <Field label="Purpose" wide><input value={d.purpose} onChange={e=>set({purpose:e.target.value})}/></Field><Field label="Instructions" wide hint="The agent must cite sources and cannot change records without approval — this is enforced by the platform, not only by these instructions."><textarea rows={8} value={d.instructions} onChange={e=>set({instructions:e.target.value})}/></Field>
   <Field label="Owner"><select value={a.ownerId} onChange={e=>call('set-owner',{ownerId:e.target.value},'Owner changed')}>{s.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>
   <Field label="Model" hint="Empty uses the company’s default model gateway."><input value={d.model||''} onChange={e=>set({model:e.target.value||undefined})}/></Field><Field label="Temperature"><input type="number" step="0.1" min={0} max={1} value={d.temperature} onChange={e=>set({temperature:Number(e.target.value)})}/></Field></div>}
  {tab==='access'&&<div className="form-grid">
   <Field label="Pages it works on" wide hint="The agent appears on these pages and can only use tools belonging to them."><TagPicker values={d.pages} options={allPages} onChange={v=>set({pages:v})} placeholder="Any page"/></Field>
   <Field label="Who can use it" hint="Empty = everyone with AI access. __owner__ = only the owner."><TagPicker values={d.roles} options={['admin','manager','employee','__owner__',...s.roles.map(r=>r.id)]} onChange={v=>set({roles:v})} placeholder="Everyone"/></Field>
   <Field label="Acts as"><select value={d.runAs} onChange={e=>set({runAs:e.target.value as Def['runAs']})}><option value="requester">The person using it (their permissions)</option><option value="service">A restricted service identity</option></select></Field>
   {d.runAs==='service'&&<><Field label="Service record scope"><select value={d.recordScope} onChange={e=>set({recordScope:e.target.value as Def['recordScope']})}><option value="own">Own records</option><option value="department">One department</option><option value="all">All records on its pages</option></select></Field><Field label="Service department"><select value={d.serviceDepartment||''} onChange={e=>set({serviceDepartment:e.target.value})}><option value="">—</option>{s.departments.map(x=><option key={x.name}>{x.name}</option>)}</select></Field></>}
   <Field label="Tools" wide>{!tools.data?<Skeleton rows={3}/>:<div className="tool-grid">{tools.data.tools.map(t=><label key={t.id} className={cx('tool-item',t.kind==='mutation'&&'mut')}><input type="checkbox" checked={d.tools.includes(t.id)} onChange={e=>set({tools:e.target.checked?[...d.tools,t.id]:d.tools.filter(x=>x!==t.id)})}/><div><b>{t.label}</b> <Chip tone={t.kind==='read'?'gray':t.risk==='high'?'red':'amber'}>{t.kind==='read'?'read':`changes · ${t.risk}`}</Chip><small>{t.description}</small></div></label>)}</div>}</Field>
   <Field label="Also require approval for" wide><TagPicker values={d.extraApprovals} options={d.tools} onChange={v=>set({extraApprovals:v})} placeholder="Only changes (always)"/></Field>
   <Field label="Connectors it may use" wide>{(cons.data?.connectors||[]).map(c=><label key={c.id} className="check"><input type="checkbox" checked={d.connectors.includes(c.id)} onChange={e=>set({connectors:e.target.checked?[...d.connectors,c.id]:d.connectors.filter(x=>x!==c.id)})}/>{c.name}{d.connectors.includes(c.id)&&a.publishedVersion&&<button type="button" className="link small" onClick={()=>call('revoke-connector',{connectorId:c.id},'Access revoked')}> revoke now</button>}</label>)}{!cons.data?.connectors.length&&<small className="muted">No connectors installed.</small>}</Field>
   <Field label="Knowledge" wide><div className="row-gap wrap">{(['search','graph','files','connectors'] as const).map(k=><label key={k} className="check"><input type="checkbox" checked={d.knowledge[k]} onChange={e=>set({knowledge:{...d.knowledge,[k]:e.target.checked}})}/>{k==='graph'?'Work Graph context':k==='search'?'Company search':k==='files'?'Processed files':'Connector data'}</label>)}</div></Field></div>}
  {tab==='triggers'&&<div className="form-grid"><Field label="Scheduled run"><select value={d.schedule} onChange={e=>set({schedule:e.target.value as Def['schedule']})}><option value="none">Never</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></Field>{d.schedule!=='none'&&<Field label="Scheduled request" wide><textarea rows={2} value={d.scheduledPrompt||''} onChange={e=>set({scheduledPrompt:e.target.value})}/></Field>}
   <Field label="Run when something happens" wide>{d.triggers.map((t,i)=><div key={i} className="row-gap"><input aria-label="Module" placeholder="Module (e.g. Purchasing)" value={t.module||''} onChange={e=>set({triggers:d.triggers.map((x,j)=>j===i?{...x,module:e.target.value}:x)})}/><input aria-label="Event contains" placeholder="Event contains (e.g. submitted)" value={t.action||''} onChange={e=>set({triggers:d.triggers.map((x,j)=>j===i?{...x,action:e.target.value}:x)})}/><input aria-label="Request" className="grow" placeholder="What the agent should do" value={t.prompt} onChange={e=>set({triggers:d.triggers.map((x,j)=>j===i?{...x,prompt:e.target.value}:x)})}/><Btn size="sm" variant="ghost" icon="X" title="Remove" onClick={()=>set({triggers:d.triggers.filter((_,j)=>j!==i)})}/></div>)}<Btn size="sm" icon="Plus" onClick={()=>set({triggers:[...d.triggers,{module:'',action:'',prompt:''}]})}>Add trigger</Btn></Field></div>}
  {tab==='limits'&&<div className="form-grid"><Field label="Max steps per run"><input type="number" min={1} max={10} value={d.maxSteps} onChange={e=>set({maxSteps:Number(e.target.value)})}/></Field><Field label="Monthly token budget" hint="0 = no limit"><input type="number" min={0} value={d.tokenBudget} onChange={e=>set({tokenBudget:Number(e.target.value)})}/></Field><Field label="Monthly cost budget (USD)"><input type="number" min={0} step="0.01" value={d.costBudgetMicros/1e6} onChange={e=>set({costBudgetMicros:Math.round(Number(e.target.value)*1e6)})}/></Field><Field label="Keep run logs (days)"><input type="number" min={1} value={d.retentionDays} onChange={e=>set({retentionDays:Number(e.target.value)})}/></Field></div>}
  {tab==='test'&&(a.publishedVersion?<AgentRun agent={{id:a.id,name:a.name,purpose:d.purpose}}/>:<Note>Publish the agent to test it (publishing runs the critical security evaluations first).</Note>)}
  {tab==='evals'&&<>{data.evals.map(e=><Card key={e.id} title={`v${e.version} · ${dateTime(e.createdAt)}`} actions={<Chip tone={e.criticalFailed?'red':'green'}>{e.criticalFailed?'critical failure':'passed'}</Chip>}><ul className="eval-list">{e.results.map(r=><li key={r.id}><Chip tone={r.status==='passed'?'green':r.status==='failed'?'red':'gray'}>{r.status}</Chip> {r.name}{r.critical&&<small className="muted"> (critical)</small>}{r.detail&&<small className="muted"> — {r.detail}</small>}</li>)}</ul></Card>)}{!data.evals.length&&<Empty icon="FlaskConical" title="Not evaluated yet"/>}</>}
  {tab==='versions'&&<div className="lb-table"><table className="plain"><tbody>{data.versions.map(v=><tr key={v.version}><td>v{v.version}{v.version===a.publishedVersion&&<> <Chip tone="green">live</Chip></>}</td><td>{v.evalStatus}</td><td>{dateTime(v.createdAt)}</td><td>{v.version!==a.publishedVersion&&<Btn size="sm" icon="RotateCcw" onClick={()=>call('rollback',{version:v.version},'Rolled back')}>Roll back</Btn>}</td></tr>)}</tbody></table></div>}
  {tab==='runs'&&<Runs agent={a.id}/>}
 </div>;
}
type RunRow={id:string,agentId:string,name:string,version:number,runAs:string,requestedBy:string,trigger:string,status:string,steps:number,tokens:number,cost:number,ms:number,error:string,startedAt:string};
function Runs({agent,mine}:{agent?:string,mine?:boolean}){
 const {person,toast}=useApp();const {data,error,reload}=useApi<{runs:RunRow[]}>(`/api/agents?view=runs${agent?`&agent=${agent}`:''}`);
 return <><ErrorNote error={error} onRetry={reload}/>{!data?<Skeleton/>:!data.runs.length?<Empty icon="History" title="No runs yet"/>:<div className="lb-table"><table className="plain"><thead><tr><th>When</th><th>Agent</th><th>For</th><th>Trigger</th><th>Status</th><th>Steps</th><th>Tokens</th><th/></tr></thead><tbody>{data.runs.map(r=><tr key={r.id}><td>{mine?dateTime(r.startedAt):<a href={`#/admin/ai/runs/${r.id}`}>{dateTime(r.startedAt)}</a>}</td><td>{r.name} <small className="muted">v{r.version}</small></td><td>{person(r.requestedBy)?.name||r.runAs}</td><td>{r.trigger}</td><td><Chip tone={statusTone(r.status)}>{r.status.replace('_',' ')}</Chip>{r.error&&<small className="muted"> {r.error.slice(0,80)}</small>}</td><td>{r.steps}</td><td>{r.tokens}</td><td>{!mine&&r.status==='failed'&&<Btn size="sm" icon="RotateCcw" onClick={async()=>{try{await api('/api/agents',{action:'retry-run',runId:r.id});toast('Retried');reload()}catch(e){toast((e as Error).message,'error')}}}>Retry</Btn>}</td></tr>)}</tbody></table></div>}</>;
}
function RunDetail({id}:{id:string}){
 const {person}=useApp();const {data,error}=useApi<{run:Record<string,unknown>&{citations:{title:string,link:string}[]},tools:{step:number,tool:string,input:string,output:string,status:string,ms:number,createdAt:string}[],approvals:{id:string,tool:string,effect:string,risk:string,status:string}[]}>(`/api/agents?run=${id}`);
 if(error)return <ErrorNote error={error}/>;if(!data)return <Skeleton/>;const r=data.run;
 return <div><a href="#/admin/ai/runs" className="link small">← All runs</a><h2>{String(r.name)} <Chip tone={statusTone(String(r.status))}>{String(r.status)}</Chip></h2>
  <div className="ctx-facts"><Stat label="Requested by" value={person(String(r.requested_by))?.name||'—'}/><Stat label="Acting as" value={String(r.run_as)}/><Stat label="Trigger" value={String(r.trigger)}/><Stat label="Version" value={`v${r.agent_version}`}/><Stat label="Tokens" value={Number(r.prompt_tokens)+Number(r.completion_tokens)}/><Stat label="Duration" value={`${(Number(r.duration_ms)/1000).toFixed(1)} s`}/></div>
  <Card title="Request"><p>{String(r.input_text||'')}</p>{r.record_type?<small className="muted">Record: {String(r.record_type)} {String(r.record_id)}</small>:null}</Card>
  <Card title="Tool calls">{data.tools.length?<ol className="timeline">{data.tools.map((t,i)=><li key={i}><span className="dot"/><div><b>{t.step}. {t.tool}</b> <Chip tone={statusTone(t.status==='ok'?'succeeded':t.status)}>{t.status}</Chip><small>{t.ms} ms</small><pre className="code small">{t.input}</pre><small className="muted">{t.output}</small></div></li>)}</ol>:<p className="muted small">No tools used.</p>}</Card>
  {data.approvals.length>0&&<Card title="Proposed actions">{data.approvals.map(a=><div key={a.id} className="agent-approval"><b>{a.tool}</b> <Chip tone={a.status==='approved'?'green':a.status==='pending'?'amber':'gray'}>{a.status}</Chip><p className="small">{a.effect}</p></div>)}</Card>}
  <Card title="Answer">{r.output_text?<Markdown text={String(r.output_text)}/>:<p className="muted">{String(r.error||'No answer.')}</p>}{r.citations.length>0&&<div className="cites">{r.citations.map((c,i)=><a key={i} className="chip chip-gray" href={c.link}>{c.title}</a>)}</div>}</Card>
 </div>;
}
export function ApprovalQueue(){
 const {toast,person}=useApp();const {data,error,reload}=useApi<{approvals:Approval[]}>('/api/agents?view=approvals');const [edit,setEdit]=useState<{a:Approval,json:string}|null>(null);
 const decide=async(a:Approval,approve:boolean,edited?:Record<string,unknown>)=>{try{await api('/api/agents',{action:approve?'approve':'reject',approvalId:a.id,edited});toast(approve?'Approved — executed with your permissions':'Rejected');setEdit(null);reload()}catch(e){toast((e as Error).message,'error')}};
 return <><ErrorNote error={error} onRetry={reload}/>{!data?<Skeleton/>:!data.approvals.length?<Empty icon="ShieldCheck" title="No AI actions waiting">Agents propose changes here; nothing changes until someone approves.</Empty>:<ul className="approval-list">{data.approvals.map(a=><li key={a.id}><div className="row-gap"><Chip tone={a.risk==='high'?'red':a.risk==='medium'?'amber':'gray'}>{a.risk} risk</Chip><b>{a.toolLabel}</b><small className="muted">by {a.agent} for {person(a.requestedBy)?.name||'someone'} · {ago(a.createdAt)}</small></div><p>{a.effect}</p>{a.evidence.length>0&&<div className="cites"><small className="muted">Evidence:</small>{a.evidence.map((e,i)=><a key={i} className="chip chip-gray" href={e.link}>{e.title}</a>)}</div>}<pre className="code small">{JSON.stringify(a.input,null,1)}</pre>
  <div className="row-gap"><Btn size="sm" variant="primary" icon="Check" onClick={()=>decide(a,true)}>Approve</Btn><Btn size="sm" icon="Pencil" onClick={()=>setEdit({a,json:JSON.stringify(a.input,null,2)})}>Edit and approve</Btn><Btn size="sm" icon="X" onClick={()=>decide(a,false)}>Reject</Btn></div></li>)}</ul>}
  {edit&&<Modal open onClose={()=>setEdit(null)} title={`Edit: ${edit.a.toolLabel}`} footer={<Btn variant="primary" onClick={()=>{try{decide(edit.a,true,JSON.parse(edit.json))}catch{toast('Invalid JSON','error')}}}>Approve edited</Btn>}><textarea rows={12} className="code" value={edit.json} onChange={e=>setEdit({...edit,json:e.target.value})}/></Modal>}</>;
}
function ProviderHealth({t,reload}:{t:Tower,reload:()=>void}){
 const p=t.provider;return <Card title="Model gateway" actions={<Btn size="sm" variant="ghost" icon="RefreshCw" onClick={reload}>Refresh</Btn>}>{!p?<Note tone="warn">No AI provider is configured. Agents cannot run until one is added below or the platform default is enabled.</Note>:<div className="ctx-facts"><Stat label="Provider" value={p.name}/><Stat label="Default model" value={p.model}/><Stat label="Source" value={p.source==='company'?'Company key':'Platform default'}/><Stat label="Last success" value={p.lastSuccess?ago(p.lastSuccess):'—'}/><Stat label="Last failure" value={p.lastFailure?ago(p.lastFailure):'—'} tone={p.lastFailure&&(!p.lastSuccess||p.lastFailure>p.lastSuccess)?'red':undefined}/></div>}
  <p className="muted small">Agents call models through this gateway only. Keys are stored encrypted on the server and never sent to the browser.</p></Card>;
}
function ToolsTab({t}:{t:Tower|null|undefined}){
 const {data}=useApi<{tools:Tool[]}>('/api/agents?view=tools');
 return !data?<Skeleton/>:<div className="lb-table"><table className="plain"><thead><tr><th>Tool</th><th>Kind</th><th>Needs page permission</th><th>Approval</th><th>Per run</th><th>Calls (30d)</th><th>Audit</th></tr></thead><tbody>{data.tools.map(x=>{const n=(t?.tools||[]).filter(y=>y.tool===x.id);return <tr key={x.id}><td><b>{x.label}</b><br/><small className="muted">{x.description}</small></td><td><Chip tone={x.kind==='read'?'gray':x.risk==='high'?'red':'amber'}>{x.kind==='read'?'read':`change · ${x.risk}`}</Chip></td><td>{x.page}: {x.action}</td><td>{x.kind==='mutation'?'Always':'—'}</td><td>{x.perRun}</td><td>{n.reduce((s,y)=>s+y.n,0)}{n.some(y=>y.status!=='ok')&&<small className="muted"> ({n.filter(y=>y.status!=='ok').reduce((s,y)=>s+y.n,0)} not ok)</small>}</td><td className="small">{x.audit}</td></tr>})}</tbody></table></div>;
}
function Knowledge(){
 const {data}=useApi<{agents:AgentSum[]}>('/api/agents');const graph=useApi<{indexing:{active:boolean,stage:string},operations?:{nodes:{type:string,n:number}[],edges:number,pendingEvents:number,failedEvents:number}}>('/api/graph?types=project');
 return <><Card title="Knowledge sources">
  <p className="small">Agents answer only from what the acting identity can open: company search, the Work Graph (connected records), processed files (text, OCR and transcripts) and connector data that is synced or read live. Each agent’s sources are set on its Access tab.</p>
  {graph.data&&<div className="ctx-facts"><Stat label="Graph records" value={graph.data.operations?graph.data.operations.nodes.reduce((n,x)=>n+x.n,0):'—'}/><Stat label="Relationships" value={graph.data.operations?.edges??'—'}/><Stat label="Events waiting" value={graph.data.operations?.pendingEvents??0}/><Stat label="Failed events" value={graph.data.operations?.failedEvents??0}/><Stat label="Rebuild" value={graph.data.indexing.active?graph.data.indexing.stage||'running':'idle'}/></div>}</Card>
  <Card title="By agent">{!data?<Skeleton/>:<ul className="mini-list">{data.agents.map(a=><li key={a.id} className="mini-row"><a href={`#/admin/ai/agents/${a.id}`}>{a.name}</a><span>{a.tools.filter(t=>['search_knowledge','graph_context','summarize_file','read_connector'].includes(t)).join(', ')||'no knowledge tools'}</span></li>)}</ul>}</Card></>;
}
function Evaluations({t}:{t:Tower|null|undefined}){
 return !t?<Skeleton/>:!t.evals.length?<Empty icon="FlaskConical" title="No evaluations yet">Evaluations run before every publish: permission boundaries, prompt injection, cross-tenant access, citation and approval behaviour.</Empty>:<div className="lb-table"><table className="plain"><thead><tr><th>Agent</th><th>Version</th><th>Result</th><th>When</th></tr></thead><tbody>{t.evals.map((e,i)=><tr key={i}><td><a href={`#/admin/ai/agents/${e.agentId}`}>{e.name}</a></td><td>v{e.version}</td><td><Chip tone={e.criticalFailed?'red':e.passed?'green':'amber'}>{e.criticalFailed?'critical failure':e.passed?'passed':'warnings'}</Chip></td><td>{dateTime(e.createdAt)}</td></tr>)}</tbody></table></div>;
}
function UsageTab({t}:{t:Tower}){
 return <><div className="ctx-facts"><Stat label="Runs (30 days)" value={t.totals.runs}/><Stat label="Tokens" value={t.totals.tokens.toLocaleString()}/><Stat label="Estimated cost" value={t.totals.cost?`$${(t.totals.cost/1e6).toFixed(2)}`:'—'}/></div>
  <div className="lb-table"><table className="plain"><thead><tr><th>Provider</th><th>Model</th><th>Requests</th><th>Tokens</th><th>Failures</th></tr></thead><tbody>{t.usage.map((u,i)=><tr key={i}><td>{u.provider}</td><td>{u.model}</td><td>{u.requests}</td><td>{(u.tokens||0).toLocaleString()}</td><td>{u.failures||0}</td></tr>)}{!t.usage.length&&<tr><td colSpan={5} className="muted">No AI usage in the last 30 days.</td></tr>}</tbody></table></div></>;
}
function Policies({t,reload}:{t:Tower,reload:()=>void}){
 const {toast,ask}=useApp();const [prices,setPrices]=useState(JSON.stringify(t.prices,null,1));
 return <><Card title="Company-wide kill switch"><p className="small">Stops every agent immediately, cancels queued and running work, and blocks new runs until switched off.</p><Btn variant={t.killSwitch?'primary':'default'} icon={t.killSwitch?'Play':'OctagonX'} onClick={async()=>{if(!t.killSwitch&&await ask({title:'Stop all AI now?',confirm:'Stop all agents',danger:true})===false)return;try{await api('/api/agents',{action:'kill-switch',on:!t.killSwitch});toast(t.killSwitch?'AI resumed':'All agents stopped');reload()}catch(e){toast((e as Error).message,'error')}}}>{t.killSwitch?'Turn AI back on':'Stop all agents'}</Btn></Card>
  <Card title="Rules enforced by the platform"><ul className="small"><li>Agents act as the requester or a restricted service identity — never as an administrator.</li><li>Every change (tasks, tickets, messages, purchases, connector actions) is a proposal until a person approves it; the approver’s permissions are re-checked when it runs.</li><li>Read tools check the same page permissions and record rules as the modules.</li><li>Instructions found inside documents, emails or connector data are treated as data, never as commands; blocked attempts are logged as policy violations.</li><li>Publishing requires critical security evaluations to pass.</li><li>Budgets stop runs when the monthly token or cost limit is reached.</li></ul></Card>
  <Card title="Model prices (for cost estimates)"><Field label="Per model: USD per million tokens" hint='e.g. {"llama-3.3-70b-versatile":{"prompt":0.59,"completion":0.79}}'><textarea rows={4} className="code" value={prices} onChange={e=>setPrices(e.target.value)}/></Field><Btn size="sm" onClick={async()=>{try{await api('/api/agents',{action:'prices',prices:JSON.parse(prices)});toast('Saved');reload()}catch(e){toast((e as Error).message,'error')}}}>Save prices</Btn></Card></>;
}
