'use client';
import {useState} from 'react';
import {api,useApi,ago,cx,dateTime} from './lib';
import {useApp,Btn,Chip,Field,ErrorNote,Skeleton,Empty,Icon,Note,Card,Modal} from './kit';

// Connector Fabric: the three connector modes (synced, federated, action) with health, sync logs and retry
// queues, webhooks, installation approvals, manifests, live queries, action confirmation, test environments
// and usage limits. Every response is already filtered by the server to what the viewer may use.
type Mode='synced'|'federated'|'action';
type Resource={id:string,label:string,modes:Mode[],description:string,schema:string[],requires?:string};
type ActionInput={key:string,label:string,type:string,required?:boolean};
type ActionDef={id:string,label:string,description:string,risk:'low'|'medium'|'high',confirm:boolean,requires?:string,input:ActionInput[],verify:string,recovery:string};
type Manifest={id:string,name:string,provider:string,description:string,version:string,modes:Mode[],auth:string,requiredScopes:string[],resources:Resource[],actions:ActionDef[],triggers:string[],rateLimit:{perMinute:number,perDay:number|null},webhook:boolean,permissions:string[],aiTools:string[],studioWidgets:string[],unsupported:string[]};
type Installed={id:string,name:string,provider:string,scope:string,status:string,health:string,paused:boolean,environment:string,dailyCallLimit:number,lastOkAt:string|null,lastSyncAt:string|null,nextSyncAt:string|null,lastError:string,grantedScopes:string[],accountIdentity:string,modes:Mode[],resources:number,actions:number,calls24h:number,errors24h:number,agents:{id:string,name:string}[],workflows:{id:string,name:string}[]};
type Run={id:string,connectorId:string,action:string,input:Record<string,unknown>,status:string,origin:string,requestedBy:string,result:unknown,error:string,verified:boolean|null,createdAt:string,connector?:string,environment?:string};
const tone=(s:string)=>['ok','healthy','connected','succeeded','approved','configured'].includes(s)?'green':['failed','error','down','rejected','unhealthy'].includes(s)?'red':['pending','pending_confirmation','degraded','needs-auth','queued','retrying'].includes(s)?'amber':'gray';
const MODE_LABEL:Record<Mode,string>={synced:'Synced (copied, searchable, in the Work Graph)',federated:'Federated (read live, not stored)',action:'Action (changes in the other system, with confirmation)'};

export function FabricOverview({base}:{base:string}){
 const [tab,setTab]=useState('health');
 const tabs=[['health','Health'],['syncs','Syncs & retries'],['logs','Logs'],['webhooks','Webhooks'],['actions','Action confirmations'],['installs','Install requests'],['catalog','Catalog']];
 return <div><nav className="app-nav">{tabs.map(([id,l])=><button key={id} className={cx('app-nav-link',tab===id&&'on')} onClick={()=>setTab(id)}>{l}</button>)}</nav>
  {tab==='health'&&<Health base={base}/>}{tab==='syncs'&&<Syncs/>}{tab==='logs'&&<Logs/>}{tab==='webhooks'&&<Webhooks/>}{tab==='actions'&&<PendingActions/>}{tab==='installs'&&<Installs/>}{tab==='catalog'&&<Catalog/>}</div>;
}
function Health({base}:{base:string}){
 const {data,error,reload}=useApi<{connectors:Installed[]}>('/api/connectors/fabric?view=health');
 return <><ErrorNote error={error} onRetry={reload}/>{!data?<Skeleton/>:!data.connectors.length?<Empty icon="Link" title="No connectors installed"/>:<div className="lb-table"><table className="plain"><thead><tr><th>Connector</th><th>Modes</th><th>Health</th><th>Last sync</th><th>Calls 24h</th><th>Environment</th><th>Used by</th></tr></thead><tbody>{data.connectors.map(c=><tr key={c.id}><td><a href={`#/${base}/${c.id}`}><b>{c.name}</b></a><br/><small className="muted">{c.provider} · {c.scope}{c.accountIdentity?` · ${c.accountIdentity}`:''}</small></td><td>{c.modes.map(m=><Chip key={m} tone="gray">{m}</Chip>)}</td><td><Chip tone={c.paused?'amber':tone(c.health)}>{c.paused?'paused':c.health}</Chip>{c.lastError&&<><br/><small className="muted">{c.lastError.slice(0,80)}</small></>}</td><td>{c.lastSyncAt?ago(c.lastSyncAt):'—'}{c.nextSyncAt&&<><br/><small className="muted">next {dateTime(c.nextSyncAt)}</small></>}</td><td>{c.calls24h}{c.errors24h>0&&<small className="muted"> ({c.errors24h} errors)</small>}{c.dailyCallLimit>0&&<small className="muted"> / {c.dailyCallLimit}</small>}</td><td><Chip tone={c.environment==='test'?'amber':'gray'}>{c.environment}</Chip></td><td className="small">{[...c.agents.map(a=>`Agent: ${a.name}`),...c.workflows.map(w=>`App: ${w.name}`)].join(', ')||'—'}</td></tr>)}</tbody></table></div>}</>;
}
function Syncs(){
 const {toast}=useApp();const {data,error,reload}=useApi<{syncs:{connectorId:string,connector:string,cursor:string,lastFullAt:string|null,lastIncrementalAt:string|null,stats:Record<string,number>,updatedAt:string}[],queue:{id:string,kind:string,connectorId:string,status:string,attempts:number,error:string,runAfter:string}[]}>('/api/connectors/fabric?view=syncs');
 const sync=async(id:string,full:boolean)=>{try{await api('/api/connectors/fabric',{action:'sync',id,full});toast(full?'Full resync queued':'Sync queued');reload()}catch(e){toast((e as Error).message,'error')}};
 return <><ErrorNote error={error} onRetry={reload}/>{!data?<Skeleton/>:<>
  <Card title="Checkpoints">{!data.syncs.length?<p className="muted small">No synced connectors yet.</p>:<div className="lb-table"><table className="plain"><thead><tr><th>Connector</th><th>Last incremental</th><th>Last full</th><th>Last run</th><th/></tr></thead><tbody>{data.syncs.map(s=><tr key={s.connectorId}><td>{s.connector}</td><td>{s.lastIncrementalAt?ago(s.lastIncrementalAt):'—'}</td><td>{s.lastFullAt?ago(s.lastFullAt):'—'}</td><td className="small">{Object.entries(s.stats).map(([k,v])=>`${k}: ${v}`).join(' · ')}</td><td className="row-gap"><Btn size="sm" icon="RefreshCw" onClick={()=>sync(s.connectorId,false)}>Sync</Btn><Btn size="sm" variant="ghost" onClick={()=>sync(s.connectorId,true)}>Full resync</Btn></td></tr>)}</tbody></table></div>}</Card>
  <Card title="Retry queue" actions={<Btn size="sm" variant="ghost" icon="RefreshCw" onClick={reload}>Refresh</Btn>}>{!data.queue.length?<p className="muted small">Nothing queued.</p>:<div className="lb-table"><table className="plain"><thead><tr><th>Job</th><th>Status</th><th>Attempts</th><th>Next run</th><th>Error</th></tr></thead><tbody>{data.queue.map(j=><tr key={j.id}><td>{j.kind}</td><td><Chip tone={tone(j.status)}>{j.status}</Chip></td><td>{j.attempts}</td><td>{j.runAfter?dateTime(j.runAfter):'—'}</td><td className="small">{j.error}</td></tr>)}</tbody></table></div>}</Card></>}</>;
}
function Logs({id}:{id?:string}){
 const {data,error,reload}=useApi<{logs:{id:string,connector:string,action:string,status:string,ms:number,detail:string,createdAt:string}[]}>(`/api/connectors/fabric?view=logs${id?`&id=${id}`:''}`);
 return <><ErrorNote error={error} onRetry={reload}/>{!data?<Skeleton/>:!data.logs.length?<Empty icon="ScrollText" title="No activity yet"/>:<div className="lb-table"><table className="plain"><thead><tr><th>When</th>{!id&&<th>Connector</th>}<th>Operation</th><th>Status</th><th>Time</th><th>Detail</th></tr></thead><tbody>{data.logs.map(l=><tr key={l.id}><td>{dateTime(l.createdAt)}</td>{!id&&<td>{l.connector}</td>}<td>{l.action}</td><td><Chip tone={tone(l.status)}>{l.status}</Chip></td><td>{l.ms} ms</td><td className="small mono">{String(l.detail||'').slice(0,160)}</td></tr>)}</tbody></table></div>}</>;
}
function Webhooks(){
 const {toast}=useApp();const {data,error}=useApi<{webhooks:(Installed&{url:string,hasSecret:boolean})[]}>('/api/connectors/fabric?view=webhooks');
 return <><ErrorNote error={error}/>{!data?<Skeleton/>:!data.webhooks.length?<Empty icon="Webhook" title="No webhook connectors">Add a Webhook connector to receive signed events. Each delivery becomes a synced record, a Work Graph node and an event Studio automations can trigger on.</Empty>:<ul className="mini-list">{data.webhooks.map(w=><li key={w.id} className="mini-row"><b>{w.name}</b><code className="small">{w.url}</code><Btn size="sm" icon="Copy" onClick={()=>{navigator.clipboard?.writeText(w.url);toast('Copied')}}>Copy URL</Btn><Chip tone={w.hasSecret?'green':'red'}>{w.hasSecret?'signed (HMAC)':'no secret'}</Chip><small className="muted">last event {w.lastSyncAt?ago(w.lastSyncAt):'never'}</small></li>)}</ul>}</>;
}
export function PendingActions(){
 const {toast}=useApp();const {data,error,reload}=useApi<{actions:Run[]}>('/api/connectors/fabric?view=pending-actions');
 const decide=async(r:Run,ok:boolean)=>{try{await api('/api/connectors/fabric',{action:ok?'confirm-action':'reject-action',runId:r.id});toast(ok?'Confirmed and executed':'Rejected');reload()}catch(e){toast((e as Error).message,'error')}};
 return <><ErrorNote error={error} onRetry={reload}/>{!data?<Skeleton/>:!data.actions.length?<Empty icon="ShieldCheck" title="No actions waiting">Consequential connector actions (send email, create events, write to other systems) wait here for a person.</Empty>:<ul className="approval-list">{data.actions.map(r=><li key={r.id}><div className="row-gap"><b>{r.connector}: {r.action}</b><Chip tone="gray">{r.origin}</Chip><small className="muted">{ago(r.createdAt)}</small></div><pre className="code small">{JSON.stringify(r.input,null,1)}</pre><div className="row-gap"><Btn size="sm" variant="primary" icon="Check" onClick={()=>decide(r,true)}>Confirm</Btn><Btn size="sm" icon="X" onClick={()=>decide(r,false)}>Reject</Btn></div></li>)}</ul>}</>;
}
function Installs(){
 const {toast,person}=useApp();const {data,error,reload}=useApi<{requests:{id:string,provider:string,name:string,level:string,reason:string,requestedBy:string,status:string,createdAt:string,connectorId:string|null}[]}>('/api/connectors/fabric?view=installs');
 const decide=async(id:string,approve:boolean)=>{try{await api('/api/connectors/fabric',{action:'decide-install',id,approve});toast(approve?'Approved and installed':'Declined');reload()}catch(e){toast((e as Error).message,'error')}};
 return <><ErrorNote error={error} onRetry={reload}/>{!data?<Skeleton/>:!data.requests.length?<Empty icon="PackagePlus" title="No installation requests"/>:<div className="lb-table"><table className="plain"><thead><tr><th>Connector</th><th>Level</th><th>Requested by</th><th>Reason</th><th>Status</th><th/></tr></thead><tbody>{data.requests.map(r=><tr key={r.id}><td>{r.name} <small className="muted">{r.provider}</small></td><td>{r.level}</td><td>{person(r.requestedBy)?.name||'—'} · {ago(r.createdAt)}</td><td className="small">{r.reason}</td><td><Chip tone={tone(r.status)}>{r.status}</Chip></td><td>{r.status==='pending'&&<div className="row-gap"><Btn size="sm" variant="primary" onClick={()=>decide(r.id,true)}>Approve</Btn><Btn size="sm" onClick={()=>decide(r.id,false)}>Decline</Btn></div>}</td></tr>)}</tbody></table></div>}</>;
}
export function Catalog(){
 const {toast}=useApp();const {data,error}=useApi<{types:{id:string,name:string,category:string,description:string,auth:string,manifest:Manifest}[]}>('/api/connectors/fabric?view=catalog');const [req,setReq]=useState<{id:string,name:string}|null>(null);const [reason,setReason]=useState('');const [level,setLevel]=useState('company');const [open,setOpen]=useState<Manifest|null>(null);
 return <><ErrorNote error={error}/>{!data?<Skeleton/>:<div className="module-grid">{data.types.map(t=><div key={t.id} className="module-card"><Icon name="Plug" size={18}/><div><b>{t.name}</b><small>{t.description}</small><div className="row-gap wrap">{t.manifest.modes.map(m=><Chip key={m} tone="gray">{m}</Chip>)}</div><div className="row-gap"><Btn size="sm" onClick={()=>setOpen(t.manifest)}>Manifest</Btn><Btn size="sm" variant="primary" onClick={()=>setReq({id:t.id,name:t.name})}>Request install</Btn></div></div></div>)}</div>}
  {open&&<Modal open wide onClose={()=>setOpen(null)} title={`${open.name} manifest`}><ManifestView m={open}/></Modal>}
  {req&&<Modal open onClose={()=>setReq(null)} title={`Request ${req.name}`} subtitle="An administrator reviews the request before anything is installed or any data is accessed." footer={<Btn variant="primary" disabled={!reason.trim()} onClick={async()=>{try{await api('/api/connectors/fabric',{action:'request-install',provider:req.id,reason,level});toast('Request sent to administrators');setReq(null);setReason('')}catch(e){toast((e as Error).message,'error')}}}>Send request</Btn>}>
   <Field label="Level"><select value={level} onChange={e=>setLevel(e.target.value)}><option value="company">Company</option><option value="department">Department</option><option value="user">Just me (personal)</option></select></Field><Field label="Why is it needed?"><textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></Field></Modal>}</>;
}
export function ManifestView({m}:{m:Manifest}){
 return <div className="manifest"><p>{m.description}</p>
  <div className="ctx-facts"><div className="ctx-fact"><small>Version</small><b>{m.version}</b></div><div className="ctx-fact"><small>Authentication</small><b>{m.auth}</b></div><div className="ctx-fact"><small>Rate limit</small><b>{m.rateLimit.perMinute}/min{m.rateLimit.perDay?` · ${m.rateLimit.perDay}/day`:''}</b></div><div className="ctx-fact"><small>Webhooks</small><b>{m.webhook?'Yes':'No'}</b></div></div>
  <h4>Modes</h4><ul>{m.modes.map(x=><li key={x}>{MODE_LABEL[x]}</li>)}</ul>
  {m.requiredScopes.length>0&&<><h4>Permissions requested</h4><div className="row-gap wrap">{m.requiredScopes.map(s=><Chip key={s} tone="gray">{s}</Chip>)}</div></>}
  <h4>Data</h4>{m.resources.length?<ul>{m.resources.map(r=><li key={r.id}><b>{r.label}</b> <small className="muted">({r.modes.join(', ')})</small> — {r.description}{r.schema.length>0&&<small className="muted"> Fields: {r.schema.join(', ')}</small>}</li>)}</ul>:<p className="muted small">None.</p>}
  <h4>Actions</h4>{m.actions.length?<ul>{m.actions.map(a=><li key={a.id}><b>{a.label}</b> <Chip tone={a.risk==='high'?'red':a.risk==='medium'?'amber':'gray'}>{a.risk}</Chip>{a.confirm&&<Chip tone="violet">needs confirmation</Chip>} — {a.description}<br/><small className="muted">Verification: {a.verify} · Recovery: {a.recovery}</small></li>)}</ul>:<p className="muted small">None (read-only).</p>}
  <h4>Available to</h4><p className="small">AI tools: {m.aiTools.join(', ')||'—'} · Studio widgets: {m.studioWidgets.join(', ')||'—'} · Triggers: {m.triggers.join(', ')||'—'}</p>
  {m.unsupported.length>0&&<Note>Not supported: {m.unsupported.join('; ')}</Note>}</div>;
}

// Per-connector fabric panel (a tab of the connector page).
export function ConnectorFabric({id,canConfigure}:{id:string,canConfigure:boolean}){
 const {toast,s}=useApp();
 const {data,error,reload}=useApi<{manifest:Manifest,connector:Installed&{policy?:{allowAgents:string[],autoConfirm:string[],allowAutomations:boolean}},checkpoint:{lastFullAt:string|null,lastIncrementalAt:string|null,stats:string}|null}>(`/api/connectors/fabric?view=manifest&id=${id}`);
 const agents=useApi<{agents:{id:string,name:string}[]}>(s.user.permissions.agents?'/api/agents':null);
 const runs=useApi<{runs:Run[]}>(`/api/connectors/fabric?view=actions&id=${id}`);
 const [q,setQ]=useState('');const [res,setRes]=useState('');const [live,setLive]=useState<{items:{externalId:string,title:string,excerpt:string,url:string,updatedAt:string|null,citation:string}[],retrievedAt:string}|null>(null);const [busy,setBusy]=useState('');
 const [act,setAct]=useState<ActionDef|null>(null);const [input,setInput]=useState<Record<string,string>>({});
 const [policy,setPolicy]=useState<{allowAgents:string[],autoConfirm:string[],allowAutomations:boolean}|null>(null);const [env,setEnv]=useState<{environment:string,dailyCallLimit:number}|null>(null);
 const [rest,setRest]=useState<string|null>(null);
 if(error)return <ErrorNote error={error} onRetry={reload}/>;if(!data)return <Skeleton/>;
 const m=data.manifest,c=data.connector;const pol=policy||{allowAgents:c.policy?.allowAgents||[],autoConfirm:c.policy?.autoConfirm||[],allowAutomations:c.policy?.allowAutomations!==false};const en=env||{environment:c.environment,dailyCallLimit:c.dailyCallLimit};
 const federatedRes=m.resources.filter(r=>r.modes.includes('federated'));
 const call=async(action:string,extra:Record<string,unknown>,msg:string)=>{setBusy(action);try{const r=await api<Record<string,unknown>>('/api/connectors/fabric',{action,id,...extra});toast(msg);reload();runs.reload();return r}catch(e){toast((e as Error).message,'error');return null}finally{setBusy('')}};
 return <div className="fabric">
  {c.environment==='test'&&<Note tone="warn">Test environment: actions are simulated and nothing is changed in {c.name}.</Note>}
  <Card title="Manifest"><ManifestView m={m}/></Card>
  {m.modes.includes('synced')&&<Card title="Synced data" actions={canConfigure&&<div className="row-gap"><Btn size="sm" icon="RefreshCw" busy={busy==='sync'} onClick={()=>call('sync',{},'Sync queued')}>Sync now</Btn><Btn size="sm" variant="ghost" onClick={()=>call('sync',{full:true},'Full resync queued')}>Full resync</Btn></div>}>
   <p className="small">Last incremental: {data.checkpoint?.lastIncrementalAt?ago(data.checkpoint.lastIncrementalAt):'never'} · last full: {data.checkpoint?.lastFullAt?ago(data.checkpoint.lastFullAt):'never'}. Synced records are searchable, appear in the Work Graph with lineage, and are removed when the connector is disconnected.</p><SyncedRecords id={id}/></Card>}
  {federatedRes.length>0&&<Card title="Live query (federated — not stored)"><form className="row-gap" onSubmit={async e=>{e.preventDefault();setBusy('live');try{setLive(await api(`/api/connectors/fabric?view=live&id=${id}&resource=${encodeURIComponent(res||federatedRes[0].id)}&q=${encodeURIComponent(q)}`))}catch(err){toast((err as Error).message,'error')}finally{setBusy('')}}}><select aria-label="Resource" value={res||federatedRes[0].id} onChange={e=>setRes(e.target.value)}>{federatedRes.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select><input className="grow" aria-label="Query" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search…"/><Btn type="submit" busy={busy==='live'}>Query live</Btn></form>
   {live&&<><small className="muted">Retrieved {dateTime(live.retrievedAt)} with your connection’s permissions.</small><ul className="mini-list">{live.items.map(i=><li key={i.externalId} className="mini-row"><a href={i.url||undefined} target="_blank" rel="noreferrer"><b>{i.title}</b></a><span className="small">{i.excerpt}</span></li>)}{!live.items.length&&<li className="muted small">Nothing found.</li>}</ul></>}</Card>}
  {m.actions.length>0&&<Card title="Actions">{m.actions.map(a=><div key={a.id} className="mini-row"><b>{a.label}</b><Chip tone={a.risk==='high'?'red':a.risk==='medium'?'amber':'gray'}>{a.risk}</Chip><span className="small">{a.description}</span><Btn size="sm" onClick={()=>{setAct(a);setInput({})}}>Run…</Btn></div>)}
   <h4>Recent action runs</h4>{!runs.data?<Skeleton rows={2}/>:!runs.data.runs.length?<p className="muted small">None yet.</p>:<div className="lb-table"><table className="plain"><thead><tr><th>When</th><th>Action</th><th>Origin</th><th>Status</th><th>Verified</th></tr></thead><tbody>{runs.data.runs.map(r=><tr key={r.id}><td>{dateTime(r.createdAt)}</td><td>{r.action}</td><td>{r.origin}</td><td><Chip tone={tone(r.status)}>{r.status.replace('_',' ')}</Chip>{r.error&&<small className="muted"> {r.error}</small>}</td><td>{r.verified==null?'—':r.verified?'Yes':'No'}</td></tr>)}</tbody></table></div>}</Card>}
  {canConfigure&&<Card title="Policies" actions={<Btn size="sm" variant="primary" busy={busy==='policy'} onClick={()=>call('policy',pol,'Policy saved')}>Save</Btn>}>
   <Field label="AI agents allowed to use it">{(agents.data?.agents||[]).map(a=><label key={a.id} className="check"><input type="checkbox" checked={pol.allowAgents.includes(a.id)} onChange={e=>setPolicy({...pol,allowAgents:e.target.checked?[...pol.allowAgents,a.id]:pol.allowAgents.filter(x=>x!==a.id)})}/>{a.name}</label>)}{!agents.data?.agents.length&&<small className="muted">No agents.</small>}</Field>
   <label className="check"><input type="checkbox" checked={pol.allowAutomations} onChange={e=>setPolicy({...pol,allowAutomations:e.target.checked})}/>Studio automations may request actions</label>
   <Field label="Pre-approved for automations (low/medium risk only)">{m.actions.filter(a=>a.risk!=='high').map(a=><label key={a.id} className="check"><input type="checkbox" checked={pol.autoConfirm.includes(a.id)} onChange={e=>setPolicy({...pol,autoConfirm:e.target.checked?[...pol.autoConfirm,a.id]:pol.autoConfirm.filter(x=>x!==a.id)})}/>{a.label}</label>)}{!m.actions.some(a=>a.risk!=='high')&&<small className="muted">High-risk actions always need a person.</small>}</Field></Card>}
  {canConfigure&&<Card title="Environment and limits" actions={<Btn size="sm" variant="primary" busy={busy==='environment'} onClick={()=>call('environment',en,'Saved')}>Save</Btn>}><div className="form-grid"><Field label="Environment" hint="Test simulates every action."><select value={en.environment} onChange={e=>setEnv({...en,environment:e.target.value})}><option value="production">Production</option><option value="test">Test (simulate actions)</option></select></Field><Field label="Daily call limit" hint="0 = plan limit only"><input type="number" min={0} value={en.dailyCallLimit} onChange={e=>setEnv({...en,dailyCallLimit:Number(e.target.value)})}/></Field></div></Card>}
  {canConfigure&&c.provider==='rest'&&<Card title="REST resources and actions" actions={rest!==null&&<Btn size="sm" variant="primary" onClick={async()=>{try{const j=JSON.parse(rest) as {resources:unknown[],actions:unknown[]};await call('resources',j,'Saved');setRest(null)}catch(e){toast((e as Error).message,'error')}}}>Save</Btn>}>
   <p className="small">Declare what to read (synced and live) and what actions may be requested. Paths are relative to the connector’s base URL.</p>
   {rest===null?<Btn size="sm" onClick={()=>setRest(JSON.stringify({resources:m.resources.map(r=>({id:r.id,label:r.label,path:r.description.replace(/^GET /,'')})),actions:m.actions.map(a=>({id:a.id,label:a.label,method:'POST',path:'/',risk:a.risk,fields:a.input.map(i=>i.key)}))},null,2))}>Edit definitions</Btn>:<textarea rows={12} className="code" value={rest} onChange={e=>setRest(e.target.value)}/>}</Card>}
  <Card title="Operations log"><Logs id={id}/></Card>
  {act&&<Modal open onClose={()=>setAct(null)} title={act.label} subtitle={act.confirm||act.risk!=='low'?'This action will wait for confirmation before it changes anything.':act.description} footer={<Btn variant="primary" busy={busy==='action'} onClick={async()=>{const r=await call('action',{connectorAction:act.id,input:Object.fromEntries(Object.entries(input).map(([k,v])=>[k,act.input.find(i=>i.key===k)?.type==='emails'?v.split(',').map(x=>x.trim()).filter(Boolean):v]))},'Submitted');if(r){setAct(null)}}}>Submit</Btn>}>
   {act.input.map(i=><Field key={i.key} label={`${i.label}${i.required?' *':''}`}>{i.type==='textarea'||i.type==='json'?<textarea rows={4} value={input[i.key]||''} onChange={e=>setInput({...input,[i.key]:e.target.value})}/>:<input type={i.type==='datetime'?'datetime-local':i.type==='email'?'email':'text'} value={input[i.key]||''} onChange={e=>setInput({...input,[i.key]:e.target.value})} placeholder={i.type==='emails'?'Comma-separated':''}/>}</Field>)}
   <small className="muted">Verification: {act.verify}</small></Modal>}
 </div>;
}
function SyncedRecords({id}:{id:string}){
 const [q,setQ]=useState('');const {data,error}=useApi<{records:{id:string,externalId:string,kind:string,title:string,excerpt:string,url:string,sourceUpdatedAt:string|null,lastVerifiedAt:string|null}[]}>(`/api/connectors/fabric?view=records&id=${id}&limit=50&q=${encodeURIComponent(q)}`);
 const [link,setLink]=useState<string|null>(null);
 return <><input type="search" aria-label="Search synced records" placeholder="Search synced records…" value={q} onChange={e=>setQ(e.target.value)}/><ErrorNote error={error}/>{!data?<Skeleton rows={3}/>:!data.records.length?<p className="muted small">No synced records yet.</p>:<ul className="mini-list">{data.records.map(r=><li key={r.id} className="mini-row"><Chip tone="gray">{r.kind}</Chip><a href={r.url||undefined} target="_blank" rel="noreferrer"><b>{r.title}</b></a><small className="muted">{r.sourceUpdatedAt?`updated ${ago(r.sourceUpdatedAt)}`:''}{r.lastVerifiedAt?` · verified ${ago(r.lastVerifiedAt)}`:''}</small><Btn size="sm" variant="ghost" icon="Link2" onClick={()=>setLink(r.id)}>Connect to a record</Btn></li>)}</ul>}
  {link&&<LinkExternal connectorId={id} recordId={link} onClose={()=>setLink(null)}/>}</>;
}
function LinkExternal({connectorId,recordId,onClose}:{connectorId:string,recordId:string,onClose:()=>void}){
 const {toast}=useApp();const [q,setQ]=useState('');const [res,setRes]=useState<{id:string,type:string,sourceId:string,title:string,label:string}[]>([]);
 const search=async(v:string)=>{setQ(v);if(v.trim().length<2){setRes([]);return}try{setRes((await api<{nodes:typeof res}>(`/api/graph?q=${encodeURIComponent(v)}`)).nodes.filter(n=>n.type!=='external'))}catch{setRes([])}};
 return <Modal open onClose={onClose} title="Connect to a One Workspace record" subtitle="The external record keeps its source and lineage in the Work Graph."><Field label="Find a record"><input autoFocus value={q} onChange={e=>search(e.target.value)}/></Field><div className="mini-list">{res.map(r=><button key={r.id} className="mini-row" onClick={async()=>{try{await api('/api/connectors/fabric',{action:'link-record',id:connectorId,recordId,entityType:r.type,entityId:r.sourceId});toast('Connected');onClose()}catch(e){toast((e as Error).message,'error')}}}><Chip tone="gray">{r.label}</Chip><span>{r.title}</span></button>)}</div></Modal>;
}

// Connected apps inside a record: synced external records linked to it (e.g. Outlook threads, Drive files).
export function ConnectedApps({type,id}:{type:string,id:string}){
 const {can}=useApp();const {data}=useApi<{sections:{key:string,label:string,items:{id:string,title:string,url:string,provider:string|null,syncMode:string|null,lastVerifiedAt:string|null}[]}[]}>(can('graph')?`/api/graph?view=context&type=${encodeURIComponent(type)}&id=${encodeURIComponent(id)}`:null);
 const items=(data?.sections||[]).flatMap(s=>s.items).filter(i=>i.provider);
 if(!items.length)return null;
 return <Card title="Connected apps"><ul className="mini-list">{items.map(i=><li key={i.id} className="mini-row"><Icon name="Link" size={14}/><a href={i.url} target="_blank" rel="noreferrer">{i.title}</a><small className="muted">{i.provider} · {i.syncMode||'live'}{i.lastVerifiedAt?` · verified ${ago(i.lastVerifiedAt)}`:''}</small></li>)}</ul></Card>;
}
