'use client';
import {useEffect,useState} from 'react';
import {api,useApi,go,cx,ago,dateTime} from './lib';
import {useApp,Btn,Chip,Header,Grid,Modal,Field,ErrorNote,Skeleton,Empty,Card,Icon,Note,Tabs,KV,Stat,type Col} from './kit';
import {aiStatus} from './assistant';
import {pageLabels} from '../access-policy';

// ── Connector Center (company or platform scope) ──────────────────────────
type CField={key:string,label:string,hint?:string,required?:boolean,options?:string[],placeholder?:string};
type CType={id:string,name:string,category:string,description:string,auth:string,icon:string,family?:string,config:CField[],secrets:CField[],readable:boolean};
type Tool={name:string,description:string,readOnly:boolean,destructive:boolean,inputSchema:unknown};
type Connector={id:string,provider:string,name:string,description:string,authType:string,config:Record<string,string>,secretHint:string,hasWebhookSecret:boolean,status:string,health:string,lastOkAt:string|null,lastSyncAt:string|null,lastError:string,syncMinutes:number,pages:string[],roles:string[],allowedTools:string[],mutatingTools:string[],tools:Tool[],resources:{uri:string,name:string,description:string}[],fieldMap:Record<string,string>,createdBy:string,createdAt:string,updatedBy:string,updatedAt:string};
type ListData={types:CType[],connectors:Connector[],canConfigure:boolean,limit:number|null,roles:{id:string,name:string}[],redirectUri:string};
const statusTone=(s:string)=>s==='connected'?'green':s==='disabled'?'gray':s==='error'?'red':'amber';
const healthTone=(h:string)=>h==='healthy'?'green':h==='failing'?'red':'gray';
const usePages=[['app-pages','Custom pages (widgets)'],['assistant','ONE (AI assistant)']];
export function ConnectorCenter({scope,parts}:{scope:'company'|'platform',parts:string[]}){
 const base=scope==='platform'?'platform/connectors':'admin/connectors';const q=scope==='platform'?'&scope=platform':'';
 const {toast}=useApp();const {data,error,reload}=useApi<ListData>(`/api/connectors?x=1${q}`);
 const [adding,setAdding]=useState(false);
 useEffect(()=>{const m=/[?&]oauth=([^&]+)/.exec(location.hash);if(m){toast(decodeURIComponent(m[1]),m[1].startsWith('Connected')?'ok':'error');history.replaceState(null,'',location.hash.replace(/\?oauth=[^&]+/,''))}},[toast]);
 if(parts[0]&&data)return <ConnectorDetail id={parts[0]} scope={scope} types={data.types} roles={data.roles} onBack={()=>{reload();go(base)}}/>;
 const cols:Col<Connector>[]=[
  {key:'name',label:'Connector',render:c=><div className="cell-title"><b>{c.name}</b><small>{data?.types.find(t=>t.id===c.provider)?.name||c.provider}{c.description?` · ${c.description}`:''}</small></div>},
  {key:'status',label:'Status',width:120,render:c=><Chip tone={statusTone(c.status)}>{c.status}</Chip>},
  {key:'health',label:'Health',width:100,render:c=><Chip tone={healthTone(c.health)}>{c.health}</Chip>},
  {key:'lastOkAt',label:'Last success',width:120,render:c=><span className="muted">{ago(c.lastOkAt)}</span>},
  {key:'lastSyncAt',label:'Last sync',width:120,render:c=><span className="muted">{ago(c.lastSyncAt)}</span>},
  {key:'pages',label:'Enabled on',width:170,render:c=>(c.pages||[]).map(p=>pageLabels[p]||p).join(', ')||<span className="muted">Nowhere yet</span>},
 ];
 return <div className="page">
  <Header icon="Link" tone={scope==='platform'?'red':'gray'} title={scope==='platform'?'Platform connectors':'Connector Center'} subtitle={scope==='platform'?'Global app registrations (Microsoft, Google) that companies can sign in through, plus platform-level services. Secrets are encrypted and never shown again after saving.':'Connect Microsoft 365, Google Workspace, APIs, webhooks and MCP servers. Choose which pages and roles may use each one. Secrets are encrypted and never shown again after saving.'} actions={data?.canConfigure&&<Btn variant="primary" icon="Plus" onClick={()=>setAdding(true)}>Add connector</Btn>}/>
  <ErrorNote error={error} onRetry={reload}/>
  {!data?<Skeleton/>:!data.connectors.length?<Empty icon="Link" title="No connectors yet" action={data.canConfigure&&<Btn variant="primary" icon="Plus" onClick={()=>setAdding(true)}>Add connector</Btn>}>{data.canConfigure?'Add your first connector to bring data from other systems into widgets and the AI assistant.':'No connectors are enabled for your role.'}</Empty>:<Grid id={`connectors-${scope}`} rows={data.connectors} cols={cols} exportName="connectors" onOpen={c=>data.canConfigure&&go(`${base}/${c.id}`)}/>}
  {data?.limit!=null&&<p className="muted small">{data.connectors.length} of {data.limit} connectors on your plan.</p>}
  {adding&&data&&<AddConnector scope={scope} types={data.types} redirectUri={data.redirectUri} onClose={()=>setAdding(false)} onDone={id=>{setAdding(false);reload();go(`${base}/${id}`)}}/>}
 </div>;
}
function AddConnector({scope,types,redirectUri,onClose,onDone}:{scope:string,types:CType[],redirectUri:string,onClose:()=>void,onDone:(id:string)=>void}){
 const {toast}=useApp();const [type,setType]=useState<CType|null>(null);const [v,setV]=useState<{name:string,description:string,config:Record<string,string>,secrets:Record<string,string>}>({name:'',description:'',config:{},secrets:{}});const [busy,setBusy]=useState(false),[shown,setShown]=useState<{id:string,secret:string}|null>(null);
 const cats=[...new Set(types.map(t=>t.category))];
 if(shown)return <Modal open onClose={()=>onDone(shown.id)} title="Webhook signing secret" footer={<Btn variant="primary" onClick={()=>onDone(shown.id)}>I have stored it</Btn>}><Note tone="warn">This secret is shown <b>once</b>. Store it in the sending system; you can rotate it later.</Note><div className="copy-link"><code>{shown.secret}</code><Btn size="sm" icon="Copy" onClick={()=>{navigator.clipboard.writeText(shown.secret);toast('Copied')}}>Copy</Btn></div></Modal>;
 return <Modal open wide onClose={onClose} title={type?`Add ${type.name}`:'Add a connector'} subtitle={type?.description} footer={type?<><Btn variant="ghost" onClick={()=>setType(null)}>Back</Btn><div className="grow"/><Btn variant="primary" busy={busy} onClick={async()=>{setBusy(true);try{const r=await api<{id:string,webhookSecret?:string}>('/api/connectors',{action:'create',scope,provider:type.id,...v,name:v.name||type.name});if(r.webhookSecret)setShown({id:r.id,secret:r.webhookSecret});else onDone(r.id)}catch(e){toast((e as Error).message,'error')}finally{setBusy(false)}}}>Add connector</Btn></>:<Btn variant="ghost" onClick={onClose}>Cancel</Btn>}>
  {!type?<>{cats.map(c=><div key={c} className="page-pick-group"><p className="rail-section">{c}</p><div className="page-pick">{types.filter(t=>t.category===c).map(t=><button key={t.id} type="button" className="module-card" onClick={()=>setType(t)}><Icon name={t.icon} size={18}/><div><b>{t.name}</b><small>{t.description}</small></div></button>)}</div></div>)}
   <div className="page-pick-group"><p className="rail-section">AI providers</p><button type="button" className="module-card" onClick={()=>{onClose();go(scope==='platform'?'platform/connectors':'admin/ai')}}><Icon name="Sparkles" size={18}/><div><b>OpenAI, Anthropic, Gemini, Azure OpenAI, self-hosted</b><small>{scope==='platform'?'The platform default is Groq (server secret GROQ_API_KEY).':'Configured in AI settings: a company provider overrides the platform Groq default for your company only.'}</small></div></button></div></>
  :<div className="form-grid">
   <Field label="Name"><input value={v.name} placeholder={type.name} onChange={e=>setV({...v,name:e.target.value})}/></Field>
   <Field label="Description"><input value={v.description} onChange={e=>setV({...v,description:e.target.value})}/></Field>
   {type.config.map(f=><Field key={f.key} label={f.label+(f.required?'':' (optional)')} hint={f.hint}>{f.options?<select value={v.config[f.key]||f.options[0]} onChange={e=>setV({...v,config:{...v.config,[f.key]:e.target.value}})}>{f.options.map(o=><option key={o} value={o}>{o}</option>)}</select>:<input value={v.config[f.key]||''} placeholder={f.placeholder} onChange={e=>setV({...v,config:{...v.config,[f.key]:e.target.value}})}/>}</Field>)}
   {type.secrets.map(f=><Field key={f.key} label={f.label+(f.required?'':' (optional)')} hint={f.hint||'Encrypted at rest. It will never be shown again.'}><input type="password" autoComplete="off" value={v.secrets[f.key]||''} onChange={e=>setV({...v,secrets:{...v.secrets,[f.key]:e.target.value}})}/></Field>)}
   {type.auth==='oauth2'&&<Note>After adding, use <b>Connect</b> to sign in. Register this redirect URI in the app registration: <code>{redirectUri}</code></Note>}
   {type.auth==='webhook'&&<Note>A signing secret and the webhook URL are created for you.</Note>}
   {type.auth==='mcp'&&<Note>After adding, use <b>Test connection</b> to discover tools and resources. No tool can be used until you allow it.</Note>}
  </div>}
 </Modal>;
}
function ConnectorDetail({id,scope,types,roles,onBack}:{id:string,scope:'company'|'platform',types:CType[],roles:{id:string,name:string}[],onBack:()=>void}){
 const {toast,ask}=useApp();const q=scope==='platform'?'&scope=platform':'';
 const {data,error,reload}=useApi<{connector:Connector,logs:{id:string,action:string,status:string,ms:number,detail:string|null,createdAt:string,actorName:string|null}[],history:{action:string,createdAt:string,actorName?:string}[],webhookUrl:string|null,redirectUri:string}>(`/api/connectors?id=${id}${q}`);
 const [tab,setTab]=useState('overview'),[busy,setBusy]=useState<string|null>(null),[edit,setEdit]=useState<Connector|null>(null),[rotate,setRotate]=useState<Record<string,string>>({}),[secret,setSecret]=useState<string|null>(null);
 useEffect(()=>{if(data)setEdit(JSON.parse(JSON.stringify(data.connector)))},[data]);
 if(error)return <div className="page"><ErrorNote error={error} onRetry={reload}/></div>;
 if(!data||!edit)return <div className="page"><Skeleton rows={8}/></div>;
 const c=data.connector;const type=types.find(t=>t.id===c.provider);
 const act=async(action:string,extra:Record<string,unknown>={},msg?:string)=>{setBusy(action);try{const r=await api<any>('/api/connectors',{action,id:c.id,scope,...extra});if(r.ok===false)toast(r.error||'Failed','error');else if(msg)toast(msg);reload();return r}catch(e){toast((e as Error).message,'error')}finally{setBusy(null)}};
 return <div className="page">
  <div className="doc-top"><Btn variant="ghost" icon="ArrowLeft" onClick={onBack}>All connectors</Btn></div>
  <Header icon={type?.icon||'Link'} tone="gray" title={<>{c.name} <Chip tone={statusTone(c.status)}>{c.status}</Chip> <Chip tone={healthTone(c.health)}>{c.health}</Chip></>} subtitle={`${type?.name||c.provider} · ${c.authType} · added by ${c.createdBy} ${ago(c.createdAt)}`} actions={<>
   {c.authType==='oauth2'&&<Btn icon="LogIn" busy={busy==='oauth-start'} onClick={async()=>{const r=await act('oauth-start');if(r?.url)location.href=r.url}}>{c.status==='connected'?'Reconnect':'Connect'}</Btn>}
   <Btn icon="RefreshCw" busy={busy==='test'} onClick={async()=>{const r=await act('test');if(r?.ok)toast(`Connection OK (${r.ms} ms)`)}}>Test connection</Btn>
   {c.status==='disabled'?<Btn onClick={()=>act('enable',{},'Enabled')}>Enable</Btn>:<Btn onClick={async()=>{if(await ask({title:`Disable ${c.name}?`,body:'Widgets and the assistant stop using it. Settings and credentials are kept.',confirm:'Disable',danger:true})!==false)act('disable',{},'Disabled')}}>Disable</Btn>}
  </>}/>
  {c.lastError&&<Note tone="warn">Last error: {c.lastError}</Note>}
  <Tabs value={tab} onChange={setTab} items={[{id:'overview',label:'Overview'},{id:'configure',label:'Configure'},{id:'access',label:'Pages & roles'},...(c.authType==='mcp'?[{id:'tools',label:`Tools (${c.tools.length})`}]:[]),{id:'credentials',label:'Credentials'},{id:'logs',label:'Logs'},{id:'audit',label:'Audit history'}]}/>
  {tab==='overview'&&<div className="cards-3"><Card title="Status"><KV items={[['Status',c.status],['Health',c.health],['Last success',c.lastOkAt?dateTime(c.lastOkAt):'never'],['Last synchronization',c.lastSyncAt?dateTime(c.lastSyncAt):'never'],['Sync frequency',c.syncMinutes?`every ${c.syncMinutes} min (run on demand)`:'on demand'],['Credentials',c.secretHint||(c.hasWebhookSecret?'webhook secret set':'none')]]}/><div className="row-gap"><Btn size="sm" icon="RefreshCw" busy={busy==='sync'} onClick={async()=>{const r=await act('sync');if(r?.ok)toast('Synchronized')}}>Sync now</Btn></div></Card>
   <Card title="Connection" className="span2"><KV items={[['Type',type?.name||c.provider],['Authentication',c.authType],['Requested permissions',type?.family?(c.config.scopes||'default scopes for this connector'):c.authType==='oauth2'?(c.config.scopes||'—'):'—'],...Object.entries(c.config).map(([k,v])=>[type?.config.find(f=>f.key===k)?.label||k,v] as [string,string])]}/>{data.webhookUrl&&<><p className="field-label">Webhook URL</p><div className="copy-link"><code>{data.webhookUrl}</code><Btn size="sm" icon="Copy" onClick={()=>{navigator.clipboard.writeText(data.webhookUrl!);toast('Copied')}}>Copy</Btn></div><p className="muted small">Send <code>X-OneWorkspace-Timestamp</code> (unix seconds) and <code>X-OneWorkspace-Signature: sha256=HMAC_SHA256(secret, timestamp + "." + body)</code>. Events older than 5 minutes are refused.</p></>}{c.authType==='oauth2'&&<p className="muted small">Redirect URI: <code>{data.redirectUri}</code></p>}</Card></div>}
  {tab==='configure'&&<Card title="Configuration" actions={<Btn variant="primary" busy={busy==='update'} onClick={()=>act('update',{name:edit.name,description:edit.description,config:edit.config,syncMinutes:edit.syncMinutes,fieldMap:edit.fieldMap},'Saved')}>Save</Btn>}><div className="form-grid">
   <Field label="Name"><input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></Field>
   <Field label="Description"><input value={edit.description} onChange={e=>setEdit({...edit,description:e.target.value})}/></Field>
   {type?.config.map(f=><Field key={f.key} label={f.label} hint={f.hint}>{f.options?<select value={edit.config[f.key]||f.options[0]} onChange={e=>setEdit({...edit,config:{...edit.config,[f.key]:e.target.value}})}>{f.options.map(o=><option key={o}>{o}</option>)}</select>:<input value={edit.config[f.key]||''} placeholder={f.placeholder} onChange={e=>setEdit({...edit,config:{...edit.config,[f.key]:e.target.value}})}/>}</Field>)}
   <Field label="Sync frequency (minutes)" hint="0 = on demand. Scheduled runs need a Cron Trigger; today syncs run from Sync now and when widgets read."><input type="number" min={0} max={1440} value={edit.syncMinutes} onChange={e=>setEdit({...edit,syncMinutes:Number(e.target.value)})}/></Field>
   {type?.readable&&c.authType!=='mcp'&&<Field label="Field mapping" wide hint="One per line: external field = One Workspace field. Only mapped fields are shown in widgets when set."><textarea rows={4} value={Object.entries(edit.fieldMap).map(([k,v])=>`${k} = ${v}`).join('\n')} onChange={e=>setEdit({...edit,fieldMap:Object.fromEntries(e.target.value.split('\n').map(l=>l.split('=').map(x=>x.trim())).filter(([k,v])=>k&&v))})}/></Field>}
  </div></Card>}
  {tab==='access'&&<Card title="Where it can be used" actions={<Btn variant="primary" busy={busy==='update'} onClick={()=>act('update',{pages:edit.pages,roles:edit.roles},'Access saved')}>Save</Btn>}>
   <p className="field-label">Pages</p><div className="page-pick">{usePages.map(([p,l])=><label key={p} className={cx('module-card',edit.pages.includes(p)&&'on')}><input type="checkbox" checked={edit.pages.includes(p)} onChange={e=>setEdit({...edit,pages:e.target.checked?[...edit.pages,p]:edit.pages.filter(x=>x!==p)})}/><div><b>{l}</b></div></label>)}</div>
   {scope==='company'&&<><p className="field-label">Roles</p><div className="chip-picks">{[...roles.map(r=>[r.id,r.name]),['manager','Department Heads (type)'],['employee','Standard Users (type)'],['viewer','Viewers (type)']].map(([rid,name])=><button key={rid} type="button" className={cx('chip-btn',edit.roles.includes(rid)&&'on')} onClick={()=>setEdit({...edit,roles:edit.roles.includes(rid)?edit.roles.filter(x=>x!==rid):[...edit.roles,rid]})}>{name}</button>)}</div>
   <Note>Company Admins can always use it. Everyone else also needs the “Use connectors” permission on their role. Connectors never bypass One Workspace permissions and their data is treated as untrusted text.</Note></>}
  </Card>}
  {tab==='tools'&&<Card title="MCP tools and resources" actions={<Btn variant="primary" busy={busy==='update'} onClick={()=>act('update',{allowedTools:edit.allowedTools,mutatingTools:edit.mutatingTools},'Tool access saved')}>Save</Btn>}>
   {!c.tools.length?<Empty icon="Cpu" title="No tools discovered">Use Test connection to discover the server's tools.</Empty>:<table className="plain"><thead><tr><th>Tool</th><th>Allowed</th><th>Changes data</th><th/></tr></thead><tbody>{c.tools.map(t=><tr key={t.name}><td><b className="mono">{t.name}</b><br/><small className="muted">{t.description}</small>{t.destructive&&<Chip tone="red">destructive hint</Chip>}{t.readOnly&&<Chip tone="green">read-only hint</Chip>}</td><td><input type="checkbox" aria-label={`Allow ${t.name}`} checked={edit.allowedTools.includes(t.name)} onChange={e=>setEdit({...edit,allowedTools:e.target.checked?[...edit.allowedTools,t.name]:edit.allowedTools.filter(x=>x!==t.name)})}/></td><td><input type="checkbox" aria-label={`${t.name} changes data`} checked={edit.mutatingTools.includes(t.name)} onChange={e=>setEdit({...edit,mutatingTools:e.target.checked?[...edit.mutatingTools,t.name]:edit.mutatingTools.filter(x=>x!==t.name)})}/></td><td>{c.allowedTools.includes(t.name)&&<RunTool connector={c} tool={t} scope={scope}/>}</td></tr>)}</tbody></table>}
   <Note>Tools marked “changes data” always ask for confirmation and can only be run by administrators. Mark every tool that is not strictly read-only.</Note>
   {!!c.resources.length&&<><p className="field-label">Resources</p><ul className="small">{c.resources.map(r=><li key={r.uri}><span className="mono">{r.uri}</span> {r.name&&`· ${r.name}`}</li>)}</ul></>}
  </Card>}
  {tab==='credentials'&&<Card title="Credentials">
   {c.provider==='webhook'?<><p>Rotate the signing secret if it may have leaked. The old secret stops working immediately.</p><Btn icon="RefreshCw" onClick={async()=>{if(await ask({title:'Rotate webhook secret?',body:'The sending system must be updated with the new secret.',confirm:'Rotate',danger:true})===false)return;const r=await act('rotate',{},'Secret rotated');if(r?.webhookSecret)setSecret(r.webhookSecret)}}>Rotate signing secret</Btn>{secret&&<><Note tone="warn">Shown once:</Note><div className="copy-link"><code>{secret}</code><Btn size="sm" icon="Copy" onClick={()=>{navigator.clipboard.writeText(secret);toast('Copied')}}>Copy</Btn></div></>}</>
   :!type?.secrets.length?<p className="muted">This connector has no stored credentials{c.authType==='oauth2'?' other than the sign-in tokens from Connect':''}.</p>
   :<div className="form-grid">{type.secrets.map(f=><Field key={f.key} label={`New ${f.label.toLowerCase()}`} hint={c.secretHint?`Current: ${c.secretHint}`:'Not set'}><input type="password" autoComplete="off" value={rotate[f.key]||''} onChange={e=>setRotate({...rotate,[f.key]:e.target.value})}/></Field>)}<div className="form-actions"><Btn variant="primary" disabled={!Object.values(rotate).some(Boolean)} onClick={async()=>{await act('rotate',{secrets:rotate},'Credentials rotated');setRotate({})}}>Rotate credentials</Btn></div></div>}
   <div className="danger-list"><div><div><b>Disconnect</b><small>Deletes this connector, its credentials and tool settings. Logs are kept.</small></div><Btn variant="danger" onClick={async()=>{const v=await ask({title:`Disconnect ${c.name}?`,body:<>Type <b>{c.name}</b> to confirm. Widgets using it will stop working.</>,confirm:'Disconnect',danger:true,input:{label:'Connector name',required:true}});if(v===false)return;const r=await act('disconnect',{confirm:v},'Disconnected');if(r?.ok)onBack()}}>Disconnect</Btn></div></div>
  </Card>}
  {tab==='logs'&&<Card title="Activity (latest 80)">{!data.logs.length?<p className="muted">No activity yet.</p>:<table className="plain"><thead><tr><th>When</th><th>Action</th><th>Status</th><th>Time</th><th>Who</th><th>Detail</th></tr></thead><tbody>{data.logs.map(l=><tr key={l.id}><td className="muted">{dateTime(l.createdAt)}</td><td className="mono">{l.action}</td><td><Chip tone={l.status==='ok'?'green':l.status==='denied'?'amber':'red'}>{l.status}</Chip></td><td>{l.ms?`${l.ms} ms`:''}</td><td>{l.actorName||(l.action.startsWith('webhook')?'Webhook':'—')}</td><td className="small mono muted" title="Connector content is untrusted">{l.detail?.slice(0,160)}</td></tr>)}</tbody></table>}</Card>}
  {tab==='audit'&&<Card title="Configuration history">{!data.history.length?<p className="muted">No changes recorded.</p>:<div className="mini-list">{data.history.map((h,i)=><div key={i} className="mini-row"><Icon name="History" size={15}/><span>{h.action}<small>{h.actorName||''} · {dateTime(h.createdAt)}</small></span></div>)}</div>}</Card>}
 </div>;
}
function RunTool({connector,tool,scope}:{connector:Connector,tool:Tool,scope:string}){
 const {toast,ask}=useApp();const [open,setOpen]=useState(false),[args,setArgs]=useState('{}'),[out,setOut]=useState<{result:string,isError:boolean}|null>(null),[busy,setBusy]=useState(false);const [ctrl,setCtrl]=useState<AbortController|null>(null);
 async function run(confirm=false){let a:unknown;try{a=JSON.parse(args||'{}')}catch{toast('Arguments must be JSON.','error');return}setBusy(true);const c=new AbortController();setCtrl(c);try{const r=await api<any>('/api/connectors',{action:'mcp-call',scope,id:connector.id,tool:tool.name,args:a,confirm,page:'app-pages'},{signal:c.signal});if(r.needsConfirmation){setBusy(false);if(await ask({title:`Run ${tool.name}?`,body:r.message,confirm:'Run tool',danger:true})!==false)return run(true);return}setOut(r)}catch(e){toast((e as Error).name==='AbortError'?'Cancelled':(e as Error).message,'error')}finally{setBusy(false);setCtrl(null)}}
 return <><Btn size="sm" icon="Workflow" onClick={()=>setOpen(true)}>Run</Btn>{open&&<Modal open onClose={()=>{ctrl?.abort();setOpen(false)}} title={`Run ${tool.name}`} subtitle={tool.description} footer={<>{busy&&<Btn onClick={()=>ctrl?.abort()}>Cancel</Btn>}<div className="grow"/><Btn variant="primary" busy={busy} onClick={()=>run(false)}>Run</Btn></>}>
  <Field label="Arguments (JSON)"><textarea rows={5} className="mono" value={args} onChange={e=>setArgs(e.target.value)}/></Field>
  {out&&<><Note tone={out.isError?'warn':'info'}>Result from {connector.name} (untrusted content, shown as plain text):</Note><pre className="tool-out">{out.result}</pre></>}
 </Modal>}</>;
}

// ── Company AI settings (Company Admins) ─────────────────────────────────
type Knowledge={available:boolean,source:string|null,model:string|null,store:string|null,documents:number,chunks:number,lastIndexedAt:string|null};
type AiSettingsData={knowledge:Knowledge,provider:{provider:string,label:string,model:string,embeddingModel?:string,baseUrl:string,secretHint:string,active:boolean,fallback:string,updatedAt:string,updatedBy:string}|null,platformDefault:{provider:string,model:string}|null,catalog:{id:string,name:string,baseUrl:string,defaultModel:string,needsBaseUrl:boolean,embeddings:boolean,tools:boolean}[],limit:number,used:number,retentionDays:number,usage:{kind:string,requests:number,promptTokens:number,completionTokens:number,failures:number}[],recent:{kind:string,provider:string,model:string,ok:number,createdAt:string,memberName:string|null}[]};
export function AiSettings(){
 const {toast,ask}=useApp();const {data,error,reload}=useApi<AiSettingsData>('/api/ai?view=settings');
 const [v,setV]=useState({provider:'openai',model:'',baseUrl:'',apiKey:'',fallback:'none',label:'',embeddingModel:''});const [indexing,setIndexing]=useState<{processed:number,remaining:number}|null>(null);const [busy,setBusy]=useState<string|null>(null);const [days,setDays]=useState(90);
 useEffect(()=>{if(data){const p=data.provider;setV({provider:p?.provider||'openai',model:p?.model||'',baseUrl:p?.baseUrl||'',apiKey:'',fallback:p?.fallback||'none',label:p?.label||'',embeddingModel:p?.embeddingModel||''});setDays(data.retentionDays)}},[data]);
 if(error)return <div className="page"><ErrorNote error={error} onRetry={reload}/></div>;
 if(!data)return <div className="page"><Skeleton rows={8}/></div>;
 const cat=data.catalog.find(c=>c.id===v.provider);
 async function runIndex(rebuild:boolean){const since=rebuild?new Date().toISOString():undefined;let done=0;setIndexing({processed:0,remaining:0});try{for(let i=0;i<500;i++){const r=await api<{processed:number,remaining:number}>('/api/ai',{action:'knowledge-index',since});done+=r.processed;setIndexing({processed:done,remaining:r.remaining});if(!r.remaining||!r.processed)break}toast(`Knowledge index up to date (${done} records processed)`);reload()}catch(e){toast((e as Error).message,'error')}finally{setIndexing(null)}}
 const call=async(action:string,body:Record<string,unknown>,msg:string)=>{setBusy(action);try{const r=await api<any>('/api/ai',{action,...body});if(r.ok===false)toast(r.error,'error');else toast(msg);if(action!=='provider-test')reload();aiStatus(true);return r}catch(e){toast((e as Error).message,'error')}finally{setBusy(null)}};
 const using=data.provider?.active?`${data.catalog.find(c=>c.id===data.provider!.provider)?.name||data.provider.provider} · ${data.provider.model}`:data.platformDefault?`Platform default · Groq · ${data.platformDefault.model}`:'Not configured';
 return <div className="page">
  <Header icon="Sparkles" tone="violet" title="AI settings" subtitle="Your company uses the platform's Groq default unless you connect your own provider. Your provider applies to your company only and never changes the platform's Groq credentials."/>
  <div className="stats"><Stat label="AI in use" value={using} icon="Sparkles" tone="violet"/><Stat label="Requests this month" value={`${data.used.toLocaleString()} / ${data.limit.toLocaleString()}`} icon="Activity" tone="sky"/><Stat label="Conversation retention" value={data.retentionDays?`${data.retentionDays} days`:'Kept'} icon="Clock" tone="amber"/></div>
  <div className="split-2">
   <Card title="Company AI provider" actions={data.provider&&<Btn variant="ghost" icon="Trash2" onClick={async()=>{if(await ask({title:'Remove your AI provider?',body:'Your company goes back to the platform default (Groq), if it is available. The stored key is deleted.',confirm:'Remove',danger:true})!==false)call('provider-remove',{},'Provider removed')}}>Use platform default</Btn>}>
    <div className="form-grid">
     <Field label="Provider"><select value={v.provider} onChange={e=>{const c=data.catalog.find(x=>x.id===e.target.value);setV({...v,provider:e.target.value,model:c?.defaultModel||'',baseUrl:''})}}>{data.catalog.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>
     <Field label="Model" hint="Stored per company; not hard-coded."><input value={v.model} placeholder={cat?.defaultModel||'model name'} onChange={e=>setV({...v,model:e.target.value})}/></Field>
     {(cat?.needsBaseUrl||v.baseUrl)&&<Field label="Endpoint URL" wide hint={v.provider==='azure-openai'?'https://<resource>.openai.azure.com/openai/deployments/<deployment>':'https://… (http is accepted only for a service on this machine)'}><input value={v.baseUrl} onChange={e=>setV({...v,baseUrl:e.target.value})}/></Field>}
     <Field label="API key" wide hint={data.provider?.secretHint&&data.provider.provider===v.provider?`Saved key ${data.provider.secretHint}. Leave empty to keep it; enter a new one to rotate.`:'Encrypted at rest and never shown again.'}><input type="password" autoComplete="off" value={v.apiKey} onChange={e=>setV({...v,apiKey:e.target.value})}/></Field>
     {cat?.embeddings&&<Field label="Embedding model (optional)" wide hint="Set it to use your provider for ONE’s vector search, e.g. text-embedding-3-small. Leave empty to use Cloudflare Workers AI embeddings."><input value={v.embeddingModel} placeholder="text-embedding-3-small" onChange={e=>setV({...v,embeddingModel:e.target.value})}/></Field>}
     <label className="check wide"><input type="checkbox" checked={v.fallback==='platform'} onChange={e=>setV({...v,fallback:e.target.checked?'platform':'none'})}/>If our provider is unavailable, fall back to the platform default (Groq). Requests would then be sent to Groq.</label>
     <div className="form-actions"><Btn icon="RefreshCw" busy={busy==='provider-test'} onClick={async()=>{const r=await call('provider-test',v,'Test passed');if(r?.ok)toast(`Provider answered in ${r.ms} ms`)}}>Test connection</Btn><Btn variant="primary" busy={busy==='provider-save'} onClick={()=>call('provider-save',v,'AI provider saved')}>Save provider</Btn></div>
    </div>
    <p className="muted small">Capabilities: chat and streaming{cat?.embeddings?', embeddings':''}{cat?.tools?', tool calling':''}. {data.provider?`Last changed by ${data.provider.updatedBy} ${ago(data.provider.updatedAt)}.`:''}</p>
   </Card>
   <Card title="Data & retention"><Field label="Keep assistant conversations for (days)" hint="0 keeps them. Older conversations are deleted automatically."><input type="number" min={0} max={3650} value={days} onChange={e=>setDays(Number(e.target.value))}/></Field><Btn onClick={()=>call('settings',{retentionDays:days},'Retention saved')}>Save retention</Btn><Note>The assistant only retrieves records the person asking can open, sends the minimum relevant excerpts, and never includes secrets. Usage logs below contain no prompts or answers.</Note></Card>
  </div>
  <Card title="Knowledge index (vector search)" actions={data.knowledge.available&&<><Btn icon="RefreshCw" busy={!!indexing} onClick={()=>runIndex(false)}>Index changes</Btn><Btn busy={!!indexing} onClick={async()=>{if(await ask({title:'Rebuild the knowledge index?',body:'Every record is embedded again. This can take a while for large workspaces and uses embedding credits.',confirm:'Rebuild'})!==false)runIndex(true)}}>Rebuild</Btn></>}>
   {!data.knowledge.available?<Note tone="warn">Vector search is off. ONE still answers using keyword search. To turn it on, the Platform Owner binds Cloudflare Workers AI and Vectorize (see README), or you set an embedding model for your own AI provider above.</Note>:
   <KV items={[['Embeddings',data.knowledge.source==='workers-ai'?`Cloudflare Workers AI · ${data.knowledge.model}`:`Your AI provider · ${data.knowledge.model}`],['Vector store',data.knowledge.store==='vectorize'?'Cloudflare Vectorize (namespace for this company only)':'Workspace database (this company only)'],['Records indexed',`${data.knowledge.documents.toLocaleString()} (${data.knowledge.chunks.toLocaleString()} chunks)`],['Last indexed',data.knowledge.lastIndexedAt?dateTime(data.knowledge.lastIndexedAt):'never']]}/>}
   {indexing&&<p className="muted small">Indexed {indexing.processed} records · {indexing.remaining} to go…</p>}
   <p className="muted small">New and changed records are indexed automatically as people use ONE. Results are always re-checked against the permissions of the person asking.</p>
  </Card>
  <Card title="Usage (last 30 days)">{!data.usage.length?<p className="muted">No AI requests yet.</p>:<table className="plain"><thead><tr><th>Feature</th><th>Requests</th><th>Tokens in</th><th>Tokens out</th><th>Failures</th></tr></thead><tbody>{data.usage.map(x=><tr key={x.kind}><td className="mono">{x.kind}</td><td>{x.requests}</td><td>{x.promptTokens}</td><td>{x.completionTokens}</td><td>{x.failures}</td></tr>)}</tbody></table>}</Card>
  <Card title="AI activity log">{!data.recent.length?<p className="muted">Nothing yet.</p>:<table className="plain"><thead><tr><th>When</th><th>Who</th><th>Feature</th><th>Provider</th><th>Result</th></tr></thead><tbody>{data.recent.map((x,i)=><tr key={i}><td className="muted">{dateTime(x.createdAt)}</td><td>{x.memberName||'—'}</td><td className="mono">{x.kind}</td><td>{x.provider} · {x.model}</td><td><Chip tone={x.ok?'green':'red'}>{x.ok?'ok':'failed'}</Chip></td></tr>)}</tbody></table>}</Card>
 </div>;
}

// ── Platform: default AI, platform connectors and health ─────────────────
export function PlatformIntegrations({parts}:{parts:string[]}){
 const {toast}=useApp();const {data,error,reload}=useApi<{ai:{id:string,name:string,requests:number,tokens:number,failures:number,companyProvider:string|null}[],connectors:{tenantId:string,workspace:string,id:string,name:string,provider:string,status:string,health:string,lastOkAt:string|null,lastError:string}[],aiDefault:{configured:boolean,provider:string,model:string,keySource:string}}>('/api/platform?view=health');
 const [model,setModel]=useState('');useEffect(()=>{if(data)setModel(data.aiDefault.model)},[data]);
 if(parts[0])return <ConnectorCenter scope="platform" parts={parts}/>;
 return <div className="page">
  <Header icon="Link" tone="red" title="Connectors & AI" subtitle="The platform's default AI provider, global connectors, and health across every company."/>
  <ErrorNote error={error} onRetry={reload}/>
  {!data?<Skeleton/>:<>
   <div className="split-2"><Card title="Default AI provider: Groq"><KV items={[['Status',data.aiDefault.configured?'Configured':'Not configured'],['Key',`${data.aiDefault.keySource} (never stored in the database or shown)`],['Used by',`${data.ai.filter(a=>!a.companyProvider).length} companies without their own provider`]]}/>{!data.aiDefault.configured&&<Note tone="warn">Set the server secret: <code>npx wrangler secret put GROQ_API_KEY</code> (or <code>GROQ_API_KEY=…</code> in <code>.dev.vars</code> locally).</Note>}<div className="row-gap"><Field label="Default model"><input value={model} onChange={e=>setModel(e.target.value)}/></Field><Btn variant="primary" onClick={async()=>{try{await api('/api/platform',{action:'ai-default',model});toast('Default model saved');reload()}catch(e){toast((e as Error).message,'error')}}}>Save</Btn></div></Card>
    <Card title="AI consumption (30 days)"><div className="mini-list">{data.ai.slice(0,12).map(a=><div key={a.id} className="mini-row"><Icon name="Sparkles" size={15}/><span>{a.name}<small>{a.requests} requests · {a.tokens.toLocaleString()} tokens{a.failures?` · ${a.failures} failed`:''} · {a.companyProvider?`own provider (${a.companyProvider})`:'Groq default'}</small></span></div>)}</div></Card></div>
   <ConnectorCenterEmbed/>
   <Card title="Connector status across companies">{!data.connectors.length?<p className="muted">No connectors yet.</p>:<table className="plain"><thead><tr><th>Workspace</th><th>Connector</th><th>Status</th><th>Health</th><th>Last success</th><th>Last error</th></tr></thead><tbody>{data.connectors.map(c=><tr key={c.id}><td>{c.workspace}</td><td>{c.name} <small className="muted">{c.provider}</small></td><td><Chip tone={statusTone(c.status)}>{c.status}</Chip></td><td><Chip tone={healthTone(c.health)}>{c.health}</Chip></td><td className="muted">{ago(c.lastOkAt)}</td><td className="small muted">{c.lastError}</td></tr>)}</tbody></table>}</Card>
  </>}
 </div>;
}
function ConnectorCenterEmbed(){return <div className="embed-block"><ConnectorCenter scope="platform" parts={[]}/></div>}
