'use client';
import {useEffect,useState} from 'react';
import {api,useApi,go,ago,cx,dateOnly} from './lib';
import {useApp,Btn,Chip,Header,Field,ErrorNote,Skeleton,Empty,Icon,Card,Tabs,Note,Markdown,PersonSelect} from './kit';
import {ConnectedContext} from './context';
import {WorkEditor} from './business';
import {workKindById} from '../work-records';

// Company Knowledge Intelligence: permission-checked search over everything the company knows, the Decision
// Register, meetings, questions with cited answers, freshness reviews and AI suggestions awaiting approval.
type Result={id:string,title:string,sourceType:string,kind:string,summary:string,excerpt:string,owner:string,modified:string,classification:string,url:string,status:string,verified:boolean,aiGenerated:boolean,topics:string[],citations:{text:string,quote:string}[],related:{id:string,title:string,url:string,kind:string}[],stale:boolean};
type Facet={value:string,n:number};
export const knowledgeViews=[{id:'search',label:'Search',icon:'Search'},{id:'topics',label:'Topics',icon:'Tags'},{id:'decisions',label:'Decision Register',icon:'Gavel'},{id:'meetings',label:'Meetings',icon:'CalendarClock'},{id:'policies',label:'Policies',icon:'ShieldCheck'},{id:'questions',label:'Questions',icon:'MessageCircleQuestion'},{id:'reviews',label:'Reviews',icon:'ClipboardCheck',section:'Stewardship'},{id:'suggestions',label:'AI suggestions',icon:'Sparkles',section:'Stewardship'}];
const KIND_ICON:Record<string,string>={document:'FileText',recording:'AudioLines',policy:'ShieldCheck',article:'BookOpen',announcement:'Megaphone',decision:'Gavel',meeting:'CalendarClock',email:'Mail',calendar:'Calendar',project:'FolderKanban',task:'ListTodo',ticket:'LifeBuoy',purchase:'ShoppingBag',asset:'Boxes',request:'Route',contract:'FileSignature',strategy:'Target',connector:'Link',app_record:'AppWindow',message:'MessageSquare'};

export default function Knowledge({parts=[]}:{parts?:string[]}){
 const v=parts[0]||'search';
 if(v==='item')return <Item id={parts[1]}/>;
 if(v==='decisions')return parts[1]==='new'?<WorkEditor kind={workKindById.get('decision')!} onSaved={id=>go(`knowledge/decisions/${id}`)}/>:parts[1]?parts[2]==='edit'?<WorkEditor kind={workKindById.get('decision')!} id={parts[1]} onSaved={id=>go(`knowledge/decisions/${id}`)}/>:<Decision id={parts[1]}/>:<Decisions/>;
 if(v==='meetings')return parts[1]==='new'?<WorkEditor kind={workKindById.get('meeting')!} onSaved={id=>go(`knowledge/meetings/${id}`)}/>:parts[1]?<Meeting id={parts[1]}/>:<Meetings/>;
 if(v==='questions')return parts[1]?<Question id={parts[1]}/>:<Questions/>;
 if(v==='reviews')return <Reviews focus={parts[1]}/>;
 if(v==='suggestions')return <Suggestions/>;
 if(v==='topics')return <Topics/>;
 if(v==='policies')return <Search preset={{kind:'policy'}} title="Policies"/>;
 return <Search/>;
}
function Search({preset={},title='Knowledge search'}:{preset?:Record<string,string>,title?:string}){
 const {toast,s}=useApp();const init=new URLSearchParams(location.hash.split('?')[1]||'');
 const [q,setQ]=useState(init.get('q')||'');const [query,setQuery]=useState(init.get('q')||'');const [f,setF]=useState<Record<string,string>>(()=>{const o:Record<string,string>={...preset};init.forEach((v,k)=>{if(k!=='q'&&v)o[k]=v});return o});const [page,setPage]=useState(1);
 const params=new URLSearchParams({view:'search',q:query,page:String(page),...f});
 const {data,error,reload}=useApi<{total:number,page:number,size:number,results:Result[],facets:Record<string,Facet[]>,semantic:boolean}>(`/api/knowledge?${params}`);
 const [sugg,setSugg]=useState<{label:string,kind:string,url:string}[]>([]);const searches=useApi<{recent:{id:string,query:string}[],saved:{id:string,name:string,query:string,filters:string}[]}>('/api/knowledge?view=searches');
const typing=q.trim().length>=2&&q!==query;const shown=typing?sugg:[];
 useEffect(()=>{if(!typing)return;const t=setTimeout(()=>api<{suggestions:typeof sugg}>(`/api/knowledge?view=autocomplete&q=${encodeURIComponent(q)}`).then(r=>setSugg(r.suggestions)).catch(()=>setSugg([])),200);return()=>clearTimeout(t)},[q,typing]);
 const setFilter=(k:string,v:string)=>{setF(o=>{const n={...o};if(!v||n[k]===v)delete n[k];else n[k]=v;return n});setPage(1)};
 const facetLabel:Record<string,string>={type:'Source',kind:'Kind',department:'Department',classification:'Classification',year:'Year'};
 return <div className="page"><Header icon="Search" tone="violet" title={title} subtitle="Every result is checked against your permissions when you search: restricted content never appears, not even in counts."/>
  <form className="kn-search" onSubmit={e=>{e.preventDefault();setQuery(q);setPage(1);setSugg([])}}><Icon name="Search" size={18}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder={`Search ${s.tenant.name} knowledge…`} aria-label="Search"/><Btn type="submit" variant="primary">Search</Btn>
   {shown.length>0&&<div className="kn-suggest">{shown.map((x,i)=><button type="button" key={i} onClick={()=>{if(x.url)location.hash=x.url;else{setQ(x.label);setQuery(x.label);setSugg([])}}}><Icon name={x.url?'FileText':'Tag'} size={13}/>{x.label}<small className="muted">{x.kind}</small></button>)}</div>}</form>
  <div className="row-gap wrap small">{(searches.data?.saved||[]).map(x=><button key={x.id} className="chip chip-violet" onClick={()=>{setQ(x.query);setQuery(x.query);setF(JSON.parse(x.filters||'{}'))}}>{x.name}</button>)}{(searches.data?.recent||[]).slice(0,6).map(x=><button key={x.id} className="chip chip-gray" onClick={()=>{setQ(x.query);setQuery(x.query)}}>{x.query}</button>)}{query&&<button className="link small" onClick={async()=>{const name=prompt('Name this search');if(!name)return;await api('/api/knowledge',{action:'save-search',q:query,filters:f,name});toast('Search saved');searches.reload()}}>Save this search</button>}</div>
  <ErrorNote error={error} onRetry={reload}/>
  <div className="kn-layout"><aside className="kn-facets">{data&&Object.entries(data.facets).map(([k,list])=>list.length>0&&<div key={k}><p className="rail-section">{facetLabel[k]||k}</p>{list.map(x=><button key={x.value} className={cx('facet',f[k]===x.value&&'on')} onClick={()=>setFilter(k,x.value)}>{x.value||'—'}<b>{x.n}</b></button>)}</div>)}
    <p className="rail-section">Dates</p><input type="date" aria-label="From" value={f.from||''} onChange={e=>setFilter('from',e.target.value)}/><input type="date" aria-label="To" value={f.to||''} onChange={e=>setFilter('to',e.target.value)}/>
    <p className="rail-section">Person</p><PersonSelect value={f.person||null} onChange={x=>setFilter('person',x||'')}/>
    <p className="rail-section">File type</p><select aria-label="File type" value={f.fileType||''} onChange={e=>setFilter('fileType',e.target.value)}><option value="">Any</option><option value="pdf">PDF</option><option value="word">Word</option><option value="sheet">Spreadsheet</option><option value="presentation">Presentation</option><option value="image">Image</option><option value="audio">Audio</option><option value="video">Video</option></select>
    {Object.keys(f).length>0&&<button className="link small" onClick={()=>setF({...preset})}>Clear filters</button>}</aside>
   <div className="kn-results">{!data?<Skeleton rows={6}/>:!data.results.length?<Empty icon="Search" title={query?'Nothing you can access matches':'Search company knowledge'}>{query?'Try other words or fewer filters.':'Documents, recordings, pages, decisions, meetings, projects, purchasing and connected sources.'}</Empty>:<>
    <p className="muted small">{data.total} result{data.total===1?'':'s'}{data.semantic?' · keyword and semantic search':' · keyword search'}</p>
    {data.results.map(r=><article key={r.id} className="kn-result"><div className="row-gap"><Icon name={KIND_ICON[r.kind]||'FileText'} size={16}/><a href={r.url} className="kn-title">{r.title}</a>{r.verified&&<Chip tone="green">verified</Chip>}{r.aiGenerated&&<Chip tone="violet">AI-generated</Chip>}{r.stale&&<Chip tone="amber">review due</Chip>}{r.classification!=='internal'&&<Chip tone="red">{r.classification}</Chip>}</div>
     <p className="small">{r.summary||r.excerpt}</p>{r.summary&&r.excerpt&&<p className="small muted kn-excerpt">…{r.excerpt}…</p>}
     {r.citations.length>0&&<ul className="small kn-cites">{r.citations.map((c,i)=><li key={i}>{c.text} <span className="muted">“{c.quote}”</span></li>)}</ul>}
     <p className="small muted">{r.kind} · {r.owner||'—'} · {r.modified?ago(r.modified):''}{r.topics.length?` · ${r.topics.join(', ')}`:''} · <a href={`#/knowledge/item/${r.id}`}>details</a>{r.related.length>0&&<> · related: {r.related.map(x=><a key={x.id} href={x.url} className="chip chip-gray">{x.title}</a>)}</>}</p></article>)}
    {data.total>data.size&&<div className="row-gap"><Btn size="sm" disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</Btn><span className="muted small">Page {page}</span><Btn size="sm" disabled={page*data.size>=data.total} onClick={()=>setPage(page+1)}>Next</Btn></div>}</>}</div></div>
 </div>;
}
function Item({id}:{id:string}){
 const {toast}=useApp();const {data,error,reload}=useApi<{item:{id:string,title:string,source_type:string,source_id:string,url:string,status:string,stage:string,last_error:string,kind:string,summary:string,classification:string,retention_class:string,verified:number,next_review_at:string|null,expires_at:string|null,cost_micros:number,processed_at:string|null,duplicate_of:string|null,detail:{keyPoints?:{text:string,quote:string}[],decisions?:{text:string,quote:string}[],actionItems?:{text:string,owner?:string,due?:string,quote:string}[],dates?:{date:string,what:string,quote:string}[],risks?:{text:string,quote:string}[],obligations?:{text:string,quote:string}[],detailed?:string,notes?:string[]},topics:{name:string}[],tags:string[],entities:{people?:{id:string,name:string}[],departments?:string[],projects?:{id:string,code:string}[],vendors?:{id:string,name:string}[],assets?:{id:string,code:string}[]},lineage:Record<string,unknown>},jobs:{stage:string,status:string,detail:string,cost:number,attempt:number,createdAt:string}[],suggestions:{id:string,kind:string,payload:{title?:string},status:string}[],canManage:boolean}>(`/api/knowledge?view=item&id=${id}`);
 if(error)return <div className="page"><ErrorNote error={error}/></div>;if(!data)return <div className="page"><Skeleton/></div>;const k=data.item;const d=k.detail;
 return <div className="page"><Header icon={KIND_ICON[k.kind]||'FileText'} tone="violet" title={k.title} subtitle={<span className="row-gap"><Chip tone={k.status==='ready'?'green':k.status==='partial'?'amber':['failed','removed','expired'].includes(k.status)?'red':'gray'}>{k.status}</Chip><span>{k.kind} · {k.classification}{k.retention_class?` · retention: ${k.retention_class}`:''}</span></span>} actions={<><Btn icon="ExternalLink" onClick={()=>{location.hash=k.url}}>Open source</Btn>{data.canManage&&<Btn icon="RefreshCw" onClick={async()=>{await api('/api/knowledge',{action:'reprocess',id:k.id});toast('Reprocessing queued');reload()}}>Reprocess</Btn>}</>}/>
  {k.last_error&&<Note tone={k.status==='failed'?'warn':'info'}>{k.last_error}</Note>}{k.duplicate_of&&<Note>An identical copy already exists in knowledge.</Note>}
  <div className="cards-2"><Card title="Summary"><p>{k.summary||'No summary.'}</p>{d.detailed&&<details><summary className="small">Detailed notes</summary><Markdown text={d.detailed}/></details>}</Card>
   <Card title="Pipeline"><ol className="kn-pipeline">{data.jobs.slice().reverse().map((j,i)=><li key={i} className={cx(j.status)}><b>{j.stage.replace(/_/g,' ')}</b> <Chip tone={j.status==='done'||j.status==='ready'?'green':j.status==='failed'?'red':j.status==='skipped'?'gray':'amber'}>{j.status}</Chip><small className="muted"> {j.detail}{j.cost?` · cost ${(j.cost/1e6).toFixed(4)}`:''} · {ago(j.createdAt)}</small></li>)}</ol><p className="small muted">Next review {k.next_review_at?dateOnly(k.next_review_at):'—'}{k.expires_at?` · expires ${dateOnly(k.expires_at)}`:''} · {k.verified?'verified by a person':'not yet verified'}</p></Card></div>
  <div className="cards-2"><List title="Key points" items={d.keyPoints}/><List title="Decisions" items={d.decisions}/><List title="Action items" items={d.actionItems}/><List title="Important dates" items={d.dates}/><List title="Risks" items={d.risks}/><List title="Obligations" items={d.obligations}/></div>
  <Card title="Entities and topics"><p className="small">{(k.entities.people||[]).map(p=><a key={p.id} className="chip chip-gray" href={`#/people/directory/${p.id}`}>{p.name}</a>)}{(k.entities.projects||[]).map(p=><a key={p.id} className="chip chip-gray" href={`#/projects/${p.id}`}>{p.code}</a>)}{(k.entities.vendors||[]).map(v=><span key={v.id} className="chip chip-gray">{v.name}</span>)}{(k.entities.assets||[]).map(a=><a key={a.id} className="chip chip-gray" href={`#/assets/${a.id}`}>{a.code}</a>)}{(k.entities.departments||[]).map(x=><span key={x} className="chip chip-gray">{x}</span>)}</p><p className="small">Topics: {k.topics.map(t=>t.name).join(', ')||'—'} · Suggested tags: {k.tags.join(', ')||'—'}</p></Card>
  {(d.notes||[]).length>0&&<Note>{(d.notes||[]).join(' · ')}</Note>}
  {data.suggestions.length>0&&<Card title="AI suggestions from this item"><ul className="small">{data.suggestions.map(s2=><li key={s2.id}>{s2.kind.replace('_',' ')}: {s2.payload.title||''} <Chip tone={s2.status==='pending'?'amber':s2.status==='accepted'?'green':'gray'}>{s2.status}</Chip></li>)}</ul><Btn size="sm" onClick={()=>go('knowledge/suggestions')}>Review suggestions</Btn></Card>}
 </div>;
}
// Extracted facts, each shown with the quote it was grounded on.
function List({title,items}:{title:string,items?:{text?:string,what?:string,date?:string,owner?:string,due?:string,quote:string}[]}){return items&&items.length?<Card title={title}><ul className="small">{items.map((x,i)=><li key={i}>{x.date?`${x.date}: `:''}{x.text||x.what}{x.owner?` — ${x.owner}`:''}{x.due?` (due ${x.due})`:''}{x.quote&&<span className="muted"> “{x.quote}”</span>}</li>)}</ul></Card>:null}
function Decisions(){
 const [status,setStatus]=useState('');const [q,setQ]=useState('');const {data,error,reload}=useApi<{decisions:{id:string,number:string,title:string,status:string,date:string|null,reviewDate:string|null,decisionMaker:string|null,affects:number,evidence:number,superseded:boolean}[]}>(`/api/knowledge?view=decisions&status=${encodeURIComponent(status)}&q=${encodeURIComponent(q)}`);const {person}=useApp();
 return <div className="page"><Header icon="Gavel" tone="violet" title="Decision Register" subtitle="What was decided, why, by whom, on what evidence, what it affected, and whether it was implemented or changed." actions={<Btn variant="primary" icon="Plus" onClick={()=>go('knowledge/decisions/new')}>Record a decision</Btn>}/>
  <div className="toolbar"><input type="search" placeholder="Search decisions…" value={q} onChange={e=>setQ(e.target.value)} aria-label="Search"/><select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['Proposed','Under review','Approved','Rejected','Implemented','Superseded','Expired'].map(x=><option key={x}>{x}</option>)}</select></div>
  <ErrorNote error={error} onRetry={reload}/>{!data?<Skeleton/>:!data.decisions.length?<Empty icon="Gavel" title="No decisions recorded"/>:<table className="plain"><thead><tr><th>Decision</th><th>Status</th><th>Date</th><th>Decision maker</th><th>Affects</th><th>Evidence</th><th>Review</th></tr></thead><tbody>{data.decisions.map(d=><tr key={d.id} className="clickable" onClick={()=>go(`knowledge/decisions/${d.id}`)}><td><b>{d.number}</b> · {d.title}{d.superseded&&<Chip tone="gray">superseded</Chip>}</td><td><Chip tone={/Approved|Implemented/.test(d.status)?'green':/Rejected|Expired/.test(d.status)?'red':'amber'}>{d.status}</Chip></td><td>{d.date?dateOnly(d.date):'—'}</td><td>{person(d.decisionMaker)?.name||''}</td><td>{d.affects}</td><td>{d.evidence}</td><td>{d.reviewDate?dateOnly(d.reviewDate):''}</td></tr>)}</tbody></table>}</div>;
}
function Decision({id}:{id:string}){
 const {toast,s,ask}=useApp();const {data,error,reload}=useApi<{decision:{id:string,number:string,title:string,status:string,description:string,decision:string,rationale:string,alternatives:string,decisionMaker:{id:string,name:string}|null,participants:{id:string,name:string}[],date:string|null,effectiveDate:string|null,reviewDate:string|null,impactedDepartments:string,risks:string,meetingId:string|null},answers:{why:string,whoApproved:string,evidence:{title:string,url:string}[],affectedWork:{type:string,title:string,url:string}[],implemented:string,laterChanged:string|{by:string,id:string}},supersedes:{id:string,title:string}[],history:{action:string,at:string,who:string}[],versions:{version:number,at:string,by:string}[],restricted:number}>(`/api/knowledge?view=decision&id=${id}`);
 if(error)return <div className="page"><ErrorNote error={error}/></div>;if(!data)return <div className="page"><Skeleton/></div>;const d=data.decision;const a=data.answers;
 const post=async(action:string,extra:Record<string,unknown>,msg:string)=>{try{await api('/api/knowledge',{action,id:d.id,...extra});toast(msg);reload()}catch(e){toast((e as Error).message,'error')}};
 const maker=d.decisionMaker?.id===s.user.id||s.user.role==='admin';
 return <div className="page"><Header icon="Gavel" tone="violet" title={<>{d.number} · {d.title}</>} subtitle={<span className="row-gap"><Chip tone={/Approved|Implemented/.test(d.status)?'green':/Rejected|Expired/.test(d.status)?'red':'amber'}>{d.status}</Chip>{d.date&&<span>Decided {dateOnly(d.date)}</span>}{d.effectiveDate&&<span>· effective {dateOnly(d.effectiveDate)}</span>}</span>}
  actions={<><Btn icon="Pencil" onClick={()=>go(`knowledge/decisions/${d.id}/edit`)}>Edit</Btn>{['Proposed','Under review'].includes(d.status)&&maker&&<><Btn variant="primary" onClick={()=>post('decide-decision',{approve:true},'Approved')}>Approve</Btn><Btn onClick={async()=>{const c=await ask({title:'Reject decision',input:{label:'Reason',required:true},confirm:'Reject',danger:true});if(c)post('decide-decision',{approve:false,comment:c},'Rejected')}}>Reject</Btn></>}{d.status==='Proposed'&&<Btn onClick={()=>post('decision-status',{status:'Under review'},'Sent for review')}>Send for review</Btn>}{d.status==='Approved'&&<Btn onClick={()=>post('decision-status',{status:'Implemented'},'Marked implemented')}>Mark implemented</Btn>}</>}/>
  <div className="cards-2"><Card title="The decision"><p><b>{d.decision||d.description||'—'}</b></p><dl className="kv-list"><dt>Rationale</dt><dd>{d.rationale||'—'}</dd><dt>Alternatives considered</dt><dd className="pre">{d.alternatives||'—'}</dd><dt>Risks</dt><dd>{d.risks||'—'}</dd><dt>Impacted departments</dt><dd>{d.impactedDepartments||'—'}</dd><dt>Decision maker</dt><dd>{d.decisionMaker?.name||'—'}</dd><dt>Participants</dt><dd>{d.participants.map(p=>p.name).join(', ')||'—'}</dd>{d.meetingId&&<><dt>Meeting</dt><dd><a href={`#/knowledge/meetings/${d.meetingId}`}>Open meeting</a></dd></>}<dt>Review / expiry</dt><dd>{d.reviewDate?dateOnly(d.reviewDate):'—'}</dd></dl></Card>
   <Card title="Answers"><dl className="kv-list"><dt>Why was it made?</dt><dd>{a.why}</dd><dt>Who approved it?</dt><dd>{a.whoApproved}</dd><dt>What evidence supported it?</dt><dd>{a.evidence.length?a.evidence.map((e,i)=><a key={i} className="chip chip-gray" href={e.url}>{e.title}</a>):'No evidence linked'}</dd><dt>Which work was affected?</dt><dd>{a.affectedWork.length?a.affectedWork.map((w,i)=><a key={i} className="chip chip-gray" href={w.url}>{w.type}: {w.title}</a>):'None linked'}</dd><dt>Was it implemented?</dt><dd>{a.implemented}</dd><dt>Was it later changed?</dt><dd>{typeof a.laterChanged==='string'?a.laterChanged:<a href={`#/knowledge/decisions/${a.laterChanged.id}`}>Superseded by {a.laterChanged.by}</a>}</dd></dl>{data.supersedes.length>0&&<p className="small">Supersedes: {data.supersedes.map(x=><a key={x.id} href={`#/knowledge/decisions/${x.id}`}>{x.title}</a>)}</p>}{data.restricted>0&&<p className="muted small"><Icon name="Lock" size={12}/> {data.restricted} connected record(s) are restricted.</p>}</Card></div>
  <ConnectedContext type="decision" id={d.id} title="Connected work"/>
  <Card title="History"><ol className="timeline">{data.history.map((h,i)=><li key={i}><span className="dot"/><div><b>{h.action}</b><small>{h.who} · {ago(h.at)}</small></div></li>)}</ol></Card>
 </div>;
}
function Meetings(){
 const {data,error}=useApi<{meetings:{id:string,number:string,title:string,status:string,date:string|null,recordings:number,documents:number,decisions:number}[]}>('/api/knowledge?view=meetings');
 return <div className="page"><Header icon="CalendarClock" tone="violet" title="Meetings" subtitle="Recordings are transcribed and summarised; suggested decisions and actions wait for a person to approve them." actions={<Btn variant="primary" icon="Plus" onClick={()=>go('knowledge/meetings/new')}>New meeting</Btn>}/><ErrorNote error={error}/>
  {!data?<Skeleton/>:!data.meetings.length?<Empty icon="CalendarClock" title="No meetings yet"/>:<table className="plain"><thead><tr><th>Meeting</th><th>Date</th><th>Status</th><th>Recordings</th><th>Documents</th><th>Decisions</th></tr></thead><tbody>{data.meetings.map(m=><tr key={m.id} className="clickable" onClick={()=>go(`knowledge/meetings/${m.id}`)}><td><b>{m.number}</b> · {m.title}</td><td>{m.date?dateOnly(m.date):'—'}</td><td>{m.status}</td><td>{m.recordings}</td><td>{m.documents}</td><td>{m.decisions}</td></tr>)}</tbody></table>}</div>;
}
function Meeting({id}:{id:string}){
 const {toast}=useApp();const rec=useApi<{record:{id:string,number:string,title:string,status:string,startDate:string|null,description:string,data:Record<string,unknown>}}>(`/api/business?id=${id}`);
 const sugg=useApi<{suggestions:{id:string,kind:string,payload:{title?:string,sourceId?:string},citations:{quote:string}[],source:{title:string,url:string}}[]}>('/api/knowledge?view=suggestions');const [up,setUp]=useState(false);
 if(rec.error)return <div className="page"><ErrorNote error={rec.error}/></div>;if(!rec.data)return <div className="page"><Skeleton/></div>;const m=rec.data.record;
 const upload=async(file:File)=>{setUp(true);try{const fd=new FormData();fd.set('file',file);const r=await fetch('/api/files',{method:'POST',body:fd});const j=await r.json() as {id?:string,files?:{id:string}[],error?:string};if(!r.ok)throw new Error(j.error||'Upload failed');const fid=j.id||j.files?.[0]?.id;if(fid)await api('/api/files',{action:'link',id:fid,entityType:'work_record',entityId:m.id});toast('Uploaded — it will be transcribed and summarised');rec.reload()}catch(e){toast((e as Error).message,'error')}finally{setUp(false)}};
 return <div className="page"><Header icon="CalendarClock" tone="violet" title={<>{m.number} · {m.title}</>} subtitle={`${m.status}${m.startDate?` · ${dateOnly(m.startDate)}`:''}`} actions={<><label className={cx('btn',up&&'busy')}><Icon name="Upload" size={15}/>Upload recording or document<input type="file" hidden accept="audio/*,video/*,.pdf,.docx,.txt,.md" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/></label><Btn icon="Gavel" onClick={()=>go(`knowledge/decisions/new?parent=${m.id}`)}>Record decision</Btn></>}/>
  {m.description&&<Card title="Notes"><p>{m.description}</p></Card>}
  <Card title="Suggested decisions and actions (approve to add to the register and create tasks)">{!sugg.data?<Skeleton rows={3}/>:<SuggestionList items={sugg.data.suggestions} onDone={()=>{sugg.reload();rec.reload()}}/>}</Card>
  <ConnectedContext type="meeting" id={m.id} title="Recordings, decisions, projects and people"/>
 </div>;
}
function SuggestionList({items,onDone}:{items:{id:string,kind:string,payload:Record<string,unknown>&{title?:string},citations:{quote:string}[],source:{title:string,url:string}}[],onDone:()=>void}){
 const {toast}=useApp();const [assign,setAssign]=useState<Record<string,string|null>>({});
 if(!items.length)return <p className="muted small">Nothing waiting for review.</p>;
 const decide=async(id:string,approve:boolean)=>{try{await api('/api/knowledge',{action:approve?'suggestion-accept':'suggestion-reject',id,edits:assign[id]?{assigneeId:assign[id]}:{}});toast(approve?'Accepted':'Rejected');onDone()}catch(e){toast((e as Error).message,'error')}};
 return <ul className="approval-list">{items.map(x=><li key={x.id}><div className="row-gap"><Chip tone="violet">{x.kind==='action_item'?'Action item':x.kind==='decision'?'Decision':'Relationship'}</Chip><b>{String(x.payload.title||'')}</b></div>
  <small className="muted">From <a href={x.source.url}>{x.source.title}</a>{x.citations[0]?.quote?` — “${x.citations[0].quote}”`:''}{x.payload.ownerName?` · owner mentioned: ${x.payload.ownerName}`:''}{x.payload.dueText?` · due: ${x.payload.dueText}`:''}</small>
  {x.kind==='action_item'&&<Field label="Assign to"><PersonSelect value={assign[x.id]??(x.payload.assigneeId as string|null)??null} onChange={v=>setAssign({...assign,[x.id]:v})}/></Field>}
  <div className="row-gap"><Btn size="sm" variant="primary" icon="Check" onClick={()=>decide(x.id,true)}>Approve</Btn><Btn size="sm" icon="X" onClick={()=>decide(x.id,false)}>Reject</Btn></div></li>)}</ul>;
}
function Suggestions(){const {data,error,reload}=useApi<{suggestions:{id:string,kind:string,payload:Record<string,unknown>,citations:{quote:string}[],source:{title:string,url:string}}[]}>('/api/knowledge?view=suggestions');
 return <div className="page"><Header icon="Sparkles" tone="violet" title="AI suggestions" subtitle="Decisions, action items and relationships found in your content. Nothing is created until a person approves it."/><ErrorNote error={error} onRetry={reload}/>{!data?<Skeleton/>:<SuggestionList items={data.suggestions as never} onDone={reload}/>}</div>}
const stateTone=(s:string)=>s==='Verified answer'?'green':s==='Expert answer'?'sky':s==='AI-generated answer'?'violet':s==='Unanswered'?'amber':'gray';
function Questions(){
 const {toast}=useApp();const [status,setStatus]=useState('');const {data,error,reload}=useApi<{questions:{id:string,title:string,status:string,state:string,department:string,created_at:string}[]}>(`/api/knowledge?view=questions&status=${status}`);const [q,setQ]=useState({title:'',body:''});
 return <div className="page"><Header icon="MessageCircleQuestion" tone="violet" title="Questions & answers" subtitle="Ask the company. Answers are labelled as verified, expert, AI-generated or unanswered, with their sources."/>
  <Card title="Ask a question"><Field label="Question" wide><input value={q.title} onChange={e=>setQ({...q,title:e.target.value})}/></Field><Field label="Details" wide><textarea rows={2} value={q.body} onChange={e=>setQ({...q,body:e.target.value})}/></Field><Btn variant="primary" disabled={q.title.trim().length<5} onClick={async()=>{try{const r=await api<{id:string}>('/api/knowledge',{action:'ask',...q});go(`knowledge/questions/${r.id}`)}catch(e){toast((e as Error).message,'error')}}}>Ask</Btn></Card>
  <div className="toolbar"><select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option><option value="unanswered">Unanswered</option><option value="answered">Answered</option><option value="verified">Verified</option><option value="escalated">Escalated</option></select></div>
  <ErrorNote error={error} onRetry={reload}/>{data&&<ul className="mini-list">{data.questions.map(x=><li key={x.id} className="mini-row"><a href={`#/knowledge/questions/${x.id}`}>{x.title}</a><Chip tone={stateTone(x.state)}>{x.state}</Chip><small className="muted">{x.department} · {ago(x.created_at)}</small></li>)}</ul>}</div>;
}
function Question({id}:{id:string}){
 const {toast,ask,s}=useApp();const {data,error,reload}=useApi<{question:{id:string,title:string,body:string,status:string,state:string,asker:string,department:string,article_id:string|null},answers:{id:string,kind:string,label:string,body:string,citations:{n:number,title:string,url:string}[],hiddenCitations:number,confidence:number|null,author:string,status:string,helpful:number,notHelpful:number,corrections:{text?:string}[],createdAt:string}[],canVerify:boolean,canAccept:boolean}>(`/api/knowledge?view=question&id=${id}`);const [body,setBody]=useState('');const [busy,setBusy]=useState('');
 if(error)return <div className="page"><ErrorNote error={error}/></div>;if(!data)return <div className="page"><Skeleton/></div>;const q=data.question;
 const op=async(o:string,extra:Record<string,unknown>={},msg='Done')=>{setBusy(o);try{await api('/api/knowledge',{action:'question',id:q.id,op:o,...extra});toast(msg);reload()}catch(e){toast((e as Error).message,'error')}finally{setBusy('')}};
 return <div className="page"><Header icon="MessageCircleQuestion" tone="violet" title={q.title} subtitle={<span className="row-gap"><Chip tone={stateTone(q.state)}>{q.state}</Chip><span>{q.asker} · {q.department}</span></span>}
  actions={<><Btn icon="Sparkles" busy={busy==='ai'} onClick={async()=>{setBusy('ai');try{await api('/api/knowledge',{action:'ai-answer',id:q.id});toast('AI answer drafted with citations');reload()}catch(e){toast((e as Error).message,'error')}finally{setBusy('')}}}>AI answer</Btn><Btn icon="TrendingUp" onClick={async()=>{const d=await ask({title:'Escalate to a department',input:{label:'Department',required:true},confirm:'Escalate'});if(d)op('escalate',{department:d},'Escalated')}}>Escalate</Btn>{q.status!=='unanswered'&&!q.article_id&&<Btn icon="BookPlus" onClick={()=>op('convert',{},'Draft article created in Spaces')}>Convert to article</Btn>}{q.article_id&&<Btn icon="BookOpen" onClick={()=>go(`spaces/page/${q.article_id}`)}>Article</Btn>}</>}/>
  {q.body&&<Card><p>{q.body}</p></Card>}
  {data.answers.map(a=><Card key={a.id} title={<span className="row-gap"><Chip tone={a.label==='Verified answer'?'green':a.kind==='ai'?'violet':a.kind==='expert'?'sky':'gray'}>{a.label}</Chip><small className="muted">{a.author} · {ago(a.createdAt)}{a.confidence!=null?` · confidence ${Math.round(a.confidence*100)}%`:''}</small></span>}
   actions={<>{data.canAccept&&a.status!=='accepted'&&<Btn size="sm" onClick={()=>op('accept',{answerId:a.id},'Accepted')}>Accept</Btn>}{data.canVerify&&!(a.label==='Verified answer')&&<Btn size="sm" variant="primary" onClick={()=>op('verify',{answerId:a.id},'Verified')}>Verify</Btn>}</>}>
   <Markdown text={a.body}/>{a.citations.length>0&&<p className="small">Sources: {a.citations.map(c=><a key={c.n} className="chip chip-gray" href={c.url}>[{c.n}] {c.title}</a>)}</p>}{a.hiddenCitations>0&&<p className="muted small">{a.hiddenCitations} source(s) are not visible to you.</p>}
   <div className="row-gap small"><button className="link" onClick={()=>op('feedback',{answerId:a.id,helpful:true},'Thanks')}>Helpful ({a.helpful})</button><button className="link" onClick={()=>op('feedback',{answerId:a.id,helpful:false},'Thanks')}>Not helpful ({a.notHelpful})</button><button className="link" onClick={async()=>{const t=await ask({title:'Request a correction',input:{label:'What is wrong?',required:true,multiline:true},confirm:'Send'});if(t)op('correction',{answerId:a.id,text:t},'Correction requested')}}>Request correction</button>{a.corrections.filter(c=>c.text).length>0&&<span className="muted">{a.corrections.filter(c=>c.text).length} correction request(s)</span>}</div></Card>)}
  {!data.answers.length&&<Empty icon="MessageCircleQuestion" title="Unanswered">Ask AI for a cited draft, answer as an expert, or escalate to a department.</Empty>}
  <Card title="Your answer"><textarea rows={4} value={body} onChange={e=>setBody(e.target.value)} aria-label="Answer"/><Btn variant="primary" disabled={!body.trim()} onClick={async()=>{try{await api('/api/knowledge',{action:'answer',id:q.id,body});setBody('');toast('Answer posted');reload()}catch(e){toast((e as Error).message,'error')}}}>Post answer</Btn>{s.user.role!=='admin'&&<small className="muted"> Posted as an expert answer if you are a subject-matter expert.</small>}</Card>
 </div>;
}
function Reviews({focus}:{focus?:string}){
 const {toast,s}=useApp();const [all,setAll]=useState(false);const {data,error,reload}=useApi<{reviews:{id:string,reason:string,detail:string,status:string,due_at:string|null,outcome:string,created_at:string,item:{id:string,title:string,url:string,kind:string}|null}[]}>(`/api/knowledge?view=reviews${all?'&all=1':''}`);
 const complete=async(id:string,outcome:string)=>{try{await api('/api/knowledge',{action:'review-complete',id,outcome});toast('Review recorded');reload()}catch(e){toast((e as Error).message,'error')}};
 return <div className="page"><Header icon="ClipboardCheck" tone="violet" title="Knowledge reviews" subtitle="Stale, expiring, conflicting, broken or unverified knowledge assigned to its owner." actions={s.user.role==='admin'&&<><label className="check"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>All reviews</label><Btn size="sm" onClick={async()=>{const r=await api<{created:number}>('/api/knowledge',{action:'freshness'});toast(`${r.created} review(s) created`);reload()}}>Run freshness check</Btn></>}/>
  <ErrorNote error={error} onRetry={reload}/>{!data?<Skeleton/>:!data.reviews.length?<Empty icon="ClipboardCheck" title="No reviews"/>:<ul className="approval-list">{data.reviews.map(r=><li key={r.id} className={cx(focus===r.id&&'focus')}><div className="row-gap"><Chip tone={r.status==='open'?'amber':'green'}>{r.reason.replace(/_/g,' ')}</Chip>{r.item?<a href={r.item.url}>{r.item.title}</a>:'Knowledge item'}<small className="muted">{r.detail}{r.due_at?` · due ${dateOnly(r.due_at)}`:''}</small></div>{r.status==='open'?<div className="row-gap"><Btn size="sm" variant="primary" onClick={()=>complete(r.id,'still_accurate')}>Still accurate</Btn><Btn size="sm" onClick={()=>complete(r.id,'updated')}>I updated it</Btn><Btn size="sm" onClick={()=>complete(r.id,'archived')}>Archive</Btn>{r.item&&<Btn size="sm" variant="ghost" onClick={()=>go(`knowledge/item/${r.item!.id}`)}>Details</Btn>}</div>:<small className="muted">{r.outcome}</small>}</li>)}</ul>}</div>;
}
function Topics(){const {data,error}=useApi<{topics:{id:string,kind:string,name:string,definition:string,synonyms:string[],count:number}[]}>('/api/knowledge?view=topics');
 return <div className="page"><Header icon="Tags" tone="violet" title="Topics" subtitle="The company taxonomy, with how much visible knowledge each topic covers."/><ErrorNote error={error}/>{!data?<Skeleton/>:!data.topics.length?<Empty icon="Tags" title="No topics yet">Administrators manage the taxonomy under Admin → Knowledge.</Empty>:<div className="module-grid">{data.topics.map(t=><a key={t.id} className="module-card" href={`#/knowledge/search?topic=${t.id}`}><Icon name="Tag" size={16}/><div><b>{t.name}</b><small>{t.definition||t.kind}</small><small className="muted">{t.count} item(s){t.synonyms.length?` · ${t.synonyms.join(', ')}`:''}</small></div></a>)}</div>}</div>}

// ── Administration (Admin → Knowledge) ──
export function KnowledgeAdmin({tab='sources'}:{tab?:string}){
 return <div className="page"><Header icon="Brain" tone="gray" title="Knowledge administration" subtitle="Processing pipeline, taxonomy and retention for the company’s knowledge."/>
  <Tabs value={tab} onChange={t=>go(`admin/knowledge/${t}`)} items={[{id:'sources',label:'Sources & pipeline'},{id:'taxonomy',label:'Taxonomy'},{id:'retention',label:'Retention'}]}/>
  {tab==='sources'&&<SourcesAdmin/>}{tab==='taxonomy'&&<TaxonomyAdmin/>}{tab==='retention'&&<RetentionAdmin/>}</div>;
}
function SourcesAdmin(){
 const {toast}=useApp();const {data,error,reload}=useApi<{byStatus:{status:string,n:number}[],byType:{type:string,n:number,cost:number}[],recent:{id:string,title:string,type:string,status:string,stage:string,error:string,attempts:number,cost:number,updatedAt:string}[],failed:{id:string,title:string,type:string,status:string,error:string,attempts:number,updatedAt:string}[],states:string[],jobs:{kind:string,status:string,n:number}[]}>('/api/knowledge?view=sources');
 return <><div className="row-gap"><Btn icon="RefreshCw" onClick={async()=>{await api('/api/knowledge',{action:'rebuild'});toast('Rebuild queued');reload()}}>Re-register all sources</Btn><Btn onClick={async()=>{const r=await api<{created:number}>('/api/knowledge',{action:'freshness'});toast(`${r.created} review(s) created`)}}>Run freshness check</Btn></div><ErrorNote error={error} onRetry={reload}/>
  {!data?<Skeleton/>:<><div className="cards-2"><Card title="By state">{data.byStatus.map(s=><p key={s.status} className="small">{s.status}: <b>{s.n}</b></p>)}</Card><Card title="By source (processing cost)">{data.byType.map(s=><p key={s.type} className="small">{s.type}: <b>{s.n}</b> · cost {((s.cost||0)/1e6).toFixed(4)}</p>)}</Card></div>
   <Card title="Needs attention (failed, retrying, unsupported, partial)"><table className="plain small"><tbody>{data.failed.map(f=><tr key={f.id}><td><a href={`#/knowledge/item/${f.id}`}>{f.title}</a></td><td>{f.type}</td><td><Chip tone={f.status==='failed'?'red':'amber'}>{f.status}</Chip></td><td>{f.error}</td><td>{f.attempts}</td><td><Btn size="sm" onClick={async()=>{try{await api('/api/knowledge',{action:'reprocess',id:f.id});toast('Queued');reload()}catch(e){toast((e as Error).message,'error')}}}>Retry</Btn></td></tr>)}</tbody></table>{!data.failed.length&&<p className="muted small">Nothing failing.</p>}</Card>
   <Card title="Recent"><table className="plain small"><tbody>{data.recent.slice(0,60).map(f=><tr key={f.id}><td><a href={`#/knowledge/item/${f.id}`}>{f.title}</a></td><td>{f.type}</td><td>{f.status}</td><td>{f.stage}</td><td className="muted">{ago(f.updatedAt)}</td></tr>)}</tbody></table></Card></>}</>;
}
function TaxonomyAdmin(){
 const {toast}=useApp();const {data,error,reload}=useApi<{items:{id:string,kind:string,name:string,definition:string,synonyms:string[],retentionDays:number|null,status:string,origin:string}[],kinds:string[],canManage:boolean,suggestions:{id:string,payload:string}[]}>('/api/knowledge?view=taxonomy');const [v,setV]=useState({kind:'topic',name:'',definition:'',synonyms:''});
 return <><ErrorNote error={error} onRetry={reload}/><Card title="Add an entry"><div className="row-gap wrap"><select aria-label="Type" value={v.kind} onChange={e=>setV({...v,kind:e.target.value})}>{(data?.kinds||[]).map(k=><option key={k}>{k}</option>)}</select><input placeholder="Name" value={v.name} onChange={e=>setV({...v,name:e.target.value})} aria-label="Name"/><input placeholder="Definition" value={v.definition} onChange={e=>setV({...v,definition:e.target.value})} aria-label="Definition"/><input placeholder="Synonyms (comma separated)" value={v.synonyms} onChange={e=>setV({...v,synonyms:e.target.value})} aria-label="Synonyms"/><Btn variant="primary" disabled={!v.name} onClick={async()=>{try{await api('/api/knowledge',{action:'taxonomy-save',...v,synonyms:v.synonyms.split(',').map(x=>x.trim()).filter(Boolean)});toast('Saved');setV({...v,name:'',definition:'',synonyms:''});reload()}catch(e){toast((e as Error).message,'error')}}}>Add</Btn></div></Card>
  {data&&data.suggestions.length>0&&<Card title="AI tag suggestions (need approval)"><ul className="mini-list">{data.suggestions.map(s=><li key={s.id} className="mini-row"><span>{String(JSON.parse(s.payload||'{}').name||'')}</span><Btn size="sm" onClick={async()=>{await api('/api/knowledge',{action:'suggestion-accept',id:s.id});reload()}}>Approve</Btn><Btn size="sm" variant="ghost" onClick={async()=>{await api('/api/knowledge',{action:'suggestion-reject',id:s.id});reload()}}>Reject</Btn></li>)}</ul></Card>}
  {!data?<Skeleton/>:<table className="plain"><thead><tr><th>Type</th><th>Name</th><th>Definition</th><th>Synonyms</th><th>Status</th><th/></tr></thead><tbody>{data.items.map(t=><tr key={t.id}><td>{t.kind}</td><td>{t.name}</td><td className="small">{t.definition}</td><td className="small">{t.synonyms.join(', ')}</td><td><Chip tone={t.status==='active'?'green':t.status==='proposed'?'amber':'gray'}>{t.status}</Chip>{t.origin==='ai'&&<Chip tone="violet">AI</Chip>}</td><td>{data.canManage&&(t.status==='proposed'?<Btn size="sm" onClick={async()=>{await api('/api/knowledge',{action:'taxonomy-approve',id:t.id});reload()}}>Approve</Btn>:t.status==='active'&&<Btn size="sm" variant="ghost" onClick={async()=>{await api('/api/knowledge',{action:'taxonomy-retire',id:t.id});reload()}}>Retire</Btn>)}</td></tr>)}</tbody></table>}</>;
}
function RetentionAdmin(){
 const {toast}=useApp();const {data,error,reload}=useApi<{classes:{id:string,name:string,definition:string,retentionDays:number|null,status:string}[],expired:{id:string,title:string,retentionClass:string,expiresAt:string}[],removed:{id:string,title:string,type:string,removedAt:string}[]}>('/api/knowledge?view=retention');const [v,setV]=useState({name:'',definition:'',retentionDays:'365'});
 return <><ErrorNote error={error} onRetry={reload}/><Card title="Retention classes"><Note>Knowledge whose topic or kind matches a retention class expires after the period and is no longer served; the source record stays in its module.</Note><div className="row-gap wrap"><input placeholder="Name (e.g. policy, contract, record)" value={v.name} onChange={e=>setV({...v,name:e.target.value})} aria-label="Name"/><input placeholder="Definition" value={v.definition} onChange={e=>setV({...v,definition:e.target.value})} aria-label="Definition"/><input type="number" value={v.retentionDays} onChange={e=>setV({...v,retentionDays:e.target.value})} aria-label="Days"/><Btn variant="primary" disabled={!v.name} onClick={async()=>{try{await api('/api/knowledge',{action:'retention-save',...v,retentionDays:Number(v.retentionDays)});toast('Saved');reload()}catch(e){toast((e as Error).message,'error')}}}>Add class</Btn></div>
  {data&&<table className="plain small"><tbody>{data.classes.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.definition}</td><td>{c.retentionDays} days</td><td>{c.status}</td></tr>)}</tbody></table>}</Card>
  {data&&<div className="cards-2"><Card title="Expired (no longer served)">{data.expired.map(x=><p key={x.id} className="small">{x.title} · {x.retentionClass} · {dateOnly(x.expiresAt)}</p>)}</Card><Card title="Removed with their source">{data.removed.map(x=><p key={x.id} className="small">{x.title} · {x.type} · {ago(x.removedAt)}</p>)}</Card></div>}</>;
}
