'use client';
import {useEffect,useState} from 'react';
import {api,useApi,go,ago,cx,dateOnly,money} from './lib';
import {useApp,Btn,Chip,Header,Field,ErrorNote,Skeleton,Empty,Icon,Modal,Card,PersonSelect,DeptSelect,Tabs,Note,TagPicker} from './kit';
import {ConnectedContext} from './context';

// Request-to-outcome lifecycle: a business need traced through approval, project, budget, purchasing,
// receipt, assets or services, measurement and the outcome review. Every figure comes from linked records.
type ReqRow={id:string,number:string,title:string,type:string,typeLabel:string,status:string,stage:string,requesterId:string,department:string,estimatedCost:number,currency:string,priority:string,requiredDate:string|null,updatedAt:string};
type Stage={id:string,stage_key:string,name:string,position:number,required:number,status:string,owner_id:string|null,due_at:string|null,started_at:string|null,completed_at:string|null,completed_by:string|null,outcome:string,linked_type:string|null,linked_id:string|null};
type Approval={id:string,stageKey:string,stage:number,name:string,mode:string,quorum:number,approverIds:string[],decisions:{by:string,for?:string|null,decision:string,comment:string,at:string}[],status:string,createdAt:string};
type Fin={proposed:number,budget:number,contingency:number,requested:number,committed:number,ordered:number,received:number,invoiced:number,paid:number,expenses:number,labour:number,actual:number,forecast:number,remaining:number,variance:number,method:string,events?:{id:string,event_type:string,measure:string,amount:number,currency:string,source_type:string,source_id:string,memo:string,occurred_at:string}[]};
type Trace={request:Record<string,unknown>&{id:string,number:string,title:string,description:string,request_type:string,requester_id:string,department:string,location:string,business_need:string,expected_outcome:string,estimated_cost:number,currency:string,priority:string,risk:string,required_date:string|null,goal_id:string|null,project_id:string|null,budget_id:string|null,status:string,current_stage:string,version:number,files_json:string,visibility:string,stages_json:string},stages:Stage[],approvals:Approval[],businessCase:(Record<string,unknown>&{problem:string,solution:string,alternatives_json:string,benefits:string,costs_json:string,assumptions:string,risks:string,dependencies:string,impacted_departments_json:string,approach:string,annual_benefit:number|null,status:string,version:number,figures:{totalCost:number,capex:number,opex:number,annualBenefit:number|null,horizonYears:number,netBenefit:number|null,roiPct:number|null,paybackMonths:number|null,formulas:Record<string,string>,missing:string[]}})|null,goal:{id:string,kind:string,number:string,title:string,status:string,progress:number}|null,project:{id:string,code:string,name:string,stage:string,health:string,progress:number,targetDate:string|null}|null,budget:{id:string,name:string,amount:number,currency:string,status:string,contingency:number,fundingSource:string}|null,documents:{id:string,kind:string,number:string,title:string,status:string,total:number,currency:string,pr_id:string|null,approvals:{step:string,status:string,decidedBy:string|null,decidedAt:string|null,comment:string}[]}[],quotations:{id:string,docId:string,amount:number,currency:string,selected:number,vendor:string}[],receipts:{id:string,poId:string,number:string,kind:string,linesJson:string,acceptance:string,receivedBy:string,createdAt:string}[],invoices:{id:string,poId:string,number:string,vendorInvoiceNo:string,amount:number,tax:number,currency:string,status:string,matchJson:string,paid:number}[],assets:{id:string,code:string,name:string,status:string,location:string,assigned_to:string|null,warranty_until:string|null,purchase_cost:number}[],services:{id:string,number:string,title:string,status:string,rating:number|null}[],benefits:{id:string,name:string,kind:string,measure:string,unit:string,baseline:number,expected:number,actual:number|null,variance:number|null,realisedPct:number|null,ownerId:string|null,reviewDate:string|null,keyResultId:string|null,measurements:{value:number,measured_at:string,note:string}[]}[],reviews:{id:string,title:string,status:string,review_date:string|null,owner_id:string|null,outcome_status:string,lessons_learned:string,results_json:string}[],finance:Fin|null,files:{id:string,name:string,entity_type:string}[],timeline:{action:string,created_at:string,who:string|null,record_id:string}[],exceptions:string[],restricted:number,canEdit:boolean,canSubmit:boolean,canManage:boolean,awaitingMe:boolean,requestTypeLabel:string};
const STATUS_TONE=(s:string)=>/completed|closed|approved|accepted|renewed|done|matched|paid/i.test(s)?'green':/rejected|withdrawn|exception|disposed/i.test(s)?'red':/changes|pending|progress|active|draft|delivered/i.test(s)?'amber':'gray';
export const lifecycleViews=[{id:'all',label:'All requests',icon:'Route'},{id:'mine',label:'My requests',icon:'UserCheck'},{id:'open',label:'In progress',icon:'Loader'},{id:'closed',label:'Closed',icon:'Archive'},{id:'services',label:'Services',icon:'Handshake',section:'Delivery'},{id:'templates',label:'Lifecycle templates',icon:'Workflow',section:'Setup'}];

export default function Lifecycle({parts=[]}:{parts?:string[]}){
 const p0=parts[0]||'all';
 if(p0==='new')return <NewRequest/>;
 if(p0==='templates')return <Templates/>;
 if(p0==='services')return parts[1]?<Service id={parts[1]}/>:<Services/>;
 if(p0==='trace')return <TraceFrom type={parts[1]} id={parts[2]}/>;
 if(['all','mine','open','closed'].includes(p0))return <RequestList filter={p0}/>;
 return <RequestPage id={p0} tab={parts[1]||'overview'}/>;
}
function RequestList({filter}:{filter:string}){
 const [q,setQ]=useState('');const {data,error,reload}=useApi<{requests:ReqRow[],canCreate:boolean}>(`/api/lifecycle?filter=${filter}&q=${encodeURIComponent(q)}`);const {person}=useApp();
 return <div className="page"><Header icon="Route" tone="violet" title="Business requests" subtitle="From need to outcome: each request is traced through approval, delivery, purchasing, assets and the benefits review." actions={data?.canCreate&&<Btn variant="primary" icon="Plus" onClick={()=>go('lifecycle/new')}>New request</Btn>}/>
  <ErrorNote error={error} onRetry={reload}/><div className="toolbar"><input type="search" placeholder="Search requests…" value={q} onChange={e=>setQ(e.target.value)} aria-label="Search"/></div>
  {!data?<Skeleton/>:!data.requests.length?<Empty icon="Route" title="No requests yet" action={data.canCreate&&<Btn variant="primary" icon="Plus" onClick={()=>go('lifecycle/new')}>Raise a request</Btn>}>Capital, operational, procurement, IT, asset, service, maintenance, staffing, contract requests and improvement ideas.</Empty>:
   <div className="lb-table"><table className="plain"><thead><tr><th>Request</th><th>Type</th><th>Stage</th><th>Status</th><th>Estimated</th><th>Requester</th><th>Updated</th></tr></thead><tbody>{data.requests.map(r=><tr key={r.id} className="clickable" onClick={()=>go(`lifecycle/${r.id}`)}><td><a href={`#/lifecycle/${r.id}`}><b>{r.number}</b> · {r.title}</a></td><td>{r.typeLabel}</td><td>{r.stage||'—'}</td><td><Chip tone={STATUS_TONE(r.status)}>{r.status}</Chip></td><td>{r.estimatedCost?`${r.currency} ${r.estimatedCost.toLocaleString()}`:'—'}</td><td>{person(r.requesterId)?.name||''}</td><td className="muted">{ago(r.updatedAt)}</td></tr>)}</tbody></table></div>}
 </div>;
}
function NewRequest(){
 const {s,toast}=useApp();const tpl=useApi<{templates:{id:string,name:string,requestTypes:string[],stages:{name:string}[]}[],requestTypes:{id:string,label:string}[]}>('/api/lifecycle?view=templates');
 const goals=useApi<{records:{id:string,kind:string,number:string,title:string}[]}>('/api/business');
 const [v,setV]=useState({title:'',description:'',requestType:'capex',department:s.user.department,location:'',businessNeed:'',expectedOutcome:'',estimatedCost:'',currency:s.tenant.currency,priority:'Medium',risk:'Medium',requiredDate:'',goalId:'',templateId:'',visibility:'department'});const [busy,setBusy]=useState('');
 const matching=(tpl.data?.templates||[]).filter(t=>t.requestTypes.includes(v.requestType));const chosen=(tpl.data?.templates||[]).find(t=>t.id===v.templateId)||matching[0];
 const save=async(submit:boolean)=>{setBusy(submit?'submit':'save');try{const r=await api<{id:string}>('/api/lifecycle',{action:'create',...v,estimatedCost:v.estimatedCost===''?0:Number(v.estimatedCost),goalId:v.goalId||null,templateId:v.templateId||undefined,requiredDate:v.requiredDate||null,submit});toast(submit?'Submitted':'Saved as draft');go(`lifecycle/${r.id}`)}catch(e){toast((e as Error).message,'error')}finally{setBusy('')}};
 return <div className="page"><Header icon="FilePlus2" tone="violet" title="New business request" actions={<><Btn variant="ghost" onClick={()=>history.back()}>Cancel</Btn><Btn busy={busy==='save'} disabled={!v.title.trim()} onClick={()=>save(false)}>Save draft</Btn><Btn variant="primary" busy={busy==='submit'} disabled={!v.title.trim()} onClick={()=>save(true)}>Submit</Btn></>}/>
  <Card><div className="form-grid">
   <Field label="Title" wide><input autoFocus value={v.title} onChange={e=>setV({...v,title:e.target.value})}/></Field>
   <Field label="Request type"><select value={v.requestType} onChange={e=>setV({...v,requestType:e.target.value,templateId:''})}>{(tpl.data?.requestTypes||[]).map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></Field>
   <Field label="Lifecycle" hint={chosen?chosen.stages.map(x=>x.name).join(' → '):''}><select value={v.templateId} onChange={e=>setV({...v,templateId:e.target.value})}><option value="">{matching[0]?`Default: ${matching[0].name}`:'Default'}</option>{(tpl.data?.templates||[]).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field>
   <Field label="Business need" wide><textarea rows={3} value={v.businessNeed} onChange={e=>setV({...v,businessNeed:e.target.value})}/></Field>
   <Field label="Expected outcome" wide><textarea rows={2} value={v.expectedOutcome} onChange={e=>setV({...v,expectedOutcome:e.target.value})}/></Field>
   <Field label="Description" wide><textarea rows={2} value={v.description} onChange={e=>setV({...v,description:e.target.value})}/></Field>
   <Field label="Department"><DeptSelect value={v.department} onChange={x=>setV({...v,department:x})}/></Field><Field label="Location"><input value={v.location} onChange={e=>setV({...v,location:e.target.value})}/></Field>
   <Field label={`Estimated cost`}><input type="number" min="0" step="0.01" value={v.estimatedCost} onChange={e=>setV({...v,estimatedCost:e.target.value})}/></Field><Field label="Currency"><input value={v.currency} onChange={e=>setV({...v,currency:e.target.value.toUpperCase()})}/></Field>
   <Field label="Priority"><select value={v.priority} onChange={e=>setV({...v,priority:e.target.value})}>{['Low','Medium','High','Critical'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Risk"><select value={v.risk} onChange={e=>setV({...v,risk:e.target.value})}>{['Low','Medium','High'].map(x=><option key={x}>{x}</option>)}</select></Field>
   <Field label="Required by"><input type="date" value={v.requiredDate} onChange={e=>setV({...v,requiredDate:e.target.value})}/></Field>
   <Field label="Contributes to (goal, objective or initiative)"><select value={v.goalId} onChange={e=>setV({...v,goalId:e.target.value})}><option value="">None</option>{(goals.data?.records||[]).filter(g=>['goal','objective','key_result','initiative','programme'].includes(g.kind)).map(g=><option key={g.id} value={g.id}>{g.number} · {g.title}</option>)}</select></Field>
   <Field label="Who can see it"><select value={v.visibility} onChange={e=>setV({...v,visibility:e.target.value})}><option value="department">My department (and approvers)</option><option value="company">Everyone with access</option><option value="private">Only me, approvers and administrators</option></select></Field>
  </div></Card></div>;
}
function Stepper({stages}:{stages:Stage[]}){
 return <ol className="lc-steps">{stages.map(s=><li key={s.id} className={cx('lc-step',s.status)} title={`${s.name}: ${s.status}${s.outcome?` — ${s.outcome}`:''}`}><span className="lc-dot">{s.status==='done'?<Icon name="Check" size={12}/>:s.status==='skipped'?<Icon name="Minus" size={12}/>:s.status==='rejected'?<Icon name="X" size={12}/>:s.position+1}</span><span className="lc-name">{s.name}</span>{!s.required&&<small className="muted">optional</small>}</li>)}</ol>;
}
function RequestPage({id,tab}:{id:string,tab:string}){
 const {toast,person,s,ask}=useApp();const {data,error,reload}=useApi<Trace>(`/api/lifecycle?id=${encodeURIComponent(id)}`);const [busy,setBusy]=useState('');
 if(error)return <div className="page"><ErrorNote error={error} onRetry={reload}/></div>;if(!data)return <div className="page"><Skeleton rows={10}/></div>;
 const r=data.request;const active=data.stages.find(x=>x.status==='active');const defs=JSON.parse(r.stages_json||'[]') as {key:string,kind:string,required:boolean,name:string}[];const activeDef=active?defs.find(d=>d.key===active.stage_key):null;
 const act=async(action:string,extra:Record<string,unknown>={},msg='Done')=>{setBusy(action);try{await api('/api/lifecycle',{action,id:r.id,...extra});toast(msg);reload()}catch(e){toast((e as Error).message,'error')}finally{setBusy('')}};
 const pending=data.approvals.filter(a=>a.status==='pending');
 const tabs=[{id:'overview',label:'Overview'},{id:'case',label:'Business case'},{id:'procurement',label:'Procurement & finance',count:data.documents.length},{id:'assets',label:'Assets & services',count:data.assets.length+data.services.length},{id:'outcome',label:'Benefits & outcome',count:data.benefits.length},{id:'trace',label:'Traceability'},{id:'activity',label:'Activity',count:data.timeline.length}];
 return <div className="page"><Header icon="Route" tone="violet" title={<>{r.number} · {r.title}</>} subtitle={<span className="row-gap wrap"><Chip tone={STATUS_TONE(r.status)}>{r.status}</Chip><span>{data.requestTypeLabel}</span><span>· {person(r.requester_id)?.name}</span><span>· {r.department}</span>{r.estimated_cost?<span>· {r.currency} {r.estimated_cost.toLocaleString()}</span>:null}</span>}
  actions={<>{data.canSubmit&&<Btn variant="primary" icon="Send" busy={busy==='submit'} onClick={()=>act('submit',{},'Submitted')}>{r.status==='Changes requested'?'Resubmit':'Submit'}</Btn>}{r.requester_id===s.user.id&&!['Closed','Completed','Rejected','Withdrawn','Renewed','Disposed'].includes(r.status)&&<Btn variant="ghost" onClick={async()=>{if(await ask({title:'Withdraw this request?',confirm:'Withdraw',danger:true})!==false)act('withdraw',{},'Withdrawn')}}>Withdraw</Btn>}</>}/>
  <Stepper stages={data.stages}/>
  {data.exceptions.length>0&&<Note tone="warn">{data.exceptions.join(' · ')}</Note>}
  {data.restricted>0&&<p className="muted small"><Icon name="Lock" size={12}/> {data.restricted} linked record(s) are outside your access and not shown.</p>}
  <Tabs value={tab} onChange={t=>go(`lifecycle/${r.id}/${t}`)} items={tabs}/>
  {tab==='overview'&&<>
   {pending.map(a=><ApprovalCard key={a.id} a={a} request={r.id} onDone={reload} requesterId={r.requester_id}/>)}
   {active&&activeDef&&activeDef.kind!=='approval'&&<Card title={`Current stage: ${active.name}`} actions={<Chip tone="amber">{active.owner_id?`Owner: ${person(active.owner_id)?.name||''}`:'Unassigned'}</Chip>}>
    <StageHelp kind={activeDef.kind}/>
    <div className="row-gap wrap">
     {activeDef.kind==='project'&&!r.project_id&&<Btn icon="FolderPlus" busy={busy==='create-project'} onClick={()=>act('create-project',{},'Project created and linked')}>Create project from request</Btn>}
     {activeDef.kind==='budget'&&!r.budget_id&&<Btn icon="PiggyBank" busy={busy==='create-budget'} onClick={async()=>{const amt=await ask({title:'Create budget',input:{label:`Amount (${r.currency})`,type:'number',required:true},confirm:'Create'});if(amt)act('create-budget',{amount:Number(amt)},'Budget created and linked')}}>Create budget</Btn>}
     {['requisition','rfq','quotations'].includes(activeDef.kind)&&<Btn icon="ClipboardList" busy={busy==='create-requisition'} onClick={()=>act('create-requisition',{submit:true},'Requisition raised and submitted')}>Raise requisition from business case</Btn>}
     {activeDef.kind==='goal'&&<LinkGoal onPick={g=>act('link',{kind:'goal',recordId:g},'Linked to goal')}/>}
     {activeDef.kind==='service'&&<Btn icon="Handshake" onClick={()=>go(`lifecycle/services/new?request=${r.id}`)}>Set up service delivery</Btn>}
     {activeDef.kind==='measurement'&&<Btn icon="Gauge" onClick={()=>go(`lifecycle/${r.id}/outcome`)}>Record benefit measurements</Btn>}
     {activeDef.kind==='outcome'&&<Btn icon="ClipboardCheck" onClick={()=>go(`lifecycle/${r.id}/outcome`)}>Outcome review</Btn>}
     {['intake','business_case','review','custom','closure','deployment','asset','receipt','order','evaluation'].includes(activeDef.kind)&&<Btn variant="primary" icon="CircleCheck" busy={busy==='complete-stage'} onClick={async()=>{const o=await ask({title:`Complete “${active.name}”`,input:{label:activeDef.kind==='closure'?'Outcome (e.g. Closed, Renewed, Disposed)':'Outcome / notes'},confirm:'Complete'});if(o!==false)act('complete-stage',{stage:active.stage_key,outcome:o||'Completed'},'Stage completed')}}>Complete stage</Btn>}
     {!activeDef.required&&<Btn variant="ghost" busy={busy==='skip-stage'} onClick={async()=>{const why=await ask({title:`Skip “${active.name}”?`,input:{label:'Reason',required:true},confirm:'Skip'});if(why)act('skip-stage',{stage:active.stage_key,reason:why},'Stage skipped')}}>Skip (optional stage)</Btn>}
    </div></Card>}
   <div className="cards-3">
    <Card title="Request"><dl className="kv-list"><dt>Business need</dt><dd>{r.business_need||'—'}</dd><dt>Expected outcome</dt><dd>{r.expected_outcome||'—'}</dd><dt>Priority / risk</dt><dd>{r.priority} / {r.risk}</dd><dt>Required by</dt><dd>{r.required_date?dateOnly(r.required_date):'—'}</dd></dl></Card>
    <Card title="Linked work">{data.goal&&<p><Icon name="Target" size={14}/> <a href={`#/strategy/item/${data.goal.id}`}>{data.goal.number} · {data.goal.title}</a> <small className="muted">{data.goal.progress}%</small></p>}{data.project&&<p><Icon name="FolderKanban" size={14}/> <a href={`#/projects/${data.project.id}`}>{data.project.code} · {data.project.name}</a> <small className="muted">{data.project.stage} · {data.project.progress}%</small></p>}{data.budget&&<p><Icon name="PiggyBank" size={14}/> {data.budget.name} · {data.budget.currency} {data.budget.amount.toLocaleString()}</p>}{!data.goal&&!data.project&&!data.budget&&<p className="muted small">Nothing linked yet.</p>}
     {data.canManage&&!data.goal&&<LinkGoal onPick={g=>act('link',{kind:'goal',recordId:g},'Linked to goal')}/>}</Card>
    {data.finance&&<Card title="Money"><FinanceMini f={data.finance} currency={r.currency}/></Card>}
   </div>
   {data.canEdit&&<EditRequest r={r} onSaved={reload}/>}
  </>}
  {tab==='case'&&<BusinessCase t={data} onSaved={reload}/>}
  {tab==='procurement'&&<Procurement t={data} request={r.id}/>}
  {tab==='assets'&&<AssetsServices t={data}/>}
  {tab==='outcome'&&<Outcome t={data} onChanged={reload}/>}
  {tab==='trace'&&<><Card title="Traceability chain"><TraceChain t={data}/></Card><ConnectedContext type="request" id={r.id} title="Work Graph: everything connected to this request"/></>}
  {tab==='activity'&&<ol className="timeline">{data.timeline.map((h,i)=><li key={i}><span className="dot"/><div><b>{h.action}</b><small>{h.who||'System'} · {ago(h.created_at)}</small></div></li>)}</ol>}
 </div>;
}
function StageHelp({kind}:{kind:string}){const help:Record<string,string>={project:'Completes automatically when a project is linked.',budget:'Completes when an active budget is linked.',requisition:'Completes when a linked requisition is approved.',rfq:'Completes when quotations are recorded on the requisition.',quotations:'Completes when the required number of vendor quotations are recorded.',evaluation:'Completes when a winning quotation is selected.',order:'Completes when a linked purchase order is issued.',receipt:'Completes when every linked order is fully received.',asset:'Completes when receipts have created asset records.',deployment:'Completes when every asset is assigned or in use.',service:'Completes when the service is accepted.',measurement:'Completes when every benefit has a measurement.',outcome:'Completes when the outcome review is completed.',goal:'Completes when the request is linked to a goal.'};return help[kind]?<p className="muted small">{help[kind]}</p>:null}
function ApprovalCard({a,request,onDone,requesterId}:{a:Approval,request:string,onDone:()=>void,requesterId:string}){
 const {person,s,toast}=useApp();const [comment,setComment]=useState('');const [busy,setBusy]=useState('');
 const decide=async(decision:string)=>{setBusy(decision);try{await api('/api/lifecycle',{action:'decide',id:request,approvalId:a.id,decision,comment});toast('Decision recorded');onDone()}catch(e){toast((e as Error).message,'error')}finally{setBusy('')}};
 const mine=a.approverIds.includes(s.user.id)&&s.user.id!==requesterId;
 return <Card title={`Approval: ${a.name}`} actions={<Chip tone="amber">{a.mode==='all'?'Everyone must approve':a.mode==='quorum'?`${a.quorum} approvals needed`:'Any one approver'}</Chip>}>
  <p className="small">Approvers: {a.approverIds.map(x=>person(x)?.name||'Someone').join(', ')||'—'}</p>
  {a.decisions.map((d,i)=><p key={i} className="small">{person(d.by)?.name}{d.for?` (for ${person(d.for)?.name})`:''}: {d.decision} {d.comment&&`— “${d.comment}”`} · {ago(d.at)}</p>)}
  {(mine||s.user.role==='admin')?<><Field label="Comment"><textarea rows={2} value={comment} onChange={e=>setComment(e.target.value)}/></Field><div className="row-gap"><Btn variant="primary" icon="Check" busy={busy==='approve'} onClick={()=>decide('approve')}>Approve</Btn><Btn icon="Undo2" busy={busy==='changes'} disabled={!comment.trim()} onClick={()=>decide('changes')}>Request changes</Btn><Btn icon="X" busy={busy==='reject'} disabled={!comment.trim()} onClick={()=>decide('reject')}>Reject</Btn></div></>:<p className="muted small">Waiting for the approvers. Delegates covering them can decide from their inbox.</p>}
 </Card>;
}
function LinkGoal({onPick}:{onPick:(id:string)=>void}){const {data}=useApi<{records:{id:string,kind:string,number:string,title:string}[]}>('/api/business');const [v,setV]=useState('');
 return <div className="row-gap"><select aria-label="Goal" value={v} onChange={e=>setV(e.target.value)}><option value="">Link to a goal or initiative…</option>{(data?.records||[]).filter(g=>['goal','objective','key_result','initiative','programme'].includes(g.kind)).map(g=><option key={g.id} value={g.id}>{g.number} · {g.title}</option>)}</select><Btn size="sm" disabled={!v} onClick={()=>onPick(v)}>Link</Btn></div>}
function EditRequest({r,onSaved}:{r:Trace['request'],onSaved:()=>void}){
 const {toast}=useApp();const [open,setOpen]=useState(false);const [v,setV]=useState({title:r.title,description:r.description,businessNeed:r.business_need,expectedOutcome:r.expected_outcome,estimatedCost:String(r.estimated_cost||''),requiredDate:r.required_date||'',priority:r.priority,risk:r.risk});
 if(!open)return <Btn icon="Pencil" onClick={()=>setOpen(true)}>Edit request</Btn>;
 return <Card title="Edit request"><div className="form-grid"><Field label="Title" wide><input value={v.title} onChange={e=>setV({...v,title:e.target.value})}/></Field><Field label="Business need" wide><textarea rows={3} value={v.businessNeed} onChange={e=>setV({...v,businessNeed:e.target.value})}/></Field><Field label="Expected outcome" wide><textarea rows={2} value={v.expectedOutcome} onChange={e=>setV({...v,expectedOutcome:e.target.value})}/></Field><Field label="Estimated cost"><input type="number" value={v.estimatedCost} onChange={e=>setV({...v,estimatedCost:e.target.value})}/></Field><Field label="Required by"><input type="date" value={v.requiredDate} onChange={e=>setV({...v,requiredDate:e.target.value})}/></Field></div>
  <div className="row-gap"><Btn variant="primary" onClick={async()=>{try{await api('/api/lifecycle',{action:'update',id:r.id,version:r.version,...v,estimatedCost:v.estimatedCost===''?0:Number(v.estimatedCost),requiredDate:v.requiredDate||null});toast('Saved');setOpen(false);onSaved()}catch(e){toast((e as Error).message,'error')}}}>Save</Btn><Btn variant="ghost" onClick={()=>setOpen(false)}>Cancel</Btn></div></Card>;
}
function FinanceMini({f,currency}:{f:Fin,currency:string}){const m=(n:number)=>`${currency} ${n.toLocaleString(undefined,{maximumFractionDigits:2})}`;
 return <dl className="kv-list fin"><dt>Proposed</dt><dd>{m(f.proposed)}</dd><dt>Approved budget</dt><dd>{m(f.budget)}</dd><dt>Committed</dt><dd>{m(f.committed)}</dd><dt>Actual</dt><dd>{m(f.actual)}</dd><dt>Forecast</dt><dd>{m(f.forecast)}</dd><dt>Remaining</dt><dd className={cx(f.remaining<0&&'overdue')}>{m(f.remaining)}</dd><dt>Variance</dt><dd className={cx(f.variance<0&&'overdue')}>{m(f.variance)}</dd></dl>}
function BusinessCase({t,onSaved}:{t:Trace,onSaved:()=>void}){
 const {toast,s}=useApp();const c=t.businessCase;const [v,setV]=useState(()=>({problem:c?.problem||'',solution:c?.solution||'',benefits:c?.benefits||'',assumptions:c?.assumptions||'',risks:c?.risks||'',dependencies:c?.dependencies||'',approach:c?.approach||'',annualBenefit:c?.annual_benefit==null?'':String(c.annual_benefit),costs:JSON.parse(c?.costs_json||'[]') as {label:string,amount:number,kind:string}[],alternatives:JSON.parse(c?.alternatives_json||'[]') as {option:string,reason:string,cost:number|null}[],impactedDepartments:JSON.parse(c?.impacted_departments_json||'[]') as string[]}));
 const f=c?.figures;const editable=t.canManage;
 const save=async()=>{try{await api('/api/lifecycle',{action:'case-save',id:t.request.id,version:c?.version,...v,annualBenefit:v.annualBenefit===''?null:Number(v.annualBenefit)});toast('Business case saved');onSaved()}catch(e){toast((e as Error).message,'error')}};
 return <div className="cards-2"><Card title="Business case" actions={editable&&<Btn size="sm" variant="primary" onClick={save}>Save</Btn>}><div className="form-grid">
  {([['problem','Problem statement'],['solution','Proposed solution'],['benefits','Benefits'],['assumptions','Financial assumptions'],['risks','Risks'],['dependencies','Dependencies'],['approach','Implementation approach']] as const).map(([k,l])=><Field key={k} label={l} wide><textarea rows={2} disabled={!editable} value={v[k]} onChange={e=>setV({...v,[k]:e.target.value})}/></Field>)}
  <Field label="Impacted departments" wide><TagPicker values={v.impactedDepartments} options={s.departments.map(d=>d.name)} onChange={x=>setV({...v,impactedDepartments:x})} placeholder="Choose departments"/></Field>
  <Field label="Expected annual benefit" hint="Used for return and payback; leave empty if not financial."><input type="number" disabled={!editable} value={v.annualBenefit} onChange={e=>setV({...v,annualBenefit:e.target.value})}/></Field>
  <Field label="Costs" wide>{v.costs.map((x,i)=><div key={i} className="row-gap"><input aria-label="Cost" value={x.label} onChange={e=>setV({...v,costs:v.costs.map((y,j)=>j===i?{...y,label:e.target.value}:y)})}/><input aria-label="Amount" type="number" value={x.amount} onChange={e=>setV({...v,costs:v.costs.map((y,j)=>j===i?{...y,amount:Number(e.target.value)}:y)})}/><select aria-label="Kind" value={x.kind} onChange={e=>setV({...v,costs:v.costs.map((y,j)=>j===i?{...y,kind:e.target.value}:y)})}><option value="capex">Capital</option><option value="opex">Operating</option></select><Btn size="sm" variant="ghost" icon="X" title="Remove" onClick={()=>setV({...v,costs:v.costs.filter((_,j)=>j!==i)})}/></div>)}{editable&&<Btn size="sm" icon="Plus" onClick={()=>setV({...v,costs:[...v.costs,{label:'',amount:0,kind:'capex'}]})}>Add cost</Btn>}</Field>
  <Field label="Alternatives considered" wide>{v.alternatives.map((x,i)=><div key={i} className="row-gap"><input aria-label="Option" value={x.option} onChange={e=>setV({...v,alternatives:v.alternatives.map((y,j)=>j===i?{...y,option:e.target.value}:y)})}/><input aria-label="Why not" placeholder="Why not chosen" value={x.reason} onChange={e=>setV({...v,alternatives:v.alternatives.map((y,j)=>j===i?{...y,reason:e.target.value}:y)})}/><Btn size="sm" variant="ghost" icon="X" title="Remove" onClick={()=>setV({...v,alternatives:v.alternatives.filter((_,j)=>j!==i)})}/></div>)}{editable&&<Btn size="sm" icon="Plus" onClick={()=>setV({...v,alternatives:[...v.alternatives,{option:'',reason:'',cost:null}]})}>Add alternative</Btn>}</Field>
 </div></Card>
 <Card title="Calculated from the entries">{!f?<p className="muted small">Save the business case to see its figures.</p>:<><dl className="kv-list"><dt>Total cost</dt><dd>{money(f.totalCost)}</dd><dt>Capital / operating</dt><dd>{money(f.capex)} / {money(f.opex)}</dd><dt>Annual benefit</dt><dd>{f.annualBenefit==null?'—':money(f.annualBenefit)}</dd><dt>Net benefit ({f.horizonYears} years)</dt><dd>{f.netBenefit==null?'—':money(f.netBenefit)}</dd><dt>Return</dt><dd>{f.roiPct==null?'—':`${f.roiPct}%`}</dd><dt>Payback</dt><dd>{f.paybackMonths==null?'—':`${f.paybackMonths} months`}</dd></dl>
  <details className="small"><summary>How these are calculated</summary><ul>{Object.entries(f.formulas).map(([k,x])=><li key={k}><b>{k}</b>: {x}</li>)}</ul></details>{f.missing.length>0&&<Note tone="warn">Missing: {f.missing.join(', ')}</Note>}</>}
 </Card></div>;
}
function Procurement({t,request}:{t:Trace,request:string}){
 const [measure,setMeasure]=useState<string|null>(null);const src=useApi<{sources:{source_type:string,source_id:string,total:number}[]}>(measure?`/api/lifecycle?view=finance&request=${request}${t.request.project_id?`&project=${t.request.project_id}`:''}&measure=${measure}`:null);
 const f=t.finance;const cur=t.request.currency;const m=(n:number)=>`${cur} ${n.toLocaleString(undefined,{maximumFractionDigits:2})}`;const docNo=new Map(t.documents.map(d=>[d.id,d.number]));
 return <>{f&&<Card title="Financial summary (immutable ledger)"><div className="fin-grid">{(['proposed','budget','requested','committed','ordered','received','invoiced','paid','actual','forecast','remaining','variance'] as const).map(k=><button key={k} className={cx('fin-cell',measure===k&&'on',(k==='remaining'||k==='variance')&&f[k]<0&&'neg')} onClick={()=>setMeasure(['actual','forecast','remaining','variance'].includes(k)?null:k==='budget'?'budget':k)} title="Show the records behind this figure"><small>{k}</small><b>{m(f[k])}</b></button>)}</div>
  <p className="muted small">{f.method}</p>{measure&&<div className="mini-list">{!src.data?<Skeleton rows={2}/>:src.data.sources.map((x,i)=><div key={i} className="mini-row"><Chip tone="gray">{x.source_type}</Chip><span>{docNo.get(x.source_id)||x.source_id.slice(0,8)}</span><b>{m(x.total)}</b></div>)}</div>}
  <details className="small"><summary>Ledger events ({f.events?.length||0})</summary><table className="plain"><tbody>{(f.events||[]).slice(0,100).map(e=><tr key={e.id}><td>{dateOnly(e.occurred_at)}</td><td>{e.measure}</td><td>{e.amount>0?'+':''}{e.amount.toLocaleString()}</td><td>{e.source_type} {docNo.get(e.source_id)||''}</td><td className="muted">{e.memo}</td></tr>)}</tbody></table></details></Card>}
  <Card title="Requisitions and orders">{!t.documents.length?<p className="muted small">No requisitions or orders linked yet.</p>:<table className="plain"><thead><tr><th>Document</th><th>Status</th><th>Total</th><th>Approvals</th></tr></thead><tbody>{t.documents.map(d=><tr key={d.id}><td><a href={`#/purchasing/${d.kind.toLowerCase()}/${d.id}`}>{d.number}</a> {d.title}{d.pr_id&&<small className="muted"> (from {docNo.get(d.pr_id)||'requisition'})</small>}</td><td><Chip tone={STATUS_TONE(d.status)}>{d.status}</Chip></td><td>{d.currency} {d.total.toLocaleString()}</td><td className="small">{d.approvals.filter(a=>a.status==='Approved').map(a=>a.step).join(', ')||'—'}</td></tr>)}</tbody></table>}</Card>
  {t.quotations.length>0&&<Card title="Vendor quotations"><table className="plain"><tbody>{t.quotations.map(q=><tr key={q.id}><td>{q.vendor}</td><td>{q.currency} {q.amount.toLocaleString()}</td><td>{q.selected?<Chip tone="green">selected</Chip>:''}</td><td className="muted small">{docNo.get(q.docId)}</td></tr>)}</tbody></table></Card>}
  {t.receipts.length>0&&<Card title="Goods and service receipts"><table className="plain"><tbody>{t.receipts.map(g=><tr key={g.id}><td>{g.number}</td><td>{g.kind}</td><td className="small">{(JSON.parse(g.linesJson||'[]') as {description:string,qty:number}[]).map(l=>`${l.qty} × ${l.description}`).join('; ')}</td><td className="muted small">{ago(g.createdAt)}</td></tr>)}</tbody></table></Card>}
  {t.invoices.length>0&&<Card title="Invoices (three-way match)"><table className="plain"><tbody>{t.invoices.map(i=><tr key={i.id}><td>{i.number} ({i.vendorInvoiceNo})</td><td>{i.currency} {(i.amount+i.tax).toLocaleString()}</td><td><Chip tone={STATUS_TONE(i.status)}>{i.status}</Chip></td><td className="small">{(JSON.parse(i.matchJson||'{}') as {reasons?:string[]}).reasons?.join('; ')}</td><td>Paid {i.paid.toLocaleString()}</td></tr>)}</tbody></table></Card>}
 </>;
}
function AssetsServices({t}:{t:Trace}){const {person}=useApp();
 return <><Card title="Assets created from receipts">{!t.assets.length?<p className="muted small">No assets yet.</p>:<table className="plain"><thead><tr><th>Asset</th><th>Status</th><th>Location</th><th>Custodian</th><th>Warranty</th><th>Cost</th><th/></tr></thead><tbody>{t.assets.map(a=><tr key={a.id}><td><a href={`#/assets/${a.id}`}>{a.code}</a> {a.name}</td><td>{a.status}</td><td>{a.location}</td><td>{a.assigned_to?person(a.assigned_to)?.name:'—'}</td><td>{a.warranty_until?dateOnly(a.warranty_until):'—'}</td><td>{a.purchase_cost.toLocaleString()}</td><td><a className="link small" href={`#/lifecycle/trace/asset/${a.id}`}>Lineage</a></td></tr>)}</tbody></table>}</Card>
  <Card title="Services" actions={<Btn size="sm" icon="Plus" onClick={()=>go(`lifecycle/services/new?request=${t.request.id}`)}>New service</Btn>}>{!t.services.length?<p className="muted small">No services.</p>:<ul className="mini-list">{t.services.map(s=><li key={s.id} className="mini-row"><a href={`#/lifecycle/services/${s.id}`}>{s.number} · {s.title}</a><Chip tone={STATUS_TONE(s.status)}>{s.status}</Chip>{s.rating?<span>{'★'.repeat(s.rating)}</span>:null}</li>)}</ul>}</Card></>}
function Outcome({t,onChanged}:{t:Trace,onChanged:()=>void}){
 const {toast,person,ask}=useApp();const r=t.request;const [b,setB]=useState({name:'',kind:'operational',measure:'',unit:'',baseline:'',expected:'',reviewDate:'',keyResultId:''});const krs=useApi<{records:{id:string,kind:string,number:string,title:string}[]}>('/api/business?kind=key_result');
 const call=async(action:string,extra:Record<string,unknown>,msg:string)=>{try{await api('/api/lifecycle',{action,id:r.id,...extra});toast(msg);onChanged()}catch(e){toast((e as Error).message,'error')}};
 return <><Card title="Benefits">{t.benefits.length>0&&<table className="plain"><thead><tr><th>Benefit</th><th>Baseline</th><th>Expected</th><th>Actual</th><th>Variance</th><th>Realised</th><th/></tr></thead><tbody>{t.benefits.map(x=><tr key={x.id}><td>{x.name}<br/><small className="muted">{x.measure} · {person(x.ownerId)?.name||''}{x.keyResultId?' · feeds a key result':''}</small></td><td>{x.baseline} {x.unit}</td><td>{x.expected} {x.unit}</td><td>{x.actual??'—'}</td><td className={cx(x.variance!=null&&x.variance<0&&'overdue')}>{x.variance??'—'}</td><td>{x.realisedPct==null?'—':`${x.realisedPct}%`}</td><td><Btn size="sm" onClick={async()=>{const val=await ask({title:`Measure: ${x.name}`,input:{label:`Value (${x.unit||'number'})`,type:'number',required:true},confirm:'Record'});if(val)call('benefit-measure',{benefitId:x.id,value:Number(val)},'Measurement recorded')}}>Measure</Btn></td></tr>)}</tbody></table>}
  {t.canManage&&<div className="form-grid"><Field label="Benefit"><input value={b.name} onChange={e=>setB({...b,name:e.target.value})}/></Field><Field label="Type"><select value={b.kind} onChange={e=>setB({...b,kind:e.target.value})}>{['financial','operational','customer','compliance'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Success measure"><input value={b.measure} onChange={e=>setB({...b,measure:e.target.value})}/></Field><Field label="Unit"><input value={b.unit} onChange={e=>setB({...b,unit:e.target.value})}/></Field><Field label="Baseline"><input type="number" value={b.baseline} onChange={e=>setB({...b,baseline:e.target.value})}/></Field><Field label="Expected"><input type="number" value={b.expected} onChange={e=>setB({...b,expected:e.target.value})}/></Field><Field label="Review date"><input type="date" value={b.reviewDate} onChange={e=>setB({...b,reviewDate:e.target.value})}/></Field><Field label="Updates key result (optional)"><select value={b.keyResultId} onChange={e=>setB({...b,keyResultId:e.target.value})}><option value="">None</option>{(krs.data?.records||[]).map(k=><option key={k.id} value={k.id}>{k.number} · {k.title}</option>)}</select></Field>
   <Btn size="sm" icon="Plus" disabled={!b.name||b.expected===''} onClick={()=>call('benefit-add',{...b,baseline:b.baseline===''?0:Number(b.baseline),expected:Number(b.expected),reviewDate:b.reviewDate||null,keyResultId:b.keyResultId||null},'Benefit added')}>Add benefit</Btn></div>}</Card>
  <Card title="Outcome reviews" actions={t.canManage&&<Btn size="sm" icon="CalendarPlus" onClick={async()=>{const d=await ask({title:'Schedule outcome review',input:{label:'Review date',type:'date',required:true},confirm:'Schedule'});if(d)call('review-schedule',{reviewDate:d},'Review scheduled')}}>Schedule review</Btn>}>
   {!t.reviews.length?<p className="muted small">No outcome review yet.</p>:t.reviews.map(o=><ReviewBlock key={o.id} o={o} request={r.id} onDone={onChanged}/>)}</Card></>;
}
function ReviewBlock({o,request,onDone}:{o:Trace['reviews'][number],request:string,onDone:()=>void}){
 const {toast}=useApp();const [v,setV]=useState({outcomeStatus:'Achieved',lessonsLearned:'',feedback:'',financialResult:'',operationalResult:'',followUps:''});const res=o.results_json?JSON.parse(o.results_json) as {benefits?:{name:string,expected:number,actual:number|null,variance:number|null,realisedPct:number|null}[],finance?:{expectedCost:number,actualCost:number,committed:number,costVariance:number}|null,unmeasured?:string[]}:{};
 if(o.status==='Completed')return <div className="review-done"><p><b>{o.title}</b> <Chip tone="green">{o.outcome_status}</Chip></p>{res.benefits&&<table className="plain small"><thead><tr><th>Benefit</th><th>Expected</th><th>Actual</th><th>Variance</th></tr></thead><tbody>{res.benefits.map(x=><tr key={x.name}><td>{x.name}</td><td>{x.expected}</td><td>{x.actual??'not measured'}</td><td>{x.variance??'—'}</td></tr>)}</tbody></table>}{res.finance&&<p className="small">Expected cost {res.finance.expectedCost.toLocaleString()} · actual {res.finance.actualCost.toLocaleString()} · committed {res.finance.committed.toLocaleString()} · variance {res.finance.costVariance.toLocaleString()}</p>}{o.lessons_learned&&<p className="small"><b>Lessons:</b> {o.lessons_learned}</p>}</div>;
 return <div className="form-grid"><p className="field-wide"><b>{o.title}</b> · due {o.review_date?dateOnly(o.review_date):'—'}</p><Field label="Outcome"><select value={v.outcomeStatus} onChange={e=>setV({...v,outcomeStatus:e.target.value})}>{['Achieved','Partially achieved','Not achieved','Too early to tell'].map(x=><option key={x}>{x}</option>)}</select></Field>
  {([['lessonsLearned','Lessons learned'],['feedback','User feedback'],['financialResult','Financial result'],['operationalResult','Operational result'],['followUps','Follow-up actions (one per line → tasks)']] as const).map(([k,l])=><Field key={k} label={l} wide><textarea rows={2} value={v[k]} onChange={e=>setV({...v,[k]:e.target.value})}/></Field>)}
  <Btn variant="primary" onClick={async()=>{try{await api('/api/lifecycle',{action:'review-complete',id:request,reviewId:o.id,...v,followUps:v.followUps.split('\n').map(x=>x.trim()).filter(Boolean)});toast('Outcome review completed');onDone()}catch(e){toast((e as Error).message,'error')}}}>Complete review</Btn></div>;
}
function TraceChain({t}:{t:Trace}){
 const r=t.request;const step=(icon:string,label:string,body:React.ReactNode,ok:boolean)=><li className={cx('trace-step',ok&&'ok')}><Icon name={icon} size={16}/><div><b>{label}</b><div className="small">{body}</div></div></li>;
 const prs=t.documents.filter(d=>d.kind==='PR'),pos=t.documents.filter(d=>d.kind==='PO');
 return <ol className="trace-chain">
  {step('Lightbulb','Need',r.business_need||r.title,true)}
  {step('FileText','Request',`${r.number} · ${r.status}`,true)}
  {step('Scale','Business case',t.businessCase?`${t.businessCase.status} · total cost ${t.businessCase.figures.totalCost.toLocaleString()}`:'—',!!t.businessCase)}
  {step('Stamp','Approvals',t.approvals.map(a=>`${a.name}: ${a.status}`).join(' · ')||'—',t.approvals.some(a=>a.status==='approved'))}
  {step('Target','Goal',t.goal?<a href={`#/strategy/item/${t.goal.id}`}>{t.goal.title}</a>:'—',!!t.goal)}
  {step('FolderKanban','Project',t.project?<a href={`#/projects/${t.project.id}`}>{t.project.code} · {t.project.name}</a>:'—',!!t.project)}
  {step('PiggyBank','Budget',t.budget?`${t.budget.name} · ${t.budget.currency} ${t.budget.amount.toLocaleString()}`:'—',!!t.budget)}
  {step('ClipboardList','Requisitions',prs.map(d=>`${d.number} (${d.status})`).join(', ')||'—',prs.length>0)}
  {step('Users','Quotations',t.quotations.length?`${t.quotations.length} from ${new Set(t.quotations.map(q=>q.vendor)).size} vendors`:'—',t.quotations.length>0)}
  {step('FileText','Purchase orders',pos.map(d=>`${d.number} (${d.status})`).join(', ')||'—',pos.length>0)}
  {step('Truck','Receipts',t.receipts.map(g=>g.number).join(', ')||'—',t.receipts.length>0)}
  {step('Boxes','Assets',t.assets.map(a=>a.code).join(', ')||'—',t.assets.length>0)}
  {step('Handshake','Services',t.services.map(s=>`${s.number} (${s.status})`).join(', ')||'—',t.services.length>0)}
  {step('Gauge','Measurement',t.benefits.map(b=>`${b.name}: ${b.actual??'—'} / ${b.expected}`).join(' · ')||'—',t.benefits.some(b=>b.actual!=null))}
  {step('ClipboardCheck','Outcome review',t.reviews.map(o=>`${o.status}${o.outcome_status?` · ${o.outcome_status}`:''}`).join(', ')||'—',t.reviews.some(o=>o.status==='Completed'))}
  {step('Flag','Closure',r.status,['Closed','Completed','Renewed','Disposed'].includes(r.status))}
 </ol>;
}
function TraceFrom({type,id}:{type?:string,id?:string}){
 const {data,error}=useApi<{requestId:string|null,asset:AssetLineage|null}>(type&&id?`/api/lifecycle?view=trace&type=${encodeURIComponent(type)}&recordId=${encodeURIComponent(id)}`:null);
 useEffect(()=>{if(data?.requestId&&type!=='asset')go(`lifecycle/${data.requestId}/trace`)},[data,type]);
 if(error)return <div className="page"><ErrorNote error={error}/></div>;if(!data)return <div className="page"><Skeleton/></div>;
 if(data.asset)return <div className="page"><AssetLineageView a={data.asset}/></div>;
 return <div className="page"><Empty icon="Route" title="No business request is linked to this record"/></div>;
}
export type AssetLineage={asset:{id:string,code:string,name:string,status:string,location:string,department:string,custodian:{id:string,name:string}|null,purchaseCost:number,purchaseDate:string|null,warrantyUntil:string|null,warrantyDaysLeft:number|null},why:{request?:{id:string,number:string,title:string,businessNeed:string,expectedOutcome:string},justification?:string,requisition?:{id:string,number:string,title:string}}|null,budget:{id?:string,name?:string,restricted?:boolean}|null,approvals:{step:string,by:string,at:string|null,record?:string}[],vendor:{id:string,name:string}|null,order:{id:string,number:string,total:number,currency:string}|null,receipt:{number:string,receivedBy:string,at:string}|null,tickets:{id:string,number:string,title:string,status:string,created_at:string}[],maintenance:{id:string,number:string,title:string,status:string,parts_cost:number,labor_cost:number}[],lifetimeCost:number,maintenanceCost:number,ageMonths:number|null,recommendation:string,reasons:string[],requestId:string|null};
export function AssetLineageView({a}:{a:AssetLineage}){
 return <Card title={`Lineage: ${a.asset.code} · ${a.asset.name}`} actions={a.requestId&&<Btn size="sm" icon="Route" onClick={()=>go(`lifecycle/${a.requestId}/trace`)}>Open request</Btn>}>
  <div className="lineage-grid">
   <div><h4>Why it was purchased</h4><p className="small">{a.why?.request?<><a href={`#/lifecycle/${a.why.request.id}`}>{a.why.request.number} · {a.why.request.title}</a><br/>{a.why.request.businessNeed}</>:a.why?.justification||'No justification recorded.'}</p></div>
   <div><h4>Funding</h4><p className="small">{a.budget?.restricted?'A budget you cannot view':a.budget?.name||'No budget linked'}</p></div>
   <div><h4>Approved by</h4><ul className="small">{a.approvals.map((x,i)=><li key={i}>{x.by} — {x.step}{x.record?` (${x.record})`:''}{x.at?` · ${dateOnly(x.at)}`:''}</li>)}{!a.approvals.length&&<li className="muted">No approvals recorded</li>}</ul></div>
   <div><h4>Vendor & order</h4><p className="small">{a.vendor?.name||'—'}{a.order&&<> · <a href={`#/purchasing/po/${a.order.id}`}>{a.order.number}</a> ({a.order.currency} {a.order.total.toLocaleString()})</>}</p></div>
   <div><h4>Received</h4><p className="small">{a.receipt?`${a.receipt.number} by ${a.receipt.receivedBy} · ${dateOnly(a.receipt.at)}`:'—'}</p></div>
   <div><h4>Custody & location</h4><p className="small">{a.asset.custodian?.name||'Unassigned'} · {a.asset.location||'—'}</p></div>
   <div><h4>Warranty</h4><p className="small">{a.asset.warrantyUntil?`${dateOnly(a.asset.warrantyUntil)} (${a.asset.warrantyDaysLeft!<0?`expired ${-a.asset.warrantyDaysLeft!} days ago`:`${a.asset.warrantyDaysLeft} days left`})`:'None recorded'}</p></div>
   <div><h4>Lifetime cost</h4><p className="small">{a.lifetimeCost.toLocaleString()} (purchase {a.asset.purchaseCost.toLocaleString()} + maintenance {a.maintenanceCost.toLocaleString()})</p></div>
  </div>
  <h4>Tickets & maintenance</h4><ul className="small">{[...a.tickets.map(t=><li key={t.id}><a href={`#/tickets/${t.id}`}>{t.number}</a> {t.title} · {t.status}</li>),...a.maintenance.map(m=><li key={m.id}><a href={`#/maintenance/orders/${m.id}`}>{m.number}</a> {m.title} · {m.status} · {(m.parts_cost+m.labor_cost).toLocaleString()}</li>)]}{!a.tickets.length&&!a.maintenance.length&&<li className="muted">None</li>}</ul>
  <Note tone={a.recommendation==='Keep in service'?'ok':'warn'}><b>{a.recommendation}.</b> {a.reasons.join(' ')}</Note>
 </Card>;
}
function Templates(){
 const {toast}=useApp();const {data,error,reload}=useApi<{templates:{id:string,name:string,kind:string,description:string,requestTypes:string[],stages:Record<string,unknown>[],status:string,version:number}[],stageKinds:string[],requestTypes:{id:string,label:string}[],canConfigure:boolean}>('/api/lifecycle?view=templates');
 const [edit,setEdit]=useState<{id?:string,name:string,kind:string,description:string,requestTypes:string[],stagesJson:string}|null>(null);
 return <div className="page"><Header icon="Workflow" tone="violet" title="Lifecycle templates" subtitle="The stages, approval gates, owners, SLAs, required fields and documents each kind of request follows. Requests in flight keep the version they started with." actions={data?.canConfigure&&<Btn variant="primary" icon="Plus" onClick={()=>setEdit({name:'',kind:'custom',description:'',requestTypes:['custom'],stagesJson:JSON.stringify([{key:'request',name:'Request',kind:'intake',required:true,owner:{kind:'requester'}},{key:'approval',name:'Approval',kind:'approval',required:true,owner:{kind:'department_head'},approval:{stages:[{name:'Department head',mode:'any',approvers:[{kind:'department_head'}]}]}},{key:'close',name:'Closure',kind:'closure',required:true,owner:{kind:'requester'}}],null,2)})}>New template</Btn>}/>
  <ErrorNote error={error} onRetry={reload}/>
  {!data?<Skeleton/>:<div className="cards-2">{data.templates.map(t=><Card key={t.id} title={<>{t.name} <small className="muted">v{t.version}</small></>} actions={data.canConfigure&&<><Btn size="sm" onClick={()=>setEdit({id:t.id,name:t.name,kind:t.kind,description:t.description,requestTypes:t.requestTypes,stagesJson:JSON.stringify(t.stages,null,2)})}>Edit</Btn>{t.status==='active'&&<Btn size="sm" variant="ghost" onClick={async()=>{await api('/api/lifecycle',{action:'template-archive',id:t.id});reload()}}>Archive</Btn>}</>}>
   <p className="small">{t.description}</p><p className="small muted">For: {t.requestTypes.map(x=>data.requestTypes.find(r=>r.id===x)?.label||x).join(', ')}{t.status!=='active'?` · ${t.status}`:''}</p>
   <ol className="lc-steps compact">{(t.stages as {key:string,name:string,kind:string,required:boolean,slaDays?:number}[]).map(s=><li key={s.key} className="lc-step"><span className="lc-name">{s.name}</span><small className="muted">{s.kind}{s.required?'':' · optional'}{s.slaDays?` · ${s.slaDays}d`:''}</small></li>)}</ol></Card>)}</div>}
  {edit&&<Modal open wide onClose={()=>setEdit(null)} title={edit.id?'Edit template':'New template'} footer={<Btn variant="primary" onClick={async()=>{try{await api('/api/lifecycle',{action:'template-save',id:edit.id,name:edit.name,kind:edit.kind,description:edit.description,requestTypes:edit.requestTypes,stages:JSON.parse(edit.stagesJson)});toast('Template saved');setEdit(null);reload()}catch(e){toast((e as Error).message,'error')}}}>Save</Btn>}>
   <div className="form-grid"><Field label="Name"><input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></Field><Field label="Kind"><select value={edit.kind} onChange={e=>setEdit({...edit,kind:e.target.value})}>{['physical_project','service_delivery','it_project','procurement','asset_acquisition','maintenance','improvement','custom'].map(k=><option key={k}>{k}</option>)}</select></Field>
    <Field label="Description" wide><input value={edit.description} onChange={e=>setEdit({...edit,description:e.target.value})}/></Field>
    <Field label="Request types" wide><TagPicker values={edit.requestTypes} options={(data?.requestTypes||[]).map(r=>r.id)} onChange={x=>setEdit({...edit,requestTypes:x})} placeholder="Choose types"/></Field>
    <Field label="Stages (JSON)" wide hint={`Each stage: key, name, kind (${(data?.stageKinds||[]).join(', ')}), required, owner {kind: requester|manager|department_head|procurement|finance|role|person, value}, slaDays, approval {stages:[{name, mode any|all|quorum, quorum, approvers:[{kind,value}], when}] , delegable}, requiredFields, requiredDocs, budgetRule {financeAbove}, minQuotes, auto.`}><textarea rows={16} className="code" value={edit.stagesJson} onChange={e=>setEdit({...edit,stagesJson:e.target.value})}/></Field></div></Modal>}
 </div>;
}
function Services(){
 const {person}=useApp();const {data,error,reload}=useApi<{services:{id:string,number:string,title:string,status:string,owner_id:string,department:string,due_at:string|null,rating:number|null,sla_met:number|null,request_id:string|null,updated_at:string}[]}>('/api/lifecycle?view=services');
 return <div className="page"><Header icon="Handshake" tone="violet" title="Service delivery" subtitle="Purchased and internal services: scope, deliverables, milestones, acceptance, SLA, quality rating, payment eligibility and renewal." actions={<Btn variant="primary" icon="Plus" onClick={()=>go('lifecycle/services/new')}>New service</Btn>}/>
  <ErrorNote error={error} onRetry={reload}/>{!data?<Skeleton/>:!data.services.length?<Empty icon="Handshake" title="No services yet"/>:<div className="lb-table"><table className="plain"><thead><tr><th>Service</th><th>Status</th><th>Owner</th><th>Due</th><th>SLA</th><th>Rating</th></tr></thead><tbody>{data.services.map(s=><tr key={s.id} className="clickable" onClick={()=>go(`lifecycle/services/${s.id}`)}><td><b>{s.number}</b> · {s.title}</td><td><Chip tone={STATUS_TONE(s.status)}>{s.status}</Chip></td><td>{person(s.owner_id)?.name}</td><td>{s.due_at?dateOnly(s.due_at):'—'}</td><td>{s.sla_met==null?'—':s.sla_met?'Met':'Missed'}</td><td>{s.rating?'★'.repeat(s.rating):'—'}</td></tr>)}</tbody></table></div>}</div>;
}
function Service({id}:{id:string}){
 const {toast,person,ask,s}=useApp();const isNew=id==='new';const reqId=new URLSearchParams(location.hash.split('?')[1]||'').get('request');
 const {data,error,reload}=useApi<{service:Record<string,unknown>&{id:string,number:string,title:string,status:string,scope:string,owner_id:string,acceptance_criteria:string,sla_target_hours:number|null,sla_met:number|null,rating:number|null,quality_score:number|null,payment_eligible:number,renewal_decision:string,review_notes:string,deliverables:{title:string,due:string|null,done:boolean}[],milestones:{title:string,due:string|null,done:boolean}[],request_id:string|null,due_at:string|null},history:{action:string,createdAt:string,who:string}[],canAccept:boolean}>(isNew?null:`/api/lifecycle?view=service&sid=${id}`);
 const vendors=useApi<{vendors:{id:string,name:string}[]}>('/api/purchasing?view=vendors');
 const [v,setV]=useState({title:'',scope:'',providerKind:'vendor',vendorId:'',providerDepartment:'',acceptanceCriteria:'',slaTargetHours:'',dueAt:'',ownerId:s.user.id as string|null,deliverables:'',milestones:''});
 const op=async(o:string,extra:Record<string,unknown>={})=>{try{await api('/api/lifecycle',{action:'service-action',id,op:o,...extra});toast('Updated');reload()}catch(e){toast((e as Error).message,'error')}};
 if(isNew)return <div className="page"><Header icon="Handshake" tone="violet" title="New service" actions={<Btn variant="primary" disabled={!v.title} onClick={async()=>{try{const r=await api<{id:string}>('/api/lifecycle',{action:'service-save',...v,requestId:reqId||undefined,vendorId:v.vendorId||undefined,slaTargetHours:v.slaTargetHours?Number(v.slaTargetHours):undefined,dueAt:v.dueAt||undefined,deliverables:v.deliverables.split('\n').filter(Boolean).map(t=>({title:t})),milestones:v.milestones.split('\n').filter(Boolean).map(t=>({title:t}))});go(`lifecycle/services/${r.id}`)}catch(e){toast((e as Error).message,'error')}}}>Create</Btn>}/>
  <Card><div className="form-grid"><Field label="Service" wide><input value={v.title} onChange={e=>setV({...v,title:e.target.value})}/></Field><Field label="Scope" wide><textarea rows={3} value={v.scope} onChange={e=>setV({...v,scope:e.target.value})}/></Field><Field label="Provider"><select value={v.providerKind} onChange={e=>setV({...v,providerKind:e.target.value})}><option value="vendor">Vendor</option><option value="internal">Internal department</option></select></Field>{v.providerKind==='vendor'?<Field label="Vendor"><select value={v.vendorId} onChange={e=>setV({...v,vendorId:e.target.value})}><option value="">—</option>{(vendors.data?.vendors||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>:<Field label="Department"><DeptSelect value={v.providerDepartment} onChange={x=>setV({...v,providerDepartment:x})}/></Field>}<Field label="Owner"><PersonSelect value={v.ownerId} onChange={x=>setV({...v,ownerId:x})}/></Field><Field label="Due"><input type="date" value={v.dueAt} onChange={e=>setV({...v,dueAt:e.target.value})}/></Field><Field label="SLA target (hours)"><input type="number" value={v.slaTargetHours} onChange={e=>setV({...v,slaTargetHours:e.target.value})}/></Field><Field label="Acceptance criteria" wide><textarea rows={2} value={v.acceptanceCriteria} onChange={e=>setV({...v,acceptanceCriteria:e.target.value})}/></Field><Field label="Deliverables (one per line)" wide><textarea rows={3} value={v.deliverables} onChange={e=>setV({...v,deliverables:e.target.value})}/></Field><Field label="Milestones (one per line)" wide><textarea rows={3} value={v.milestones} onChange={e=>setV({...v,milestones:e.target.value})}/></Field></div></Card></div>;
 if(error)return <div className="page"><ErrorNote error={error}/></div>;if(!data)return <div className="page"><Skeleton/></div>;const x=data.service;
 return <div className="page"><Header icon="Handshake" tone="violet" title={<>{x.number} · {x.title}</>} subtitle={<span className="row-gap"><Chip tone={STATUS_TONE(x.status)}>{x.status}</Chip><span>Owner {person(x.owner_id)?.name}</span>{x.request_id&&<a href={`#/lifecycle/${x.request_id}`}>Request</a>}</span>}
  actions={<>{x.status==='Planned'&&<Btn onClick={()=>op('start')}>Start delivery</Btn>}{['Planned','In delivery'].includes(x.status)&&<Btn variant="primary" onClick={()=>op('deliver')}>Mark delivered</Btn>}{x.status==='Delivered'&&data.canAccept&&<><Btn variant="primary" onClick={async()=>{const rating=await ask({title:'Accept the service',input:{label:'Rating 1–5',type:'number',required:true},confirm:'Accept'});if(rating)op('accept',{rating:Number(rating)})}}>Accept & rate</Btn><Btn onClick={async()=>{const n=await ask({title:'Reject delivery',input:{label:'Reason',required:true},confirm:'Reject',danger:true});if(n)op('reject',{notes:n})}}>Reject</Btn></>}{['Accepted','Delivered'].includes(x.status)&&data.canAccept&&<><Btn onClick={()=>op('renew')}>Renew</Btn><Btn onClick={()=>op('terminate')}>Terminate</Btn><Btn onClick={()=>op('close')}>Close</Btn></>}</>}/>
  <div className="cards-2"><Card title="Scope & acceptance"><p className="small">{x.scope||'—'}</p><p className="small"><b>Acceptance criteria:</b> {x.acceptance_criteria||'—'}</p><dl className="kv-list"><dt>SLA</dt><dd>{x.sla_target_hours?`${x.sla_target_hours} h target · ${x.sla_met==null?'not measured':x.sla_met?'met':'missed'}`:'No target'}</dd><dt>Rating</dt><dd>{x.rating?'★'.repeat(x.rating):'—'}</dd><dt>Quality</dt><dd>{x.quality_score??'—'}</dd><dt>Payment eligible</dt><dd>{x.payment_eligible?'Yes':'No'}</dd><dt>Renewal</dt><dd>{x.renewal_decision||'—'}</dd></dl></Card>
   <Card title="Milestones & deliverables"><ul className="mini-list">{x.milestones.map((m,i)=><li key={i} className="mini-row"><label className="check"><input type="checkbox" checked={m.done} onChange={e=>op('milestone',{index:i,done:e.target.checked})}/>{m.title}</label></li>)}</ul><ul className="small">{x.deliverables.map((d,i)=><li key={i}>{d.title}</li>)}</ul></Card></div>
  <Card title="History"><ol className="timeline">{data.history.map((h,i)=><li key={i}><span className="dot"/><div><b>{h.action}</b><small>{h.who} · {ago(h.createdAt)}</small></div></li>)}</ol></Card></div>;
}
