'use client';
import {useState} from 'react';
import {api,useApi,ago} from './lib';
import {useApp,Btn,Chip,Header,Field,ErrorNote,Skeleton,Card,Modal,Note,Tabs,TagPicker} from './kit';

// Platform Owner oversight of the company operating system: per-workspace Studio and AI activity, Studio
// templates published to selected companies, disabling unsafe apps, the approved widget types, and a
// per-company AI kill switch. Every action here is written to the platform audit trail.
type Ws={id:string,name:string,apps:number,published:number,disabledApps:number,records:number,automationRuns:number,failedRuns:number,agents:number,killedAgents:number,agentRuns:number,agentTokens:number,aiKillSwitch:boolean};
type InboxDefaults={slaHours?:Record<string,number>,escalation?:{afterHours?:number,to?:string},digest?:string,retentionDays?:number,disabledModules?:string[]};
type Data={inboxDefaults?:InboxDefaults,workspaces:Ws[],templates:{id:string,name:string,description:string,status:string,targets:string[],created_at:string}[],widgets:{type:string,label:string,category:string,enabled:boolean}[],audit:{tenantId:string,workspace:string,action:string,createdAt:string,who:string|null}[]};
export default function PlatformOS(){
 const {toast,ask}=useApp();const {data,error,reload}=useApi<Data>('/api/platform/os');const [tab,setTab]=useState('workspaces');const [apps,setApps]=useState<{ws:Ws,list:{id:string,name:string,slug:string,status:string,publishedVersion:number|null,disabledReason:string|null,updatedAt:string}[]}|null>(null);
 const [off,setOff]=useState<string[]|null>(null);const [tpl,setTpl]=useState<{name:string,description:string,definition:string,targets:string[]}|null>(null);
 const post=async(body:Record<string,unknown>,msg:string)=>{try{await api('/api/platform/os',body);toast(msg);reload();return true}catch(e){toast((e as Error).message,'error');return false}};
 const openApps=async(ws:Ws)=>{try{const r=await api<{apps:NonNullable<typeof apps>['list']}>(`/api/platform/os?view=apps&tenant=${ws.id}`);setApps({ws,list:r.apps})}catch(e){toast((e as Error).message,'error')}};
 return <div className="page"><Header icon="Cpu" tone="red" title="Company operating system" subtitle="Studio apps, AI agents and widgets across every workspace. Actions are audited."/>
  <ErrorNote error={error} onRetry={reload}/>
  {!data?<Skeleton rows={8}/>:<><Tabs value={tab} onChange={setTab} items={[{id:'workspaces',label:'Workspaces'},{id:'templates',label:'Studio templates',count:data.templates.filter(t=>t.status==='active').length},{id:'widgets',label:'Widget types'},{id:'inbox',label:'Inbox defaults'},{id:'audit',label:'Studio & AI audit'}]}/>
   {tab==='workspaces'&&<div className="lb-table"><table className="plain"><thead><tr><th>Workspace</th><th>Studio apps</th><th>Records</th><th>Automation runs</th><th>Agents</th><th>Agent runs</th><th>AI</th><th/></tr></thead><tbody>{data.workspaces.map(w=><tr key={w.id}><td><b>{w.name}</b></td><td>{w.apps} <small className="muted">({w.published} live{w.disabledApps?`, ${w.disabledApps} disabled`:''})</small></td><td>{w.records}</td><td>{w.automationRuns}{w.failedRuns>0&&<small className="muted"> ({w.failedRuns} failed)</small>}</td><td>{w.agents}{w.killedAgents>0&&<small className="muted"> ({w.killedAgents} stopped)</small>}</td><td>{w.agentRuns} <small className="muted">{w.agentTokens.toLocaleString()} tokens</small></td><td>{w.aiKillSwitch?<Chip tone="red">kill switch on</Chip>:<Chip tone="green">on</Chip>}</td>
    <td className="row-gap"><Btn size="sm" onClick={()=>openApps(w)}>Apps</Btn><Btn size="sm" variant={w.aiKillSwitch?'primary':'default'} onClick={async()=>{if(!w.aiKillSwitch&&await ask({title:`Stop all AI in ${w.name}?`,body:'Running agent work is cancelled and no agent can run until you turn it back on.',confirm:'Stop AI',danger:true})===false)return;post({action:'ai-kill',tenantId:w.id,on:!w.aiKillSwitch},w.aiKillSwitch?'AI turned back on':'AI stopped')}}>{w.aiKillSwitch?'Resume AI':'Stop AI'}</Btn></td></tr>)}</tbody></table></div>}
   {tab==='templates'&&<><Btn variant="primary" onClick={()=>setTpl({name:'',description:'',definition:JSON.stringify({tables:[],forms:[],workflows:[],automations:[],reports:[],pages:[],nav:[],permissions:{use:[],admin:[]},settings:{}},null,1),targets:[]})}>New platform template</Btn>
    <div className="lb-table"><table className="plain"><thead><tr><th>Template</th><th>Published to</th><th>Status</th><th/></tr></thead><tbody>{data.templates.map(t=><tr key={t.id}><td><b>{t.name}</b><br/><small className="muted">{t.description}</small></td><td>{t.targets.length?t.targets.map(id=>data.workspaces.find(w=>w.id===id)?.name||id).join(', '):'All workspaces'}</td><td><Chip tone={t.status==='active'?'green':'gray'}>{t.status}</Chip></td><td>{t.status==='active'&&<Btn size="sm" onClick={()=>post({action:'template-retire',id:t.id},'Retired')}>Retire</Btn>}</td></tr>)}</tbody></table></div></>}
   {tab==='widgets'&&<Card title="Approved widget types" actions={<Btn size="sm" variant="primary" onClick={()=>post({action:'widget-policy',disabled:off??data.widgets.filter(w=>!w.enabled).map(w=>w.type)},'Widget policy saved').then(ok=>{if(ok)setOff(null)})}>Save</Btn>}><Note>Disabled types cannot be added to any company page. Existing pages keep rendering until edited.</Note>
    {[...new Set(data.widgets.map(w=>w.category))].map(c=><div key={c}><p className="rail-section">{c}</p><div className="row-gap wrap">{data.widgets.filter(w=>w.category===c).map(w=><label key={w.type} className="check"><input type="checkbox" checked={!(off??data.widgets.filter(x=>!x.enabled).map(x=>x.type)).includes(w.type)} onChange={e=>{const cur=off??data.widgets.filter(x=>!x.enabled).map(x=>x.type);setOff(e.target.checked?cur.filter(x=>x!==w.type):[...cur,w.type])}}/>{w.label}</label>)}</div></div>)}</Card>}
   {tab==='inbox'&&<InboxDefaultsCard value={data.inboxDefaults||{}} onSave={d=>post({action:'inbox-defaults',defaults:d},'Inbox defaults saved')}/>}
   {tab==='audit'&&<div className="lb-table"><table className="plain"><thead><tr><th>When</th><th>Workspace</th><th>Who</th><th>What</th></tr></thead><tbody>{data.audit.map((a,i)=><tr key={i}><td>{ago(a.createdAt)}</td><td>{a.workspace}</td><td>{a.who||'System'}</td><td>{a.action}</td></tr>)}</tbody></table></div>}
  </>}
  {apps&&<Modal open wide onClose={()=>setApps(null)} title={`Studio apps · ${apps.ws.name}`}><div className="lb-table"><table className="plain"><tbody>{apps.list.map(a=><tr key={a.id}><td><b>{a.name}</b><br/><small className="muted">{a.slug} · {a.status}{a.publishedVersion?` · v${a.publishedVersion}`:''}</small>{a.disabledReason&&<><br/><Chip tone="red">disabled: {a.disabledReason}</Chip></>}</td><td>{a.disabledReason?<Btn size="sm" onClick={async()=>{if(await post({action:'enable-app',tenantId:apps.ws.id,appId:a.id},'Re-enabled'))openApps(apps.ws)}}>Re-enable</Btn>:<Btn size="sm" onClick={async()=>{const reason=await ask({title:`Disable ${a.name}?`,body:'The company can no longer use it until you re-enable it. They see your reason.',input:{label:'Reason',required:true},confirm:'Disable',danger:true});if(reason&&await post({action:'disable-app',tenantId:apps.ws.id,appId:a.id,reason},'Disabled'))openApps(apps.ws)}}>Disable</Btn>}</td></tr>)}{!apps.list.length&&<tr><td className="muted">No Studio apps.</td></tr>}</tbody></table></div></Modal>}
  {tpl&&<Modal open wide onClose={()=>setTpl(null)} title="Platform Studio template" footer={<Btn variant="primary" onClick={async()=>{let def;try{def=JSON.parse(tpl.definition)}catch{toast('The definition is not valid JSON.','error');return}if(await post({action:'template-save',name:tpl.name,description:tpl.description,definition:def,targets:tpl.targets},'Template saved'))setTpl(null)}}>Save</Btn>}>
   <Field label="Name"><input value={tpl.name} onChange={e=>setTpl({...tpl,name:e.target.value})}/></Field><Field label="Description"><input value={tpl.description} onChange={e=>setTpl({...tpl,description:e.target.value})}/></Field>
   <Field label="Publish to" hint="Empty = every workspace."><TagPicker values={tpl.targets.map(id=>data?.workspaces.find(w=>w.id===id)?.name||id)} options={(data?.workspaces||[]).map(w=>w.name)} onChange={v=>setTpl({...tpl,targets:v.map(n=>data?.workspaces.find(w=>w.name===n)?.id||n)})} placeholder="All workspaces"/></Field>
   <Field label="App definition (JSON)" hint="Validated with the same rules as company apps."><textarea rows={12} className="code" value={tpl.definition} onChange={e=>setTpl({...tpl,definition:e.target.value})}/></Field></Modal>}
 </div>;
}

// Platform-wide inbox defaults: each company starts from these and may override them in Admin → Inbox rules.
function InboxDefaultsCard({value,onSave}:{value:InboxDefaults,onSave:(d:InboxDefaults)=>void}){
 const [v,setV]=useState(()=>({approval:String(value.slaHours?.approval??48),task:String(value.slaHours?.task??72),ticket:String(value.slaHours?.ticket??24),after:String(value.escalation?.afterHours??-1),to:value.escalation?.to||'department_head',digest:value.digest||'none',retention:String(value.retentionDays??180),disabled:(value.disabledModules||[]).join(', ')}));
 const set=(k:keyof typeof v)=>(e:{target:{value:string}})=>setV({...v,[k]:e.target.value});
 return <Card title="Inbox defaults for every company" actions={<Btn size="sm" variant="primary" onClick={()=>onSave({slaHours:{approval:Number(v.approval)||0,task:Number(v.task)||0,ticket:Number(v.ticket)||0},escalation:{afterHours:Number(v.after),to:v.to},digest:v.digest,retentionDays:Number(v.retention)||180,disabledModules:v.disabled.split(',').map(x=>x.trim()).filter(Boolean)})}>Save</Btn>}>
  <Note>Company administrators can override these in Admin → Inbox rules. Changes are recorded in the platform audit.</Note>
  <div className="form-grid">
   <Field label="Approval SLA (hours)"><input type="number" min="0" value={v.approval} onChange={set('approval')}/></Field>
   <Field label="Task SLA (hours)"><input type="number" min="0" value={v.task} onChange={set('task')}/></Field>
   <Field label="Ticket SLA (hours)"><input type="number" min="0" value={v.ticket} onChange={set('ticket')}/></Field>
   <Field label="Escalate after (hours, −1 = never)"><input type="number" min="-1" value={v.after} onChange={set('after')}/></Field>
   <Field label="Escalate to"><select value={v.to} onChange={set('to')}><option value="department_head">Department head</option><option value="manager">Reporting manager</option><option value="admin">Company administrators</option></select></Field>
   <Field label="Digest"><select value={v.digest} onChange={set('digest')}><option value="none">None</option><option value="daily">Daily (06:00 UTC)</option></select></Field>
   <Field label="Keep completed items (days)"><input type="number" min="7" max="3650" value={v.retention} onChange={set('retention')}/></Field>
   <Field label="Modules excluded from the inbox" hint="Comma separated, e.g. inventory, schedules" wide><input value={v.disabled} onChange={set('disabled')}/></Field>
  </div>
 </Card>;
}
