'use client';
import {useMemo,useState} from 'react';
import {api,useApi,go,ago,dateOnly,dateTime,money,cx,bytes} from './lib';
import {useApp,Btn,Chip,Header,Field,Who,Avatar,ErrorNote,Skeleton,Empty,Icon,Segmented,Menu,Tabs,Modal,Note,PersonSelect,DeptSelect,Card,Stat,Thread,AudiencePicker} from './kit';
import {AiActions} from './assistant';
import {TaskBoard,Gantt,TaskForm,type TaskItem} from './tasks';
import {UploadDialog,fileIcon} from './files';

// Enterprise project planner. Every figure on the finance tab comes from linked records (requisitions,
// orders, receipts, recorded costs and logged time); nothing is estimated in the browser.
type Stage={id:string,name:string,requires?:string[],approval?:boolean,approverRole?:string,next:string[]};
type Project={id:string,code:string,name:string,type:string,methodology:string,description:string,business_case:string,department:string,location:string,owner_id:string|null,manager_id:string|null,sponsor_id:string|null,start_date:string|null,target_date:string|null,actual_end:string|null,priority:string,stage:string,health:string,currency:string,approved_budget:number,progress:number,tags:string,approval_status:string,archived_at:string|null,space_id:string|null,created_at:string,updated_at:string,open_tasks?:number,overdue?:number,team?:number,audience?:string,acl?:any};
type Rec={id:string,kind:string,title:string,body:string,status:string,priority:string,owner_id:string|null,due_date:string|null,parent_id:string|null,data:Record<string,any>,updated_at:string};
type Finance={currency:string,approved:number,requested:number,committed:number,ordered:number,received:number,invoiced:number,paid:number,labour:number,labourMinutes:number,expenses:number,actual:number,remaining:number,forecastAtCompletion:number,variance:number,documents:{id:string,kind:string,number:string,title:string,status:string,total:number,currency:string}[]};
type Detail={project:Project,members:{id:string,name:string,role:string,allocation:number,department:string,title:string}[],history:{from:string,to:string,note:string,createdAt:string,who:string}[],records:Rec[],tasks:TaskItem[],deps:{task_id:string,depends_on:string}[],criticalPath:{taskIds:string[],days:number},files:{id:string,name:string,mime:string,bytes:number,updatedAt:string,processingStatus:string}[],finance:Finance|null,costs:{id:string,kind:string,description:string,amount:number,date:string}[],assets:{id:string,code:string,name:string,status:string}[],workflow:{id:string|null,name:string,stages:Stage[],current:Stage|null,next:Stage[]},channelId:string|null,space:{id:string,name:string}|null,canManage:boolean,canApprove:boolean};
const TYPE_LABEL:Record<string,string>={capital:'Capital',construction:'Construction',service:'Service',client:'Client',procurement:'Procurement',internal:'Internal',department:'Department',it:'IT',software:'Software',maintenance:'Maintenance',custom:'Custom'};
const healthTone:Record<string,string>={green:'green',amber:'amber',red:'red'};
const FIELD_LABEL:Record<string,string>={description:'Description',businessCase:'Business case',approvedBudget:'Approved budget',startDate:'Start date',targetDate:'Target date',managerId:'Project manager',ownerId:'Owner',sponsorId:'Sponsor'};
const isIT=(p:Project)=>['it','software'].includes(p.type);
const isPhysical=(p:Project)=>['capital','construction','maintenance','service','client','procurement'].includes(p.type);
// Record groups per tab.
const GROUPS:Record<string,{label:string,kinds:string[]}>={
 plan:{label:'Plan',kinds:['phase','milestone','deliverable']},
 risks:{label:'Risks & issues',kinds:['risk','issue','decision','change','lesson','meeting']},
 delivery:{label:'Delivery',kinds:['requirement','epic','feature','story','bug','sprint','release','environment','test','deployment']},
 site:{label:'Site & service',kinds:['inspection','site-report','service-report','defect','contractor','material','equipment','certificate','handover','obligation','sla','rfq']},
};

export default function Projects({parts}:{parts:string[]}){
 if(parts[0]==='workflows')return <Workflows/>;
 if(parts[0]==='templates')return <Templates/>;
 if(parts[0]&&parts[0]!=='all'&&parts[0]!=='mine'&&parts[0]!=='archived')return <ProjectDetail id={parts[0]} tab={parts[1]||'overview'} sub={parts[2]}/>;
 return <ProjectList view={parts[0]||'all'} create={parts[1]==='new'}/>;
}
function ProjectList({view,create}:{view:string,create?:boolean}){
 const {s}=useApp();const {data,error,reload}=useApi<{projects:Project[],canCreate:boolean,types:string[]}>(`/api/projects${view==='archived'?'?archived=1':''}`);
 const [q,setQ]=useState('');const [type,setType]=useState('');const [creating,setCreating]=useState(!!create);const [layout,setLayout]=useState('cards');
 const rows=(data?.projects||[]).filter(p=>(view==='archived'?!!p.archived_at:!p.archived_at)&&(view!=='mine'||[p.owner_id,p.manager_id,p.sponsor_id].includes(s.user.id))&&(!type||p.type===type)&&(!q||`${p.code} ${p.name} ${p.department}`.toLowerCase().includes(q.toLowerCase())));
 return <div className="page">
  <Header icon="FolderKanban" tone="violet" title={view==='mine'?'My projects':view==='archived'?'Archived projects':'Projects'} subtitle="Plan, deliver and track projects with real schedules, approvals and linked finances." actions={data?.canCreate&&<Btn variant="primary" icon="Plus" onClick={()=>setCreating(true)}>New project</Btn>}/>
  <div className="toolbar"><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search projects…" aria-label="Search projects"/><select value={type} onChange={e=>setType(e.target.value)} aria-label="Type"><option value="">All types</option>{(data?.types||[]).map(t=><option key={t} value={t}>{TYPE_LABEL[t]||t}</option>)}</select><Segmented value={layout} onChange={setLayout} items={[{id:'cards',label:'',icon:'LayoutGrid'},{id:'list',label:'',icon:'List'}]}/></div>
  <ErrorNote error={error} onRetry={reload}/>
  {!data?<Skeleton rows={6}/>:!rows.length?<Empty icon="FolderKanban" title="No projects yet" action={data.canCreate&&<Btn variant="primary" icon="Plus" onClick={()=>setCreating(true)}>Create a project</Btn>}>Start from a template or a blank project.</Empty>:
   layout==='cards'?<div className="project-grid">{rows.map(p=><a key={p.id} href={`#/projects/${p.id}`} className="project-card"><div className="between"><small className="muted">{p.code} · {TYPE_LABEL[p.type]||p.type}</small><Chip tone={healthTone[p.health]}>{p.health}</Chip></div><b>{p.name}</b><small>{p.stage}{p.approval_status?.startsWith('pending')?' · awaiting approval':''}</small><div className="progress" aria-label={`${p.progress}% complete`}><span style={{width:`${p.progress}%`}}/></div><div className="row-gap small muted"><span>{p.open_tasks||0} open</span>{!!p.overdue&&<span className="text-danger">{p.overdue} overdue</span>}<span>{p.team||0} people</span>{p.target_date&&<span>Target {dateOnly(p.target_date)}</span>}</div></a>)}</div>:
   <table className="grid-table"><thead><tr><th>Project</th><th>Type</th><th>Stage</th><th>Health</th><th>Progress</th><th>Manager</th><th>Target</th><th>Open / overdue</th></tr></thead><tbody>{rows.map(p=><tr key={p.id} onClick={()=>go(`projects/${p.id}`)}><td><b>{p.code}</b> {p.name}</td><td>{TYPE_LABEL[p.type]}</td><td>{p.stage}</td><td><Chip tone={healthTone[p.health]}>{p.health}</Chip></td><td>{p.progress}%</td><td><Who id={p.manager_id}/></td><td>{p.target_date?dateOnly(p.target_date):'—'}</td><td>{p.open_tasks} / <span className={cx(!!p.overdue&&'text-danger')}>{p.overdue}</span></td></tr>)}</tbody></table>}
  {creating&&<NewProject onClose={()=>setCreating(false)} types={data?.types||[]}/>}
 </div>;
}
function NewProject({onClose,types}:{onClose:()=>void,types:string[]}){
 const {s,toast}=useApp();const {data:tpl}=useApi<{templates:{id:string,name:string,projectType:string,methodology:string}[]}>('/api/projects?view=templates');
 const [step,setStep]=useState(0);const [busy,setBusy]=useState(false);
 const [v,setV]=useState({templateId:'',name:'',type:'internal',methodology:'waterfall',description:'',businessCase:'',department:s.user.department,location:'',managerId:s.user.id as string|null,sponsorId:null as string|null,startDate:'',targetDate:'',priority:'Medium',currency:s.tenant.currency,approvedBudget:''});
 async function create(){setBusy(true);try{const r=await api<{id:string}>('/api/projects',{action:'create',...v,templateId:v.templateId||undefined,startDate:v.startDate||null,targetDate:v.targetDate||null});toast('Project created');go(`projects/${r.id}`)}catch(e){toast((e as Error).message,'error')}finally{setBusy(false)}}
 return <Modal open wide onClose={onClose} title="New project" subtitle={`Step ${step+1} of 3`} footer={<>{step>0&&<Btn variant="ghost" onClick={()=>setStep(step-1)}>Back</Btn>}<div className="grow"/><Btn variant="ghost" onClick={onClose}>Cancel</Btn>{step<2?<Btn variant="primary" disabled={step===1&&!v.name.trim()} onClick={()=>setStep(step+1)}>Next</Btn>:<Btn variant="primary" busy={busy} onClick={create}>Create project</Btn>}</>}>
  {step===0&&<div className="choice-grid"><button className={cx('choice',!v.templateId&&'on')} onClick={()=>setV({...v,templateId:''})}><Icon name="File" size={20}/><b>Blank project</b><small>Choose the type and lifecycle yourself.</small></button>{(tpl?.templates||[]).map(t=><button key={t.id} className={cx('choice',v.templateId===t.id&&'on')} onClick={()=>setV({...v,templateId:t.id,type:t.projectType,methodology:t.methodology})}><Icon name="LayoutTemplate" size={20}/><b>{t.name}</b><small>{TYPE_LABEL[t.projectType]} · {t.methodology}</small></button>)}</div>}
  {step===1&&<div className="form-grid">
   <Field label="Project name" wide><input autoFocus value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></Field>
   <Field label="Type"><select value={v.type} disabled={!!v.templateId} onChange={e=>setV({...v,type:e.target.value})}>{types.map(t=><option key={t} value={t}>{TYPE_LABEL[t]||t}</option>)}</select></Field>
   <Field label="Methodology"><select value={v.methodology} onChange={e=>setV({...v,methodology:e.target.value})}>{['waterfall','kanban','scrum','hybrid','custom'].map(m=><option key={m}>{m}</option>)}</select></Field>
   <Field label="Department"><DeptSelect value={v.department} onChange={d=>setV({...v,department:d})}/></Field>
   <Field label="Priority"><select value={v.priority} onChange={e=>setV({...v,priority:e.target.value})}>{['Low','Medium','High','Critical'].map(x=><option key={x}>{x}</option>)}</select></Field>
   <Field label="Description" wide><textarea rows={3} value={v.description} onChange={e=>setV({...v,description:e.target.value})}/></Field>
  </div>}
  {step===2&&<div className="form-grid">
   <Field label="Project manager"><PersonSelect value={v.managerId} onChange={id=>setV({...v,managerId:id})}/></Field>
   <Field label="Sponsor"><PersonSelect value={v.sponsorId} onChange={id=>setV({...v,sponsorId:id})}/></Field>
   <Field label="Start date"><input type="date" value={v.startDate} onChange={e=>setV({...v,startDate:e.target.value})}/></Field>
   <Field label="Target date"><input type="date" value={v.targetDate} onChange={e=>setV({...v,targetDate:e.target.value})}/></Field>
   <Field label={`Approved budget (${v.currency})`} hint="Leave empty until the budget is approved."><input type="number" min="0" value={v.approvedBudget} onChange={e=>setV({...v,approvedBudget:e.target.value})}/></Field>
   <Field label="Location"><input value={v.location} onChange={e=>setV({...v,location:e.target.value})}/></Field>
   <Note>A project space (files, pages, messages) and a team are created with the project. {v.templateId?'Plan items and tasks from the template are added.':''}</Note>
  </div>}
 </Modal>;
}

function ProjectDetail({id,tab,sub}:{id:string,tab:string,sub?:string}){
 const {toast,ask}=useApp();const {data,error,reload}=useApi<Detail>(`/api/projects?id=${encodeURIComponent(id)}`);const [edit,setEdit]=useState(false);
 if(error)return <div className="page"><ErrorNote error={error} onRetry={reload}/></div>;
 if(!data)return <div className="page"><Skeleton rows={10}/></div>;
 const p=data.project;
 const act=async(body:Record<string,unknown>,msg?:string)=>{try{const r=await api<{pending?:boolean}>('/api/projects',{id:p.id,...body});toast(r?.pending?'Sent for approval':msg||'Saved');reload()}catch(e){toast((e as Error).message,'error')}};
 const tabs=[{id:'overview',label:'Overview'},{id:'plan',label:'Plan'},{id:'tasks',label:'Tasks',count:data.tasks.filter(t=>!['Done','Cancelled'].includes(t.status)).length},{id:'timeline',label:'Timeline'},{id:'risks',label:'Risks & issues',count:data.records.filter(r=>['risk','issue'].includes(r.kind)&&r.status!=='Closed').length},...(isIT(p)||p.methodology==='scrum'?[{id:'delivery',label:'Delivery'}]:[]),...(isPhysical(p)?[{id:'site',label:'Site & service'}]:[]),...(data.finance?[{id:'finance',label:'Finance'}]:[]),{id:'team',label:'Team',count:data.members.length},{id:'files',label:'Files',count:data.files.length},{id:'activity',label:'Activity'}];
 return <div className="page">
  <Header icon="FolderKanban" tone="violet" title={<>{p.name} <small className="muted">{p.code}</small></>} subtitle={<span className="row-gap"><Chip tone="gray">{TYPE_LABEL[p.type]}</Chip><Chip tone={healthTone[p.health]}>{p.health}</Chip><span>{data.workflow.current?.name||p.stage}</span>{p.archived_at&&<Chip>Archived</Chip>}</span>} actions={<><AiActions entity="project" entityId={p.id} onApply={{'tasks.create':async d=>{for(const t of (d.tasks||[]).slice(0,30))await api('/api/tasks',{action:'save',projectId:p.id,title:String(t.title).slice(0,200),description:String(t.description||''),dueDate:/^\d{4}-\d{2}-\d{2}$/.test(t.dueDate||'')?t.dueDate:null,milestone:!!t.milestone,assignees:[]});reload()}}}/>{data.space&&<Btn icon="LibraryBig" onClick={()=>go(`spaces/${data.space!.id}`)}>Space</Btn>}{data.channelId&&<Btn icon="MessageSquare" onClick={()=>go(`messages/${data.channelId}`)}>Messages</Btn>}{data.canManage&&<><Btn icon="Pencil" onClick={()=>setEdit(true)}>Edit</Btn><Menu trigger={o=><Btn variant="ghost" icon="Ellipsis" title="More" onClick={o}/>} items={[{label:'Set baseline',icon:'Flag',onClick:async()=>{if(await ask({title:'Set the baseline?',body:'Current task dates are saved as the baseline for variance tracking.',confirm:'Set baseline'})!==false)act({action:'baseline'},'Baseline saved')}},{label:'Save as template',icon:'LayoutTemplate',onClick:async()=>{const n=await ask({title:'Save as template',input:{label:'Template name',required:true}});if(n!==false)act({action:'save-template',name:n},'Template saved')}},'-',{label:p.archived_at?'Restore':'Archive',icon:'Archive',onClick:()=>act({action:p.archived_at?'restore':'archive'},p.archived_at?'Restored':'Archived')}]}/></>}</>}/>
  <Tabs value={tab} onChange={t=>go(`projects/${p.id}/${t}`)} items={tabs}/>
  {tab==='overview'&&<Overview d={data} act={act}/>}
  {(tab==='plan'||tab==='risks'||tab==='delivery'||tab==='site')&&<Records d={data} group={tab} act={act}/>}
  {tab==='tasks'&&<TaskBoard view="all" project={p.id} openId={sub} embedded/>}
  {tab==='timeline'&&<><div className="between"><p className="muted small">Critical path: {data.criticalPath.taskIds.length} tasks · {data.criticalPath.days} days (finish-to-start dependencies).</p></div><Gantt rows={data.tasks} deps={data.deps} critical={data.criticalPath.taskIds} onOpen={t=>go(`projects/${p.id}/tasks/${t.id}`)}/></>}
  {tab==='finance'&&data.finance&&<FinanceTab d={data} act={act}/>}
  {tab==='team'&&<Team d={data} act={act}/>}
  {tab==='files'&&<ProjectFiles d={data} reload={reload}/>}
  {tab==='activity'&&<div className="split-2"><Card title="Stage history"><ol className="timeline">{data.history.map((h,i)=><li key={i}><span className="dot"/><div><b>{h.from?`${h.from} → ${h.to}`:`Started in ${h.to}`}</b>{h.note&&<p className="small">{h.note}</p>}<small>{h.who||'System'} · {dateTime(h.createdAt)}</small></div></li>)}</ol></Card><Card title="Discussion"><ProjectComments id={p.id}/></Card></div>}
  {edit&&<EditProject p={p} onClose={()=>setEdit(false)} onDone={()=>{setEdit(false);reload()}}/>}
 </div>;
}
function ProjectComments({id}:{id:string}){const {data,reload}=useApi<{comments:any[]}>(`/api/comments?type=project&id=${id}`);return <Thread comments={data?.comments||[]} onPost={async body=>{await api('/api/comments',{type:'project',id,body});reload()}}/>}
function Overview({d,act}:{d:Detail,act:(b:Record<string,unknown>,m?:string)=>Promise<void>}){
 const {ask}=useApp();const p=d.project;const wf=d.workflow;const pending=p.approval_status?.startsWith('pending:')?p.approval_status.slice(8):null;
 const today=new Date().toISOString().slice(0,10);const overdue=d.tasks.filter(t=>t.due_date&&t.due_date<today&&!['Done','Cancelled'].includes(t.status));
 const milestones=d.tasks.filter(t=>t.milestone).concat([]);
 return <div className="stack">
  <section className="lifecycle" aria-label="Lifecycle">{wf.stages.filter(s=>s.id!=='archived').map((s,i)=>{const idx=wf.stages.findIndex(x=>x.id===p.stage);return <div key={s.id} className={cx('stage',s.id===p.stage&&'current',i<idx&&'done',pending===s.id&&'pending')}><span>{i+1}</span><b>{s.name}</b>{s.approval&&<small><Icon name="Stamp" size={11}/> approval</small>}</div>})}</section>
  {pending&&<Note tone="warn">Waiting for approval to move to {wf.stages.find(s=>s.id===pending)?.name}.{d.canApprove&&<> <Btn size="sm" variant="primary" onClick={()=>act({action:'approve-stage'},'Approved')}>Approve</Btn> <Btn size="sm" onClick={async()=>{const n=await ask({title:'Decline this stage change?',input:{label:'Reason'},confirm:'Decline',danger:true});if(n!==false)act({action:'reject-stage',note:n},'Declined')}}>Decline</Btn></>}</Note>}
  {d.canManage&&!pending&&wf.next.length>0&&<div className="row-gap"><span className="muted small">Move to:</span>{wf.next.map(s=><Btn key={s.id} size="sm" icon={s.approval?'Stamp':'ArrowRight'} onClick={async()=>{const miss=(s.requires||[]).map(f=>FIELD_LABEL[f]||f);const n=await ask({title:`Move to ${s.name}?`,body:<>{s.approval&&<p>This stage needs approval ({s.approverRole}). The move waits until it is approved.</p>}{miss.length>0&&<p className="muted">Required: {miss.join(', ')}.</p>}</>,input:{label:'Note (optional)'},confirm:s.approval?'Request approval':'Move'});if(n!==false)act({action:'transition',to:s.id,note:n},`Moved to ${s.name}`)}}>{s.name}</Btn>)}</div>}
  <div className="stats"><Stat label="Progress" value={`${p.progress}%`} icon="Gauge"/><Stat label="Open tasks" value={d.tasks.filter(t=>!['Done','Cancelled'].includes(t.status)).length} icon="ListTodo"/><Stat label="Overdue" value={overdue.length} icon="AlarmClock" tone={overdue.length?'red':'green'}/><Stat label="Target" value={p.target_date?dateOnly(p.target_date):'—'} icon="Flag" sub={p.start_date?`Started ${dateOnly(p.start_date)}`:undefined}/>{d.finance&&<Stat label="Forecast vs budget" value={money(d.finance.forecastAtCompletion,p.currency)} sub={`Budget ${money(d.finance.approved,p.currency)}`} icon="Wallet" tone={d.finance.variance<0?'red':'green'}/>}</div>
  <div className="split-2"><Card title="About">{p.description?<p className="prewrap">{p.description}</p>:<p className="muted">No description.</p>}{p.business_case&&<><h4>Business case</h4><p className="prewrap">{p.business_case}</p></>}<dl className="kv"><div><dt>Manager</dt><dd><Who id={p.manager_id}/></dd></div><div><dt>Owner</dt><dd><Who id={p.owner_id}/></dd></div><div><dt>Sponsor</dt><dd><Who id={p.sponsor_id} fallback="—"/></dd></div><div><dt>Department</dt><dd>{p.department||'—'}</dd></div><div><dt>Methodology</dt><dd>{p.methodology}</dd></div>{p.location&&<div><dt>Location</dt><dd>{p.location}</dd></div>}</dl></Card>
   <Card title="Milestones & overdue">{milestones.map(t=><div key={t.id} className="mini-row"><Icon name="Diamond" size={14}/><span>{t.title}<small>{t.due_date?dateOnly(t.due_date):'no date'} · {t.status}</small></span></div>)}{overdue.slice(0,8).map(t=><a key={t.id} className="mini-row" href={`#/projects/${p.id}/tasks/${t.id}`}><Icon name="AlarmClock" size={14} className="text-danger"/><span>{t.title}<small className="text-danger">due {dateOnly(t.due_date)}</small></span></a>)}{!milestones.length&&!overdue.length&&<p className="muted small">No milestones or overdue tasks.</p>}</Card></div>
 </div>;
}
function Records({d,group,act}:{d:Detail,group:string,act:(b:Record<string,unknown>,m?:string)=>Promise<void>}){
 const {ask,person}=useApp();const g=GROUPS[group];const [kind,setKind]=useState('all');const [editing,setEditing]=useState<Partial<Rec>|null>(null);
 const rows=d.records.filter(r=>g.kinds.includes(r.kind)&&(kind==='all'||r.kind===kind));
 return <div className="stack">
  <div className="toolbar"><Segmented value={kind} onChange={setKind} items={[{id:'all',label:'All'},...g.kinds.filter(k=>d.records.some(r=>r.kind===k)).map(k=>({id:k,label:k.replace('-',' ')}))]}/><div className="grow"/>{d.canManage&&<Btn variant="primary" icon="Plus" onClick={()=>setEditing({kind:kind==='all'?g.kinds[0]:kind,status:'Open',priority:'Medium'})}>Add</Btn>}</div>
  {group==='plan'&&<Note>The plan is made of phases, milestones and deliverables here, and the tasks on the Tasks tab (the work breakdown). Use the Timeline for the Gantt chart and critical path.</Note>}
  {!rows.length?<Empty icon="ClipboardList" title={`No ${g.label.toLowerCase()} yet`}/>:<table className="grid-table"><thead><tr><th>Type</th><th>Title</th><th>Status</th><th>Priority</th><th>Owner</th><th>Due</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id} onClick={()=>d.canManage&&setEditing(r)}><td><Chip tone="gray">{r.kind}</Chip></td><td><b>{r.title}</b>{r.body&&<><br/><small className="muted">{r.body.slice(0,140)}</small></>}</td><td>{r.status}</td><td><Chip tone={r.priority==='Critical'?'red':r.priority==='High'?'amber':'gray'}>{r.priority}</Chip></td><td>{person(r.owner_id)?.name||'—'}</td><td>{r.due_date?dateOnly(r.due_date):'—'}</td><td onClick={e=>e.stopPropagation()}>{d.canManage&&<Btn size="sm" variant="ghost" icon="Trash2" title="Delete" onClick={async()=>{if(await ask({title:`Delete “${r.title}”?`,confirm:'Delete',danger:true})!==false)act({action:'record-delete',recordId:r.id},'Deleted')}}/>}</td></tr>)}</tbody></table>}
  {editing&&<RecordForm r={editing} kinds={g.kinds} onClose={()=>setEditing(null)} onSave={async v=>{await act({action:'record',recordId:editing.id,...v},'Saved');setEditing(null)}}/>}
 </div>;
}
function RecordForm({r,kinds,onClose,onSave}:{r:Partial<Rec>,kinds:string[],onClose:()=>void,onSave:(v:Record<string,unknown>)=>Promise<void>}){
 const [v,setV]=useState({kind:r.kind||kinds[0],title:r.title||'',body:r.body||'',status:r.status||'Open',priority:r.priority||'Medium',ownerId:r.owner_id||null as string|null,dueDate:r.due_date||'',data:r.data||{}});
 const extra:Record<string,string[]>={risk:['likelihood','impact','mitigation'],issue:['resolution'],change:['costImpact','scheduleImpactDays','decision'],defect:['location','severity'],inspection:['result','inspector'],material:['quantity','unit','supplier'],equipment:['serial','supplier'],contractor:['company','contact'],sla:['target','measure'],release:['version','environment'],test:['result','environment'],deployment:['environment','checklist']};
 return <Modal open onClose={onClose} title={r.id?'Edit':'Add'} footer={<><Btn variant="ghost" onClick={onClose}>Cancel</Btn><Btn variant="primary" disabled={!v.title.trim()} onClick={()=>onSave({...v,dueDate:v.dueDate||null})}>Save</Btn></>}>
  <div className="form-grid"><Field label="Type"><select value={v.kind} onChange={e=>setV({...v,kind:e.target.value})}>{kinds.map(k=><option key={k}>{k}</option>)}</select></Field><Field label="Status"><select value={v.status} onChange={e=>setV({...v,status:e.target.value})}>{['Open','In progress','Blocked','Mitigated','Resolved','Approved','Rejected','Closed','Done'].map(x=><option key={x}>{x}</option>)}</select></Field>
   <Field label="Title" wide><input autoFocus value={v.title} onChange={e=>setV({...v,title:e.target.value})}/></Field><Field label="Details" wide><textarea rows={3} value={v.body} onChange={e=>setV({...v,body:e.target.value})}/></Field>
   <Field label="Priority"><select value={v.priority} onChange={e=>setV({...v,priority:e.target.value})}>{['Low','Medium','High','Critical'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Due"><input type="date" value={v.dueDate} onChange={e=>setV({...v,dueDate:e.target.value})}/></Field>
   <Field label="Owner" wide><PersonSelect value={v.ownerId} onChange={id=>setV({...v,ownerId:id})}/></Field>
   {(extra[v.kind]||[]).map(k=><Field key={k} label={k.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}><input value={String(v.data[k]??'')} onChange={e=>setV({...v,data:{...v.data,[k]:e.target.value}})}/></Field>)}
  </div></Modal>;
}
function FinanceTab({d,act}:{d:Detail,act:(b:Record<string,unknown>,m?:string)=>Promise<void>}){
 const {ask,can}=useApp();const f=d.finance!;const c=f.currency;const [linking,setLinking]=useState<string|null>(null);const [cost,setCost]=useState(false);
 const rows:[string,number,string][]=[['Approved budget',f.approved,'Project budget or linked budgets'],['Requested',f.requested,'Linked requisitions (not draft/rejected)'],['Committed',f.committed,'Approved requisitions not yet ordered + open orders'],['Ordered',f.ordered,'Linked purchase orders'],['Received',f.received,'Goods received on linked orders (net of returns)'],['Invoiced',f.invoiced,'Recorded invoices'],['Paid',f.paid,'Recorded payments'],['Labour',f.labour,`${Math.round(f.labourMinutes/60)} h logged on project tasks`],['Expenses',f.expenses,'Recorded expenses'],['Actual cost',f.actual,'Received or invoiced + expenses + labour'],['Remaining',f.remaining,'Budget − actual − committed'],['Forecast at completion',f.forecastAtCompletion,'Actual + committed + recorded forecasts'],['Variance',f.variance,'Budget − forecast']];
 const max=Math.max(1,f.approved,f.forecastAtCompletion);
 return <div className="stack">
  <Note>Every figure comes from records linked to this project. Nothing is estimated.</Note>
  <div className="finance-bars" aria-label="Budget versus forecast">{[['Budget',f.approved,'fb-budget'],['Actual',f.actual,'fb-actual'],['Committed',f.committed,'fb-committed'],['Forecast',f.forecastAtCompletion,'fb-forecast']].map(([l,v,cl])=><div key={l as string} className="fb-row"><span>{l}</span><span className="fb-track"><i className={cl as string} style={{width:`${(v as number)/max*100}%`}}/></span><b>{money(v as number,c)}</b></div>)}</div>
  <table className="plain"><tbody>{rows.map(([l,v,h])=><tr key={l}><td><b>{l}</b><br/><small className="muted">{h}</small></td><td className={cx('num',(l==='Variance'||l==='Remaining')&&v<0&&'text-danger')}>{money(v,c)}</td></tr>)}</tbody></table>
  <Card title="Linked procurement" actions={d.canManage&&<><Btn size="sm" icon="Link" onClick={()=>setLinking('PR')}>Link requisition</Btn><Btn size="sm" icon="Link" onClick={()=>setLinking('PO')}>Link order</Btn>{can('requests','create')&&<Btn size="sm" icon="Plus" onClick={()=>go(`purchasing/pr/new?project=${d.project.id}`)}>New requisition</Btn>}</>}>
   {f.documents.length?<table className="plain"><tbody>{f.documents.map(x=><tr key={x.id}><td><a href={`#/purchasing/x/${x.id}`}>{x.number}</a></td><td>{x.title}</td><td>{x.status}</td><td className="num">{money(x.total,x.currency)}</td><td>{d.canManage&&<Btn size="sm" variant="ghost" icon="Unlink" title="Unlink" onClick={()=>act({action:'unlink',type:x.kind,recordId:x.id},'Unlinked')}/>}</td></tr>)}</tbody></table>:<p className="muted small">No requisitions or orders are linked yet.</p>}
  </Card>
  {d.canManage&&<Card title="Invoices, payments, expenses and forecasts" actions={<Btn size="sm" icon="Plus" onClick={()=>setCost(true)}>Record</Btn>}>{d.costs.length?<table className="plain"><tbody>{d.costs.map(x=><tr key={x.id}><td>{x.date}</td><td><Chip tone="gray">{x.kind}</Chip></td><td>{x.description}</td><td className="num">{money(x.amount,c)}</td><td><Btn size="sm" variant="ghost" icon="Trash2" title="Remove" onClick={async()=>{if(await ask({title:'Remove this entry?',confirm:'Remove',danger:true})!==false)act({action:'cost-delete',costId:x.id},'Removed')}}/></td></tr>)}</tbody></table>:<p className="muted small">None recorded.</p>}</Card>}
  {d.assets.length>0&&<Card title="Assets from this project">{d.assets.map(a=><a key={a.id} className="mini-row" href={`#/assets/${a.id}`}><Icon name="Package" size={14}/><span>{a.code} · {a.name}<small>{a.status}</small></span></a>)}</Card>}
  {linking&&<LinkDoc kind={linking} onClose={()=>setLinking(null)} onPick={id=>{act({action:'link',type:linking,recordId:id},'Linked');setLinking(null)}}/>}
  {cost&&<CostForm currency={c} onClose={()=>setCost(false)} onSave={v=>{act({action:'cost',...v},'Recorded');setCost(false)}}/>}
 </div>;
}
function LinkDoc({kind,onClose,onPick}:{kind:string,onClose:()=>void,onPick:(id:string)=>void}){
 const {data,error}=useApi<{docs:{id:string,number:string,title:string,status:string,total:number,currency:string,project_id?:string|null}[]}>(`/api/purchasing?kind=${kind}`);const [q,setQ]=useState('');
 const rows=(data?.docs||[]).filter(d=>!d.project_id&&(!q||`${d.number} ${d.title}`.toLowerCase().includes(q.toLowerCase()))).slice(0,50);
 return <Modal open onClose={onClose} title={`Link a ${kind==='PR'?'requisition':'purchase order'}`}><ErrorNote error={error}/><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search…" aria-label="Search documents" autoFocus/>{!data?<Skeleton/>:<div className="mini-list">{rows.map(d=><button key={d.id} className="mini-row" onClick={()=>onPick(d.id)}><Icon name="FileText" size={14}/><span>{d.number} · {d.title}<small>{d.status} · {money(d.total,d.currency)}</small></span></button>)}{!rows.length&&<p className="muted small">No unlinked documents you can see.</p>}</div>}</Modal>;
}
function CostForm({currency,onClose,onSave}:{currency:string,onClose:()=>void,onSave:(v:Record<string,unknown>)=>void}){
 const [v,setV]=useState({kind:'invoice',description:'',amount:'',date:new Date().toISOString().slice(0,10)});
 return <Modal open onClose={onClose} title="Record a cost" footer={<><Btn variant="ghost" onClick={onClose}>Cancel</Btn><Btn variant="primary" disabled={!v.description.trim()||!(Number(v.amount)>=0)||v.amount===''} onClick={()=>onSave({...v,amount:Number(v.amount)})}>Record</Btn></>}><div className="form-grid"><Field label="Type"><select value={v.kind} onChange={e=>setV({...v,kind:e.target.value})}><option value="invoice">Invoice</option><option value="payment">Payment</option><option value="expense">Expense</option><option value="forecast">Forecast (remaining work)</option></select></Field><Field label="Date"><input type="date" value={v.date} onChange={e=>setV({...v,date:e.target.value})}/></Field><Field label="Description" wide><input value={v.description} onChange={e=>setV({...v,description:e.target.value})}/></Field><Field label={`Amount (${currency})`}><input type="number" min="0" step="0.01" value={v.amount} onChange={e=>setV({...v,amount:e.target.value})}/></Field></div></Modal>;
}
function Team({d,act}:{d:Detail,act:(b:Record<string,unknown>,m?:string)=>Promise<void>}){
 const [add,setAdd]=useState<string|null>(null);const [role,setRole]=useState('member');const [alloc,setAlloc]=useState('100');
 const load=useMemo(()=>{const m=new Map<string,number>();for(const t of d.tasks)if(!['Done','Cancelled'].includes(t.status))for(const a of t.assignees)m.set(a,(m.get(a)||0)+1);return m},[d.tasks]);
 return <div className="stack">{d.canManage&&<div className="row-gap"><div style={{minWidth:240}}><PersonSelect value={add} onChange={setAdd} placeholder="Add a team member…"/></div><select value={role} onChange={e=>setRole(e.target.value)} aria-label="Role">{['member','manager','lead','engineer','contractor','reviewer','stakeholder'].map(r=><option key={r}>{r}</option>)}</select><input type="number" min="0" max="100" value={alloc} onChange={e=>setAlloc(e.target.value)} aria-label="Allocation %" style={{width:80}}/><span className="muted small">%</span><Btn variant="primary" disabled={!add} onClick={()=>{act({action:'members',add:[add],role,allocation:Number(alloc)},'Added');setAdd(null)}}>Add</Btn></div>}
  <table className="grid-table"><thead><tr><th>Person</th><th>Role</th><th>Allocation</th><th>Open tasks</th><th/></tr></thead><tbody>{d.members.map(m=><tr key={m.id}><td><Who id={m.id} sub/></td><td>{m.role}</td><td>{m.allocation??100}%</td><td>{load.get(m.id)||0}</td><td>{d.canManage&&<Btn size="sm" variant="ghost" icon="X" title="Remove" onClick={()=>act({action:'members',remove:[m.id]},'Removed')}/>}</td></tr>)}</tbody></table></div>;
}
function ProjectFiles({d,reload}:{d:Detail,reload:()=>void}){
 const [up,setUp]=useState(false);
 return <div className="stack"><div className="between"><span className="muted small">Files linked to the project or shared with its team.</span><Btn variant="primary" icon="Upload" onClick={()=>setUp(true)}>Upload</Btn></div>
  {d.files.length?<div className="mini-list">{d.files.map(f=><a key={f.id} className="mini-row" href={`#/files/root/${f.id}`}><Icon name={fileIcon(f.mime)} size={15}/><span>{f.name}<small>{bytes(f.bytes)} · {ago(f.updatedAt)}{f.processingStatus&&f.processingStatus!=='ready'?` · ${f.processingStatus}`:''}</small></span></a>)}</div>:<Empty icon="FolderOpen" title="No files yet"/>}
  {up&&<UploadDialog initial={[]} folderId={null} spaceId={d.space?.id} links={[{type:'project',id:d.project.id}]} defaultAcl={{mode:'project',projectId:d.project.id}} onClose={()=>setUp(false)} onDone={()=>{setUp(false);reload()}}/>}</div>;
}
function EditProject({p,onClose,onDone}:{p:Project,onClose:()=>void,onDone:()=>void}){
 const {toast}=useApp();const [v,setV]=useState({name:p.name,description:p.description,businessCase:p.business_case,department:p.department,location:p.location,ownerId:p.owner_id,managerId:p.manager_id,sponsorId:p.sponsor_id,startDate:p.start_date||'',targetDate:p.target_date||'',priority:p.priority,health:p.health,approvedBudget:String(p.approved_budget||''),progress:String(p.progress),methodology:p.methodology,tags:p.tags});
 const [acl,setAcl]=useState(p.acl||null);
 return <Modal open wide onClose={onClose} title="Edit project" footer={<><Btn variant="ghost" onClick={onClose}>Cancel</Btn><Btn variant="primary" onClick={async()=>{try{await api('/api/projects',{action:'update',id:p.id,...v,startDate:v.startDate||null,targetDate:v.targetDate||null,progress:Number(v.progress),acl});toast('Saved');onDone()}catch(e){toast((e as Error).message,'error')}}}>Save</Btn></>}>
  <div className="form-grid"><Field label="Name" wide><input value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></Field><Field label="Description" wide><textarea rows={3} value={v.description} onChange={e=>setV({...v,description:e.target.value})}/></Field><Field label="Business case" wide><textarea rows={3} value={v.businessCase} onChange={e=>setV({...v,businessCase:e.target.value})}/></Field>
   <Field label="Manager"><PersonSelect value={v.managerId} onChange={id=>setV({...v,managerId:id})}/></Field><Field label="Owner"><PersonSelect value={v.ownerId} onChange={id=>setV({...v,ownerId:id})}/></Field><Field label="Sponsor"><PersonSelect value={v.sponsorId} onChange={id=>setV({...v,sponsorId:id})}/></Field><Field label="Department"><DeptSelect value={v.department} onChange={x=>setV({...v,department:x})}/></Field>
   <Field label="Start"><input type="date" value={v.startDate} onChange={e=>setV({...v,startDate:e.target.value})}/></Field><Field label="Target"><input type="date" value={v.targetDate} onChange={e=>setV({...v,targetDate:e.target.value})}/></Field><Field label={`Approved budget (${p.currency})`}><input type="number" min="0" value={v.approvedBudget} onChange={e=>setV({...v,approvedBudget:e.target.value})}/></Field><Field label="Progress %"><input type="number" min="0" max="100" value={v.progress} onChange={e=>setV({...v,progress:e.target.value})}/></Field>
   <Field label="Health"><select value={v.health} onChange={e=>setV({...v,health:e.target.value})}><option value="green">Green</option><option value="amber">Amber</option><option value="red">Red</option></select></Field><Field label="Priority"><select value={v.priority} onChange={e=>setV({...v,priority:e.target.value})}>{['Low','Medium','High','Critical'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Methodology"><select value={v.methodology} onChange={e=>setV({...v,methodology:e.target.value})}>{['waterfall','kanban','scrum','hybrid','custom'].map(m=><option key={m}>{m}</option>)}</select></Field><Field label="Location"><input value={v.location} onChange={e=>setV({...v,location:e.target.value})}/></Field>
   <Field label="Who can see this project" wide><label className="check"><input type="checkbox" checked={!acl} onChange={e=>setAcl(e.target.checked?null:{mode:'project',projectId:p.id})}/>Team and the department (default)</label>{acl&&<AudiencePicker value={acl} onChange={setAcl}/>}</Field>
  </div></Modal>;
}
function Workflows(){
 const {toast,ask,s}=useApp();const {data,error,reload}=useApi<{workflows:{id:string,name:string,projectType:string,isDefault:boolean,stages:Stage[]}[],defaults:Record<string,{name:string,stages:Stage[]}>,types:string[]}>('/api/projects?view=workflows');const [edit,setEdit]=useState<{id?:string,name:string,projectType:string,isDefault:boolean,stages:Stage[]}|null>(null);
 if(s.user.role!=='admin')return <div className="page"><Empty icon="Lock" title="Administrators only"/></div>;
 return <div className="page"><Header icon="Workflow" tone="violet" title="Project lifecycles" subtitle="Stages, allowed transitions, required information and approval gates per project type." actions={<Btn variant="primary" icon="Plus" onClick={()=>setEdit({name:'',projectType:'',isDefault:false,stages:data?.defaults.internal.stages||[]})}>New lifecycle</Btn>}/><ErrorNote error={error} onRetry={reload}/>
  {!data?<Skeleton/>:<><h2 className="section-title">Company lifecycles</h2>{data.workflows.map(w=><Card key={w.id} title={<>{w.name} <small className="muted">{w.projectType?TYPE_LABEL[w.projectType]:'any type'}</small></>} actions={<><Btn size="sm" icon="Pencil" onClick={()=>setEdit(w)}>Edit</Btn><Btn size="sm" variant="ghost" icon="Trash2" title="Delete" onClick={async()=>{if(await ask({title:`Delete ${w.name}?`,confirm:'Delete',danger:true})===false)return;try{await api('/api/projects',{action:'workflow-delete',id:w.id});reload()}catch(e){toast((e as Error).message,'error')}}}/></>}><StageStrip stages={w.stages}/></Card>)}{!data.workflows.length&&<p className="muted">None yet: projects use the built-in lifecycles below.</p>}
   <h2 className="section-title">Built-in lifecycles</h2>{Object.entries(data.defaults).map(([k,w])=><Card key={k} title={w.name} actions={<Btn size="sm" icon="Copy" onClick={()=>setEdit({name:`${w.name} (company)`,projectType:k,isDefault:true,stages:w.stages})}>Customise</Btn>}><StageStrip stages={w.stages}/></Card>)}</>}
  {edit&&<WorkflowEditor w={edit} types={data?.types||[]} onClose={()=>setEdit(null)} onDone={()=>{setEdit(null);reload()}}/>}
 </div>;
}
const StageStrip=({stages}:{stages:Stage[]})=><div className="lifecycle small">{stages.map((s,i)=><div key={s.id} className="stage"><span>{i+1}</span><b>{s.name}</b>{s.approval&&<small><Icon name="Stamp" size={11}/> {s.approverRole}</small>}{!!s.requires?.length&&<small>needs {s.requires.map(f=>FIELD_LABEL[f]).join(', ')}</small>}</div>)}</div>;
function WorkflowEditor({w,types,onClose,onDone}:{w:{id?:string,name:string,projectType:string,isDefault:boolean,stages:Stage[]},types:string[],onClose:()=>void,onDone:()=>void}){
 const {toast}=useApp();const [v,setV]=useState(w);
 const setStage=(i:number,x:Partial<Stage>)=>setV({...v,stages:v.stages.map((s,j)=>j===i?{...s,...x}:s)});
 return <Modal open wide onClose={onClose} title={w.id?'Edit lifecycle':'New lifecycle'} footer={<><Btn variant="ghost" onClick={onClose}>Cancel</Btn><Btn variant="primary" onClick={async()=>{try{await api('/api/projects',{action:'workflow-save',...v});toast('Saved');onDone()}catch(e){toast((e as Error).message,'error')}}}>Save</Btn></>}>
  <div className="form-grid"><Field label="Name"><input value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></Field><Field label="Project type"><select value={v.projectType} onChange={e=>setV({...v,projectType:e.target.value})}><option value="">Any</option>{types.map(t=><option key={t} value={t}>{TYPE_LABEL[t]}</option>)}</select></Field><label className="check"><input type="checkbox" checked={v.isDefault} onChange={e=>setV({...v,isDefault:e.target.checked})}/>Default for this type</label></div>
  <table className="plain wf-table"><thead><tr><th>Stage</th><th>Required information</th><th>Approval</th><th>Can move to</th><th/></tr></thead><tbody>{v.stages.map((s,i)=><tr key={i}>
   <td><input value={s.name} aria-label="Stage name" onChange={e=>setStage(i,{name:e.target.value,...(w.id||s.id?{}:{id:e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-')})})}/><br/><small className="muted">{s.id}</small></td>
   <td>{Object.entries(FIELD_LABEL).map(([f,l])=><label key={f} className="check small"><input type="checkbox" checked={!!s.requires?.includes(f)} onChange={e=>setStage(i,{requires:e.target.checked?[...(s.requires||[]),f]:(s.requires||[]).filter(x=>x!==f)})}/>{l}</label>)}</td>
   <td><label className="check"><input type="checkbox" checked={!!s.approval} onChange={e=>setStage(i,{approval:e.target.checked,approverRole:s.approverRole||'admin'})}/>Needs approval</label>{s.approval&&<select value={s.approverRole} onChange={e=>setStage(i,{approverRole:e.target.value})} aria-label="Approver"><option value="admin">Administrator</option><option value="manager">Department manager</option><option value="sponsor">Project sponsor</option></select>}</td>
   <td>{v.stages.filter(x=>x.id!==s.id).map(x=><label key={x.id} className="check small"><input type="checkbox" checked={s.next.includes(x.id)} onChange={e=>setStage(i,{next:e.target.checked?[...s.next,x.id]:s.next.filter(n=>n!==x.id)})}/>{x.name}</label>)}</td>
   <td><Btn size="sm" variant="ghost" icon="X" title="Remove stage" onClick={()=>setV({...v,stages:v.stages.filter((_,j)=>j!==i).map(x=>({...x,next:x.next.filter(n=>n!==s.id)}))})}/></td></tr>)}</tbody></table>
  <Btn size="sm" icon="Plus" onClick={()=>{const id=`stage-${v.stages.length+1}`;setV({...v,stages:[...v.stages,{id,name:`Stage ${v.stages.length+1}`,next:[]}]})}}>Add stage</Btn>
 </Modal>;
}
function Templates(){
 const {toast,ask,s}=useApp();const {data,error,reload}=useApi<{templates:{id:string,name:string,projectType:string,methodology:string,createdAt:string,payload:string}[]}>('/api/projects?view=templates');
 return <div className="page"><Header icon="LayoutTemplate" tone="violet" title="Project templates" subtitle="Save a project as a template from its menu; new projects can start from one."/><ErrorNote error={error} onRetry={reload}/>{!data?<Skeleton/>:!data.templates.length?<Empty icon="LayoutTemplate" title="No templates yet">Open a project and choose “Save as template”.</Empty>:<table className="grid-table"><thead><tr><th>Name</th><th>Type</th><th>Methodology</th><th>Contents</th><th>Created</th><th/></tr></thead><tbody>{data.templates.map(t=>{let n={records:0,tasks:0};try{const x=JSON.parse(t.payload);n={records:(x.records||[]).length,tasks:(x.tasks||[]).length}}catch{};return <tr key={t.id}><td><b>{t.name}</b></td><td>{TYPE_LABEL[t.projectType]}</td><td>{t.methodology}</td><td>{n.records} plan items · {n.tasks} tasks</td><td>{ago(t.createdAt)}</td><td>{s.user.role==='admin'&&<Btn size="sm" variant="ghost" icon="Trash2" title="Delete" onClick={async()=>{if(await ask({title:`Delete ${t.name}?`,confirm:'Delete',danger:true})===false)return;try{await api('/api/projects',{action:'template-delete',id:t.id});reload()}catch(e){toast((e as Error).message,'error')}}}/>}</td></tr>})}</tbody></table>}</div>;
}
export {TaskForm,Avatar};
