'use client';
import {useState} from 'react';
import {api,useApi,go,ago,cx,dateOnly} from './lib';
import {useApp,Btn,Chip,Header,Field,ErrorNote,Skeleton,Empty,Icon,Card,Tabs,Note,PersonSelect} from './kit';
import {ConnectedContext} from './context';
import {WorkEditor} from './business';
import {workKindById} from '../work-records';

// Goals-to-execution: company strategy → objectives → key results → initiatives → programmes → projects →
// milestones → tasks. Progress is rolled up from real records; every figure shows how it was calculated.
type Item={id:string,kind:string,number:string,title:string,status:string,parentId:string|null,ownerId:string|null,department:string,progress:number,start:string|null,end:string|null,amount:number|null,visibility:string,data:Record<string,unknown>};
type Proj={id:string,code:string,name:string,progress:number,health:string,stage:string,targetDate:string|null,milestones:{id:string,title:string,status:string,due_date:string|null}[],tasks:{n:number,done:number}};
type Rollup={progress:number|null,method:string,sources:{type:string,id:string,title:string,value:number|null,weight?:number,detail?:string,updatedAt?:string|null,url?:string}[],missing:string[],override:{value:number,reason:string,by:string,at:string}|null,confidence:number|null,health:string,healthBasis:string,lastUpdated:string|null,budget?:{approved:number,actual:number,committed:number,consumedPct:number|null}|null,benefits?:{name:string,expected:number,actual:number|null}[]};
export const strategyViews=[{id:'goals',label:'Strategy map',icon:'Compass'},{id:'objectives',label:'Objectives & key results',icon:'Crosshair'},{id:'initiatives',label:'Initiatives',icon:'Rocket'},{id:'programmes',label:'Programmes',icon:'FolderTree'},{id:'portfolio',label:'Portfolio',icon:'LayoutDashboard',section:'Execution'},{id:'capacity',label:'Capacity',icon:'Users',section:'Execution'},{id:'scenarios',label:'Scenarios',icon:'GitBranch',section:'Execution'},{id:'check-ins',label:'Check-ins',icon:'Gauge',section:'Rhythm'},{id:'reviews',label:'Reviews',icon:'Presentation',section:'Rhythm'},{id:'reports',label:'Reports',icon:'ChartColumn',section:'Rhythm'},{id:'periods',label:'Planning periods',icon:'CalendarRange',section:'Setup'}];
const HEALTH_TONE=(h:string)=>h==='On track'?'green':h==='At risk'?'amber':h==='Off track'?'red':'gray';
const Bar=({v}:{v:number|null})=><span className="pbar" title={v==null?'No data':`${v}%`}><i style={{width:`${v??0}%`}}/><b>{v==null?'—':`${v}%`}</b></span>;

export default function Strategy({parts=[]}:{parts?:string[]}){
 const v=parts[0]||'goals';
 if(v==='item')return parts[2]==='edit'?<EditItem id={parts[1]}/>:<ItemPage id={parts[1]} tab={parts[2]||'overview'}/>;
 if(v==='new')return <NewItem kind={parts[1]||'objective'}/>;
 if(v==='portfolio')return <Portfolio/>;if(v==='capacity')return <Capacity/>;if(v==='scenarios')return parts[1]?<Scenario id={parts[1]}/>:<Scenarios/>;
 if(v==='check-ins')return <CheckIns/>;if(v==='reviews')return parts[1]?<Review id={parts[1]}/>:<Reviews/>;if(v==='reports')return <Reports/>;if(v==='periods')return <Periods/>;
 return <Tree kinds={v==='objectives'?['objective','key_result']:v==='initiatives'?['initiative']:v==='programmes'?['programme']:null} title={strategyViews.find(x=>x.id===v)?.label||'Strategy map'}/>;
}
function Tree({kinds,title}:{kinds:string[]|null,title:string}){
 const [period,setPeriod]=useState('');const {data,error,reload}=useApi<{items:Item[],projects:Proj[],periods:{id:string,name:string}[],canPlan:boolean,canCreate:boolean}>(`/api/strategy?view=tree&period=${period}`);const {person}=useApp();const [open,setOpen]=useState<Record<string,boolean>>({});
 if(error)return <div className="page"><ErrorNote error={error} onRetry={reload}/></div>;if(!data)return <div className="page"><Skeleton rows={10}/></div>;
 const byParent=new Map<string,Item[]>();for(const i of data.items){const k=i.parentId&&data.items.some(x=>x.id===i.parentId)?i.parentId:'root';byParent.set(k,[...(byParent.get(k)||[]),i])}
 const projOf=(i:Item)=>(Array.isArray(i.data.projects)?i.data.projects as string[]:[]).map(id=>data.projects.find(p=>p.id===id)).filter((p):p is Proj=>!!p);
 const row=(i:Item,depth:number):React.ReactNode=>{const kids=byParent.get(i.id)||[];const ps=projOf(i);const exp=open[i.id]!==false;const k=workKindById.get(i.kind);
  return <div key={i.id}><div className="tree-row" style={{paddingLeft:depth*18}}>{(kids.length||ps.length)?<button className="icon-btn" aria-label={exp?'Collapse':'Expand'} onClick={()=>setOpen({...open,[i.id]:!exp})}><Icon name={exp?'ChevronDown':'ChevronRight'} size={14}/></button>:<span className="tree-pad"/>}<Icon name={k?.icon||'Circle'} size={15}/><a href={`#/strategy/item/${i.id}`}><small className="muted">{k?.label}</small> {i.title}</a><Chip tone={HEALTH_TONE(String(i.data.health||''))}>{i.status}</Chip><Bar v={i.progress}/><small className="muted">{person(i.ownerId)?.name||''}</small>{i.visibility!=='company'&&<Icon name="Lock" size={12}/>}</div>
   {exp&&<>{kids.map(c=>row(c,depth+1))}{ps.map(p=><div key={p.id}><div className="tree-row" style={{paddingLeft:(depth+1)*18}}><span className="tree-pad"/><Icon name="FolderKanban" size={15}/><a href={`#/projects/${p.id}`}><small className="muted">Project</small> {p.code} · {p.name}</a><Chip tone={p.health==='red'?'red':p.health==='amber'?'amber':'green'}>{p.stage}</Chip><Bar v={p.progress}/><small className="muted">{p.tasks.done}/{p.tasks.n} tasks</small></div>
    {p.milestones.map(m=><div key={m.id} className="tree-row" style={{paddingLeft:(depth+2)*18}}><span className="tree-pad"/><Icon name="Flag" size={14}/><a href={`#/tasks/all/${m.id}`}><small className="muted">Milestone</small> {m.title}</a><Chip tone={m.status==='Done'?'green':'gray'}>{m.status}</Chip><small className="muted">{m.due_date?dateOnly(m.due_date):''}</small></div>)}</div>)}</>}</div>};
 const roots=kinds?data.items.filter(i=>kinds.includes(i.kind)&&!(i.parentId&&kinds.includes(data.items.find(x=>x.id===i.parentId)?.kind||''))):(byParent.get('root')||[]);
 return <div className="page"><Header icon="Compass" tone="violet" title={title} subtitle="Strategy connected to the work that delivers it. Progress rolls up from key results, projects, milestones and tasks." actions={data.canCreate&&<><select aria-label="Planning period" value={period} onChange={e=>setPeriod(e.target.value)}><option value="">All periods</option>{data.periods.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><Btn icon="Plus" variant="primary" onClick={()=>go(`strategy/new/${kinds?.[0]||'strategy'}`)}>New</Btn></>}/>
  {!data.items.length?<Empty icon="Compass" title="No strategy yet" action={data.canCreate&&<Btn variant="primary" icon="Plus" onClick={()=>go('strategy/new/strategy')}>Write the company strategy</Btn>}>Start with the strategy, then objectives and measurable key results; connect initiatives and projects to them.</Empty>:<Card pad={false}><div className="tree">{roots.map(i=>row(i,0))}</div></Card>}
 </div>;
}
function NewItem({kind}:{kind:string}){const k=workKindById.get(kind)||workKindById.get('objective')!;return <WorkEditor kind={k} onSaved={id=>go(`strategy/item/${id}`)}/>}
function EditItem({id}:{id:string}){const {data}=useApi<{record:{kind:string}}>(`/api/strategy?view=item&id=${id}`);if(!data)return <div className="page"><Skeleton/></div>;return <WorkEditor kind={workKindById.get(data.record.kind)!} id={id} onSaved={x=>go(`strategy/item/${x}`)}/>}
type ItemData={record:Item&{description:string,version:number,currency:string},rollup:Rollup,children:{id:string,kind:string,number:string,title:string,status:string,progress:number,ownerId:string|null}[],hiddenChildren:number,checkIns:{id:string,progress:number|null,confidence:number|null,health:string,achievements:string,problems:string,risks:string,decisions_needed:string,next_steps:string,forecast:string,status:string,ai_drafted:number,citations:{n:number,title:string,link:string}[],author_id:string,created_at:string,submitted_at:string|null}[],updates:{id:string,value:number,previousValue:number|null,progress:number|null,source:string,ref:string,lineage:Record<string,unknown>,note:string,status:string,actor:string,createdAt:string}[],versions:{version:number,published:number,createdAt:string}[],acknowledged:boolean,ackCount:number,canUpdate:boolean,canPlan:boolean};
function ItemPage({id,tab}:{id:string,tab:string}){
 const {toast,person,ask}=useApp();const {data,error,reload}=useApi<ItemData>(`/api/strategy?view=item&id=${id}`);
 if(error)return <div className="page"><ErrorNote error={error} onRetry={reload}/></div>;if(!data)return <div className="page"><Skeleton rows={10}/></div>;
 const r=data.record;const ro=data.rollup;const k=workKindById.get(r.kind);
 const post=async(action:string,extra:Record<string,unknown>={},msg='Saved')=>{try{await api('/api/strategy',{action,id:r.id,...extra});toast(msg);reload()}catch(e){toast((e as Error).message,'error')}};
 const childKind=r.kind==='strategy'?'objective':r.kind==='theme'||r.kind==='goal'?'objective':r.kind==='objective'?'key_result':r.kind==='key_result'?'initiative':r.kind==='initiative'?'programme':null;
 return <div className="page"><Header icon={k?.icon||'Target'} tone="violet" title={<>{r.number} · {r.title}</>} subtitle={<span className="row-gap wrap"><Chip tone={HEALTH_TONE(ro.health)}>{ro.health}</Chip><span>{k?.label}</span><span>· {r.status}</span><span>· {person(r.ownerId)?.name||'No owner'}</span>{r.visibility!=='company'&&<Chip tone="violet"><Icon name="Lock" size={11}/> {r.visibility}</Chip>}</span>}
  actions={<>{data.canUpdate&&<Btn icon="Pencil" onClick={()=>go(`strategy/item/${r.id}/edit`)}>Edit</Btn>}{childKind&&<Btn icon="Plus" onClick={()=>go(`strategy/new/${childKind}?parent=${r.id}`)}>Add {workKindById.get(childKind)?.label.toLowerCase()}</Btn>}{r.kind==='strategy'&&data.canPlan&&<Btn icon="Megaphone" onClick={()=>post('publish',{},'Published')}>Publish</Btn>}{r.kind==='strategy'&&r.status==='Published'&&!data.acknowledged&&<Btn variant="primary" icon="ThumbsUp" onClick={()=>post('acknowledge',{},'Acknowledged')}>Acknowledge</Btn>}</>}/>
  <Tabs value={tab} onChange={t=>go(`strategy/item/${r.id}/${t}`)} items={[{id:'overview',label:'Overview'},{id:'check-ins',label:'Check-ins',count:data.checkIns.length},{id:'updates',label:'Updates & lineage',count:data.updates.length},{id:'connected',label:'Connected work'},{id:'versions',label:'Versions',count:data.versions.length}]}/>
  {tab==='overview'&&<><div className="cards-2">
   <Card title="Progress" actions={data.canUpdate&&(ro.override?<Btn size="sm" variant="ghost" onClick={()=>post('clear-override',{},'Override removed')}>Remove override</Btn>:<Btn size="sm" variant="ghost" onClick={async()=>{const v=await ask({title:'Override progress',input:{label:'Progress % (0–100)',type:'number',required:true},confirm:'Next'});if(v===false)return;const why=await ask({title:'Why override the calculation?',input:{label:'Reason',required:true},confirm:'Override'});if(why)post('override',{value:Number(v),reason:why},'Overridden')}}>Override</Btn>)}>
    <div className="big-progress"><Bar v={ro.progress}/></div>
    <dl className="kv-list"><dt>Calculation</dt><dd>{ro.method||'—'}</dd><dt>Health</dt><dd>{ro.health} <small className="muted">({ro.healthBasis})</small></dd><dt>Confidence</dt><dd>{ro.confidence==null?'—':`${ro.confidence}%`}</dd><dt>Last updated</dt><dd>{ro.lastUpdated?ago(ro.lastUpdated):'—'}</dd>{ro.override&&<><dt>Manual override</dt><dd>{ro.override.value}% by {person(ro.override.by)?.name||''} — “{ro.override.reason}”</dd></>}</dl>
    {ro.missing.length>0&&<Note tone="warn">Missing data: {ro.missing.join('; ')}</Note>}
    {ro.budget&&<p className="small">Budget: {ro.budget.approved.toLocaleString()} approved · {ro.budget.actual.toLocaleString()} spent · {ro.budget.committed.toLocaleString()} committed{ro.budget.consumedPct!=null?` · ${ro.budget.consumedPct}% consumed`:''}</p>}
    {(ro.benefits||[]).length>0&&<p className="small">Benefits: {ro.benefits!.map(b=>`${b.name} ${b.actual??'—'}/${b.expected}`).join(' · ')}</p>}
   </Card>
   <Card title="Where the number comes from">{!ro.sources.length?<p className="muted small">No contributing records yet.</p>:<table className="plain small"><thead><tr><th>Source</th><th>Value</th><th>Weight</th><th>Updated</th></tr></thead><tbody>{ro.sources.map((x,i)=><tr key={i}><td>{x.url?<a href={x.url}>{x.title}</a>:x.title} <small className="muted">{x.type}</small></td><td>{x.value==null?'—':x.value}</td><td>{x.weight??''}</td><td className="muted">{x.updatedAt?ago(x.updatedAt):''}</td></tr>)}</tbody></table>}{data.hiddenChildren>0&&<p className="muted small"><Icon name="Lock" size={12}/> {data.hiddenChildren} contributing record(s) are restricted.</p>}</Card>
  </div>
  {r.kind==='key_result'&&data.canUpdate&&<KrSource r={r} onSaved={reload}/>}
  {r.kind==='strategy'&&<Card title="Strategy"><dl className="kv-list"><dt>Mission</dt><dd>{String(r.data.mission||'—')}</dd><dt>Vision</dt><dd>{String(r.data.vision||'—')}</dd><dt>Priorities</dt><dd className="pre">{String(r.data.priorities||'—')}</dd><dt>Acknowledged by</dt><dd>{data.ackCount} people</dd></dl></Card>}
  {r.description&&<Card title="Description"><p>{r.description}</p></Card>}
  <Card title="Contributing records">{!data.children.length?<p className="muted small">None yet.</p>:<ul className="mini-list">{data.children.map(c=><li key={c.id} className="mini-row"><Icon name={workKindById.get(c.kind)?.icon||'Circle'} size={14}/><a href={`#/strategy/item/${c.id}`}>{c.number} · {c.title}</a><Chip tone="gray">{c.status}</Chip><Bar v={c.progress}/></li>)}</ul>}</Card></>}
  {tab==='check-ins'&&<CheckInsFor d={data} onChanged={reload}/>}
  {tab==='updates'&&<Card title="Progress updates with source lineage">{!data.updates.length?<p className="muted small">No updates yet.</p>:<table className="plain small"><thead><tr><th>When</th><th>Value</th><th>Source</th><th>Lineage</th><th>Status</th><th/></tr></thead><tbody>{data.updates.map(u=><tr key={u.id}><td>{ago(u.createdAt)}</td><td>{u.previousValue!=null?`${u.previousValue} → `:''}{u.value}</td><td>{u.source.replace(/_/g,' ')}</td><td className="mono">{JSON.stringify(u.lineage).slice(0,140)}</td><td><Chip tone={u.status==='draft'?'amber':u.status==='rejected'?'red':'green'}>{u.status}</Chip></td><td>{u.status==='draft'&&data.canUpdate&&<><Btn size="sm" onClick={()=>post('update-decide',{updateId:u.id,approve:true},'Accepted')}>Accept</Btn><Btn size="sm" variant="ghost" onClick={()=>post('update-decide',{updateId:u.id,approve:false},'Rejected')}>Reject</Btn></>}</td></tr>)}</tbody></table>}</Card>}
  {tab==='connected'&&<ConnectedContext type={r.kind} id={r.id} title="Connected work"/>}
  {tab==='versions'&&<Card title="Version history"><ul className="mini-list">{data.versions.map(v=><li key={v.version} className="mini-row"><b>v{v.version}</b>{v.published?<Chip tone="green">published</Chip>:null}<span className="muted">{ago(v.createdAt)}</span></li>)}</ul></Card>}
 </div>;
}
function KrSource({r,onSaved}:{r:Item,onSaved:()=>void}){
 const {toast}=useApp();const cur=(r.data.dataSource||{kind:'manual'}) as Record<string,string>;const [v,setV]=useState<Record<string,string>>(cur);
 const projects=useApi<{projects:{id:string,code:string,name:string}[]}>('/api/projects');
 return <Card title="Automatic value source" actions={<Btn size="sm" variant="primary" onClick={async()=>{try{const {kind,...source}=v;await api('/api/strategy',{action:'set-source',id:r.id,kind:kind||'manual',source});toast('Source saved');onSaved()}catch(e){toast((e as Error).message,'error')}}}>Save</Btn>}>
  <p className="muted small">Values from a source are read with the owner’s permissions and every change is stored with its lineage.</p>
  <div className="form-grid"><Field label="Source"><select value={v.kind||'manual'} onChange={e=>setV({kind:e.target.value})}><option value="manual">Manual</option><option value="project">Project progress</option><option value="purchasing">Purchasing / finance</option><option value="asset">Asset count</option><option value="report">Studio report</option><option value="connector">Connector (live count)</option></select></Field>
   {v.kind==='project'&&<Field label="Project"><select value={v.projectId||''} onChange={e=>setV({...v,projectId:e.target.value})}><option value="">—</option>{(projects.data?.projects||[]).map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></Field>}
   {v.kind==='purchasing'&&<><Field label="Project"><select value={v.projectId||''} onChange={e=>setV({...v,projectId:e.target.value})}><option value="">—</option>{(projects.data?.projects||[]).map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></Field><Field label="Measure"><select value={v.measure||'actual'} onChange={e=>setV({...v,measure:e.target.value})}>{['actual','committed','ordered','received','budget','remaining','forecast','requested','invoiced','paid'].map(x=><option key={x}>{x}</option>)}</select></Field></>}
   {v.kind==='asset'&&<><Field label="Category"><input value={v.category||''} onChange={e=>setV({...v,category:e.target.value})}/></Field><Field label="Status"><input value={v.status||''} onChange={e=>setV({...v,status:e.target.value})}/></Field></>}
   {v.kind==='report'&&<><Field label="App address"><input value={v.app||''} onChange={e=>setV({...v,app:e.target.value})}/></Field><Field label="Report key"><input value={v.report||''} onChange={e=>setV({...v,report:e.target.value})}/></Field></>}
   {v.kind==='connector'&&<><Field label="Connector id"><input value={v.connectorId||''} onChange={e=>setV({...v,connectorId:e.target.value})}/></Field><Field label="Resource"><input value={v.resource||''} onChange={e=>setV({...v,resource:e.target.value})}/></Field><Field label="Query"><input value={v.query||''} onChange={e=>setV({...v,query:e.target.value})}/></Field></>}
  </div></Card>;
}
function CheckInsFor({d,onChanged}:{d:ItemData,onChanged:()=>void}){
 const {toast,person}=useApp();const r=d.record;const draft=d.checkIns.find(c=>c.status==='draft');
 const [v,setV]=useState(()=>({progress:String(draft?.progress??d.rollup.progress??''),confidence:String(draft?.confidence??''),health:draft?.health||'',achievements:draft?.achievements||'',problems:draft?.problems||'',risks:draft?.risks||'',decisionsNeeded:draft?.decisions_needed||'',nextSteps:draft?.next_steps||'',forecast:draft?.forecast||'',value:''}));const [busy,setBusy]=useState('');
 const save=async(submit:boolean)=>{setBusy(submit?'submit':'save');try{await api('/api/strategy',{action:'check-in',id:r.id,checkInId:draft?.id,submit,...v});toast(submit?'Check-in submitted':'Draft saved');onChanged()}catch(e){toast((e as Error).message,'error')}finally{setBusy('')}};
 return <>{d.canUpdate&&<Card title={draft?(draft.ai_drafted?'AI-drafted check-in (review before submitting)':'Draft check-in'):'New check-in'} actions={<Btn size="sm" icon="Sparkles" busy={busy==='ai'} onClick={async()=>{setBusy('ai');try{await api('/api/strategy',{action:'draft-check-in',id:r.id});toast('Draft created from cited evidence');onChanged()}catch(e){toast((e as Error).message,'error')}finally{setBusy('')}}}>Draft with AI</Btn>}>
   {draft?.ai_drafted?<Note>This draft was written by AI from the records cited below. Nothing is final until you submit it.</Note>:null}
   <div className="form-grid"><Field label="Progress %"><input type="number" min={0} max={100} value={v.progress} onChange={e=>setV({...v,progress:e.target.value})}/></Field><Field label="Confidence %"><input type="number" min={0} max={100} value={v.confidence} onChange={e=>setV({...v,confidence:e.target.value})}/></Field><Field label="Health"><select value={v.health} onChange={e=>setV({...v,health:e.target.value})}><option value="">—</option>{['On track','At risk','Off track'].map(x=><option key={x}>{x}</option>)}</select></Field>{r.kind==='key_result'&&<Field label="New value (optional)"><input type="number" value={v.value} onChange={e=>setV({...v,value:e.target.value})}/></Field>}
    {([['achievements','Achievements'],['problems','Problems'],['risks','Risks'],['decisionsNeeded','Decisions needed'],['nextSteps','Next steps'],['forecast','Updated forecast']] as const).map(([k,l])=><Field key={k} label={l} wide><textarea rows={2} value={v[k]} onChange={e=>setV({...v,[k]:e.target.value})}/></Field>)}</div>
   {draft&&draft.citations.length>0&&<p className="small">Sources: {draft.citations.map(c=><a key={c.n} className="chip chip-gray" href={c.link}>[E{c.n}] {c.title}</a>)}</p>}
   <div className="row-gap"><Btn busy={busy==='save'} onClick={()=>save(false)}>Save draft</Btn><Btn variant="primary" busy={busy==='submit'} onClick={()=>save(true)}>Submit check-in</Btn></div></Card>}
  <Card title="History">{d.checkIns.filter(c=>c.status==='submitted').map(c=><div key={c.id} className="checkin"><p><b>{c.submitted_at?dateOnly(c.submitted_at):''}</b> · {person(c.author_id)?.name} · {c.progress??'—'}% · confidence {c.confidence??'—'}% <Chip tone={HEALTH_TONE(c.health)}>{c.health||'—'}</Chip>{c.ai_drafted?<Chip tone="violet">AI-assisted</Chip>:null}</p>{c.achievements&&<p className="small"><b>Achievements:</b> {c.achievements}</p>}{c.problems&&<p className="small"><b>Problems:</b> {c.problems}</p>}{c.decisions_needed&&<p className="small"><b>Decisions needed:</b> {c.decisions_needed}</p>}{c.next_steps&&<p className="small"><b>Next:</b> {c.next_steps}</p>}{c.citations.length>0&&<p className="small">{c.citations.map(x=><a key={x.n} className="chip chip-gray" href={x.link}>{x.title}</a>)}</p>}</div>)}{!d.checkIns.some(c=>c.status==='submitted')&&<p className="muted small">No check-ins yet.</p>}</Card></>;
}
type PItem={type:string,id:string,number:string,title:string,owner:string|null,department:string,status:string,priority:string,health:string,progress:number|null,start:string|null,end:string|null,funding:number|null,budget:{approved:number,actual:number,committed:number,consumedPct:number|null}|null,connected:boolean,themeId:string|null,dependsOn:string[],url:string};
function Portfolio(){
 const [filter,setFilter]=useState('all');const [mode,setMode]=useState('list');const [theme,setTheme]=useState('');const {data,error,reload}=useApi<{items:PItem[],themes:{id:string,title:string}[]}>(`/api/strategy?view=portfolio&filter=${filter}&theme=${theme}`);const {person}=useApp();
 const filters=[['all','All'],['initiatives','Initiatives'],['programmes','Programmes'],['projects','Projects'],['risk','At risk'],['unfunded','Unfunded'],['delayed','Delayed'],['unowned','Without an owner'],['unconnected','Not connected to a goal']];
 const modes=[['list','List'],['cards','Cards'],['timeline','Timeline'],['roadmap','Roadmap'],['calendar','Calendar'],['dependencies','Dependencies'],['matrix','Health matrix'],['budget','Budget']];
 const items=data?.items||[];const dated=items.filter(i=>i.start||i.end);const min=dated.reduce((m,i)=>(i.start||i.end!)<m?(i.start||i.end!):m,'9999'),max=dated.reduce((m,i)=>(i.end||i.start!)>m?(i.end||i.start!):m,'0000');const span=Math.max(1,(Date.parse(max)-Date.parse(min))/86400000);
 return <div className="page"><Header icon="LayoutDashboard" tone="violet" title="Portfolio" subtitle="Initiatives, programmes and projects with health, progress, funding and dependencies."/>
  <div className="toolbar wrap"><select aria-label="Filter" value={filter} onChange={e=>setFilter(e.target.value)}>{filters.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><select aria-label="Theme" value={theme} onChange={e=>setTheme(e.target.value)}><option value="">All themes</option>{(data?.themes||[]).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><div className="segmented">{modes.map(([k,l])=><button key={k} className={cx('seg-btn',mode===k&&'on')} onClick={()=>setMode(k)}>{l}</button>)}</div></div>
  <ErrorNote error={error} onRetry={reload}/>
  {!data?<Skeleton/>:!items.length?<Empty icon="LayoutDashboard" title="Nothing matches"/>:
   mode==='cards'?<div className="module-grid">{items.map(i=><a key={i.id} className="module-card" href={i.url}><Icon name={i.type==='project'?'FolderKanban':i.type==='programme'?'FolderTree':'Rocket'} size={18}/><div><b>{i.number} · {i.title}</b><small>{i.type} · {i.status}</small><Bar v={i.progress}/><Chip tone={HEALTH_TONE(i.health)}>{i.health}</Chip></div></a>)}</div>
   :mode==='timeline'||mode==='roadmap'?<Card pad={false}><div className="roadmap">{(mode==='roadmap'?[...new Set(items.map(i=>i.type))]:['']).map(g=><div key={g}>{g&&<p className="rail-section">{g}s</p>}{items.filter(i=>(!g||i.type===g)&&(i.start||i.end)).map(i=>{const s=Date.parse(i.start||i.end!),e=Date.parse(i.end||i.start!);return <div key={i.id} className="rm-row"><a href={i.url} className="rm-label">{i.title}</a><div className="rm-track"><i className={cx('rm-bar',`tone-${HEALTH_TONE(i.health)}`)} style={{left:`${(s-Date.parse(min))/86400000/span*100}%`,width:`${Math.max(1.5,(e-s)/86400000/span*100)}%`}} title={`${i.start||'?'} → ${i.end||'?'} · ${i.progress??'—'}%`}/></div></div>})}</div>)}<div className="rm-scale"><span>{min}</span><span>{max}</span></div></div></Card>
   :mode==='calendar'?<ul className="lb-cal">{items.filter(i=>i.end).sort((a,b)=>String(a.end).localeCompare(String(b.end))).map(i=><li key={i.id}><span className="lb-date">{i.end}</span><a href={i.url}>{i.title}</a><Chip tone={HEALTH_TONE(i.health)}>{i.health}</Chip></li>)}</ul>
   :mode==='dependencies'?<Card title="Dependency map">{items.filter(i=>i.dependsOn.length).map(i=><p key={i.id} className="small"><a href={i.url}>{i.title}</a> depends on {i.dependsOn.map(d=>items.find(x=>x.id===d)?.title||'a restricted record').join(', ')}</p>)}{!items.some(i=>i.dependsOn.length)&&<p className="muted small">No dependencies recorded. Add “depends on” links on initiatives or projects.</p>}</Card>
   :mode==='matrix'?<div className="matrix">{['Critical','High','Medium','Low',''].map(p=><div key={p} className="matrix-row"><b>{p||'No priority'}</b>{['On track','At risk','Off track','Unknown'].map(h=><div key={h} className={cx('matrix-cell',`tone-${HEALTH_TONE(h)}`)}>{items.filter(i=>(i.priority||'')===p&&i.health===h).map(i=><a key={i.id} href={i.url} className="chip chip-gray">{i.number}</a>)}</div>)}</div>)}<div className="matrix-row"><b/>{['On track','At risk','Off track','Unknown'].map(h=><small key={h} className="muted">{h}</small>)}</div></div>
   :mode==='budget'?<table className="plain"><thead><tr><th>Item</th><th>Approved</th><th>Actual</th><th>Committed</th><th>Consumed</th></tr></thead><tbody>{items.filter(i=>i.budget||i.funding).map(i=><tr key={i.id}><td><a href={i.url}>{i.title}</a></td><td>{(i.budget?.approved??i.funding??0).toLocaleString()}</td><td>{(i.budget?.actual??0).toLocaleString()}</td><td>{(i.budget?.committed??0).toLocaleString()}</td><td>{i.budget?.consumedPct==null?'—':`${i.budget.consumedPct}%`}</td></tr>)}</tbody></table>
   :<table className="plain"><thead><tr><th>Item</th><th>Type</th><th>Status</th><th>Health</th><th>Progress</th><th>Owner</th><th>Dates</th><th>Goal</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><a href={i.url}>{i.number} · {i.title}</a></td><td>{i.type}</td><td>{i.status}</td><td><Chip tone={HEALTH_TONE(i.health)}>{i.health}</Chip></td><td><Bar v={i.progress}/></td><td>{person(i.owner)?.name||<span className="muted">none</span>}</td><td className="small">{i.start||'?'} → {i.end||'?'}</td><td>{i.connected?<Icon name="Link" size={13}/>:<span className="muted small">not linked</span>}</td></tr>)}</tbody></table>}
 </div>;
}
function Capacity(){
 const {toast,s}=useApp();const [dept,setDept]=useState('');const {data,error,reload}=useApi<{from:string,to:string,rows:{id:string,name:string,department:string,available:number,planned:number,utilisation:number|null,overAllocated:boolean,projects:number,skills:string[],timeOffDays:number|null}[],departments:{name:string,available:number,planned:number,people:number,utilisation:number|null}[],unassignedHours:number,unassigned:{id:string,title:string,hours:number}[],conflicts:{member:string,projects:number,planned:number,available:number}[],note:string}>(`/api/strategy?view=capacity&department=${encodeURIComponent(dept)}`);
 const [hours,setHours]=useState('');
 return <div className="page"><Header icon="Users" tone="violet" title="Capacity" subtitle="Planned work from task estimates against availability for the next four weeks."/>
  <div className="toolbar"><select aria-label="Department" value={dept} onChange={e=>setDept(e.target.value)}><option value="">All departments</option>{s.departments.map(d=><option key={d.name}>{d.name}</option>)}</select><input type="number" placeholder="My hours per week" value={hours} onChange={e=>setHours(e.target.value)} aria-label="My hours per week"/><Btn size="sm" disabled={!hours} onClick={async()=>{try{await api('/api/strategy',{action:'capacity-save',memberId:s.user.id,hoursPerWeek:Number(hours)});toast('Saved');reload()}catch(e){toast((e as Error).message,'error')}}}>Save my capacity</Btn></div>
  <ErrorNote error={error} onRetry={reload}/>{!data?<Skeleton/>:<><Note>{data.note}</Note>
   <Card title="Departments"><table className="plain"><thead><tr><th>Department</th><th>People</th><th>Available h</th><th>Planned h</th><th>Utilisation</th></tr></thead><tbody>{data.departments.map(d=><tr key={d.name}><td>{d.name}</td><td>{d.people}</td><td>{d.available}</td><td>{d.planned}</td><td className={cx((d.utilisation||0)>100&&'overdue')}>{d.utilisation==null?'—':`${d.utilisation}%`}</td></tr>)}</tbody></table></Card>
   <Card title="People you can see in detail"><table className="plain"><thead><tr><th>Person</th><th>Available h</th><th>Planned h</th><th>Utilisation</th><th>Projects</th><th>Time off (days)</th><th>Skills</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.available}</td><td>{r.planned}</td><td className={cx(r.overAllocated&&'overdue')}>{r.utilisation==null?'—':`${r.utilisation}%`}</td><td>{r.projects}</td><td>{r.timeOffDays??'—'}</td><td className="small">{r.skills.join(', ')}</td></tr>)}</tbody></table></Card>
   {data.conflicts.length>0&&<Note tone="warn">Over-allocated across several projects: {data.conflicts.map(c=>`${c.member} (${c.planned}/${c.available} h, ${c.projects} projects)`).join('; ')}</Note>}
   <Card title={`Unassigned work: ${data.unassignedHours} h`}>{data.unassigned.length?<ul className="small">{data.unassigned.map(t=><li key={t.id}><a href={`#/tasks/all/${t.id}`}>{t.title}</a> · {t.hours} h</li>)}</ul>:<p className="muted small">{data.unassignedHours?'Details are visible to managers.':'None.'}</p>}</Card></>}
 </div>;
}
function Scenarios(){
 const {toast}=useApp();const {data,error,reload}=useApi<{scenarios:{id:string,name:string,owner_id:string,status:string,updated_at:string}[],canPlan:boolean}>('/api/strategy?view=scenarios');const {person,ask}=useApp();
 return <div className="page"><Header icon="GitBranch" tone="violet" title="Planning scenarios" subtitle="Private what-if plans. Nothing changes in live records until a scenario is approved and applied." actions={data?.canPlan&&<Btn variant="primary" icon="Plus" onClick={async()=>{const n=await ask({title:'New scenario',input:{label:'Name',required:true},confirm:'Create'});if(n){try{const r=await api<{id:string}>('/api/strategy',{action:'scenario-create',name:n});go(`strategy/scenarios/${r.id}`)}catch(e){toast((e as Error).message,'error')}}}}>New scenario</Btn>}/>
  <ErrorNote error={error} onRetry={reload}/>{!data?<Skeleton/>:!data.scenarios.length?<Empty icon="GitBranch" title="No scenarios"/>:<ul className="mini-list">{data.scenarios.map(s=><li key={s.id} className="mini-row"><a href={`#/strategy/scenarios/${s.id}`}>{s.name}</a><Chip tone={s.status==='applied'?'green':s.status==='approved'?'violet':s.status==='submitted'?'amber':'gray'}>{s.status}</Chip><small className="muted">{person(s.owner_id)?.name} · {ago(s.updated_at)}</small></li>)}</ul>}</div>;
}
type Effects={timelines:{project:string,title:string,from:string|null,to:string|null,shiftDays:number,tasksShifted:number}[],goals:{id:string,title:string,effect:string}[],dependencies:{id:string,title:string,effect:string}[],budgets:{title:string,before:number,after:number,remainingAfter:number}[],capacity:{before:number,after:number,overAllocatedBefore:number,overAllocatedAfter:number}|null,risks:string[],benefits:{name:string,effect:string}[],notes:string[]};
function Scenario({id}:{id:string}){
 const {toast,s}=useApp();const {data,error,reload}=useApi<{scenario:{id:string,name:string,description:string,status:string,owner_id:string,result:Effects&{evaluatedAt?:string}},changes:{id:string,change_type:string,target_type:string,target_id:string,params:Record<string,unknown>}[],changeTypes:string[],canApprove:boolean,isOwner:boolean}>(`/api/strategy?view=scenario&id=${id}`);
 const projects=useApi<{projects:{id:string,code:string,name:string}[]}>('/api/projects');const [c,setC]=useState({changeType:'delay_project',targetId:'',days:'30',targetDate:'',amount:'',priority:'High',from:null as string|null,to:null as string|null,hours:'20',name:''});
 if(error)return <div className="page"><ErrorNote error={error}/></div>;if(!data)return <div className="page"><Skeleton/></div>;const sc=data.scenario;const eff=sc.result;
 const post=async(action:string,extra:Record<string,unknown>={},msg='Done')=>{try{await api('/api/strategy',{action,id,...extra});toast(msg);reload()}catch(e){toast((e as Error).message,'error')}};
 const addChange=()=>{const t=c.changeType;const params:Record<string,unknown>=t==='delay_project'?{days:Number(c.days)}:t==='change_target'?{targetDate:c.targetDate}:t==='change_funding'?{amount:Number(c.amount)}:t==='change_priority'?{priority:c.priority}:t==='reassign_team'?{from:c.from,to:c.to}:t==='reduce_capacity'?{hoursPerWeek:Number(c.hours),members:[c.from]}:t==='add_project'?{name:c.name,budget:c.amount?Number(c.amount):undefined}:{};
  post('scenario-change',{changeType:t,targetType:t==='remove_initiative'?'initiative':t==='reduce_capacity'?'member':'project',targetId:t==='reduce_capacity'?c.from:t==='add_project'?'new':c.targetId,params},'Change added')};
 return <div className="page"><Header icon="GitBranch" tone="violet" title={sc.name} subtitle={<span className="row-gap"><Chip tone={sc.status==='applied'?'green':'amber'}>{sc.status}</Chip><span>Private planning scenario — live records are unchanged until it is approved and applied.</span></span>}
  actions={<>{data.isOwner&&sc.status==='draft'&&<><Btn icon="Calculator" onClick={()=>post('scenario-evaluate',{},'Effects calculated')}>Evaluate effects</Btn><Btn variant="primary" icon="Send" onClick={()=>post('scenario-submit',{},'Submitted for approval')}>Submit</Btn></>}{data.canApprove&&sc.status==='submitted'&&<><Btn variant="primary" onClick={()=>post('scenario-approve',{},'Approved')}>Approve</Btn><Btn onClick={()=>post('scenario-reject',{},'Rejected')}>Reject</Btn></>}{sc.status==='approved'&&(data.canApprove||s.user.role==='admin')&&<Btn variant="primary" icon="Play" onClick={()=>post('scenario-apply',{},'Applied to live records')}>Apply to live records</Btn>}</>}/>
  <div className="cards-2"><Card title="Changes">{data.changes.map(x=><p key={x.id} className="small"><b>{x.change_type.replace(/_/g,' ')}</b> · {x.target_type} {x.target_id.slice(0,8)} · {JSON.stringify(x.params)}{data.isOwner&&sc.status==='draft'&&<button className="link small" onClick={()=>post('scenario-change-remove',{changeId:x.id},'Removed')}> remove</button>}</p>)}
   {data.isOwner&&sc.status==='draft'&&<div className="form-grid"><Field label="Change"><select value={c.changeType} onChange={e=>setC({...c,changeType:e.target.value})}>{data.changeTypes.map(t=><option key={t} value={t}>{t.replace(/_/g,' ')}</option>)}</select></Field>
    {['delay_project','change_target','change_funding','change_priority','reassign_team'].includes(c.changeType)&&<Field label="Project"><select value={c.targetId} onChange={e=>setC({...c,targetId:e.target.value})}><option value="">—</option>{(projects.data?.projects||[]).map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></Field>}
    {c.changeType==='remove_initiative'&&<Field label="Initiative id"><input value={c.targetId} onChange={e=>setC({...c,targetId:e.target.value})}/></Field>}
    {c.changeType==='delay_project'&&<Field label="Delay (days)"><input type="number" value={c.days} onChange={e=>setC({...c,days:e.target.value})}/></Field>}{c.changeType==='change_target'&&<Field label="New target"><input type="date" value={c.targetDate} onChange={e=>setC({...c,targetDate:e.target.value})}/></Field>}
    {['change_funding','add_project'].includes(c.changeType)&&<Field label="Amount"><input type="number" value={c.amount} onChange={e=>setC({...c,amount:e.target.value})}/></Field>}{c.changeType==='add_project'&&<Field label="Project name"><input value={c.name} onChange={e=>setC({...c,name:e.target.value})}/></Field>}
    {c.changeType==='change_priority'&&<Field label="Priority"><select value={c.priority} onChange={e=>setC({...c,priority:e.target.value})}>{['Low','Medium','High','Critical'].map(x=><option key={x}>{x}</option>)}</select></Field>}
    {['reassign_team','reduce_capacity'].includes(c.changeType)&&<Field label={c.changeType==='reassign_team'?'From':'Person'}><PersonSelect value={c.from} onChange={x=>setC({...c,from:x})}/></Field>}{c.changeType==='reassign_team'&&<Field label="To"><PersonSelect value={c.to} onChange={x=>setC({...c,to:x})}/></Field>}{c.changeType==='reduce_capacity'&&<Field label="Hours per week"><input type="number" value={c.hours} onChange={e=>setC({...c,hours:e.target.value})}/></Field>}
    <Btn size="sm" icon="Plus" onClick={addChange}>Add change</Btn></div>}</Card>
   <Card title={`Expected effects${eff.evaluatedAt?` (calculated ${ago(eff.evaluatedAt)})`:''}`}>{!eff.evaluatedAt?<p className="muted small">Evaluate to see the effects on goals, timelines, capacity, budgets, dependencies, risks and benefits.</p>:<>
    {eff.timelines.map((t,i)=><p key={i} className="small"><b>{t.title}</b>: {t.from||'?'} → {t.to||'?'} ({t.shiftDays>0?'+':''}{t.shiftDays} days, {t.tasksShifted} dated tasks affected)</p>)}
    {eff.goals.map((g,i)=><p key={i} className="small"><Icon name="Target" size={12}/> {g.title}: {g.effect}</p>)}
    {eff.dependencies.map((d,i)=><p key={i} className="small"><Icon name="Link" size={12}/> {d.title}: {d.effect}</p>)}
    {eff.budgets.map((b,i)=><p key={i} className="small"><Icon name="PiggyBank" size={12}/> {b.title}: {b.before.toLocaleString()} → {b.after.toLocaleString()} (remaining {b.remainingAfter.toLocaleString()})</p>)}
    {eff.capacity&&<p className="small"><Icon name="Users" size={12}/> Capacity {Math.round(eff.capacity.before)} → {Math.round(eff.capacity.after)} h; over-allocated {eff.capacity.overAllocatedBefore} → {eff.capacity.overAllocatedAfter}</p>}
    {eff.benefits.map((b,i)=><p key={i} className="small"><Icon name="Gauge" size={12}/> {b.name}: {b.effect}</p>)}
    {eff.risks.length>0&&<Note tone="warn">{eff.risks.join(' ')}</Note>}{eff.notes.map((n,i)=><p key={i} className="muted small">{n}</p>)}</>}</Card></div>
 </div>;
}
function CheckIns(){
 const [all,setAll]=useState(false);const {data,error}=useApi<{due:{id:string,kind:string,title:string,ownerId:string|null,nextCheckIn:string|null,overdue:boolean,cadence:string,drafts:number}[],recent:{id:string,targetId:string,title:string,progress:number|null,confidence:number|null,health:string,status:string,aiDrafted:number,submittedAt:string|null,createdAt:string}[]}>(`/api/strategy?view=check-ins${all?'&all=1':''}`);const {person}=useApp();
 return <div className="page"><Header icon="Gauge" tone="violet" title="Check-ins" subtitle="Scheduled updates on objectives, key results and initiatives. Missing updates appear in owners’ inboxes." actions={<label className="check"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Everyone I can see</label>}/>
  <ErrorNote error={error}/>{!data?<Skeleton/>:<div className="cards-2"><Card title="Due">{!data.due.length?<p className="muted small">Nothing scheduled.</p>:<ul className="mini-list">{data.due.map(d=><li key={d.id} className="mini-row"><a href={`#/strategy/item/${d.id}/check-ins`}>{d.title}</a><small className={cx(d.overdue&&'overdue')}>{d.nextCheckIn?dateOnly(d.nextCheckIn):'not scheduled'}</small><small className="muted">{person(d.ownerId)?.name} · {d.cadence}</small>{d.drafts>0&&<Chip tone="amber">{d.drafts} draft</Chip>}</li>)}</ul>}</Card>
   <Card title="Recent">{data.recent.map(r=><p key={r.id} className="small"><a href={`#/strategy/item/${r.targetId}/check-ins`}>{r.title}</a> · {r.progress??'—'}% · {r.health||'—'} · {r.status}{r.aiDrafted?' · AI-assisted':''} · {ago(r.submittedAt||r.createdAt)}</p>)}</Card></div>}</div>;
}
function Reviews(){
 const {toast,s}=useApp();const {data,error,reload}=useApi<{reviews:{id:string,kind:string,title:string,department:string,created_at:string}[]}>('/api/strategy?view=reviews');const [kind,setKind]=useState('monthly');const [dept,setDept]=useState('');
 return <div className="page"><Header icon="Presentation" tone="violet" title="Reviews & review packs" subtitle="Weekly, monthly, quarterly business reviews and executive or department packs, generated from live rollups."/>
  <Card title="Generate a review pack"><div className="row-gap wrap"><select aria-label="Type" value={kind} onChange={e=>setKind(e.target.value)}><option value="weekly">Weekly check-in review</option><option value="monthly">Monthly review</option><option value="qbr">Quarterly business review</option><option value="executive">Executive review pack</option><option value="department">Department review pack</option></select>{kind==='department'&&<select aria-label="Department" value={dept} onChange={e=>setDept(e.target.value)}><option value="">My department</option>{s.departments.map(d=><option key={d.name}>{d.name}</option>)}</select>}<Btn variant="primary" onClick={async()=>{try{const r=await api<{id:string}>('/api/strategy',{action:'review-generate',kind,department:dept||undefined});toast('Review pack ready');go(`strategy/reviews/${r.id}`)}catch(e){toast((e as Error).message,'error')}}}>Generate</Btn></div></Card>
  <ErrorNote error={error} onRetry={reload}/>{data&&<ul className="mini-list">{data.reviews.map(r=><li key={r.id} className="mini-row"><a href={`#/strategy/reviews/${r.id}`}>{r.title}</a><small className="muted">{ago(r.created_at)}</small></li>)}</ul>}</div>;
}
function Review({id}:{id:string}){
 const {data,error}=useApi<{review:{title:string,created_at:string,content:{summary:{items:number,onTrack:number,atRisk:number,offTrack:number,noData:number},items:{id:string,kind:string,number:string,title:string,progress:number|null,health:string,method:string,missing:string[]}[],atRisk:{id:string,title:string,health:string,progress:number|null}[],overdueCheckIns:{id:string,title:string,due:string}[],decisionsNeeded:{targetId:string,text:string}[],problems:{targetId:string,text:string}[]}}}>(`/api/strategy?view=review&id=${id}`);
 if(error)return <div className="page"><ErrorNote error={error}/></div>;if(!data)return <div className="page"><Skeleton/></div>;const c=data.review.content;
 return <div className="page"><Header icon="Presentation" tone="violet" title={data.review.title} subtitle={`Generated ${ago(data.review.created_at)} · items you cannot see are removed`} actions={<Btn icon="Printer" onClick={()=>window.print()}>Print</Btn>}/>
  <div className="stat-row">{([['Items',c.summary.items],['On track',c.summary.onTrack],['At risk',c.summary.atRisk],['Off track',c.summary.offTrack],['No data',c.summary.noData]] as const).map(([l,n])=><Card key={l} title={l}><b className="big">{n}</b></Card>)}</div>
  <Card title="Needs attention">{c.atRisk.map(i=><p key={i.id} className="small"><a href={`#/strategy/item/${i.id}`}>{i.title}</a> <Chip tone={HEALTH_TONE(i.health)}>{i.health}</Chip> {i.progress??'—'}%</p>)}{!c.atRisk.length&&<p className="muted small">Nothing at risk.</p>}</Card>
  {c.decisionsNeeded.length>0&&<Card title="Decisions needed">{c.decisionsNeeded.map((d,i)=><p key={i} className="small">{c.items.find(x=>x.id===d.targetId)?.title}: {d.text}</p>)}</Card>}
  {c.overdueCheckIns.length>0&&<Card title="Missing check-ins">{c.overdueCheckIns.map(o=><p key={o.id} className="small">{o.title} (due {o.due})</p>)}</Card>}
  <Card title="All items"><table className="plain small"><thead><tr><th>Item</th><th>Progress</th><th>Health</th><th>Method</th><th>Missing</th></tr></thead><tbody>{c.items.map(i=><tr key={i.id}><td><a href={`#/strategy/item/${i.id}`}>{i.number} · {i.title}</a></td><td>{i.progress??'—'}</td><td>{i.health}</td><td>{i.method}</td><td>{i.missing.join('; ')}</td></tr>)}</tbody></table></Card></div>;
}
function Reports(){
 const {data,error}=useApi<{rows:{id:string,kind:string,number:string,title:string,department:string,status:string,progress:number|null,health:string,method:string,missing:number,confidence:number|null,lastUpdated:string|null}[]}>('/api/strategy?view=report');
 return <div className="page"><Header icon="ChartColumn" tone="violet" title="Strategy report" subtitle="Every objective, key result, initiative and programme you can see, with its calculation method."/><ErrorNote error={error}/>
  {!data?<Skeleton/>:<table className="plain"><thead><tr><th>Item</th><th>Type</th><th>Department</th><th>Progress</th><th>Health</th><th>Confidence</th><th>Method</th><th>Missing data</th><th>Updated</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.id}><td><a href={`#/strategy/item/${r.id}`}>{r.number} · {r.title}</a></td><td>{r.kind}</td><td>{r.department}</td><td><Bar v={r.progress}/></td><td><Chip tone={HEALTH_TONE(r.health)}>{r.health}</Chip></td><td>{r.confidence??'—'}</td><td className="small">{r.method}</td><td>{r.missing||''}</td><td className="muted small">{r.lastUpdated?ago(r.lastUpdated):''}</td></tr>)}</tbody></table>}</div>;
}
function Periods(){
 const {toast}=useApp();const {data,error,reload}=useApi<{periods:{id:string,name:string,kind:string,startDate:string,endDate:string,status:string}[]}>('/api/strategy?view=periods');const [v,setV]=useState({name:'',kind:'quarter',startDate:'',endDate:''});
 return <div className="page"><Header icon="CalendarRange" tone="violet" title="Planning periods" subtitle="Annual, quarterly and custom periods used to plan objectives and key results."/>
  <Card><div className="row-gap wrap"><input placeholder="Name (e.g. Q1 2027)" value={v.name} onChange={e=>setV({...v,name:e.target.value})} aria-label="Name"/><select aria-label="Type" value={v.kind} onChange={e=>setV({...v,kind:e.target.value})}>{['annual','quarter','month','custom'].map(x=><option key={x}>{x}</option>)}</select><input type="date" aria-label="Start" value={v.startDate} onChange={e=>setV({...v,startDate:e.target.value})}/><input type="date" aria-label="End" value={v.endDate} onChange={e=>setV({...v,endDate:e.target.value})}/><Btn variant="primary" disabled={!v.name||!v.startDate||!v.endDate} onClick={async()=>{try{await api('/api/strategy',{action:'period-save',...v});toast('Saved');reload()}catch(e){toast((e as Error).message,'error')}}}>Add period</Btn></div></Card>
  <ErrorNote error={error}/>{data&&<table className="plain"><tbody>{data.periods.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.kind}</td><td>{p.startDate} → {p.endDate}</td><td>{p.status}</td></tr>)}</tbody></table>}</div>;
}
