import {sqliteTable,text,integer,real,index,primaryKey,uniqueIndex} from 'drizzle-orm/sqlite-core';

// ── Tenancy ──────────────────────────────────────────────────────────────────
// Every company is a tenant. All business tables carry tenant_id and every
// server query filters by the signed-in member's tenant.
export const tenants=sqliteTable('tenants',{id:text('id').primaryKey(),slug:text('slug').notNull().unique(),name:text('name').notNull(),legalName:text('legal_name').notNull().default(''),domains:text('domains').notNull().default(''),status:text('status').notNull().default('active'),plan:text('plan').notNull().default('business'),brandColor:text('brand_color').notNull().default('#6D5EF8'),currency:text('currency').notNull().default('GHS'),timezone:text('timezone').notNull().default('Africa/Accra'),settingsJson:text('settings_json').notNull().default('{}'),createdAt:text('created_at').notNull()});

export const members=sqliteTable('members',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),role:text('role',{enum:['admin','manager','employee','viewer']}).notNull(),department:text('department').notNull(),active:integer('active').notNull().default(1),createdAt:text('created_at').notNull(),tenantId:text('tenant_id').notNull().default('procus'),phone:text('phone').notNull().default(''),title:text('title').notNull().default(''),managerId:text('manager_id'),location:text('location').notNull().default(''),roleId:text('role_id'),employeeCode:text('employee_code').notNull().default(''),platformRole:text('platform_role'),lastSeenAt:text('last_seen_at'),notifyEmail:integer('notify_email').notNull().default(1),identityId:text('identity_id'),additionalLocations:text('additional_locations').notNull().default('[]'),invitedAt:text('invited_at'),updatedAt:text('updated_at'),updatedBy:text('updated_by'),preferencesJson:text('preferences_json').notNull().default('{}')},t=>[index('members_tenant').on(t.tenantId,t.name),index('members_identity').on(t.identityId)]);
export const records=sqliteTable('records',{id:text('id').primaryKey(),module:text('module').notNull(),title:text('title').notNull(),department:text('department').notNull(),status:text('status').notNull(),owner:text('owner').notNull(),amount:real('amount').notNull().default(0),details:text('details').notNull().default(''),updated:text('updated').notNull(),version:integer('version').notNull().default(1),createdBy:text('created_by').notNull().references(()=>members.id),fileKey:text('file_key'),tenantId:text('tenant_id').notNull().default('procus')},t=>[index('idx_records_department_module').on(t.department,t.module),index('idx_records_creator').on(t.createdBy),index('records_tenant').on(t.tenantId,t.module)]);
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),action:text('action').notNull(),actor:text('actor').notNull(),recordId:text('record_id').notNull(),department:text('department').notNull(),before:text('before_json'),after:text('after_json'),createdAt:text('created_at').notNull(),tenantId:text('tenant_id').notNull().default('procus'),supportSessionId:text('support_session_id')},t=>[index('idx_audit_department_time').on(t.department,t.createdAt),index('audit_tenant_time').on(t.tenantId,t.createdAt),index('audit_tenant_record').on(t.tenantId,t.recordId)]);
export const sessions=sqliteTable('sessions',{tokenHash:text('token_hash').primaryKey(),memberId:text('member_id').notNull().references(()=>members.id),expires:integer('expires').notNull(),identityId:text('identity_id'),supportSessionId:text('support_session_id')});
export const authFlows=sqliteTable('auth_flows',{state:text('state').primaryKey(),verifier:text('verifier').notNull(),nonce:text('nonce').notNull(),expires:integer('expires').notNull()});
export const importBatches=sqliteTable('import_batches',{id:text('id').primaryKey(),source:text('source').notNull(),dataset:text('dataset').notNull(),filename:text('filename').notNull(),sha256:text('sha256').notNull(),importedAt:text('imported_at').notNull(),rowCount:integer('row_count').notNull(),headersJson:text('headers_json').notNull(),tenantId:text('tenant_id').notNull().default('procus')});
export const sourceRows=sqliteTable('source_rows',{id:text('id').primaryKey(),batchId:text('batch_id').notNull().references(()=>importBatches.id),sourceKey:text('source_key'),sheet:text('sheet').notNull(),rowNumber:integer('row_number').notNull(),payloadJson:text('payload_json').notNull()},t=>[index('source_rows_batch').on(t.batchId),uniqueIndex('source_rows_position').on(t.batchId,t.sheet,t.rowNumber)]);
export const sourceLinks=sqliteTable('links',{fromId:text('from_id').notNull().references(()=>sourceRows.id),toId:text('to_id').notNull().references(()=>sourceRows.id),kind:text('kind').notNull()},t=>[primaryKey({columns:[t.fromId,t.toId,t.kind]})]);
export const qualityIssues=sqliteTable('quality_issues',{id:text('id').primaryKey(),batchId:text('batch_id').notNull(),kind:text('kind').notNull(),detailJson:text('detail_json').notNull()});
export const passwords=sqliteTable('passwords',{memberId:text('member_id').primaryKey().references(()=>members.id),username:text('username').notNull().unique(),salt:text('salt').notNull(),hash:text('password_hash').notNull(),iterations:integer('iterations').notNull(),mustChange:integer('must_change').notNull().default(1)});
export const loginAttempts=sqliteTable('login_attempts',{key:text('key').primaryKey(),attempts:integer('attempts').notNull(),expires:integer('expires').notNull()});

export const researchAccess=sqliteTable('research_access',{memberId:text('member_id').primaryKey().references(()=>members.id),grantedBy:text('granted_by').notNull(),createdAt:text('created_at').notNull()});
export const researchRecordings=sqliteTable('research_recordings',{id:text('id').primaryKey(),title:text('title').notNull(),context:text('context').notNull().default(''),filename:text('filename').notNull(),mime:text('mime').notNull(),bytes:integer('bytes').notNull(),fileKey:text('file_key').notNull(),createdBy:text('created_by').notNull().references(()=>members.id),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),status:text('status').notNull().default('Uploaded'),transcript:text('transcript'),summary:text('summary'),error:text('error'),leaseUntil:integer('lease_until').notNull().default(0),attempts:integer('attempts').notNull().default(0),transcriptionModel:text('transcription_model'),summaryModel:text('summary_model'),tenantId:text('tenant_id').notNull().default('procus')},t=>[index('research_created').on(t.createdAt),index('research_tenant').on(t.tenantId,t.createdAt)]);

export const itNvrs=sqliteTable('it_nvrs',{id:text('id').primaryKey(),name:text('name').notNull(),address:text('address').notNull(),location:text('location').notNull().default(''),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),tenantId:text('tenant_id').notNull().default('procus')},t=>[uniqueIndex('it_nvrs_address_unique').on(t.tenantId,t.address)]);
export const itNvrReadings=sqliteTable('it_nvr_readings',{id:text('id').primaryKey(),nvrId:text('nvr_id').notNull().references(()=>itNvrs.id),readingDate:text('reading_date').notNull(),diskNo:integer('disk_no').notNull(),capacityGb:real('capacity_gb').notNull(),remainingGb:real('remaining_gb').notNull(),status:text('status').notNull(),attribute:text('attribute').notNull(),storageType:text('storage_type').notNull(),notes:text('notes').notNull().default(''),recordedBy:text('recorded_by').notNull().references(()=>members.id),recordedAt:text('recorded_at').notNull()},t=>[uniqueIndex('nvr_disk_day').on(t.nvrId,t.readingDate,t.diskNo)]);

export const accessRules=sqliteTable('access_rules',{id:text('id').primaryKey(),subjectType:text('subject_type').notNull(),subjectId:text('subject_id').notNull(),department:text('department').notNull(),page:text('page').notNull(),action:text('action').notNull(),effect:text('effect').notNull(),scope:text('scope').notNull(),tenantId:text('tenant_id').notNull().default('procus')},t=>[uniqueIndex('access_rule_subject_action').on(t.tenantId,t.subjectType,t.subjectId,t.department,t.page,t.action)]);

export const researchCloudJobs=sqliteTable('research_cloud_jobs',{recordingId:text('recording_id').primaryKey().references(()=>researchRecordings.id),providerId:text('provider_id').unique(),tokenHash:text('token_hash').notNull(),state:text('state').notNull(),leaseUntil:integer('lease_until').notNull().default(0),attempts:integer('attempts').notNull().default(0)});

// ── Organisation ─────────────────────────────────────────────────────────────
export const roles=sqliteTable('roles',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),name:text('name').notNull(),description:text('description').notNull().default(''),base:text('base').notNull().default('employee'),permissionsJson:text('permissions_json').notNull().default('{}'),locationsJson:text('locations_json').notNull().default('[]'),defaultScreen:text('default_screen').notNull().default(''),scopeJson:text('scope_json').notNull().default('{}'),vendorAccess:integer('vendor_access').notNull().default(0),assignedOnly:integer('assigned_only').notNull().default(0),template:text('template').notNull().default('custom'),pagesJson:text('pages_json'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedBy:text('updated_by').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('roles_tenant_name').on(t.tenantId,t.name)]);
export const departments=sqliteTable('departments',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),name:text('name').notNull(),code:text('code').notNull().default(''),headId:text('head_id'),description:text('description').notNull().default(''),color:text('color').notNull().default(''),createdAt:text('created_at').notNull(),parentId:text('parent_id'),costCentre:text('cost_centre').notNull().default(''),status:text('status').notNull().default('Active'),createdBy:text('created_by'),updatedBy:text('updated_by'),updatedAt:text('updated_at')},t=>[uniqueIndex('departments_tenant_name').on(t.tenantId,t.name)]);
export const locations=sqliteTable('locations',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),name:text('name').notNull(),parentId:text('parent_id'),path:text('path').notNull(),kind:text('kind').notNull().default('Site'),createdAt:text('created_at').notNull()},t=>[uniqueIndex('locations_tenant_path').on(t.tenantId,t.path)]);
export const counters=sqliteTable('counters',{tenantId:text('tenant_id').notNull(),key:text('key').notNull(),value:integer('value').notNull()},t=>[primaryKey({columns:[t.tenantId,t.key]})]);

// ── Assets & tickets ─────────────────────────────────────────────────────────
export const assets=sqliteTable('assets',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),code:text('code').notNull(),name:text('name').notNull(),category:text('category').notNull().default(''),kind:text('kind').notNull().default('Physical'),brand:text('brand').notNull().default(''),model:text('model').notNull().default(''),serial:text('serial').notNull().default(''),status:text('status').notNull().default('In store'),condition:text('condition').notNull().default('Good'),location:text('location').notNull().default(''),department:text('department').notNull().default(''),assignedTo:text('assigned_to'),purchaseDate:text('purchase_date'),purchaseCost:real('purchase_cost').notNull().default(0),warrantyUntil:text('warranty_until'),vendor:text('vendor').notNull().default(''),notes:text('notes').notNull().default(''),sourceId:text('source_id'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1),subcategory:text('subcategory').notNull().default(''),costCentre:text('cost_centre').notNull().default(''),barcode:text('barcode').notNull().default(''),usefulLifeMonths:integer('useful_life_months').notNull().default(0),salvageValue:real('salvage_value').notNull().default(0),dueBack:text('due_back'),disposalDate:text('disposal_date'),disposalMethod:text('disposal_method').notNull().default(''),disposalValue:real('disposal_value').notNull().default(0),disposalReason:text('disposal_reason').notNull().default('')},t=>[uniqueIndex('assets_tenant_code').on(t.tenantId,t.code),uniqueIndex('assets_tenant_source').on(t.tenantId,t.sourceId),index('assets_tenant_status').on(t.tenantId,t.status)]);
export const tickets=sqliteTable('tickets',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),number:text('number').notNull(),title:text('title').notNull(),description:text('description').notNull().default(''),type:text('type').notNull().default('Incident'),category:text('category').notNull().default(''),priority:text('priority').notNull().default('Medium'),status:text('status').notNull().default('New'),department:text('department').notNull().default(''),assigneeId:text('assignee_id'),requesterId:text('requester_id').notNull(),assetId:text('asset_id'),location:text('location').notNull().default(''),dueAt:text('due_at'),resolvedAt:text('resolved_at'),sourceId:text('source_id'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1),subcategory:text('subcategory').notNull().default(''),impact:text('impact').notNull().default('Medium'),urgency:text('urgency').notNull().default('Medium'),affectedUserId:text('affected_user_id'),approvalStatus:text('approval_status').notNull().default(''),approverId:text('approver_id'),escalatedAt:text('escalated_at')},t=>[uniqueIndex('tickets_tenant_number').on(t.tenantId,t.number),uniqueIndex('tickets_tenant_source').on(t.tenantId,t.sourceId),index('tickets_tenant_status').on(t.tenantId,t.status)]);
export const comments=sqliteTable('comments',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),entityType:text('entity_type').notNull(),entityId:text('entity_id').notNull(),authorId:text('author_id').notNull(),body:text('body').notNull(),internal:integer('internal').notNull().default(0),createdAt:text('created_at').notNull()},t=>[index('comments_entity').on(t.tenantId,t.entityType,t.entityId)]);

// ── Purchasing ───────────────────────────────────────────────────────────────
export const vendors=sqliteTable('vendors',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),name:text('name').notNull(),email:text('email').notNull().default(''),phone:text('phone').notNull().default(''),address:text('address').notNull().default(''),taxId:text('tax_id').notNull().default(''),category:text('category').notNull().default(''),status:text('status').notNull().default('Active'),notes:text('notes').notNull().default(''),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('vendors_tenant_name').on(t.tenantId,t.name)]);
export const purchaseDocs=sqliteTable('purchase_docs',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),kind:text('kind').notNull(),number:text('number').notNull(),title:text('title').notNull(),justification:text('justification').notNull().default(''),department:text('department').notNull(),location:text('location').notNull().default(''),requesterId:text('requester_id').notNull(),vendorId:text('vendor_id'),prId:text('pr_id'),neededBy:text('needed_by'),currency:text('currency').notNull().default('GHS'),subtotal:real('subtotal').notNull().default(0),tax:real('tax').notNull().default(0),total:real('total').notNull().default(0),status:text('status').notNull().default('Draft'),terms:text('terms').notNull().default(''),sourceId:text('source_id'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),submittedAt:text('submitted_at'),version:integer('version').notNull().default(1),costCentre:text('cost_centre').notNull().default(''),budgetId:text('budget_id')},t=>[uniqueIndex('purchase_docs_number').on(t.tenantId,t.number),uniqueIndex('purchase_docs_source').on(t.tenantId,t.sourceId),index('purchase_docs_kind').on(t.tenantId,t.kind,t.status)]);
export const purchaseLines=sqliteTable('purchase_lines',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),docId:text('doc_id').notNull(),lineNo:integer('line_no').notNull(),description:text('description').notNull(),itemCode:text('item_code').notNull().default(''),qty:real('qty').notNull(),unit:text('unit').notNull().default('ea'),unitPrice:real('unit_price').notNull(),taxRate:real('tax_rate').notNull().default(0),receivedQty:real('received_qty').notNull().default(0),returnedQty:real('returned_qty').notNull().default(0),inventoryItemId:text('inventory_item_id')},t=>[index('purchase_lines_doc').on(t.tenantId,t.docId)]);
export const approvalWorkflows=sqliteTable('approval_workflows',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),docType:text('doc_type').notNull(),name:text('name').notNull(),department:text('department').notNull().default('*'),minAmount:real('min_amount').notNull().default(0),stepsJson:text('steps_json').notNull(),active:integer('active').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('workflows_tenant').on(t.tenantId,t.docType)]);
export const approvals=sqliteTable('approvals',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),docId:text('doc_id').notNull(),stepNo:integer('step_no').notNull(),stepName:text('step_name').notNull(),approverIds:text('approver_ids').notNull().default('[]'),status:text('status').notNull(),decidedBy:text('decided_by'),decidedAt:text('decided_at'),comment:text('comment').notNull().default(''),createdAt:text('created_at').notNull()},t=>[index('approvals_doc').on(t.tenantId,t.docId),index('approvals_status').on(t.tenantId,t.status)]);

// ── Collaboration ────────────────────────────────────────────────────────────
export const notifications=sqliteTable('notifications',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),memberId:text('member_id').notNull(),kind:text('kind').notNull(),title:text('title').notNull(),body:text('body').notNull().default(''),link:text('link').notNull().default(''),readAt:text('read_at'),emailStatus:text('email_status').notNull().default('none'),createdAt:text('created_at').notNull()},t=>[index('notifications_member').on(t.memberId,t.createdAt)]);
export const folders=sqliteTable('folders',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),parentId:text('parent_id'),name:text('name').notNull(),department:text('department').notNull().default(''),visibility:text('visibility').notNull().default('company'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()},t=>[index('folders_tenant').on(t.tenantId,t.parentId)]);
export const files=sqliteTable('files',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),folderId:text('folder_id'),name:text('name').notNull(),mime:text('mime').notNull(),bytes:integer('bytes').notNull(),fileKey:text('file_key').notNull(),department:text('department').notNull().default(''),visibility:text('visibility').notNull().default('company'),tags:text('tags').notNull().default(''),description:text('description').notNull().default(''),version:integer('version').notNull().default(1),uploadedBy:text('uploaded_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),entityType:text('entity_type'),entityId:text('entity_id')},t=>[index('files_tenant_folder').on(t.tenantId,t.folderId),index('files_entity').on(t.tenantId,t.entityType,t.entityId)]);
export const fileVersions=sqliteTable('file_versions',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),fileId:text('file_id').notNull(),version:integer('version').notNull(),fileKey:text('file_key').notNull(),bytes:integer('bytes').notNull(),uploadedBy:text('uploaded_by').notNull(),createdAt:text('created_at').notNull()},t=>[index('file_versions_file').on(t.tenantId,t.fileId)]);
export const pages=sqliteTable('pages',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),department:text('department').notNull().default(''),parentId:text('parent_id'),kind:text('kind').notNull().default('page'),title:text('title').notNull(),body:text('body').notNull().default(''),icon:text('icon').notNull().default(''),status:text('status').notNull().default('Draft'),pinned:integer('pinned').notNull().default(0),authorId:text('author_id').notNull(),updatedBy:text('updated_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1)},t=>[index('pages_tenant_space').on(t.tenantId,t.department)]);

// ── Identity & platform ──────────────────────────────────────────────────────
// A person is one global identity; each workspace they belong to has a membership row in `members`.
// `tenant_id` is the workspace key throughout the schema.
export const identities=sqliteTable('identities',{id:text('id').primaryKey(),email:text('email').notNull().unique(),username:text('username').unique(),name:text('name').notNull(),lastMemberId:text('last_member_id'),createdAt:text('created_at').notNull()});
export const credentials=sqliteTable('credentials',{identityId:text('identity_id').primaryKey().references(()=>identities.id),salt:text('salt').notNull(),hash:text('password_hash').notNull(),iterations:integer('iterations').notNull(),mustChange:integer('must_change').notNull().default(0),updatedAt:text('updated_at').notNull()});
// One-time invitation / password-reset tokens. Only a SHA-256 hash of the token is stored.
export const authTokens=sqliteTable('auth_tokens',{tokenHash:text('token_hash').primaryKey(),identityId:text('identity_id').notNull().references(()=>identities.id),memberId:text('member_id'),tenantId:text('tenant_id'),purpose:text('purpose').notNull(),createdBy:text('created_by'),createdAt:text('created_at').notNull(),expires:integer('expires').notNull(),usedAt:text('used_at')},t=>[index('auth_tokens_identity').on(t.identityId,t.purpose)]);
export const supportSessions=sqliteTable('support_sessions',{id:text('id').primaryKey(),ownerIdentityId:text('owner_identity_id').notNull(),tenantId:text('tenant_id').notNull().references(()=>tenants.id),reason:text('reason').notNull(),startedAt:text('started_at').notNull(),endedAt:text('ended_at'),ip:text('ip').notNull().default(''),userAgent:text('user_agent').notNull().default('')},t=>[index('support_sessions_tenant').on(t.tenantId,t.startedAt)]);
export const platformAudit=sqliteTable('platform_audit',{id:text('id').primaryKey(),actorIdentityId:text('actor_identity_id').notNull(),tenantId:text('tenant_id'),supportSessionId:text('support_session_id'),action:text('action').notNull(),method:text('method').notNull().default(''),path:text('path').notNull().default(''),detailJson:text('detail_json'),ip:text('ip').notNull().default(''),createdAt:text('created_at').notNull()},t=>[index('platform_audit_time').on(t.createdAt),index('platform_audit_tenant').on(t.tenantId,t.createdAt)]);
export const savedViews=sqliteTable('saved_views',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),memberId:text('member_id').notNull(),gridId:text('grid_id').notNull(),name:text('name').notNull(),stateJson:text('state_json').notNull(),createdAt:text('created_at').notNull()},t=>[index('saved_views_member').on(t.tenantId,t.memberId,t.gridId)]);

// ── Asset audits, inventory, maintenance, purchasing extensions ─────────────
export const assetAudits=sqliteTable('asset_audits',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),name:text('name').notNull(),location:text('location').notNull().default(''),status:text('status').notNull().default('Open'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),closedAt:text('closed_at')},t=>[index('asset_audits_tenant').on(t.tenantId,t.createdAt)]);
export const assetAuditItems=sqliteTable('asset_audit_items',{auditId:text('audit_id').notNull(),tenantId:text('tenant_id').notNull(),assetId:text('asset_id').notNull(),result:text('result').notNull(),note:text('note').notNull().default(''),checkedBy:text('checked_by').notNull(),checkedAt:text('checked_at').notNull()},t=>[primaryKey({columns:[t.auditId,t.assetId]})]);
export const inventoryItems=sqliteTable('inventory_items',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),sku:text('sku').notNull(),name:text('name').notNull(),category:text('category').notNull().default(''),unit:text('unit').notNull().default('ea'),minStock:real('min_stock').notNull().default(0),reorderQty:real('reorder_qty').notNull().default(0),tracking:text('tracking').notNull().default('none'),unitCost:real('unit_cost').notNull().default(0),status:text('status').notNull().default('Active'),notes:text('notes').notNull().default(''),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('inventory_items_sku').on(t.tenantId,t.sku)]);
export const stockLevels=sqliteTable('stock_levels',{tenantId:text('tenant_id').notNull(),itemId:text('item_id').notNull(),location:text('location').notNull(),qty:real('qty').notNull().default(0)},t=>[primaryKey({columns:[t.tenantId,t.itemId,t.location]})]);
export const stockMoves=sqliteTable('stock_moves',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),itemId:text('item_id').notNull(),type:text('type').notNull(),qty:real('qty').notNull(),fromLocation:text('from_location'),toLocation:text('to_location'),batch:text('batch').notNull().default(''),serial:text('serial').notNull().default(''),reference:text('reference').notNull().default(''),note:text('note').notNull().default(''),unitCost:real('unit_cost').notNull().default(0),actor:text('actor').notNull(),createdAt:text('created_at').notNull()},t=>[index('stock_moves_item').on(t.tenantId,t.itemId,t.createdAt)]);
export const maintenancePlans=sqliteTable('maintenance_plans',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),assetId:text('asset_id'),title:text('title').notNull(),description:text('description').notNull().default(''),intervalValue:integer('interval_value').notNull(),intervalUnit:text('interval_unit').notNull(),nextDue:text('next_due').notNull(),assigneeId:text('assignee_id'),department:text('department').notNull().default(''),checklist:text('checklist').notNull().default(''),estimatedCost:real('estimated_cost').notNull().default(0),active:integer('active').notNull().default(1),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()},t=>[index('maintenance_plans_tenant').on(t.tenantId,t.nextDue)]);
export const workOrders=sqliteTable('work_orders',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),number:text('number').notNull(),planId:text('plan_id'),assetId:text('asset_id'),ticketId:text('ticket_id'),title:text('title').notNull(),description:text('description').notNull().default(''),status:text('status').notNull().default('Open'),priority:text('priority').notNull().default('Medium'),assigneeId:text('assignee_id'),department:text('department').notNull().default(''),dueAt:text('due_at'),partsJson:text('parts_json').notNull().default('[]'),partsCost:real('parts_cost').notNull().default(0),laborCost:real('labor_cost').notNull().default(0),completionNotes:text('completion_notes').notNull().default(''),evidenceFileId:text('evidence_file_id'),completedAt:text('completed_at'),completedBy:text('completed_by'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('work_orders_number').on(t.tenantId,t.number),index('work_orders_status').on(t.tenantId,t.status)]);
export const quotations=sqliteTable('quotations',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),docId:text('doc_id').notNull(),vendorId:text('vendor_id').notNull(),amount:real('amount').notNull(),currency:text('currency').notNull(),validUntil:text('valid_until'),notes:text('notes').notNull().default(''),fileId:text('file_id'),selected:integer('selected').notNull().default(0),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()},t=>[index('quotations_doc').on(t.tenantId,t.docId)]);
export const budgets=sqliteTable('budgets',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),name:text('name').notNull(),department:text('department').notNull().default(''),costCentre:text('cost_centre').notNull().default(''),periodStart:text('period_start').notNull(),periodEnd:text('period_end').notNull(),amount:real('amount').notNull(),currency:text('currency').notNull(),status:text('status').notNull().default('Active'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()},t=>[index('budgets_tenant').on(t.tenantId,t.periodEnd)]);

// ── Platform settings, AI, connectors and the page builder (migration 0009) ──
// Platform-wide configuration owned by the Platform Owner (page catalog overrides, packages, AI defaults).
export const platformSettings=sqliteTable('platform_settings',{key:text('key').primaryKey(),valueJson:text('value_json').notNull(),updatedBy:text('updated_by').notNull(),updatedAt:text('updated_at').notNull()});
// A company's own AI provider. Overrides the platform Groq default for that workspace only.
export const aiProviders=sqliteTable('ai_providers',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull().references(()=>tenants.id),provider:text('provider').notNull(),label:text('label').notNull().default(''),model:text('model').notNull(),baseUrl:text('base_url').notNull().default(''),secretEnc:text('secret_enc'),secretHint:text('secret_hint').notNull().default(''),active:integer('active').notNull().default(1),fallback:text('fallback').notNull().default('platform'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedBy:text('updated_by').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('ai_providers_tenant').on(t.tenantId)]);
export const aiConversations=sqliteTable('ai_conversations',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull().references(()=>tenants.id),memberId:text('member_id').notNull(),title:text('title').notNull().default(''),page:text('page').notNull().default(''),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('ai_conversations_member').on(t.tenantId,t.memberId,t.updatedAt)]);
export const aiMessages=sqliteTable('ai_messages',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull().references(()=>tenants.id),conversationId:text('conversation_id').notNull(),role:text('role').notNull(),content:text('content').notNull(),citationsJson:text('citations_json').notNull().default('[]'),feedback:integer('feedback').notNull().default(0),createdAt:text('created_at').notNull()},t=>[index('ai_messages_conversation').on(t.tenantId,t.conversationId,t.createdAt)]);
export const aiUsage=sqliteTable('ai_usage',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull().references(()=>tenants.id),memberId:text('member_id').notNull(),provider:text('provider').notNull(),model:text('model').notNull(),kind:text('kind').notNull(),promptTokens:integer('prompt_tokens').notNull().default(0),completionTokens:integer('completion_tokens').notNull().default(0),ok:integer('ok').notNull().default(1),createdAt:text('created_at').notNull()},t=>[index('ai_usage_tenant').on(t.tenantId,t.createdAt)]);
// Connectors: tenant_id is the owning workspace, or '__platform__' for Platform Owner connectors.
export const connectors=sqliteTable('connectors',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),scope:text('scope').notNull().default('company'),provider:text('provider').notNull(),name:text('name').notNull(),description:text('description').notNull().default(''),authType:text('auth_type').notNull(),configJson:text('config_json').notNull().default('{}'),secretEnc:text('secret_enc'),secretHint:text('secret_hint').notNull().default(''),webhookSecretEnc:text('webhook_secret_enc'),status:text('status').notNull().default('draft'),health:text('health').notNull().default('unknown'),lastOkAt:text('last_ok_at'),lastSyncAt:text('last_sync_at'),lastError:text('last_error').notNull().default(''),syncMinutes:integer('sync_minutes').notNull().default(0),pagesJson:text('pages_json').notNull().default('[]'),rolesJson:text('roles_json').notNull().default('[]'),allowedToolsJson:text('allowed_tools_json').notNull().default('[]'),mutatingToolsJson:text('mutating_tools_json').notNull().default('[]'),toolsJson:text('tools_json').notNull().default('[]'),resourcesJson:text('resources_json').notNull().default('[]'),fieldMapJson:text('field_map_json').notNull().default('{}'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedBy:text('updated_by').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('connectors_tenant').on(t.tenantId,t.name)]);
export const connectorLogs=sqliteTable('connector_logs',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),connectorId:text('connector_id').notNull(),actor:text('actor').notNull().default(''),action:text('action').notNull(),status:text('status').notNull(),durationMs:integer('duration_ms').notNull().default(0),detailJson:text('detail_json'),createdAt:text('created_at').notNull()},t=>[index('connector_logs_connector').on(t.tenantId,t.connectorId,t.createdAt)]);
export const oauthStates=sqliteTable('oauth_states',{stateHash:text('state_hash').primaryKey(),tenantId:text('tenant_id').notNull(),connectorId:text('connector_id').notNull(),memberId:text('member_id').notNull(),verifierEnc:text('verifier_enc').notNull(),expires:integer('expires').notNull()});
// Visual page builder: a page, its immutable versions, and reusable templates.
export const appPages=sqliteTable('app_pages',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull().references(()=>tenants.id),slug:text('slug').notNull(),title:text('title').notNull(),description:text('description').notNull().default(''),icon:text('icon').notNull().default('LayoutGrid'),status:text('status').notNull().default('draft'),draftJson:text('draft_json').notNull(),draftVersion:integer('draft_version').notNull().default(1),publishedVersion:integer('published_version'),visibilityJson:text('visibility_json').notNull().default('{}'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedBy:text('updated_by').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('app_pages_slug').on(t.tenantId,t.slug)]);
export const appPageVersions=sqliteTable('app_page_versions',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull().references(()=>tenants.id),pageId:text('page_id').notNull(),version:integer('version').notNull(),layoutJson:text('layout_json').notNull(),note:text('note').notNull().default(''),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('app_page_versions_page').on(t.tenantId,t.pageId,t.version)]);
export const pageTemplates=sqliteTable('page_templates',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),scope:text('scope').notNull().default('company'),name:text('name').notNull(),description:text('description').notNull().default(''),layoutJson:text('layout_json').notNull(),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()},t=>[index('page_templates_tenant').on(t.tenantId,t.name)]);
