import {sqliteTable,text,integer,real,index,primaryKey,uniqueIndex} from 'drizzle-orm/sqlite-core';

// ── Tenancy ──────────────────────────────────────────────────────────────────
// Every company is a tenant. All business tables carry tenant_id and every
// server query filters by the signed-in member's tenant.
export const tenants=sqliteTable('tenants',{id:text('id').primaryKey(),slug:text('slug').notNull().unique(),name:text('name').notNull(),legalName:text('legal_name').notNull().default(''),domains:text('domains').notNull().default(''),status:text('status').notNull().default('active'),plan:text('plan').notNull().default('business'),brandColor:text('brand_color').notNull().default('#6D5EF8'),currency:text('currency').notNull().default('GHS'),timezone:text('timezone').notNull().default('Africa/Accra'),settingsJson:text('settings_json').notNull().default('{}'),createdAt:text('created_at').notNull()});

export const members=sqliteTable('members',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),role:text('role',{enum:['admin','manager','employee','viewer']}).notNull(),department:text('department').notNull(),active:integer('active').notNull().default(1),createdAt:text('created_at').notNull(),tenantId:text('tenant_id').notNull().default('procus'),phone:text('phone').notNull().default(''),title:text('title').notNull().default(''),managerId:text('manager_id'),location:text('location').notNull().default(''),roleId:text('role_id'),employeeCode:text('employee_code').notNull().default(''),platformRole:text('platform_role'),lastSeenAt:text('last_seen_at'),notifyEmail:integer('notify_email').notNull().default(1)},t=>[index('members_tenant').on(t.tenantId,t.name)]);
export const records=sqliteTable('records',{id:text('id').primaryKey(),module:text('module').notNull(),title:text('title').notNull(),department:text('department').notNull(),status:text('status').notNull(),owner:text('owner').notNull(),amount:real('amount').notNull().default(0),details:text('details').notNull().default(''),updated:text('updated').notNull(),version:integer('version').notNull().default(1),createdBy:text('created_by').notNull().references(()=>members.id),fileKey:text('file_key'),tenantId:text('tenant_id').notNull().default('procus')},t=>[index('idx_records_department_module').on(t.department,t.module),index('idx_records_creator').on(t.createdBy),index('records_tenant').on(t.tenantId,t.module)]);
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),action:text('action').notNull(),actor:text('actor').notNull(),recordId:text('record_id').notNull(),department:text('department').notNull(),before:text('before_json'),after:text('after_json'),createdAt:text('created_at').notNull(),tenantId:text('tenant_id').notNull().default('procus')},t=>[index('idx_audit_department_time').on(t.department,t.createdAt),index('audit_tenant_time').on(t.tenantId,t.createdAt),index('audit_tenant_record').on(t.tenantId,t.recordId)]);
export const sessions=sqliteTable('sessions',{tokenHash:text('token_hash').primaryKey(),memberId:text('member_id').notNull().references(()=>members.id),expires:integer('expires').notNull()});
export const authFlows=sqliteTable('auth_flows',{state:text('state').primaryKey(),verifier:text('verifier').notNull(),nonce:text('nonce').notNull(),expires:integer('expires').notNull()});
export const importBatches=sqliteTable('import_batches',{id:text('id').primaryKey(),source:text('source').notNull(),dataset:text('dataset').notNull(),filename:text('filename').notNull(),sha256:text('sha256').notNull(),importedAt:text('imported_at').notNull(),rowCount:integer('row_count').notNull(),headersJson:text('headers_json').notNull(),tenantId:text('tenant_id').notNull().default('procus')});
export const sourceRows=sqliteTable('source_rows',{id:text('id').primaryKey(),batchId:text('batch_id').notNull().references(()=>importBatches.id),sourceKey:text('source_key'),sheet:text('sheet').notNull(),rowNumber:integer('row_number').notNull(),payloadJson:text('payload_json').notNull()},t=>[index('source_rows_batch').on(t.batchId),uniqueIndex('source_rows_position').on(t.batchId,t.sheet,t.rowNumber)]);
export const sourceLinks=sqliteTable('links',{fromId:text('from_id').notNull().references(()=>sourceRows.id),toId:text('to_id').notNull().references(()=>sourceRows.id),kind:text('kind').notNull()},t=>[primaryKey({columns:[t.fromId,t.toId,t.kind]})]);
export const qualityIssues=sqliteTable('quality_issues',{id:text('id').primaryKey(),batchId:text('batch_id').notNull(),kind:text('kind').notNull(),detailJson:text('detail_json').notNull()});
export const passwords=sqliteTable('passwords',{memberId:text('member_id').primaryKey().references(()=>members.id),username:text('username').notNull().unique(),salt:text('salt').notNull(),hash:text('password_hash').notNull(),iterations:integer('iterations').notNull(),mustChange:integer('must_change').notNull().default(1)});
export const loginAttempts=sqliteTable('login_attempts',{key:text('key').primaryKey(),attempts:integer('attempts').notNull(),expires:integer('expires').notNull()});

export const researchAccess=sqliteTable('research_access',{memberId:text('member_id').primaryKey().references(()=>members.id),grantedBy:text('granted_by').notNull(),createdAt:text('created_at').notNull()});
export const researchRecordings=sqliteTable('research_recordings',{id:text('id').primaryKey(),title:text('title').notNull(),context:text('context').notNull().default(''),filename:text('filename').notNull(),mime:text('mime').notNull(),bytes:integer('bytes').notNull(),fileKey:text('file_key').notNull(),createdBy:text('created_by').notNull().references(()=>members.id),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),status:text('status').notNull().default('Uploaded'),transcript:text('transcript'),summary:text('summary'),error:text('error'),leaseUntil:integer('lease_until').notNull().default(0),attempts:integer('attempts').notNull().default(0),transcriptionModel:text('transcription_model'),summaryModel:text('summary_model'),tenantId:text('tenant_id').notNull().default('procus')},t=>[index('research_created').on(t.createdAt),index('research_tenant').on(t.tenantId,t.createdAt)]);

export const itNvrs=sqliteTable('it_nvrs',{id:text('id').primaryKey(),name:text('name').notNull(),address:text('address').notNull(),location:text('location').notNull().default(''),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),tenantId:text('tenant_id').notNull().default('procus')},t=>[uniqueIndex('it_nvrs_address_unique').on(t.tenantId,t.address)]);
export const itNvrReadings=sqliteTable('it_nvr_readings',{id:text('id').primaryKey(),nvrId:text('nvr_id').notNull().references(()=>itNvrs.id),readingDate:text('reading_date').notNull(),diskNo:integer('disk_no').notNull(),capacityGb:real('capacity_gb').notNull(),remainingGb:real('remaining_gb').notNull(),status:text('status').notNull(),attribute:text('attribute').notNull(),storageType:text('storage_type').notNull(),notes:text('notes').notNull().default(''),recordedBy:text('recorded_by').notNull().references(()=>members.id),recordedAt:text('recorded_at').notNull()},t=>[uniqueIndex('nvr_disk_day').on(t.nvrId,t.readingDate,t.diskNo)]);

export const accessRules=sqliteTable('access_rules',{id:text('id').primaryKey(),subjectType:text('subject_type').notNull(),subjectId:text('subject_id').notNull(),department:text('department').notNull(),page:text('page').notNull(),action:text('action').notNull(),effect:text('effect').notNull(),scope:text('scope').notNull(),tenantId:text('tenant_id').notNull().default('procus')},t=>[uniqueIndex('access_rule_subject_action').on(t.tenantId,t.subjectType,t.subjectId,t.department,t.page,t.action)]);

export const researchCloudJobs=sqliteTable('research_cloud_jobs',{recordingId:text('recording_id').primaryKey().references(()=>researchRecordings.id),providerId:text('provider_id').unique(),tokenHash:text('token_hash').notNull(),state:text('state').notNull(),leaseUntil:integer('lease_until').notNull().default(0),attempts:integer('attempts').notNull().default(0)});

// ── Organisation ─────────────────────────────────────────────────────────────
export const roles=sqliteTable('roles',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),name:text('name').notNull(),description:text('description').notNull().default(''),base:text('base').notNull().default('employee'),permissionsJson:text('permissions_json').notNull().default('{}'),locationsJson:text('locations_json').notNull().default('[]'),defaultScreen:text('default_screen').notNull().default(''),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedBy:text('updated_by').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('roles_tenant_name').on(t.tenantId,t.name)]);
export const departments=sqliteTable('departments',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),name:text('name').notNull(),code:text('code').notNull().default(''),headId:text('head_id'),description:text('description').notNull().default(''),color:text('color').notNull().default(''),createdAt:text('created_at').notNull()},t=>[uniqueIndex('departments_tenant_name').on(t.tenantId,t.name)]);
export const locations=sqliteTable('locations',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),name:text('name').notNull(),parentId:text('parent_id'),path:text('path').notNull(),kind:text('kind').notNull().default('Site'),createdAt:text('created_at').notNull()},t=>[uniqueIndex('locations_tenant_path').on(t.tenantId,t.path)]);
export const counters=sqliteTable('counters',{tenantId:text('tenant_id').notNull(),key:text('key').notNull(),value:integer('value').notNull()},t=>[primaryKey({columns:[t.tenantId,t.key]})]);

// ── Assets & tickets ─────────────────────────────────────────────────────────
export const assets=sqliteTable('assets',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),code:text('code').notNull(),name:text('name').notNull(),category:text('category').notNull().default(''),kind:text('kind').notNull().default('Physical'),brand:text('brand').notNull().default(''),model:text('model').notNull().default(''),serial:text('serial').notNull().default(''),status:text('status').notNull().default('In store'),condition:text('condition').notNull().default('Good'),location:text('location').notNull().default(''),department:text('department').notNull().default(''),assignedTo:text('assigned_to'),purchaseDate:text('purchase_date'),purchaseCost:real('purchase_cost').notNull().default(0),warrantyUntil:text('warranty_until'),vendor:text('vendor').notNull().default(''),notes:text('notes').notNull().default(''),sourceId:text('source_id'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1)},t=>[uniqueIndex('assets_tenant_code').on(t.tenantId,t.code),uniqueIndex('assets_tenant_source').on(t.tenantId,t.sourceId),index('assets_tenant_status').on(t.tenantId,t.status)]);
export const tickets=sqliteTable('tickets',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),number:text('number').notNull(),title:text('title').notNull(),description:text('description').notNull().default(''),type:text('type').notNull().default('Incident'),category:text('category').notNull().default(''),priority:text('priority').notNull().default('Medium'),status:text('status').notNull().default('New'),department:text('department').notNull().default(''),assigneeId:text('assignee_id'),requesterId:text('requester_id').notNull(),assetId:text('asset_id'),location:text('location').notNull().default(''),dueAt:text('due_at'),resolvedAt:text('resolved_at'),sourceId:text('source_id'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1)},t=>[uniqueIndex('tickets_tenant_number').on(t.tenantId,t.number),uniqueIndex('tickets_tenant_source').on(t.tenantId,t.sourceId),index('tickets_tenant_status').on(t.tenantId,t.status)]);
export const comments=sqliteTable('comments',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),entityType:text('entity_type').notNull(),entityId:text('entity_id').notNull(),authorId:text('author_id').notNull(),body:text('body').notNull(),internal:integer('internal').notNull().default(0),createdAt:text('created_at').notNull()},t=>[index('comments_entity').on(t.tenantId,t.entityType,t.entityId)]);

// ── Purchasing ───────────────────────────────────────────────────────────────
export const vendors=sqliteTable('vendors',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),name:text('name').notNull(),email:text('email').notNull().default(''),phone:text('phone').notNull().default(''),address:text('address').notNull().default(''),taxId:text('tax_id').notNull().default(''),category:text('category').notNull().default(''),status:text('status').notNull().default('Active'),notes:text('notes').notNull().default(''),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('vendors_tenant_name').on(t.tenantId,t.name)]);
export const purchaseDocs=sqliteTable('purchase_docs',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),kind:text('kind').notNull(),number:text('number').notNull(),title:text('title').notNull(),justification:text('justification').notNull().default(''),department:text('department').notNull(),location:text('location').notNull().default(''),requesterId:text('requester_id').notNull(),vendorId:text('vendor_id'),prId:text('pr_id'),neededBy:text('needed_by'),currency:text('currency').notNull().default('GHS'),subtotal:real('subtotal').notNull().default(0),tax:real('tax').notNull().default(0),total:real('total').notNull().default(0),status:text('status').notNull().default('Draft'),terms:text('terms').notNull().default(''),sourceId:text('source_id'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),submittedAt:text('submitted_at'),version:integer('version').notNull().default(1)},t=>[uniqueIndex('purchase_docs_number').on(t.tenantId,t.number),uniqueIndex('purchase_docs_source').on(t.tenantId,t.sourceId),index('purchase_docs_kind').on(t.tenantId,t.kind,t.status)]);
export const purchaseLines=sqliteTable('purchase_lines',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),docId:text('doc_id').notNull(),lineNo:integer('line_no').notNull(),description:text('description').notNull(),itemCode:text('item_code').notNull().default(''),qty:real('qty').notNull(),unit:text('unit').notNull().default('ea'),unitPrice:real('unit_price').notNull(),taxRate:real('tax_rate').notNull().default(0),receivedQty:real('received_qty').notNull().default(0)},t=>[index('purchase_lines_doc').on(t.tenantId,t.docId)]);
export const approvalWorkflows=sqliteTable('approval_workflows',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),docType:text('doc_type').notNull(),name:text('name').notNull(),department:text('department').notNull().default('*'),minAmount:real('min_amount').notNull().default(0),stepsJson:text('steps_json').notNull(),active:integer('active').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('workflows_tenant').on(t.tenantId,t.docType)]);
export const approvals=sqliteTable('approvals',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),docId:text('doc_id').notNull(),stepNo:integer('step_no').notNull(),stepName:text('step_name').notNull(),approverIds:text('approver_ids').notNull().default('[]'),status:text('status').notNull(),decidedBy:text('decided_by'),decidedAt:text('decided_at'),comment:text('comment').notNull().default(''),createdAt:text('created_at').notNull()},t=>[index('approvals_doc').on(t.tenantId,t.docId),index('approvals_status').on(t.tenantId,t.status)]);

// ── Collaboration ────────────────────────────────────────────────────────────
export const notifications=sqliteTable('notifications',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),memberId:text('member_id').notNull(),kind:text('kind').notNull(),title:text('title').notNull(),body:text('body').notNull().default(''),link:text('link').notNull().default(''),readAt:text('read_at'),emailStatus:text('email_status').notNull().default('none'),createdAt:text('created_at').notNull()},t=>[index('notifications_member').on(t.memberId,t.createdAt)]);
export const folders=sqliteTable('folders',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),parentId:text('parent_id'),name:text('name').notNull(),department:text('department').notNull().default(''),visibility:text('visibility').notNull().default('company'),createdBy:text('created_by').notNull(),createdAt:text('created_at').notNull()},t=>[index('folders_tenant').on(t.tenantId,t.parentId)]);
export const files=sqliteTable('files',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),folderId:text('folder_id'),name:text('name').notNull(),mime:text('mime').notNull(),bytes:integer('bytes').notNull(),fileKey:text('file_key').notNull(),department:text('department').notNull().default(''),visibility:text('visibility').notNull().default('company'),tags:text('tags').notNull().default(''),description:text('description').notNull().default(''),version:integer('version').notNull().default(1),uploadedBy:text('uploaded_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('files_tenant_folder').on(t.tenantId,t.folderId)]);
export const fileVersions=sqliteTable('file_versions',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),fileId:text('file_id').notNull(),version:integer('version').notNull(),fileKey:text('file_key').notNull(),bytes:integer('bytes').notNull(),uploadedBy:text('uploaded_by').notNull(),createdAt:text('created_at').notNull()},t=>[index('file_versions_file').on(t.tenantId,t.fileId)]);
export const pages=sqliteTable('pages',{id:text('id').primaryKey(),tenantId:text('tenant_id').notNull(),department:text('department').notNull().default(''),parentId:text('parent_id'),kind:text('kind').notNull().default('page'),title:text('title').notNull(),body:text('body').notNull().default(''),icon:text('icon').notNull().default(''),status:text('status').notNull().default('Draft'),pinned:integer('pinned').notNull().default(0),authorId:text('author_id').notNull(),updatedBy:text('updated_by').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1)},t=>[index('pages_tenant_space').on(t.tenantId,t.department)]);
