// Regenerates app/ui/icons.ts with only the lucide icons referenced by name in app/ui.
// Run after adding a new icon name: node scripts/gen-icons.mjs
import fs from 'node:fs';
import * as lucide from 'lucide-react';
const dir='app/ui';const used=new Set(['Circle']);
// Shared registries (widgets, record kinds, modules, pages) also name icons.
const extra=['app/widgets.ts','app/work-records.ts','app/modules.ts','app/page-catalog.ts'].filter(p=>fs.existsSync(p));
for(const f of [...fs.readdirSync(dir).filter(f=>/\.tsx?$/.test(f)&&f!=='icons.ts').map(f=>`${dir}/${f}`),...extra]){const src=fs.readFileSync(f,'utf8');for(const m of src.matchAll(/['"]([A-Z][A-Za-z0-9]*)['"]/g))if(m[1] in lucide&&typeof lucide[m[1]]==='object')used.add(m[1])}
const names=[...used].sort();
fs.writeFileSync(`${dir}/icons.ts`,`// Generated by scripts/gen-icons.mjs — do not edit by hand.\nimport {${names.join(',')}} from 'lucide-react';\nexport const icons={${names.join(',')}};\n`);
console.log(names.length,'icons');
